/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
import DiscreteSW.Auto.CalderonZygmund
import DiscreteSW.Auto.DiscreteSteinWainger
import DiscreteSW.Auto.HardyLittlewoodMaximal
import DiscreteSW.Auto.KhintchineInequality
import DiscreteSW.Auto.MarcinkiewiczInterpolation

/-!
# The `DiscreteSW` library

This file was automatically generated by Claude.

Top-level import file of the formalization.
-/
