/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license.
This file was automatically generated by Claude.
-/
import DiscreteSW.Auto.Arithmetic
import DiscreteSW.Auto.CalderonZygmund
import DiscreteSW.Auto.DiscreteSteinWainger
import DiscreteSW.Auto.HardyLittlewoodMaximal
import DiscreteSW.Auto.KhintchineInequality
import DiscreteSW.Auto.MarcinkiewiczInterpolation
import DiscreteSW.Auto.Oscillation
import DiscreteSW.Auto.RealVariable
import DiscreteSW.Auto.Sampling
import DiscreteSW.Auto.Tools
