/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import DiscreteSW.Auto.MarcinkiewiczInterpolation
public import DiscreteSW.Auto.HardyLittlewoodMaximal
public import DiscreteSW.Auto.KhintchineInequality
public import DiscreteSW.Auto.CalderonZygmund
public import DiscreteSW.Auto.Sec2_1Notation
public import DiscreteSW.Auto.Sec2_2ExponentialSums
public import DiscreteSW.Auto.Sec2_4_2_5MultiplierApproximations
public import DiscreteSW.Auto.Sec2_3IonescuWainger
public import DiscreteSW.Auto.Sec5MajorArcParameters
public import DiscreteSW.Auto.Sec4MainArgument
public import DiscreteSW.Auto.Sec6ErrorEstimate
public import DiscreteSW.Auto.DiscreteSteinWainger

/-!
# The `DiscreteSW` library

This file was automatically generated by Claude.

Top-level import file of the formalization. The four prerequisites
(`MarcinkiewiczInterpolation`, `HardyLittlewoodMaximal`, `KhintchineInequality`,
`CalderonZygmund`) are followed by the eight files of the main argument, in import order, aligned
with the sections of B. Krause, J. Roos, arXiv:2107.14616v2 (KR II): `Sec2_1Notation`,
`Sec2_2ExponentialSums`, `Sec2_4_2_5MultiplierApproximations`, `Sec2_3IonescuWainger`,
`Sec5MajorArcParameters`, `Sec4MainArgument`, `Sec6ErrorEstimate` and `DiscreteSteinWainger`
(which contains the main theorem `Auto.discrete_stein_wainger_lp`; see its module docstring for
an overview).
-/
