/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license.
This file was automatically generated by Claude.
-/
import Mathlib
import DiscreteSW.Auto.Tools

/-!
# The Calderón–Zygmund theorem for convolution operators with integrable kernels

This file proves the **Calderón–Zygmund theorem** for convolution operators `f ↦ H * f` with
an integrable kernel `H` on `E = ℝⁿ`, in the quantitative form of Blueprint Lemma 4.2
(`lem:cz`, "An integrable-kernel singular-integral estimate") of `blueprints/discrete-sw.tex`:
the weak type `(1,1)` and strong type `(p,p)` (`1 < p < ∞`) norms are bounded by constants
depending only on `n` (and `p`) times the constant `A` of the hypotheses, independently of
`‖H‖₁`. The statements depend on Mathlib only; the proofs also use
`DiscreteSW.Auto.Tools` (Young's inequality, dual testing, Hölder, the envelope integral) and,
through it, `DiscreteSW.Auto.MarcinkiewiczInterpolation`.

## Formulation

* `E = EuclideanSpace ℝ (Fin n)` with `n ≥ 1` and Lebesgue measure `volume`; functions are
  complex valued; the convolution is `H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f`, i.e.
  `H * f(x) = ∫ H(y) f(x - y) dy` (defined as `0` where the integral diverges; for `H ∈ L¹` and
  `f ∈ L^p` it converges absolutely almost everywhere).
* Hypotheses on the kernel, with a constant `A ≥ 0`:
  * `Integrable H`;
  * `H` is differentiable at every `x ≠ 0` with `‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1)`;
  * the `L²` bound `eLpNorm (H * g) 2 ≤ A * eLpNorm g 2` for every `g ∈ L²`, or alternatively
    the multiplier bound `‖𝓕 H ξ‖ ≤ A` for all `ξ` (which implies the `L²` bound by
    Plancherel: `eLpNorm_convolution_two_le_of_norm_fourier_le`).
  The size bound `|H(x)| ≤ A |x|^{-n}` and the continuity of `∇H` required in the blueprint are
  not needed (so the results here are formally stronger).
* Conclusions:
  * weak type `(1,1)`: `volume {x | t < ‖H * f x‖} ≤ C_n A t⁻¹ ‖f‖₁` for `f ∈ L¹`, `t > 0`,
    with the explicit constant `C_n = czWeakConst n`;
  * strong type `(p,p)`: for `1 < p < ∞` there is `C_{n,p} > 0` (independent of `H`, `A`, `f`)
    with `‖H * f‖_p ≤ C_{n,p} A ‖f‖_p` for all `f ∈ L^p`.

## Proof

The weak type bound is proved directly for every `f ∈ L¹` (no density argument), by the
Calderón–Zygmund decomposition at height `s = t / A`:
* dyadic cubes `czCube (k, j) = ∏ [j_i 2^k, (j_i + 1) 2^k)` (`czDyIdx`, nesting, volume, diameter);
* the maximal bad dyadic cubes (`czBad`, `czTop`, `czSel`, `czIdx`): they are countably many,
  pairwise disjoint, with union `Ω = czBadSet f s`, `|Ω| ≤ s⁻¹ ‖f‖₁`, and
  `∫_Q |f| ≤ 2^n s |Q|` (their parents are not bad);
* Lebesgue differentiation (`ae_enorm_le_of_notMem_czBadSet`, via Mathlib's Vitali family for
  doubling measures and balls containing the dyadic cubes) gives `|f| ≤ s` a.e. off `Ω`;
* the good part `g = czGood f s` (`f` off `Ω`, the averages `f_Q` on the cubes) satisfies
  `|g| ≤ 2^n s`, `‖g‖₁ ≤ ‖f‖₁`, `‖g‖₂² ≤ 2^n s ‖f‖₁`, and the bad part `b = f - g` has mean
  zero on every selected cube;
* the Hörmander condition `∫_{|x - c| > 2δ} |H(x - y) - H(x - c)| dx ≤ czHormConst n * A` for
  `|y - c| ≤ δ` (`lintegral_compl_closedBall_enorm_sub_le`, mean value theorem and the envelope
  integral of `DiscreteSW.Auto.Tools`) and cancellation give `∫_{E ∖ Ω*} |H * b| ≤ C A ‖b‖₁`
  off the enlarged set `Ω* = czStar f s` (`lintegral_compl_czStar_convolution_le`);
* Chebyshev for `H * g` (with the `L²` hypothesis) and `H * b`, and `|Ω*| ≤ (4√n)^n |Ω|`.
The case `A = 0` follows by letting `A' ↓ 0`. The strong bounds for `1 < p < 2` follow from the
Marcinkiewicz interpolation theorem (`eLpNorm_le_of_hasWeakTypeOn` on the truncation closed class
`L^p`), `p = 2` is the hypothesis, and `p > 2` follows by duality
(`integral_convolution_mul_conj`, `eLpNorm_le_of_dual_test`) from the case `p' < 2` for the
adjoint kernel `H*(x) = conj (H(-x))` (`czAdjoint`), which satisfies the same hypotheses
(its `L²` bound again by duality).

## Main results

* `volume_lt_norm_convolution_le`: Blueprint Lemma 4.2, first assertion (weak type `(1,1)`).
* `exists_eLpNorm_convolution_le`: Blueprint Lemma 4.2, second assertion (strong type `(p,p)`).
* `eLpNorm_convolution_two_le_of_norm_fourier_le`: `‖Ĥ‖_∞ ≤ A` implies the `L²` hypothesis;
  `volume_lt_norm_convolution_le_of_norm_fourier_le`,
  `exists_eLpNorm_convolution_le_of_norm_fourier_le`: the two assertions in Fourier form.
* Reusable ingredients: `lintegral_compl_closedBall_enorm_sub_le` (Hörmander condition),
  `integral_convolution_mul_conj` (`∫ (K * f) φ̄ = ∫ f (K* * φ)‾`), and the dyadic
  Calderón–Zygmund decomposition (`czGood`, `czBadSet`, `czStar` and their properties).

## References

* A. P. Calderón and A. Zygmund, *On the existence of certain singular integrals*, Acta Math.
  **88** (1952), 85–139.
* E. M. Stein, *Singular Integrals and Differentiability Properties of Functions*, Princeton
  University Press, 1970, Chapter II, §2.
* L. Grafakos, *Classical Fourier Analysis*, 3rd ed., Graduate Texts in Mathematics 249,
  Springer, 2014, §5.3.
-/

open MeasureTheory Metric Set Filter Topology
open scoped ENNReal NNReal Convolution ComplexConjugate

noncomputable section

namespace Auto

/-! ## Dyadic cubes -/

section Dyadic

variable {n : ℕ}

/-- The integer index `(⌊x_i / 2^k⌋)_i` of the dyadic cube of side length `2^k` containing `x`. -/
def czDyIdx (k : ℤ) (x : EuclideanSpace ℝ (Fin n)) : Fin n → ℤ :=
  fun i => ⌊x i / (2 : ℝ) ^ k⌋

/-- The half-open dyadic cube `∏_i [j_i 2^k, (j_i + 1) 2^k)` with index `p = (k, j)`. -/
def czCube (p : ℤ × (Fin n → ℤ)) : Set (EuclideanSpace ℝ (Fin n)) :=
  {y | czDyIdx p.1 y = p.2}

/-- The corner `(j_i 2^k)_i` of the dyadic cube with index `p = (k, j)`. -/
def czCorner (p : ℤ × (Fin n → ℤ)) : EuclideanSpace ℝ (Fin n) :=
  WithLp.toLp 2 (fun i => (p.2 i : ℝ) * (2 : ℝ) ^ p.1)

lemma measurable_czDyIdx (k : ℤ) : Measurable (czDyIdx (n := n) k) := by
  refine measurable_pi_iff.2 fun i => ?_
  exact Int.measurable_floor.comp (((measurable_pi_apply i).comp
    (MeasurableEquiv.toLp 2 (Fin n → ℝ)).symm.measurable).div_const _)

lemma measurableSet_czCube (p : ℤ × (Fin n → ℤ)) : MeasurableSet (czCube p) :=
  measurable_czDyIdx p.1 (measurableSet_singleton p.2)

lemma mem_czCube_self (k : ℤ) (x : EuclideanSpace ℝ (Fin n)) : x ∈ czCube (k, czDyIdx k x) :=
  rfl

lemma czCorner_mem (p : ℤ × (Fin n → ℤ)) : czCorner p ∈ czCube p := by
  show czDyIdx p.1 (czCorner p) = p.2
  funext i
  have h2 : (2 : ℝ) ^ p.1 ≠ 0 := (zpow_pos two_pos _).ne'
  simp [czDyIdx, czCorner, mul_div_assoc, div_self h2]

/-- Membership in a dyadic cube in terms of coordinates. -/
lemma mem_czCube_iff {p : ℤ × (Fin n → ℤ)} {y : EuclideanSpace ℝ (Fin n)} :
    y ∈ czCube p ↔ ∀ i, (p.2 i : ℝ) * (2 : ℝ) ^ p.1 ≤ y i ∧ y i < (p.2 i + 1) * (2 : ℝ) ^ p.1 := by
  have h2 : (0 : ℝ) < (2 : ℝ) ^ p.1 := zpow_pos two_pos _
  simp only [czCube, mem_ofPred_eq, funext_iff, czDyIdx, Int.floor_eq_iff, le_div_iff₀ h2,
    div_lt_iff₀ h2]

/-- Nesting: the dyadic cubes of `x` and `y` at scale `k` agree, then so do those at scale
`k' ≥ k`. -/
lemma czDyIdx_eq_of_le {k k' : ℤ} (hk : k ≤ k') {x y : EuclideanSpace ℝ (Fin n)}
    (h : czDyIdx k y = czDyIdx k x) : czDyIdx k' y = czDyIdx k' x := by
  obtain ⟨m, rfl⟩ : ∃ m : ℕ, k' = k + m := ⟨(k' - k).toNat, by omega⟩
  have key : ∀ z : EuclideanSpace ℝ (Fin n), ∀ i,
      czDyIdx (k + m) z i = czDyIdx k z i / ((2 ^ m : ℕ) : ℤ) := by
    intro z i
    simp only [czDyIdx]
    rw [← Int.floor_div_natCast]
    congr 1
    rw [zpow_add₀ two_ne_zero, zpow_natCast, div_div]
    push_cast
    ring
  funext i
  rw [key, key, h]

lemma czCube_subset_of_le {k k' : ℤ} (hk : k ≤ k') (x : EuclideanSpace ℝ (Fin n)) :
    czCube (k, czDyIdx k x) ⊆ czCube (k', czDyIdx k' x) :=
  fun _ hy => czDyIdx_eq_of_le hk hy

/-- The volume of a dyadic cube of side `2^k` is `(2^k)^n`. -/
lemma volume_czCube (p : ℤ × (Fin n → ℤ)) :
    volume (czCube p) = ENNReal.ofReal ((2 : ℝ) ^ p.1) ^ n := by
  have he := measurePreserving_euclideanEquivPi n
  have hset : czCube p = euclideanEquivPi n ⁻¹'
      (Set.univ.pi fun i => Set.Ico ((p.2 i : ℝ) * (2 : ℝ) ^ p.1)
        ((p.2 i + 1) * (2 : ℝ) ^ p.1)) := by
    ext y
    rw [mem_czCube_iff]
    simp only [mem_preimage, Set.mem_pi, mem_univ, true_implies, mem_Ico]
    rfl
  rw [hset, he.measure_preimage (MeasurableSet.univ_pi fun _ => measurableSet_Ico).nullMeasurableSet,
    Real.volume_pi_Ico]
  simp only [add_mul, one_mul, add_sub_cancel_left, Finset.prod_const, Finset.card_univ,
    Fintype.card_fin]

lemma volume_czCube_ne_zero (p : ℤ × (Fin n → ℤ)) : volume (czCube p) ≠ 0 := by
  rw [volume_czCube]
  exact pow_ne_zero _ (ENNReal.ofReal_pos.2 (zpow_pos two_pos _)).ne'

lemma volume_czCube_ne_top (p : ℤ × (Fin n → ℤ)) : volume (czCube p) ≠ ∞ := by
  rw [volume_czCube]
  exact ENNReal.pow_ne_top ENNReal.ofReal_ne_top

/-- Two points of a dyadic cube of side `2^k` are at distance at most `√n 2^k`. -/
lemma norm_sub_le_of_mem_czCube {p : ℤ × (Fin n → ℤ)} {y z : EuclideanSpace ℝ (Fin n)}
    (hy : y ∈ czCube p) (hz : z ∈ czCube p) : ‖y - z‖ ≤ Real.sqrt n * (2 : ℝ) ^ p.1 := by
  rw [mem_czCube_iff] at hy hz
  have h2 : (0 : ℝ) < (2 : ℝ) ^ p.1 := zpow_pos two_pos _
  have hi : ∀ i, ‖(y - z).ofLp i‖ ^ 2 ≤ ((2 : ℝ) ^ p.1) ^ 2 := by
    intro i
    have h1 := hy i
    have h3 := hz i
    have : |y i - z i| ≤ (2 : ℝ) ^ p.1 := by
      rw [abs_le]; constructor <;> nlinarith
    simp only [PiLp.sub_apply, Real.norm_eq_abs]
    exact pow_le_pow_left₀ (abs_nonneg _) this 2
  rw [EuclideanSpace.norm_eq, Real.sqrt_le_left (by positivity)]
  calc ∑ i, ‖(y - z).ofLp i‖ ^ 2 ≤ ∑ _i : Fin n, ((2 : ℝ) ^ p.1) ^ 2 :=
        Finset.sum_le_sum fun i _ => hi i
    _ = (Real.sqrt n * (2 : ℝ) ^ p.1) ^ 2 := by
        rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul, mul_pow,
          Real.sq_sqrt (Nat.cast_nonneg _)]

lemma czCube_subset_closedBall {p : ℤ × (Fin n → ℤ)} {x : EuclideanSpace ℝ (Fin n)}
    (hx : x ∈ czCube p) : czCube p ⊆ closedBall x (Real.sqrt n * (2 : ℝ) ^ p.1) :=
  fun _ hy => mem_closedBall_iff_norm.2 (norm_sub_le_of_mem_czCube hy hx)

end Dyadic

/-! ## The Calderón–Zygmund selection of maximal dyadic cubes -/

section Selection

variable {n : ℕ} (f : EuclideanSpace ℝ (Fin n) → ℂ) (s : ℝ)

/-- The dyadic cube `p` is *bad* for `f` at height `s`: `s |Q| < ∫_Q ‖f‖`. -/
def czBad (p : ℤ × (Fin n → ℤ)) : Prop :=
  ENNReal.ofReal s * volume (czCube p) < ∫⁻ y in czCube p, ‖f y‖ₑ

/-- The Calderón–Zygmund exceptional set `Ω`: the union of all bad dyadic cubes. -/
def czBadSet : Set (EuclideanSpace ℝ (Fin n)) := {x | ∃ k : ℤ, czBad f s (k, czDyIdx k x)}

/-- The scale of the maximal bad dyadic cube containing `x` (for `x ∈ Ω`). -/
def czTop (x : EuclideanSpace ℝ (Fin n)) : ℤ := sSup {k : ℤ | czBad f s (k, czDyIdx k x)}

/-- The index of the maximal bad dyadic cube containing `x` (for `x ∈ Ω`). -/
def czSel (x : EuclideanSpace ℝ (Fin n)) : ℤ × (Fin n → ℤ) :=
  (czTop f s x, czDyIdx (czTop f s x) x)

/-- The indices of the selected (maximal bad) dyadic cubes. -/
def czIdx : Set (ℤ × (Fin n → ℤ)) := czSel f s '' czBadSet f s

variable {f s}

lemma czIdx_countable : (czIdx f s).Countable := Set.to_countable _

/-- Bad cubes have bounded scale, for `n ≥ 1`, `s > 0` and `∫ ‖f‖ < ∞`. -/
lemma exists_scale_lt_of_czBad (hn : 0 < n) (hs : 0 < s) (hf : ∫⁻ y, ‖f y‖ₑ ≠ ∞) :
    ∃ K : ℤ, ∀ p, czBad f s p → p.1 < K := by
  set I := ∫⁻ y, ‖f y‖ₑ
  obtain ⟨m, hm⟩ := pow_unbounded_of_one_lt (I.toReal / s) one_lt_two
  refine ⟨m, fun p hp => ?_⟩
  by_contra hk
  push Not at hk
  have h1 : (1 : ℝ) ≤ (2 : ℝ) ^ p.1 := one_le_zpow₀ one_le_two (le_trans (by positivity) hk)
  have h2 : (2 : ℝ) ^ m ≤ ((2 : ℝ) ^ p.1) ^ n := by
    calc (2 : ℝ) ^ m = (2 : ℝ) ^ (m : ℤ) := (zpow_natCast _ _).symm
      _ ≤ (2 : ℝ) ^ p.1 := zpow_le_zpow_right₀ one_le_two hk
      _ ≤ ((2 : ℝ) ^ p.1) ^ n := le_self_pow₀ h1 hn.ne'
  have h3 : I < ENNReal.ofReal s * volume (czCube p) := by
    rw [volume_czCube, ← ENNReal.ofReal_pow (zpow_pos two_pos _).le,
      ← ENNReal.ofReal_mul hs.le, ← ENNReal.ofReal_toReal hf]
    refine (ENNReal.ofReal_lt_ofReal_iff (by positivity)).2 ?_
    rw [div_lt_iff₀ hs] at hm
    nlinarith
  exact absurd (hp.trans_le (setLIntegral_le_lintegral _ _)) (not_lt.2 h3.le)

variable (hn : 0 < n) (hs : 0 < s) (hf : ∫⁻ y, ‖f y‖ₑ ≠ ∞)
include hn hs hf

lemma bddAbove_czBad (x : EuclideanSpace ℝ (Fin n)) :
    BddAbove {k : ℤ | czBad f s (k, czDyIdx k x)} := by
  obtain ⟨K, hK⟩ := exists_scale_lt_of_czBad hn hs hf
  exact ⟨K, fun k hk => (hK _ hk).le⟩

lemma czBad_czSel {x : EuclideanSpace ℝ (Fin n)} (hx : x ∈ czBadSet f s) :
    czBad f s (czSel f s x) :=
  Int.csSup_mem hx (bddAbove_czBad hn hs hf x)

lemma le_czTop {x : EuclideanSpace ℝ (Fin n)} {k : ℤ} (hk : czBad f s (k, czDyIdx k x)) :
    k ≤ czTop f s x :=
  le_csSup (bddAbove_czBad hn hs hf x) hk

/-- Key property of the selection: every point `y` of the selected cube of `x ∈ Ω` lies in `Ω`
and has the same selected cube. -/
lemma czSel_eq_of_mem {x y : EuclideanSpace ℝ (Fin n)} (hx : x ∈ czBadSet f s)
    (hy : y ∈ czCube (czSel f s x)) : y ∈ czBadSet f s ∧ czSel f s y = czSel f s x := by
  have hy' : czDyIdx (czTop f s x) y = czDyIdx (czTop f s x) x := hy
  have hbad : czBad f s (czTop f s x, czDyIdx (czTop f s x) y) := by
    rw [hy']; exact czBad_czSel hn hs hf hx
  have hyΩ : y ∈ czBadSet f s := ⟨_, hbad⟩
  refine ⟨hyΩ, ?_⟩
  have h1 : czTop f s x ≤ czTop f s y := le_czTop hn hs hf hbad
  have h2 : czTop f s y ≤ czTop f s x := by
    by_contra h
    push Not at h
    have hb := czBad_czSel hn hs hf hyΩ
    simp only [czSel] at hb
    rw [czDyIdx_eq_of_le h.le hy'] at hb
    exact absurd (le_czTop hn hs hf hb) (not_le.2 h)
  have heq : czTop f s y = czTop f s x := le_antisymm h2 h1
  simp only [czSel, heq, hy']

lemma czSel_eq_of_mem_czIdx {p : ℤ × (Fin n → ℤ)} (hp : p ∈ czIdx f s)
    {y : EuclideanSpace ℝ (Fin n)} (hy : y ∈ czCube p) :
    y ∈ czBadSet f s ∧ czSel f s y = p := by
  obtain ⟨x, hx, rfl⟩ := hp
  exact czSel_eq_of_mem hn hs hf hx hy

lemma czBadSet_eq_biUnion : czBadSet f s = ⋃ p ∈ czIdx f s, czCube p := by
  ext x
  simp only [mem_iUnion, exists_prop]
  constructor
  · intro hx
    exact ⟨czSel f s x, ⟨x, hx, rfl⟩, mem_czCube_self _ x⟩
  · rintro ⟨p, hp, hx⟩
    exact (czSel_eq_of_mem_czIdx hn hs hf hp hx).1

lemma czIdx_pairwiseDisjoint : (czIdx f s).PairwiseDisjoint czCube := by
  intro p hp q hq hpq
  refine Set.disjoint_left.2 fun z hzp hzq => hpq ?_
  rw [← (czSel_eq_of_mem_czIdx hn hs hf hp hzp).2, (czSel_eq_of_mem_czIdx hn hs hf hq hzq).2]

omit hn hs hf in
lemma measurableSet_biUnion_czCube (T : Set (ℤ × (Fin n → ℤ))) :
    MeasurableSet (⋃ p ∈ T, czCube p) :=
  MeasurableSet.biUnion (Set.to_countable _) fun p _ => measurableSet_czCube p

lemma measurableSet_czBadSet : MeasurableSet (czBadSet f s) := by
  rw [czBadSet_eq_biUnion hn hs hf]; exact measurableSet_biUnion_czCube _

lemma czBad_of_mem_czIdx {p : ℤ × (Fin n → ℤ)} (hp : p ∈ czIdx f s) : czBad f s p := by
  obtain ⟨x, hx, rfl⟩ := hp
  exact czBad_czSel hn hs hf hx

/-- The parent of a selected cube is not bad, whence `∫_Q ‖f‖ ≤ 2^n s |Q|`. -/
lemma setLIntegral_czCube_le {p : ℤ × (Fin n → ℤ)} (hp : p ∈ czIdx f s) :
    ∫⁻ y in czCube p, ‖f y‖ₑ ≤ 2 ^ n * ENNReal.ofReal s * volume (czCube p) := by
  obtain ⟨x, hx, rfl⟩ := hp
  set k := czTop f s x
  have hnot : ¬ czBad f s (k + 1, czDyIdx (k + 1) x) := fun h =>
    absurd (le_czTop hn hs hf h) (by omega)
  rw [czBad, not_lt] at hnot
  have hsub : czCube (czSel f s x) ⊆ czCube (k + 1, czDyIdx (k + 1) x) :=
    czCube_subset_of_le (by omega) x
  have hvol : volume (czCube (k + 1, czDyIdx (k + 1) x)) = 2 ^ n * volume (czCube (czSel f s x)) := by
    rw [volume_czCube, volume_czCube]
    simp only [czSel]
    rw [zpow_add_one₀ two_ne_zero, ENNReal.ofReal_mul (zpow_pos two_pos _).le, mul_pow,
      mul_comm]
    congr 2
    simp
  calc ∫⁻ y in czCube (czSel f s x), ‖f y‖ₑ
      ≤ ∫⁻ y in czCube (k + 1, czDyIdx (k + 1) x), ‖f y‖ₑ := lintegral_mono_set hsub
    _ ≤ ENNReal.ofReal s * volume (czCube (k + 1, czDyIdx (k + 1) x)) := hnot
    _ = 2 ^ n * ENNReal.ofReal s * volume (czCube (czSel f s x)) := by rw [hvol]; ring

/-- `|Ω| ≤ s⁻¹ ∫_Ω ‖f‖`. -/
lemma volume_czBadSet_le :
    volume (czBadSet f s) ≤ (ENNReal.ofReal s)⁻¹ * ∫⁻ y, ‖f y‖ₑ := by
  have hs' : ENNReal.ofReal s ≠ 0 := (ENNReal.ofReal_pos.2 hs).ne'
  rw [czBadSet_eq_biUnion hn hs hf, measure_biUnion czIdx_countable
    (czIdx_pairwiseDisjoint hn hs hf) fun p _ => measurableSet_czCube p]
  calc ∑' p : czIdx f s, volume (czCube (p : ℤ × (Fin n → ℤ)))
      ≤ ∑' p : czIdx f s, (ENNReal.ofReal s)⁻¹ * ∫⁻ y in czCube p, ‖f y‖ₑ := by
        refine ENNReal.tsum_le_tsum fun p => ?_
        have h := (czBad_of_mem_czIdx hn hs hf p.2).le
        exact (ENNReal.mul_le_iff_le_inv hs' ENNReal.ofReal_ne_top).1 h
    _ = (ENNReal.ofReal s)⁻¹ * ∫⁻ y in ⋃ p ∈ czIdx f s, czCube p, ‖f y‖ₑ := by
        rw [ENNReal.tsum_mul_left, lintegral_biUnion czIdx_countable
          (fun p _ => measurableSet_czCube p) (czIdx_pairwiseDisjoint hn hs hf)]
    _ ≤ (ENNReal.ofReal s)⁻¹ * ∫⁻ y, ‖f y‖ₑ := by
        exact mul_le_mul_right (setLIntegral_le_lintegral _ _) _

end Selection

/-! ## The Calderón–Zygmund decomposition `f = g + b` -/

section Decomposition

variable {n : ℕ}


/-- A closed Euclidean ball of radius `R` is contained in the cube of half side `R`, hence has
volume at most `(2R)^n`. -/
lemma volume_closedBall_le_euclidean (c : EuclideanSpace ℝ (Fin n)) {R : ℝ} (hR : 0 ≤ R) :
    volume (closedBall c R) ≤ ENNReal.ofReal ((2 * R) ^ n) := by
  rw [← volume_euclideanCube c hR]
  refine measure_mono fun y hy => ?_
  intro i
  have h1 := PiLp.norm_apply_le (y - c) i
  simp only [PiLp.sub_apply, Real.norm_eq_abs] at h1
  exact h1.trans (mem_closedBall_iff_norm.1 hy)

/-- **Lebesgue differentiation along dyadic cubes**: `‖f‖ ≤ s` almost everywhere off the
exceptional set `Ω`. -/
lemma ae_enorm_le_of_notMem_czBadSet (hn : 0 < n) {f : EuclideanSpace ℝ (Fin n) → ℂ} {s : ℝ}
    (hf : Integrable f) : ∀ᵐ x, x ∉ czBadSet f s → ‖f x‖ₑ ≤ ENNReal.ofReal s := by
  have hL := (IsUnifLocDoublingMeasure.vitaliFamily
    (volume : Measure (EuclideanSpace ℝ (Fin n))) 1).ae_tendsto_lintegral_enorm_sub_div
    hf.locallyIntegrable
  filter_upwards [hL] with x hx hxΩ
  set δ : ℕ → ℝ := fun m => Real.sqrt n * (2 : ℝ) ^ (-(m : ℤ)) with hδ_def
  have hsqrt : 0 < Real.sqrt n := Real.sqrt_pos.2 (by exact_mod_cast hn)
  have hδpos : ∀ m, 0 < δ m := fun m => mul_pos hsqrt (zpow_pos two_pos _)
  have hδ : Tendsto δ atTop (𝓝[>] 0) := by
    refine tendsto_nhdsWithin_iff.2 ⟨?_, Eventually.of_forall hδpos⟩
    have h := (tendsto_pow_atTop_nhds_zero_of_lt_one (by norm_num : (0 : ℝ) ≤ 1 / 2)
      (by norm_num)).const_mul (Real.sqrt n)
    rw [mul_zero] at h
    refine h.congr fun m => ?_
    simp [δ, zpow_neg, zpow_natCast]
  have hB := IsUnifLocDoublingMeasure.tendsto_closedBall_filterAt
    (volume : Measure (EuclideanSpace ℝ (Fin n))) (K := 1) (fun _ => x) δ hδ
    (Eventually.of_forall fun m => by rw [one_mul]; exact mem_closedBall_self (hδpos m).le)
  have hlim := hx.comp hB
  set a : ℕ → ℝ≥0∞ := fun m =>
    (∫⁻ y in closedBall x (δ m), ‖f y - f x‖ₑ) / volume (closedBall x (δ m)) with ha_def
  have hlim' : Tendsto a atTop (𝓝 0) := hlim
  set c : ℝ≥0∞ := ENNReal.ofReal ((2 * Real.sqrt n) ^ n) with hc_def
  have hbound : ∀ m, ‖f x‖ₑ ≤ ENNReal.ofReal s + c * a m := by
    intro m
    set k : ℤ := -(m : ℤ)
    set Q := czCube (k, czDyIdx k x)
    set B := closedBall x (δ m)
    have hQB : Q ⊆ B := czCube_subset_closedBall (mem_czCube_self k x)
    have hnot : ¬ czBad f s (k, czDyIdx k x) := fun h => hxΩ ⟨k, h⟩
    replace hnot : ∫⁻ y in Q, ‖f y‖ₑ ≤ ENNReal.ofReal s * volume Q := not_lt.1 hnot
    have hB0 : volume B ≠ 0 := (measure_closedBall_pos _ x (hδpos m)).ne'
    have hBt : volume B ≠ ∞ := measure_closedBall_lt_top.ne
    have hBQ : volume B ≤ c * volume Q := by
      refine (volume_closedBall_le_euclidean x (hδpos m).le).trans_eq ?_
      rw [volume_czCube, hc_def, ← ENNReal.ofReal_pow (zpow_pos two_pos _).le,
        ← ENNReal.ofReal_mul (by positivity)]
      congr 1
      simp only [δ, k]
      ring
    have h1 : ‖f x‖ₑ * volume Q ≤ ENNReal.ofReal s * volume Q + a m * (c * volume Q) := by
      calc ‖f x‖ₑ * volume Q = ∫⁻ _ in Q, ‖f x‖ₑ := (setLIntegral_const _ _).symm
        _ ≤ ∫⁻ y in Q, (‖f y‖ₑ + ‖f y - f x‖ₑ) := by
            refine lintegral_mono fun y => ?_
            calc ‖f x‖ₑ = ‖f y - (f y - f x)‖ₑ := by rw [sub_sub_cancel]
              _ ≤ ‖f y‖ₑ + ‖f y - f x‖ₑ := enorm_sub_le
        _ = (∫⁻ y in Q, ‖f y‖ₑ) + ∫⁻ y in Q, ‖f y - f x‖ₑ :=
            lintegral_add_left' hf.aestronglyMeasurable.enorm.restrict _
        _ ≤ ENNReal.ofReal s * volume Q + ∫⁻ y in B, ‖f y - f x‖ₑ :=
            add_le_add hnot (lintegral_mono_set hQB)
        _ = ENNReal.ofReal s * volume Q + a m * volume B := by
            rw [ha_def, ENNReal.div_mul_cancel hB0 hBt]
        _ ≤ ENNReal.ofReal s * volume Q + a m * (c * volume Q) := by gcongr
    have h2 : ‖f x‖ₑ * volume Q ≤ (ENNReal.ofReal s + c * a m) * volume Q := by
      refine h1.trans_eq ?_; ring
    exact (ENNReal.mul_le_mul_iff_left (volume_czCube_ne_zero _) (volume_czCube_ne_top _)).1 h2
  have hlim2 : Tendsto (fun m => ENNReal.ofReal s + c * a m) atTop
      (𝓝 (ENNReal.ofReal s + c * 0)) :=
    tendsto_const_nhds.add (ENNReal.Tendsto.const_mul hlim' (Or.inr ENNReal.ofReal_ne_top))
  rw [mul_zero, add_zero] at hlim2
  exact ge_of_tendsto' hlim2 hbound

variable (f : EuclideanSpace ℝ (Fin n) → ℂ) (s : ℝ)

/-- The average `f_Q = |Q|⁻¹ ∫_Q f` of `f` over the dyadic cube `p`. -/
def czAvg (p : ℤ × (Fin n → ℤ)) : ℂ :=
  (volume (czCube p)).toReal⁻¹ • ∫ y in czCube p, f y

open Classical in
/-- The Calderón–Zygmund good part: `g = f` off `Ω`, and `g = f_Q` on each selected cube `Q`. -/
def czGood : EuclideanSpace ℝ (Fin n) → ℂ :=
  (czBadSet f s).piecewise (fun x => czAvg f (czSel f s x)) f

/-- The enlarged exceptional set `Ω* = ⋃_Q B(c_Q, 2√n ℓ(Q))`. -/
def czStar : Set (EuclideanSpace ℝ (Fin n)) :=
  ⋃ p ∈ czIdx f s, closedBall (czCorner p) (2 * (Real.sqrt n * (2 : ℝ) ^ p.1))

variable {f s}

lemma czGood_of_notMem {x : EuclideanSpace ℝ (Fin n)} (hx : x ∉ czBadSet f s) :
    czGood f s x = f x := by
  classical
  simp [czGood, Set.piecewise_eq_of_notMem _ _ _ hx]

lemma czGood_of_mem {x : EuclideanSpace ℝ (Fin n)} (hx : x ∈ czBadSet f s) :
    czGood f s x = czAvg f (czSel f s x) := by
  classical
  simp [czGood, Set.piecewise_eq_of_mem _ _ _ hx]

/-- `‖f_Q‖ |Q| ≤ ∫_Q ‖f‖`. -/
lemma enorm_czAvg_mul_le (p : ℤ × (Fin n → ℤ)) :
    ‖czAvg f p‖ₑ * volume (czCube p) ≤ ∫⁻ y in czCube p, ‖f y‖ₑ := by
  have h0 := volume_czCube_ne_zero p
  have ht := volume_czCube_ne_top p
  have hpos : 0 < (volume (czCube p)).toReal := ENNReal.toReal_pos h0 ht
  rw [czAvg, enorm_smul, Real.enorm_eq_ofReal (inv_pos.2 hpos).le,
    ENNReal.ofReal_inv_of_pos hpos, ENNReal.ofReal_toReal ht]
  calc (volume (czCube p))⁻¹ * ‖∫ y in czCube p, f y‖ₑ * volume (czCube p)
      = ‖∫ y in czCube p, f y‖ₑ * ((volume (czCube p))⁻¹ * volume (czCube p)) := by ring
    _ = ‖∫ y in czCube p, f y‖ₑ := by rw [ENNReal.inv_mul_cancel h0 ht, mul_one]
    _ ≤ ∫⁻ y in czCube p, ‖f y‖ₑ := enorm_integral_le_lintegral_enorm _

/-- The averages over the cube `p` of `f` integrate back: `∫_Q f_Q = ∫_Q f`. -/
lemma setIntegral_czAvg (p : ℤ × (Fin n → ℤ)) :
    ∫ _ in czCube p, czAvg f p = ∫ y in czCube p, f y := by
  have hpos : 0 < (volume (czCube p)).toReal :=
    ENNReal.toReal_pos (volume_czCube_ne_zero p) (volume_czCube_ne_top p)
  rw [setIntegral_const, czAvg, smul_smul, Measure.real, mul_inv_cancel₀ hpos.ne', one_smul]

variable (hn : 0 < n) (hs : 0 < s) (hf : ∫⁻ y, ‖f y‖ₑ ≠ ∞)
include hn hs hf

lemma czGood_of_mem_czCube {p : ℤ × (Fin n → ℤ)} (hp : p ∈ czIdx f s)
    {y : EuclideanSpace ℝ (Fin n)} (hy : y ∈ czCube p) : czGood f s y = czAvg f p := by
  obtain ⟨hyΩ, hsel⟩ := czSel_eq_of_mem_czIdx hn hs hf hp hy
  rw [czGood_of_mem hyΩ, hsel]

/-- On a selected cube, `‖f_Q‖ ≤ 2^n s`. -/
lemma enorm_czAvg_le {p : ℤ × (Fin n → ℤ)} (hp : p ∈ czIdx f s) :
    ‖czAvg f p‖ₑ ≤ 2 ^ n * ENNReal.ofReal s := by
  have h := (enorm_czAvg_mul_le (f := f) p).trans (setLIntegral_czCube_le hn hs hf hp)
  exact (ENNReal.mul_le_mul_iff_left (volume_czCube_ne_zero p) (volume_czCube_ne_top p)).1 h

lemma measurable_czGood (hfm : Measurable f) : Measurable (czGood f s) := by
  classical
  intro U hU
  have hA : (fun x => czAvg f (czSel f s x)) ⁻¹' U ∩ czBadSet f s =
      ⋃ p ∈ czIdx f s ∩ {p | czAvg f p ∈ U}, czCube p := by
    ext x
    simp only [mem_inter_iff, mem_preimage, mem_iUnion, exists_prop, mem_ofPred_eq]
    constructor
    · rintro ⟨hxU, hx⟩
      exact ⟨czSel f s x, ⟨⟨x, hx, rfl⟩, hxU⟩, mem_czCube_self _ x⟩
    · rintro ⟨p, ⟨hp, hpU⟩, hx⟩
      obtain ⟨hxΩ, hsel⟩ := czSel_eq_of_mem_czIdx hn hs hf hp hx
      exact ⟨by rw [hsel]; exact hpU, hxΩ⟩
  have hΩ := measurableSet_czBadSet hn hs hf
  rw [czGood, Set.piecewise_preimage, Set.ite]
  refine MeasurableSet.union ?_ ((hfm hU).diff hΩ)
  rw [hA]; exact measurableSet_biUnion_czCube _

/-- `‖g‖ ≤ 2^n s` almost everywhere. -/
lemma ae_enorm_czGood_le (hfi : Integrable f) :
    ∀ᵐ x, ‖czGood f s x‖ₑ ≤ 2 ^ n * ENNReal.ofReal s := by
  filter_upwards [ae_enorm_le_of_notMem_czBadSet hn (s := s) hfi] with x hx
  by_cases hxΩ : x ∈ czBadSet f s
  · rw [czGood_of_mem hxΩ]
    exact enorm_czAvg_le hn hs hf ⟨x, hxΩ, rfl⟩
  · rw [czGood_of_notMem hxΩ]
    exact (hx hxΩ).trans (le_mul_of_one_le_left zero_le (one_le_pow₀ one_le_two))

/-- `∫_Ω ‖g‖ ≤ ∫_Ω ‖f‖`. -/
lemma setLIntegral_czGood_le :
    ∫⁻ y in czBadSet f s, ‖czGood f s y‖ₑ ≤ ∫⁻ y in czBadSet f s, ‖f y‖ₑ := by
  rw [czBadSet_eq_biUnion hn hs hf, lintegral_biUnion czIdx_countable
    (fun p _ => measurableSet_czCube p) (czIdx_pairwiseDisjoint hn hs hf),
    lintegral_biUnion czIdx_countable
    (fun p _ => measurableSet_czCube p) (czIdx_pairwiseDisjoint hn hs hf)]
  refine ENNReal.tsum_le_tsum fun p => ?_
  calc ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)), ‖czGood f s y‖ₑ
      = ∫⁻ _ in czCube (p : ℤ × (Fin n → ℤ)), ‖czAvg f p‖ₑ :=
        setLIntegral_congr_fun (measurableSet_czCube _) fun y hy => by
          rw [czGood_of_mem_czCube hn hs hf p.2 hy]
    _ = ‖czAvg f p‖ₑ * volume (czCube (p : ℤ × (Fin n → ℤ))) := setLIntegral_const _ _
    _ ≤ _ := enorm_czAvg_mul_le _

/-- `∫ ‖g‖ ≤ ∫ ‖f‖`. -/
lemma lintegral_czGood_le : ∫⁻ y, ‖czGood f s y‖ₑ ≤ ∫⁻ y, ‖f y‖ₑ := by
  have hΩ := measurableSet_czBadSet hn hs hf
  rw [← lintegral_add_compl _ hΩ, ← lintegral_add_compl (fun y => ‖f y‖ₑ) hΩ]
  refine add_le_add (setLIntegral_czGood_le hn hs hf) (le_of_eq ?_)
  exact setLIntegral_congr_fun hΩ.compl fun y hy => by rw [czGood_of_notMem hy]

/-- `∫ ‖g‖² ≤ 2^n s ∫ ‖f‖`. -/
lemma lintegral_czGood_sq_le (hfi : Integrable f) :
    ∫⁻ y, ‖czGood f s y‖ₑ ^ (2 : ℝ) ≤ 2 ^ n * ENNReal.ofReal s * ∫⁻ y, ‖f y‖ₑ := by
  calc ∫⁻ y, ‖czGood f s y‖ₑ ^ (2 : ℝ)
      ≤ ∫⁻ y, 2 ^ n * ENNReal.ofReal s * ‖czGood f s y‖ₑ := by
        refine lintegral_mono_ae ((ae_enorm_czGood_le hn hs hf hfi).mono fun y hy => ?_)
        rw [ENNReal.rpow_two, sq]
        exact mul_le_mul_left hy _
    _ = 2 ^ n * ENNReal.ofReal s * ∫⁻ y, ‖czGood f s y‖ₑ :=
        lintegral_const_mul' _ _ (by simp [ENNReal.mul_eq_top])
    _ ≤ 2 ^ n * ENNReal.ofReal s * ∫⁻ y, ‖f y‖ₑ := by
        exact mul_le_mul_right (lintegral_czGood_le hn hs hf) _

/-- The mean-zero property of the bad part: `∫_Q (f - g) = 0` on every selected cube. -/
lemma setIntegral_czBad_eq_zero (hfi : Integrable f) {p : ℤ × (Fin n → ℤ)}
    (hp : p ∈ czIdx f s) : ∫ y in czCube p, (f - czGood f s) y = 0 := by
  have hg : ∫ y in czCube p, czGood f s y = ∫ y in czCube p, f y := by
    rw [← setIntegral_czAvg (f := f) p]
    exact setIntegral_congr_fun (measurableSet_czCube p) fun y hy =>
      czGood_of_mem_czCube hn hs hf hp hy
  have hgi : IntegrableOn (czGood f s) (czCube p) := by
    refine (integrableOn_congr_fun (fun y hy => (czGood_of_mem_czCube hn hs hf hp hy).symm)
      (measurableSet_czCube p)).1 ?_
    exact integrableOn_const (volume_czCube_ne_top p)
  simp only [Pi.sub_apply]
  rw [integral_sub hfi.integrableOn hgi, hg, sub_self]

omit hn hs hf in
/-- The bad part vanishes off `Ω`. -/
lemma czBad_eq_zero_of_notMem {x : EuclideanSpace ℝ (Fin n)} (hx : x ∉ czBadSet f s) :
    (f - czGood f s) x = 0 := by
  simp [czGood_of_notMem hx]

/-- `|Ω*| ≤ (4√n)^n |Ω|`. -/
lemma volume_czStar_le :
    volume (czStar f s) ≤ ENNReal.ofReal ((4 * Real.sqrt n) ^ n) * volume (czBadSet f s) := by
  rw [czBadSet_eq_biUnion hn hs hf, measure_biUnion czIdx_countable
    (czIdx_pairwiseDisjoint hn hs hf) fun p _ => measurableSet_czCube p, ← ENNReal.tsum_mul_left]
  refine (measure_biUnion_le _ czIdx_countable _).trans (ENNReal.tsum_le_tsum fun p => ?_)
  refine (volume_closedBall_le_euclidean _ (by positivity)).trans_eq ?_
  rw [volume_czCube, ← ENNReal.ofReal_pow (zpow_pos two_pos _).le,
    ← ENNReal.ofReal_mul (by positivity)]
  congr 1
  ring

omit hn hs hf in
lemma measurableSet_czStar : MeasurableSet (czStar f s) :=
  MeasurableSet.biUnion czIdx_countable fun _ _ => measurableSet_closedBall

end Decomposition

/-! ## The Hörmander condition from the gradient bound -/

section Hormander

variable {n : ℕ}

/-- The constant `2^{2n+1} · 2^{n+2} 5^n` of the Hörmander estimate
`∫_{|x - c| > 2δ} |H(x - y) - H(x - c)| dx ≤ C_n A` for `|y - c| ≤ δ`. -/
def czHormConst (n : ℕ) : ℝ := 2 ^ (2 * n + 1) * (2 ^ (n + 2) * 5 ^ n)

lemma czHormConst_nonneg (n : ℕ) : 0 ≤ czHormConst n := by unfold czHormConst; positivity

/-- Mean value estimate: for `|y - c| ≤ δ` and `|x - c| > 2δ`,
`|H(x - y) - H(x - c)| ≤ A 2^{n+1} δ |x - c|^{-n-1}`. -/
lemma norm_sub_le_of_norm_fderiv_le {H : EuclideanSpace ℝ (Fin n) → ℂ} {A : ℝ} (hA : 0 ≤ A)
    (hdiff : ∀ x ≠ 0, DifferentiableAt ℝ H x)
    (hgrad : ∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1)) {x y c : EuclideanSpace ℝ (Fin n)}
    {δ : ℝ} (hy : ‖y - c‖ ≤ δ) (hx : 2 * δ < ‖x - c‖) :
    ‖H (x - y) - H (x - c)‖ ≤ A * 2 ^ (n + 1) * δ / ‖x - c‖ ^ (n + 1) := by
  set u₀ := x - c with hu₀_def
  have hδ0 : 0 ≤ δ := (norm_nonneg _).trans hy
  have hu₀ : 0 < ‖u₀‖ := by linarith
  have hlow : ∀ u ∈ closedBall u₀ δ, ‖u₀‖ / 2 ≤ ‖u‖ := by
    intro u hu
    have h1 := norm_sub_norm_le u₀ u
    rw [mem_closedBall_iff_norm'] at hu
    linarith
  have hne : ∀ u ∈ closedBall u₀ δ, u ≠ 0 := by
    intro u hu h0
    have := hlow u hu
    rw [h0, norm_zero] at this
    linarith
  have hbound : ∀ u ∈ closedBall u₀ δ, ‖fderiv ℝ H u‖ ≤ A * 2 ^ (n + 1) / ‖u₀‖ ^ (n + 1) := by
    intro u hu
    refine (hgrad u (hne u hu)).trans ?_
    calc A / ‖u‖ ^ (n + 1) ≤ A / (‖u₀‖ / 2) ^ (n + 1) :=
          div_le_div_of_nonneg_left hA (by positivity)
            (pow_le_pow_left₀ (by positivity) (hlow u hu) _)
      _ = A * 2 ^ (n + 1) / ‖u₀‖ ^ (n + 1) := by rw [div_pow]; field_simp
  have hmem : x - y ∈ closedBall u₀ δ := by
    rw [mem_closedBall_iff_norm, hu₀_def, sub_sub_sub_cancel_left, norm_sub_rev]
    exact hy
  have hmvt := (convex_closedBall u₀ δ).norm_image_sub_le_of_norm_fderiv_le
    (fun u hu => hdiff u (hne u hu)) hbound (mem_closedBall_self hδ0) hmem
  calc ‖H (x - y) - H (x - c)‖ ≤ A * 2 ^ (n + 1) / ‖u₀‖ ^ (n + 1) * ‖x - y - u₀‖ := hmvt
    _ ≤ A * 2 ^ (n + 1) / ‖u₀‖ ^ (n + 1) * δ :=
        mul_le_mul_of_nonneg_left (mem_closedBall_iff_norm.1 hmem) (by positivity)
    _ = A * 2 ^ (n + 1) * δ / ‖x - c‖ ^ (n + 1) := by ring

/-- Comparison with the envelope: `δ |u|^{-n-1} ≤ 2^n B_{2δ}(u)` for `|u| ≥ 2δ > 0`. -/
private lemma div_pow_le_envelope {δ : ℝ} (hδ : 0 < δ) {u : EuclideanSpace ℝ (Fin n)}
    (hu : 2 * δ ≤ ‖u‖) : δ / ‖u‖ ^ (n + 1) ≤ 2 ^ n * envelope n (2 * δ) u := by
  have hu0 : 0 < ‖u‖ := by linarith
  rw [envelope_eq_div (by positivity), mul_div_assoc', div_le_div_iff₀ (by positivity)
    (by positivity)]
  calc δ * (2 * δ + ‖u‖) ^ (n + 1) ≤ δ * (2 * ‖u‖) ^ (n + 1) :=
        mul_le_mul_of_nonneg_left (pow_le_pow_left₀ (by positivity) (by linarith) _) hδ.le
    _ = 2 ^ n * (2 * δ) * ‖u‖ ^ (n + 1) := by rw [mul_pow, pow_succ]; ring

/-- **Hörmander's condition** from the gradient bound `|∇H(x)| ≤ A |x|^{-n-1}`: for
`|y - c| ≤ δ`, `∫_{|x - c| > 2δ} |H(x - y) - H(x - c)| dx ≤ C_n A`, with
`C_n = czHormConst n`. -/
theorem lintegral_compl_closedBall_enorm_sub_le {H : EuclideanSpace ℝ (Fin n) → ℂ} {A : ℝ}
    (hA : 0 ≤ A) (hdiff : ∀ x ≠ 0, DifferentiableAt ℝ H x)
    (hgrad : ∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1)) {y c : EuclideanSpace ℝ (Fin n)}
    {δ : ℝ} (hδ : 0 < δ) (hy : ‖y - c‖ ≤ δ) :
    ∫⁻ x in (closedBall c (2 * δ))ᶜ, ‖H (x - y) - H (x - c)‖ₑ ≤
      ENNReal.ofReal (czHormConst n * A) := by
  set K : ℝ := A * 2 ^ (2 * n + 1)
  have hK : 0 ≤ K := by positivity
  calc ∫⁻ x in (closedBall c (2 * δ))ᶜ, ‖H (x - y) - H (x - c)‖ₑ
      ≤ ∫⁻ x in (closedBall c (2 * δ))ᶜ, ENNReal.ofReal (K * envelope n (2 * δ) (x - c)) := by
        refine setLIntegral_mono' measurableSet_closedBall.compl fun x hx => ?_
        have hx' : 2 * δ < ‖x - c‖ := by
          simpa [mem_closedBall, dist_eq_norm] using hx
        rw [← ofReal_norm]
        refine ENNReal.ofReal_le_ofReal ((norm_sub_le_of_norm_fderiv_le hA hdiff hgrad hy
          hx').trans ?_)
        have h := div_pow_le_envelope hδ hx'.le
        calc A * 2 ^ (n + 1) * δ / ‖x - c‖ ^ (n + 1)
            = A * 2 ^ (n + 1) * (δ / ‖x - c‖ ^ (n + 1)) := by ring
          _ ≤ A * 2 ^ (n + 1) * (2 ^ n * envelope n (2 * δ) (x - c)) :=
              mul_le_mul_of_nonneg_left h (by positivity)
          _ = K * envelope n (2 * δ) (x - c) := by simp only [K]; ring
    _ ≤ ∫⁻ x, ENNReal.ofReal (K * envelope n (2 * δ) (x - c)) := setLIntegral_le_lintegral _ _
    _ = ENNReal.ofReal K * ∫⁻ x, ENNReal.ofReal (envelope n (2 * δ) x) := by
        simp_rw [ENNReal.ofReal_mul hK]
        rw [lintegral_const_mul' _ _ ENNReal.ofReal_ne_top]
        congr 1
        exact lintegral_sub_right_eq_self (fun x => ENNReal.ofReal (envelope n (2 * δ) x)) c
    _ ≤ ENNReal.ofReal K * ENNReal.ofReal (envelopeConst n) :=
        mul_le_mul_right (lintegral_envelope_le (by positivity)) _
    _ = ENNReal.ofReal (czHormConst n * A) := by
        rw [← ENNReal.ofReal_mul hK]
        congr 1
        simp only [K, czHormConst, envelopeConst]
        ring

end Hormander

/-! ## The weak type `(1,1)` estimate -/

section WeakOne

variable {n : ℕ}

/-- Convolution in the form `H * g(x) = ∫ H(x - y) g(y) dy`. -/
lemma convolution_eq_integral_sub (H g : EuclideanSpace ℝ (Fin n) → ℂ)
    (x : EuclideanSpace ℝ (Fin n)) :
    (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) x = ∫ y, H (x - y) * g y := by
  rw [convolution_def]
  simp only [ContinuousLinearMap.mul_apply']
  rw [← integral_sub_left_eq_self (fun y => H (x - y) * g y) (μ := volume) x]
  simp only [sub_sub_cancel]

lemma integrable_mul_of_convolutionExistsAt {H g : EuclideanSpace ℝ (Fin n) → ℂ}
    {x : EuclideanSpace ℝ (Fin n)}
    (h : ConvolutionExistsAt H g x (ContinuousLinearMap.mul ℂ ℂ) volume) :
    Integrable (fun y => H (x - y) * g y) := by
  have := (show Integrable (fun t => (ContinuousLinearMap.mul ℂ ℂ) (H t) (g (x - t))) volume
    from h).comp_sub_left x
  simpa [ContinuousLinearMap.mul_apply', sub_sub_cancel] using this

/-- A function differentiable off the origin is measurable. -/
lemma measurable_of_differentiableAt_ne_zero {H : EuclideanSpace ℝ (Fin n) → ℂ}
    (hdiff : ∀ x ≠ 0, DifferentiableAt ℝ H x) : Measurable H :=
  measurable_of_continuousOn_compl_singleton 0 fun x hx =>
    (hdiff x hx).continuousAt.continuousWithinAt

variable {f : EuclideanSpace ℝ (Fin n) → ℂ} {s : ℝ}
variable (hn : 0 < n) (hs : 0 < s) (hf : ∫⁻ y, ‖f y‖ₑ ≠ ∞)
include hn hs hf

lemma integrable_czGood (hfm : Measurable f) : Integrable (czGood f s) :=
  ⟨(measurable_czGood hn hs hf hfm).aestronglyMeasurable,
    (lintegral_czGood_le hn hs hf).trans_lt hf.lt_top⟩

/-- Cancellation: `|H * b(x)| ≤ ∑_Q ∫_Q |H(x - y) - H(x - c_Q)| |b(y)| dy` wherever the
convolution integral converges. -/
lemma enorm_convolution_czBad_le (hfi : Integrable f) (hfm : Measurable f)
    {H : EuclideanSpace ℝ (Fin n) → ℂ} {x : EuclideanSpace ℝ (Fin n)}
    (hconv : ConvolutionExistsAt H (f - czGood f s) x (ContinuousLinearMap.mul ℂ ℂ) volume) :
    ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (f - czGood f s)) x‖ₑ ≤
      ∑' p : czIdx f s, ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)),
        ‖H (x - y) - H (x - czCorner p)‖ₑ * ‖(f - czGood f s) y‖ₑ := by
  set b := f - czGood f s with hb_def
  have hbi : Integrable b := hfi.sub (integrable_czGood hn hs hf hfm)
  have hint := integrable_mul_of_convolutionExistsAt hconv
  rw [convolution_eq_integral_sub,
    ← setIntegral_eq_integral_of_forall_compl_eq_zero (s := czBadSet f s) (fun y hy => by
      simp only [hb_def]; rw [czBad_eq_zero_of_notMem hy, mul_zero]),
    czBadSet_eq_biUnion hn hs hf, biUnion_eq_iUnion,
    integral_iUnion (fun p => measurableSet_czCube _)
      (fun (p q : czIdx f s) hpq => czIdx_pairwiseDisjoint hn hs hf p.2 q.2
        (Subtype.coe_injective.ne hpq)) hint.integrableOn]
  refine enorm_tsum_le_tsum_enorm.trans (ENNReal.tsum_le_tsum fun p => ?_)
  have hzero := setIntegral_czBad_eq_zero hn hs hf hfi p.2
  have heq : ∫ y in czCube (p : ℤ × (Fin n → ℤ)), H (x - y) * b y =
      ∫ y in czCube (p : ℤ × (Fin n → ℤ)), (H (x - y) - H (x - czCorner p)) * b y := by
    simp_rw [sub_mul]
    rw [integral_sub hint.integrableOn (hbi.integrableOn.const_mul _), integral_const_mul,
      hzero, mul_zero, sub_zero]
  rw [heq]
  refine (enorm_integral_le_lintegral_enorm _).trans_eq ?_
  exact lintegral_congr fun y => enorm_mul _ _

/-- The bad part estimate off the enlarged exceptional set:
`∫_{E ∖ Ω*} |H * b| ≤ C_n A ∫ |b|`. -/
theorem lintegral_compl_czStar_convolution_le (hfi : Integrable f) (hfm : Measurable f)
    {H : EuclideanSpace ℝ (Fin n) → ℂ} {A : ℝ} (hA : 0 ≤ A) (hH : Integrable H)
    (hdiff : ∀ x ≠ 0, DifferentiableAt ℝ H x)
    (hgrad : ∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1)) :
    ∫⁻ x in (czStar f s)ᶜ, ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (f - czGood f s)) x‖ₑ ≤
      ENNReal.ofReal (czHormConst n * A) * ∫⁻ y, ‖(f - czGood f s) y‖ₑ := by
  set b := f - czGood f s with hb_def
  have hHm : Measurable H := measurable_of_differentiableAt_ne_zero hdiff
  have hbm : Measurable b := hfm.sub (measurable_czGood hn hs hf hfm)
  have hbi : Integrable b := hfi.sub (integrable_czGood hn hs hf hfm)
  have hG : ∀ c : EuclideanSpace ℝ (Fin n), Measurable fun z : EuclideanSpace ℝ (Fin n) ×
      EuclideanSpace ℝ (Fin n) => ‖H (z.1 - z.2) - H (z.1 - c)‖ₑ * ‖b z.2‖ₑ := fun c =>
    ((hHm.comp (measurable_fst.sub measurable_snd)).sub
      (hHm.comp (measurable_fst.sub_const c))).enorm.mul (hbm.comp measurable_snd).enorm
  set F : czIdx f s → EuclideanSpace ℝ (Fin n) → ℝ≥0∞ := fun p x =>
    ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)), ‖H (x - y) - H (x - czCorner p)‖ₑ * ‖b y‖ₑ
  have hFm : ∀ p, Measurable (F p) := fun p => (hG (czCorner p)).lintegral_prod_right'
  have hae : ∀ᵐ x, ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) x‖ₑ ≤ ∑' p, F p x := by
    filter_upwards [ae_convolutionExistsAt_of_memLp le_rfl (memLp_one_iff_integrable.2 hH)
      (memLp_one_iff_integrable.2 hbi)] with x hx
    exact enorm_convolution_czBad_le hn hs hf hfi hfm hx
  set C := ENNReal.ofReal (czHormConst n * A)
  calc ∫⁻ x in (czStar f s)ᶜ, ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) x‖ₑ
      ≤ ∫⁻ x in (czStar f s)ᶜ, ∑' p, F p x := lintegral_mono_ae (ae_restrict_of_ae hae)
    _ = ∑' p, ∫⁻ x in (czStar f s)ᶜ, F p x := lintegral_tsum fun p => (hFm p).aemeasurable
    _ ≤ ∑' p : czIdx f s, C * ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)), ‖b y‖ₑ := by
        refine ENNReal.tsum_le_tsum fun p => ?_
        set c := czCorner (p : ℤ × (Fin n → ℤ))
        set δ := Real.sqrt n * (2 : ℝ) ^ (p : ℤ × (Fin n → ℤ)).1
        have hδ : 0 < δ := mul_pos (Real.sqrt_pos.2 (by exact_mod_cast hn)) (zpow_pos two_pos _)
        have hsub : (czStar f s)ᶜ ⊆ (closedBall c (2 * δ))ᶜ :=
          compl_subset_compl.2 (subset_biUnion_of_mem (u := fun p : ℤ × (Fin n → ℤ) =>
            closedBall (czCorner p) (2 * (Real.sqrt n * (2 : ℝ) ^ p.1))) p.2)
        calc ∫⁻ x in (czStar f s)ᶜ, F p x ≤ ∫⁻ x in (closedBall c (2 * δ))ᶜ, F p x :=
              lintegral_mono_set hsub
          _ = ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)), ∫⁻ x in (closedBall c (2 * δ))ᶜ,
                ‖H (x - y) - H (x - c)‖ₑ * ‖b y‖ₑ :=
              lintegral_lintegral_swap (hG c).aemeasurable
          _ = ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)),
                (∫⁻ x in (closedBall c (2 * δ))ᶜ, ‖H (x - y) - H (x - c)‖ₑ) * ‖b y‖ₑ := by
              refine lintegral_congr fun y => ?_
              exact lintegral_mul_const _ (((hHm.comp (measurable_id.sub_const y)).sub
                (hHm.comp (measurable_id.sub_const c))).enorm)
          _ ≤ ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)), C * ‖b y‖ₑ := by
              refine setLIntegral_mono' (measurableSet_czCube _) fun y hy => ?_
              exact mul_le_mul_left (lintegral_compl_closedBall_enorm_sub_le hA hdiff hgrad hδ
                (norm_sub_le_of_mem_czCube hy (czCorner_mem _))) _
          _ = C * ∫⁻ y in czCube (p : ℤ × (Fin n → ℤ)), ‖b y‖ₑ :=
              lintegral_const_mul _ hbm.enorm
    _ = C * ∫⁻ y in ⋃ p ∈ czIdx f s, czCube p, ‖b y‖ₑ := by
        rw [ENNReal.tsum_mul_left, lintegral_biUnion czIdx_countable
          (fun p _ => measurableSet_czCube p) (czIdx_pairwiseDisjoint hn hs hf)]
    _ ≤ C * ∫⁻ y, ‖b y‖ₑ := mul_le_mul_right (setLIntegral_le_lintegral _ _) _

omit hn hs hf

/-- The constant `C_n = (4√n)^n + 4·2^n + 4 · czHormConst n` of the weak type `(1,1)` bound
(Blueprint Lemma 4.2 (`lem:cz`)). -/
def czWeakConst (n : ℕ) : ℝ := (4 * Real.sqrt n) ^ n + 4 * 2 ^ n + 4 * czHormConst n

lemma czWeakConst_pos (n : ℕ) : 0 < czWeakConst n := by
  have := czHormConst_nonneg n
  unfold czWeakConst; positivity

/-- Chebyshev: `μ{τ < |u|} ≤ τ⁻¹ ∫ |u|`. -/
lemma measure_lt_norm_le_lintegral {α : Type*} [MeasurableSpace α] {μ : Measure α}
    {u : α → ℂ} (hu : AEStronglyMeasurable u μ) {τ : ℝ} (hτ : 0 < τ) :
    μ {x | τ < ‖u x‖} ≤ ENNReal.ofReal τ⁻¹ * ∫⁻ x, ‖u x‖ₑ ∂μ := by
  refine (measure_mono fun x (hx : τ < ‖u x‖) => (show ENNReal.ofReal τ ≤ ‖u x‖ₑ by
    rw [← ofReal_norm]; exact ENNReal.ofReal_le_ofReal hx.le)).trans
    ((meas_ge_le_lintegral_div hu.enorm (ENNReal.ofReal_pos.2 hτ).ne'
      ENNReal.ofReal_ne_top).trans_eq ?_)
  rw [div_eq_mul_inv, mul_comm, ENNReal.ofReal_inv_of_pos hτ]

/-- Chebyshev: `μ{τ < |u|} ≤ τ⁻² ∫ |u|²`. -/
lemma measure_lt_norm_le_lintegral_sq {α : Type*} [MeasurableSpace α] {μ : Measure α}
    {u : α → ℂ} (hu : AEStronglyMeasurable u μ) {τ : ℝ} (hτ : 0 < τ) :
    μ {x | τ < ‖u x‖} ≤ ENNReal.ofReal (τ ^ 2)⁻¹ * ∫⁻ x, ‖u x‖ₑ ^ (2 : ℝ) ∂μ := by
  have hτ2 : 0 < τ ^ 2 := by positivity
  refine (measure_mono fun x (hx : τ < ‖u x‖) =>
    (show ENNReal.ofReal (τ ^ 2) ≤ ‖u x‖ₑ ^ (2 : ℝ) by
      rw [← ofReal_norm, ENNReal.rpow_two, ← ENNReal.ofReal_pow (norm_nonneg _)]
      exact ENNReal.ofReal_le_ofReal (pow_le_pow_left₀ hτ.le hx.le 2))).trans
    ((meas_ge_le_lintegral_div (hu.enorm.pow_const _) (ENNReal.ofReal_pos.2 hτ2).ne'
      ENNReal.ofReal_ne_top).trans_eq ?_)
  rw [div_eq_mul_inv, mul_comm, ENNReal.ofReal_inv_of_pos hτ2]

/-- The weak type `(1,1)` estimate for `A > 0` and measurable `f`. -/
theorem volume_lt_norm_convolution_le_of_pos (hn : 0 < n) {H : EuclideanSpace ℝ (Fin n) → ℂ}
    {A : ℝ} (hA : 0 < A) (hH : Integrable H) (hdiff : ∀ x ≠ 0, DifferentiableAt ℝ H x)
    (hgrad : ∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1))
    (hL2 : ∀ g : EuclideanSpace ℝ (Fin n) → ℂ, MemLp g 2 volume →
      eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
        ENNReal.ofReal A * eLpNorm g 2 volume)
    {f : EuclideanSpace ℝ (Fin n) → ℂ} (hfi : Integrable f) (hfm : Measurable f) {t : ℝ}
    (ht : 0 < t) :
    volume {x | t < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) x‖} ≤
      ENNReal.ofReal (czWeakConst n * A / t) * ∫⁻ y, ‖f y‖ₑ := by
  set s := t / A with hs_def
  have hs : 0 < s := div_pos ht hA
  have hf : ∫⁻ y, ‖f y‖ₑ ≠ ∞ := hfi.2.ne
  set g := czGood f s with hg_def
  set b := f - g with hb_def
  set F := ∫⁻ y, ‖f y‖ₑ with hF_def
  have hgi : Integrable g := integrable_czGood hn hs hf hfm
  have hbi : Integrable b := hfi.sub hgi
  have hHi := memLp_one_iff_integrable.2 hH
  have hsplit : ∀ᵐ x, (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) x =
      (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) x +
        (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) x := by
    filter_upwards [ae_convolutionExistsAt_of_memLp le_rfl hHi (memLp_one_iff_integrable.2 hgi),
      ae_convolutionExistsAt_of_memLp le_rfl hHi (memLp_one_iff_integrable.2 hbi)] with x h1 h2
    rw [← h1.distrib_add h2]
    congr 2
    simp [hb_def]
  have hincl : {x | t < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) x‖} ≤ᵐ[volume]
      (({x | t / 2 < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) x‖} ∪
        ({x | t / 2 < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) x‖} ∩ (czStar f s)ᶜ)) ∪
          czStar f s : Set _) := by
    filter_upwards [hsplit] with x hx
    intro hxt
    have hxt' : t < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) x +
        (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) x‖ := by rw [← hx]; exact hxt
    by_cases hstar : x ∈ czStar f s
    · exact Or.inr hstar
    · left
      by_contra hc
      simp only [mem_union, mem_inter_iff, mem_compl_iff, mem_ofPred_eq, not_or, not_and,
        not_lt] at hc
      have := norm_add_le ((H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) x)
        ((H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) x)
      have hb' : ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) x‖ ≤ t / 2 :=
        not_lt.1 fun h => hc.2 h hstar
      linarith [hc.1]
  -- the exceptional set
  have hstar : volume (czStar f s) ≤ ENNReal.ofReal ((4 * Real.sqrt n) ^ n * A / t) * F := by
    refine (volume_czStar_le hn hs hf).trans
      ((mul_le_mul_right (volume_czBadSet_le hn hs hf) _).trans_eq ?_)
    rw [← ENNReal.ofReal_inv_of_pos hs, ← mul_assoc, ← ENNReal.ofReal_mul (by positivity)]
    congr 2
    rw [hs_def]
    field_simp
  -- the good part
  have hconvg : AEStronglyMeasurable (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) volume :=
    AEStronglyMeasurable.convolution (ContinuousLinearMap.mul ℂ ℂ) hH.1 hgi.1
  have hgsq := lintegral_czGood_sq_le hn hs hf hfi
  have hg2 : MemLp g 2 volume := by
    have h := (eLpNorm_two_rpow_two hgi.1).trans_le hgsq
    have hlt : eLpNorm g 2 volume ^ (2 : ℝ) < ∞ := h.trans_lt (by
      refine ENNReal.mul_lt_top (ENNReal.mul_lt_top ?_ ENNReal.ofReal_lt_top) hf.lt_top
      exact ENNReal.pow_lt_top ENNReal.ofNat_lt_top)
    exact (ENNReal.rpow_lt_top_iff_of_pos (by norm_num)).1 hlt
  have hgood : volume {x | t / 2 < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) x‖} ≤
      ENNReal.ofReal (4 * 2 ^ n * A / t) * F := by
    refine (measure_lt_norm_le_lintegral_sq hconvg (half_pos ht)).trans ?_
    rw [← eLpNorm_two_rpow_two hconvg]
    calc ENNReal.ofReal ((t / 2) ^ 2)⁻¹ *
          eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ^ (2 : ℝ)
        ≤ ENNReal.ofReal ((t / 2) ^ 2)⁻¹ *
            (ENNReal.ofReal A * eLpNorm g 2 volume) ^ (2 : ℝ) :=
          mul_le_mul_right (ENNReal.rpow_le_rpow (hL2 g hg2) (by norm_num)) _
      _ = ENNReal.ofReal ((t / 2) ^ 2)⁻¹ *
            (ENNReal.ofReal (A ^ 2) * ∫⁻ y, ‖g y‖ₑ ^ (2 : ℝ)) := by
          rw [ENNReal.mul_rpow_of_nonneg _ _ (by norm_num), eLpNorm_two_rpow_two hgi.1,
            ENNReal.rpow_two (ENNReal.ofReal A), ← ENNReal.ofReal_pow hA.le]
      _ ≤ ENNReal.ofReal ((t / 2) ^ 2)⁻¹ *
            (ENNReal.ofReal (A ^ 2) * (2 ^ n * ENNReal.ofReal s * F)) :=
          mul_le_mul_right (mul_le_mul_right hgsq _) _
      _ = ENNReal.ofReal (4 * 2 ^ n * A / t) * F := by
          rw [← ENNReal.ofReal_ofNat 2, ← ENNReal.ofReal_pow (by norm_num),
            ← ENNReal.ofReal_mul (by positivity), ← mul_assoc, ← mul_assoc,
            ← ENNReal.ofReal_mul (by positivity), ← ENNReal.ofReal_mul (by positivity)]
          congr 2
          rw [hs_def]
          field_simp
          ring
  -- the bad part
  have hb1 : ∫⁻ y, ‖b y‖ₑ ≤ 2 * F := by
    calc ∫⁻ y, ‖b y‖ₑ ≤ ∫⁻ y, (‖f y‖ₑ + ‖g y‖ₑ) :=
          lintegral_mono fun y => by simp only [hb_def, Pi.sub_apply]; exact enorm_sub_le
      _ = F + ∫⁻ y, ‖g y‖ₑ := lintegral_add_left' hfi.1.enorm _
      _ ≤ F + F := add_le_add le_rfl (lintegral_czGood_le hn hs hf)
      _ = 2 * F := (two_mul F).symm
  have hconvb : AEStronglyMeasurable (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) volume :=
    AEStronglyMeasurable.convolution (ContinuousLinearMap.mul ℂ ℂ) hH.1 hbi.1
  have hbad : volume ({x | t / 2 < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) x‖} ∩
      (czStar f s)ᶜ) ≤ ENNReal.ofReal (4 * czHormConst n * A / t) * F := by
    rw [← Measure.restrict_apply' measurableSet_czStar.compl]
    refine (measure_lt_norm_le_lintegral hconvb.restrict (half_pos ht)).trans ?_
    calc ENNReal.ofReal (t / 2)⁻¹ *
          ∫⁻ x in (czStar f s)ᶜ, ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) x‖ₑ
        ≤ ENNReal.ofReal (t / 2)⁻¹ *
            (ENNReal.ofReal (czHormConst n * A) * ∫⁻ y, ‖b y‖ₑ) :=
          mul_le_mul_right (lintegral_compl_czStar_convolution_le hn hs hf hfi hfm hA.le hH
            hdiff hgrad) _
      _ ≤ ENNReal.ofReal (t / 2)⁻¹ * (ENNReal.ofReal (czHormConst n * A) * (2 * F)) :=
          mul_le_mul_right (mul_le_mul_right hb1 _) _
      _ = ENNReal.ofReal (4 * czHormConst n * A / t) * F := by
          have := czHormConst_nonneg n
          rw [← ENNReal.ofReal_ofNat 2, ← mul_assoc, ← mul_assoc,
            ← ENNReal.ofReal_mul (by positivity), ← ENNReal.ofReal_mul (by positivity)]
          congr 2
          field_simp
          ring
  calc volume {x | t < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) x‖}
      ≤ volume ((({x | t / 2 < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) x‖} ∪
        ({x | t / 2 < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) x‖} ∩ (czStar f s)ᶜ)) ∪
          czStar f s : Set _)) := measure_mono_ae hincl
    _ ≤ volume {x | t / 2 < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) x‖} +
        volume ({x | t / 2 < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] b) x‖} ∩
          (czStar f s)ᶜ) + volume (czStar f s) :=
        (measure_union_le _ _).trans (add_le_add_left (measure_union_le _ _) _)
    _ ≤ ENNReal.ofReal (4 * 2 ^ n * A / t) * F +
        ENNReal.ofReal (4 * czHormConst n * A / t) * F +
        ENNReal.ofReal ((4 * Real.sqrt n) ^ n * A / t) * F :=
        add_le_add (add_le_add hgood hbad) hstar
    _ = ENNReal.ofReal (czWeakConst n * A / t) * F := by
        have := czHormConst_nonneg n
        rw [← add_mul, ← add_mul, ← ENNReal.ofReal_add (by positivity) (by positivity),
          ← ENNReal.ofReal_add (by positivity) (by positivity)]
        congr 2
        unfold czWeakConst
        ring

/-- Passage to the limit `ε → 0⁺` in bounds `X ≤ φ(ε) F` with `φ` continuous at `0`. -/
lemma le_ofReal_mul_of_forall_pos {X F : ℝ≥0∞} (hF : F ≠ ∞) {φ : ℝ → ℝ}
    (hφ : ContinuousAt φ 0) (h : ∀ ε : ℝ, 0 < ε → X ≤ ENNReal.ofReal (φ ε) * F) :
    X ≤ ENNReal.ofReal (φ 0) * F := by
  have h1 : Tendsto (fun m : ℕ => (1 : ℝ) / (m + 1)) atTop (𝓝 0) :=
    tendsto_one_div_add_atTop_nhds_zero_nat
  have h2 : Tendsto (fun m : ℕ => ENNReal.ofReal (φ (1 / (m + 1))) * F) atTop
      (𝓝 (ENNReal.ofReal (φ 0) * F)) :=
    ENNReal.Tendsto.mul_const ((ENNReal.continuous_ofReal.tendsto _).comp (hφ.tendsto.comp h1))
      (Or.inr hF)
  exact ge_of_tendsto' h2 fun m => h _ (by positivity)

/-- Monotonicity of the gradient hypothesis in `A`. -/
lemma norm_fderiv_le_of_le {H : EuclideanSpace ℝ (Fin n) → ℂ} {A A' : ℝ} (hAA : A ≤ A')
    (hgrad : ∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1)) :
    ∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A' / ‖x‖ ^ (n + 1) := fun x hx =>
  (hgrad x hx).trans (div_le_div_of_nonneg_right hAA (by positivity))

/-- Monotonicity of the `L²` hypothesis in `A`. -/
lemma eLpNorm_two_le_of_le {H : EuclideanSpace ℝ (Fin n) → ℂ} {A A' : ℝ} (hAA : A ≤ A')
    (hL2 : ∀ g : EuclideanSpace ℝ (Fin n) → ℂ, MemLp g 2 volume →
      eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
        ENNReal.ofReal A * eLpNorm g 2 volume) :
    ∀ g : EuclideanSpace ℝ (Fin n) → ℂ, MemLp g 2 volume →
      eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
        ENNReal.ofReal A' * eLpNorm g 2 volume := fun g hg =>
  (hL2 g hg).trans (mul_le_mul_left (ENNReal.ofReal_le_ofReal hAA) _)

/-- **Calderón–Zygmund theorem, weak type `(1,1)`** (Blueprint Lemma 4.2 (`lem:cz`), first
assertion). Let `n ≥ 1`, `E = ℝⁿ` with Lebesgue measure, and `H ∈ L¹(E)` differentiable off `0`
with `|∇H(x)| ≤ A |x|^{-n-1}` for `x ≠ 0`, such that convolution by `H` has `L²` operator norm
at most `A` (`‖H * g‖₂ ≤ A ‖g‖₂` for all `g ∈ L²`). Then for every `f ∈ L¹` and `t > 0`,
`|{x : |H * f(x)| > t}| ≤ C_n A t⁻¹ ‖f‖₁`, with `C_n = czWeakConst n` depending only on `n`
(not on `‖H‖₁`). The size bound `|H(x)| ≤ A|x|^{-n}` of the blueprint is not needed. -/
theorem volume_lt_norm_convolution_le (hn : 0 < n) {H : EuclideanSpace ℝ (Fin n) → ℂ}
    {A : ℝ} (hA : 0 ≤ A) (hH : Integrable H) (hdiff : ∀ x ≠ 0, DifferentiableAt ℝ H x)
    (hgrad : ∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1))
    (hL2 : ∀ g : EuclideanSpace ℝ (Fin n) → ℂ, MemLp g 2 volume →
      eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
        ENNReal.ofReal A * eLpNorm g 2 volume)
    {f : EuclideanSpace ℝ (Fin n) → ℂ} (hf : MemLp f 1 volume) {t : ℝ} (ht : 0 < t) :
    volume {x | t < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) x‖} ≤
      ENNReal.ofReal (czWeakConst n * A / t) * eLpNorm f 1 volume := by
  have hfi : Integrable f := memLp_one_iff_integrable.1 hf
  set f' := hfi.1.mk f
  have hff' : f =ᵐ[volume] f' := hfi.1.ae_eq_mk
  have hf'i : Integrable f' := hfi.congr hff'
  have hf'm : Measurable f' := hfi.1.stronglyMeasurable_mk.measurable
  have hconv : H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f =
      H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f' :=
    convolution_congr _ EventuallyEq.rfl hff'
  rw [hconv, eLpNorm_congr_ae hff', eLpNorm_one_eq_lintegral_enorm hf'i.1]
  have key := le_ofReal_mul_of_forall_pos hf'i.2.ne (φ := fun ε => czWeakConst n * (A + ε) / t)
    (by fun_prop) fun ε hε => volume_lt_norm_convolution_le_of_pos hn (by linarith) hH hdiff
      (norm_fderiv_le_of_le (by linarith) hgrad) (eLpNorm_two_le_of_le (by linarith) hL2) hf'i
      hf'm ht
  simpa using key

end WeakOne

/-! ## The adjoint kernel and duality -/

section Adjoint

variable {n : ℕ}

/-- The adjoint convolution kernel `H*(x) = conj (H(-x))`. -/
def czAdjoint (H : EuclideanSpace ℝ (Fin n) → ℂ) : EuclideanSpace ℝ (Fin n) → ℂ :=
  fun x => conj (H (-x))

lemma czAdjoint_czAdjoint (H : EuclideanSpace ℝ (Fin n) → ℂ) : czAdjoint (czAdjoint H) = H := by
  funext x; simp [czAdjoint]

lemma measurable_czAdjoint {H : EuclideanSpace ℝ (Fin n) → ℂ} (hH : Measurable H) :
    Measurable (czAdjoint H) :=
  Complex.continuous_conj.measurable.comp (hH.comp measurable_neg)

lemma integrable_czAdjoint {H : EuclideanSpace ℝ (Fin n) → ℂ} (hH : Integrable H)
    (hHm : Measurable H) : Integrable (czAdjoint H) := by
  have h0 : Integrable (fun x => H (0 - x)) := hH.comp_sub_left 0
  refine h0.norm.mono' (measurable_czAdjoint hHm).aestronglyMeasurable
    (Eventually.of_forall fun x => ?_)
  simp [czAdjoint]

lemma differentiableAt_czAdjoint {H : EuclideanSpace ℝ (Fin n) → ℂ}
    (hdiff : ∀ x ≠ 0, DifferentiableAt ℝ H x) :
    ∀ x ≠ 0, DifferentiableAt ℝ (czAdjoint H) x ∧ ‖fderiv ℝ (czAdjoint H) x‖ ≤ ‖fderiv ℝ H (-x)‖ := by
  intro x hx
  have h2 : HasFDerivAt H (fderiv ℝ H (-x)) (-x) :=
    (hdiff (-x) (neg_ne_zero.2 hx)).hasFDerivAt
  have h3 := h2.comp x ((hasFDerivAt_id x).neg)
  have h4 := (Complex.conjCLE : ℂ ≃L[ℝ] ℂ).hasFDerivAt.comp x h3
  have hfun : (⇑(Complex.conjCLE : ℂ ≃L[ℝ] ℂ) ∘ (H ∘ Neg.neg)) = czAdjoint H := by
    funext y; simp [czAdjoint]
  rw [hfun] at h4
  refine ⟨h4.differentiableAt, ?_⟩
  rw [h4.fderiv]
  refine ContinuousLinearMap.opNorm_le_bound _ (norm_nonneg _) fun v => ?_
  simp only [ContinuousLinearMap.coe_comp, Function.comp_apply, ContinuousLinearEquiv.coe_coe,
    Complex.conjCLE_apply, Complex.norm_conj, neg_apply,
    ContinuousLinearMap.coe_id', id_eq]
  calc ‖(fderiv ℝ H (-x)) (-v)‖ ≤ ‖fderiv ℝ H (-x)‖ * ‖-v‖ := ContinuousLinearMap.le_opNorm _ _
    _ = ‖fderiv ℝ H (-x)‖ * ‖v‖ := by rw [norm_neg]

/-- The adjoint kernel satisfies the same gradient bound. -/
lemma norm_fderiv_czAdjoint_le {H : EuclideanSpace ℝ (Fin n) → ℂ} {A : ℝ}
    (hdiff : ∀ x ≠ 0, DifferentiableAt ℝ H x)
    (hgrad : ∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1)) :
    ∀ x ≠ 0, ‖fderiv ℝ (czAdjoint H) x‖ ≤ A / ‖x‖ ^ (n + 1) := fun x hx =>
  ((differentiableAt_czAdjoint hdiff x hx).2).trans
    (by simpa [norm_neg] using hgrad (-x) (neg_ne_zero.2 hx))

/-- `∫∫ |K(x - y)| |f(y)| |φ(x)| dy dx < ∞` for `K ∈ L¹`, `f ∈ L^p`, `φ ∈ L^q`. -/
lemma lintegral_triple_lt_top {K f φ : EuclideanSpace ℝ (Fin n) → ℂ} (hK : Integrable K)
    {p q : ℝ} (hpq : p.HolderConjugate q) (hf : MemLp f (ENNReal.ofReal p) volume)
    (hφ : MemLp φ (ENNReal.ofReal q) volume) :
    ∫⁻ x, ‖φ x‖ₑ * ∫⁻ y, ‖K y‖ₑ * ‖f (x - y)‖ₑ < ∞ := by
  have hp1 : 1 ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hpq.lt.le
  set U := fun x => ∫⁻ y, ‖K y‖ₑ * ‖f (x - y)‖ₑ
  have hUm : AEMeasurable U volume :=
    aemeasurable_lintegral_mul_sub hK.1.enorm hf.aestronglyMeasurable.enorm
  have hU : eLpNorm U (ENNReal.ofReal p) volume < ∞ :=
    (eLpNorm_lintegral_enorm_mul_sub_le hp1 hK.1 hf.aestronglyMeasurable).trans_lt
      (ENNReal.mul_lt_top (by rw [← memLp_one_iff_integrable] at hK; exact hK) hf)
  have hUi : ∫⁻ x, U x ^ p ∂volume < ∞ := by
    have := lintegral_rpow_enorm_lt_top_of_eLpNorm_lt_top (by simpa using hpq.pos)
      ENNReal.ofReal_ne_top hU
    simpa [enorm_eq_self, ENNReal.toReal_ofReal hpq.nonneg] using this
  have hφi : ∫⁻ x, ‖φ x‖ₑ ^ q ∂volume < ∞ := by
    have := lintegral_rpow_enorm_lt_top_of_eLpNorm_lt_top (by simpa using hpq.symm.pos)
      ENNReal.ofReal_ne_top hφ
    simpa [ENNReal.toReal_ofReal hpq.symm.nonneg] using this
  calc ∫⁻ x, ‖φ x‖ₑ * U x = ∫⁻ x, (U * fun x => ‖φ x‖ₑ) x := by
        congr 1; funext x; simp [mul_comm]
    _ ≤ (∫⁻ x, U x ^ p) ^ (1 / p) * (∫⁻ x, ‖φ x‖ₑ ^ q) ^ (1 / q) :=
        ENNReal.lintegral_mul_le_Lp_mul_Lq volume hpq hUm hφ.aestronglyMeasurable.enorm
    _ < ∞ := ENNReal.mul_lt_top (ENNReal.rpow_lt_top_of_nonneg (by have := hpq.pos; positivity)
        hUi.ne) (ENNReal.rpow_lt_top_of_nonneg (by have := hpq.symm.pos; positivity) hφi.ne)

/-- **Duality for convolutions**: `∫ (K * f) φ̄ = ∫ f (K* * φ)‾` for `K ∈ L¹` measurable,
`f ∈ L^p`, `φ ∈ L^q` (Hölder conjugate exponents). -/
theorem integral_convolution_mul_conj {K f φ : EuclideanSpace ℝ (Fin n) → ℂ} (hK : Integrable K)
    (hKm : Measurable K) {p q : ℝ} (hpq : p.HolderConjugate q)
    (hf : MemLp f (ENNReal.ofReal p) volume) (hφ : MemLp φ (ENNReal.ofReal q) volume) :
    ∫ x, (K ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) x * conj (φ x) =
      ∫ y, f y * conj ((czAdjoint K ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] φ) y) := by
  set F : EuclideanSpace ℝ (Fin n) → EuclideanSpace ℝ (Fin n) → ℂ :=
    fun x y => K (x - y) * f y * conj (φ x)
  have hFm : AEStronglyMeasurable (Function.uncurry F) (volume.prod volume) := by
    refine ((hKm.comp (measurable_fst.sub measurable_snd)).aestronglyMeasurable.mul
      (hf.aestronglyMeasurable.comp_snd)).mul ?_
    exact (Complex.continuous_conj.comp_aestronglyMeasurable hφ.aestronglyMeasurable).comp_fst
  have hFi : Integrable (Function.uncurry F) (volume.prod volume) := by
    refine ⟨hFm, ?_⟩
    rw [HasFiniteIntegral, lintegral_prod _ hFm.enorm]
    refine lt_of_eq_of_lt ?_ (lintegral_triple_lt_top hK hpq hf hφ)
    refine lintegral_congr fun x => ?_
    simp only [Function.uncurry_apply_pair, F, enorm_mul, RCLike.enorm_conj]
    have hm : AEMeasurable (fun y => ‖K (x - y)‖ₑ * ‖f y‖ₑ) volume :=
      (hKm.comp (measurable_const.sub measurable_id)).enorm.aemeasurable.mul
        hf.aestronglyMeasurable.enorm
    rw [lintegral_mul_const'' _ hm, mul_comm,
      ← lintegral_sub_left_eq_self (fun y => ‖K y‖ₑ * ‖f (x - y)‖ₑ) x]
    congr 1
    simp only [sub_sub_cancel]
  have hL : ∀ x, (K ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) x * conj (φ x) = ∫ y, F x y := by
    intro x
    rw [convolution_eq_integral_sub, ← integral_mul_const]
  have hR : ∀ y, f y * conj ((czAdjoint K ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] φ) y) =
      ∫ x, F x y := by
    intro y
    rw [convolution_eq_integral_sub, ← integral_conj, ← integral_const_mul]
    refine integral_congr_ae (Eventually.of_forall fun x => ?_)
    simp only [F, czAdjoint, map_mul, Complex.conj_conj, neg_sub]
    ring
  simp_rw [hL, hR]
  exact integral_integral_swap hFi

/-- The adjoint kernel inherits the `L²` bound, by duality. -/
lemma eLpNorm_czAdjoint_convolution_two_le {H : EuclideanSpace ℝ (Fin n) → ℂ} {A : ℝ}
    (hH : Integrable H) (hHm : Measurable H)
    (hL2 : ∀ g : EuclideanSpace ℝ (Fin n) → ℂ, MemLp g 2 volume →
      eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
        ENNReal.ofReal A * eLpNorm g 2 volume) :
    ∀ g : EuclideanSpace ℝ (Fin n) → ℂ, MemLp g 2 volume →
      eLpNorm (czAdjoint H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
        ENNReal.ofReal A * eLpNorm g 2 volume := by
  intro g hg
  have h22 : (2 : ℝ).HolderConjugate 2 := Real.HolderConjugate.two_two
  have e2 : ENNReal.ofReal 2 = 2 := ENNReal.ofReal_ofNat 2
  have hg' : MemLp g (ENNReal.ofReal 2) volume := by rwa [e2]
  have hHa := integrable_czAdjoint hH hHm
  have hHam := measurable_czAdjoint hHm
  have key := eLpNorm_le_of_dual_test h22 (h := czAdjoint H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g)
    (AEStronglyMeasurable.convolution _ hHa.1 hg.aestronglyMeasurable)
    (A := ENNReal.ofReal A * eLpNorm g 2 volume) ?_
  · rwa [e2] at key
  intro φ _ _ _ hφ2 _
  have hφ2' : MemLp φ (ENNReal.ofReal 2) volume := hφ2.trans_lt ENNReal.one_lt_top
  rw [integral_convolution_mul_conj hHa hHam h22 hg' hφ2', czAdjoint_czAdjoint]
  rw [e2] at hφ2 hφ2'
  calc ‖∫ y, g y * conj ((H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] φ) y)‖ₑ
      ≤ eLpNorm g (ENNReal.ofReal 2) volume *
          eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] φ) (ENNReal.ofReal 2) volume :=
        enorm_integral_mul_conj_le h22 hg.aestronglyMeasurable
          (AEStronglyMeasurable.convolution _ hH.1 hφ2'.aestronglyMeasurable)
    _ ≤ eLpNorm g 2 volume * (ENNReal.ofReal A * eLpNorm φ 2 volume) := by
        rw [e2]; exact mul_le_mul_right (hL2 φ hφ2') _
    _ ≤ eLpNorm g 2 volume * (ENNReal.ofReal A * 1) :=
        mul_le_mul_right (mul_le_mul_right hφ2 _) _
    _ = ENNReal.ofReal A * eLpNorm g 2 volume := by rw [mul_one, mul_comm]

end Adjoint

/-! ## Strong type `(p,p)` bounds -/

section Strong

variable {n : ℕ}

/-- The hypotheses of the Calderón–Zygmund theorem, with constant `A`, for the kernel `H`. -/
private abbrev CZHyp (n : ℕ) (H : EuclideanSpace ℝ (Fin n) → ℂ) (A : ℝ) : Prop :=
  Integrable H ∧ (∀ x ≠ 0, DifferentiableAt ℝ H x) ∧
    (∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1)) ∧
    ∀ g : EuclideanSpace ℝ (Fin n) → ℂ, MemLp g 2 volume →
      eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
        ENNReal.ofReal A * eLpNorm g 2 volume

/-- `L^p` bounds for `1 < p < 2`, for `A > 0`, by Marcinkiewicz interpolation between the weak
type `(1,1)` estimate and the `L²` hypothesis. -/
private lemma exists_eLpNorm_convolution_le_of_lt_two (hn : 0 < n) {p : ℝ} (hp1 : 1 < p) (hp2 : p < 2) :
    ∃ K : ℝ, 0 < K ∧ ∀ (H : EuclideanSpace ℝ (Fin n) → ℂ) (A : ℝ), 0 < A → CZHyp n H A →
      ∀ f : EuclideanSpace ℝ (Fin n) → ℂ, MemLp f (ENNReal.ofReal p) volume →
        eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) (ENNReal.ofReal p) volume ≤
          ENNReal.ofReal (K * A) * eLpNorm f (ENNReal.ofReal p) volume := by
  set θ : ℝ := 2 - 2 / p with hθ_def
  have hp0 : 0 < p := by linarith
  have hθ0 : 0 ≤ θ := by
    rw [hθ_def, sub_nonneg, div_le_iff₀ hp0]; linarith
  have hθ1 : 0 ≤ 1 - θ := by
    rw [hθ_def, show 1 - (2 - 2 / p) = 2 / p - 1 by ring, sub_nonneg, le_div_iff₀ hp0]; linarith
  set M : ℝ := (marcinkiewiczConst 1 2 p : ℝ)
  have hM : 0 ≤ M := NNReal.coe_nonneg _
  set Cw := czWeakConst n
  have hCw := czWeakConst_pos n
  refine ⟨M * Cw ^ (1 - θ) + 1, by positivity, fun H A hA ⟨hH, hdiff, hgrad, hL2⟩ f hf => ?_⟩
  have hp1' : 1 ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hp1.le
  have hHi := memLp_one_iff_integrable.2 hH
  set T : (EuclideanSpace ℝ (Fin n) → ℂ) → EuclideanSpace ℝ (Fin n) → ℂ :=
    fun g => H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g
  set D : Set (EuclideanSpace ℝ (Fin n) → ℂ) := {g | MemLp g (ENNReal.ofReal p) volume}
  set A₁ : ℝ≥0 := Real.toNNReal (Cw * A)
  set A₂ : ℝ≥0 := Real.toNNReal A
  have hA₁ : (A₁ : ℝ≥0∞) = ENNReal.ofReal (Cw * A) := rfl
  have hA₂ : (A₂ : ℝ≥0∞) = ENNReal.ofReal A := rfl
  have hA₁0 : (A₁ : ℝ≥0∞) ≠ 0 := by
    rw [hA₁]; exact (ENNReal.ofReal_pos.2 (mul_pos hCw hA)).ne'
  have hA₂0 : (A₂ : ℝ≥0∞) ≠ 0 := by rw [hA₂]; exact (ENNReal.ofReal_pos.2 hA).ne'
  have hT1 : HasWeakTypeOn T D 1 A₁ volume volume := by
    refine hasWeakTypeOn_of_forall_real fun g _ t ht => ?_
    rw [ENNReal.rpow_one, ENNReal.ofReal_one]
    by_cases hg1 : MemLp g 1 volume
    · refine (volume_lt_norm_convolution_le hn hA.le hH hdiff hgrad hL2 hg1 ht).trans_eq ?_
      rw [ENNReal.ofReal_div_of_pos ht, hA₁, div_eq_mul_inv, div_eq_mul_inv]
      ring
    · rw [not_lt_top_iff.1 hg1, ENNReal.mul_top hA₁0, ENNReal.top_div_of_ne_top
        ENNReal.ofReal_ne_top]
      exact le_top
  have hT2 : HasWeakTypeOn T D 2 A₂ volume volume := by
    refine HasStrongTypeOn.hasWeakTypeOn two_pos fun g _ => ?_
    rw [ENNReal.ofReal_ofNat]
    by_cases hg2 : MemLp g 2 volume
    · rw [hA₂]; exact hL2 g hg2
    · rw [not_lt_top_iff.1 hg2, ENNReal.mul_top hA₂0]; exact le_top
  have hsub : IsSublinearOn T D volume := by
    intro g hg g' hg'
    filter_upwards [ae_convolutionExistsAt_of_memLp hp1' hHi hg,
      ae_convolutionExistsAt_of_memLp hp1' hHi hg'] with x h1 h2
    simp only [T]
    rw [h1.distrib_add h2]
    exact norm_add_le _ _
  have hmain := eLpNorm_le_of_hasWeakTypeOn (a := 1) (b := 2) (p := p) (θ := θ) one_pos hp1 hp2
    (by rw [hθ_def]; field_simp; ring) hT1 hT2 hsub isTruncationClosed_memLp (f := f) hf
    hf.aestronglyMeasurable (AEStronglyMeasurable.convolution _ hH.1 hf.aestronglyMeasurable)
  refine hmain.trans (mul_le_mul_left ?_ _)
  rw [hA₁, hA₂, ENNReal.ofReal_rpow_of_nonneg (by positivity) hθ1,
    ENNReal.ofReal_rpow_of_nonneg hA.le hθ0, show (marcinkiewiczConst 1 2 p : ℝ≥0∞) =
      ENNReal.ofReal M from (ENNReal.ofReal_coe_nnreal).symm,
    ← ENNReal.ofReal_mul hM, ← ENNReal.ofReal_mul (by positivity)]
  refine ENNReal.ofReal_le_ofReal ?_
  rw [Real.mul_rpow hCw.le hA.le, mul_assoc, mul_assoc, ← Real.rpow_add hA,
    show 1 - θ + θ = 1 by ring, Real.rpow_one]
  nlinarith

/-- `L^p` bounds for `2 < p < ∞`, for `A > 0`, by duality with the adjoint kernel at the
conjugate exponent `p' < 2`. -/
private lemma exists_eLpNorm_convolution_le_of_two_lt (hn : 0 < n) {p : ℝ} (hp : 2 < p) :
    ∃ K : ℝ, 0 < K ∧ ∀ (H : EuclideanSpace ℝ (Fin n) → ℂ) (A : ℝ), 0 < A → CZHyp n H A →
      ∀ f : EuclideanSpace ℝ (Fin n) → ℂ, MemLp f (ENNReal.ofReal p) volume →
        eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) (ENNReal.ofReal p) volume ≤
          ENNReal.ofReal (K * A) * eLpNorm f (ENNReal.ofReal p) volume := by
  have hp1 : 1 < p := by linarith
  set q := p.conjExponent
  have hpq : p.HolderConjugate q := Real.HolderConjugate.conjExponent hp1
  have hq1 : 1 < q := hpq.symm.lt
  have hq2 : q < 2 := by
    simp only [q, Real.conjExponent]
    rw [div_lt_iff₀ (by linarith)]; linarith
  obtain ⟨K, hK, hbound⟩ := exists_eLpNorm_convolution_le_of_lt_two hn hq1 hq2
  refine ⟨K, hK, fun H A hA ⟨hH, hdiff, hgrad, hL2⟩ f hf => ?_⟩
  have hHm := measurable_of_differentiableAt_ne_zero hdiff
  have hadj := hbound (czAdjoint H) A hA ⟨integrable_czAdjoint hH hHm,
    fun x hx => (differentiableAt_czAdjoint hdiff x hx).1, norm_fderiv_czAdjoint_le hdiff hgrad,
    eLpNorm_czAdjoint_convolution_two_le hH hHm hL2⟩
  refine eLpNorm_le_of_dual_test hpq
    (AEStronglyMeasurable.convolution _ hH.1 hf.aestronglyMeasurable) fun φ _ _ _ hφq _ => ?_
  have hφ : MemLp φ (ENNReal.ofReal q) volume := hφq.trans_lt ENNReal.one_lt_top
  have hHa := integrable_czAdjoint hH hHm
  rw [integral_convolution_mul_conj hH hHm hpq hf hφ]
  calc ‖∫ y, f y * conj ((czAdjoint H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] φ) y)‖ₑ
      ≤ eLpNorm f (ENNReal.ofReal p) volume *
          eLpNorm (czAdjoint H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] φ)
            (ENNReal.ofReal q) volume :=
        enorm_integral_mul_conj_le hpq hf.aestronglyMeasurable
          (AEStronglyMeasurable.convolution _ hHa.1 hφ.aestronglyMeasurable)
    _ ≤ eLpNorm f (ENNReal.ofReal p) volume *
          (ENNReal.ofReal (K * A) * eLpNorm φ (ENNReal.ofReal q) volume) :=
        mul_le_mul_right (hadj φ hφ) _
    _ ≤ eLpNorm f (ENNReal.ofReal p) volume * (ENNReal.ofReal (K * A) * 1) :=
        mul_le_mul_right (mul_le_mul_right hφq _) _
    _ = ENNReal.ofReal (K * A) * eLpNorm f (ENNReal.ofReal p) volume := by
        rw [mul_one, mul_comm]

/-- **Calderón–Zygmund theorem, strong type `(p,p)`** (Blueprint Lemma 4.2 (`lem:cz`), second
assertion). Let `n ≥ 1` and `1 < p < ∞`. There is a constant `C = C_{n,p} > 0` such that for
every `A ≥ 0` and every `H ∈ L¹(E)` differentiable off `0` with `|∇H(x)| ≤ A |x|^{-n-1}`
(`x ≠ 0`) and `‖H * g‖₂ ≤ A ‖g‖₂` for all `g ∈ L²`, one has `‖H * f‖_p ≤ C A ‖f‖_p` for every
`f ∈ L^p`. The constant depends only on `n` and `p` (not on `‖H‖₁`); the size bound
`|H(x)| ≤ A|x|^{-n}` of the blueprint is not needed. -/
theorem exists_eLpNorm_convolution_le (hn : 0 < n) {p : ℝ} (hp : 1 < p) :
    ∃ C : ℝ, 0 < C ∧ ∀ (H : EuclideanSpace ℝ (Fin n) → ℂ) (A : ℝ), 0 ≤ A → Integrable H →
      (∀ x ≠ 0, DifferentiableAt ℝ H x) → (∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1)) →
      (∀ g : EuclideanSpace ℝ (Fin n) → ℂ, MemLp g 2 volume →
        eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
          ENNReal.ofReal A * eLpNorm g 2 volume) →
      ∀ f : EuclideanSpace ℝ (Fin n) → ℂ, MemLp f (ENNReal.ofReal p) volume →
        eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) (ENNReal.ofReal p) volume ≤
          ENNReal.ofReal (C * A) * eLpNorm f (ENNReal.ofReal p) volume := by
  obtain ⟨K, hK, hbound⟩ : ∃ K : ℝ, 0 < K ∧ ∀ (H : EuclideanSpace ℝ (Fin n) → ℂ) (A : ℝ),
      0 < A → CZHyp n H A → ∀ f : EuclideanSpace ℝ (Fin n) → ℂ,
        MemLp f (ENNReal.ofReal p) volume →
        eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) (ENNReal.ofReal p) volume ≤
          ENNReal.ofReal (K * A) * eLpNorm f (ENNReal.ofReal p) volume := by
    rcases lt_trichotomy p 2 with hp2 | rfl | hp2
    · exact exists_eLpNorm_convolution_le_of_lt_two hn hp hp2
    · refine ⟨1, one_pos, fun H A _ ⟨_, _, _, hL2⟩ f hf => ?_⟩
      rw [ENNReal.ofReal_ofNat, one_mul] at *
      exact hL2 f hf
    · exact exists_eLpNorm_convolution_le_of_two_lt hn hp2
  refine ⟨K, hK, fun H A hA hH hdiff hgrad hL2 f hf => ?_⟩
  have key := le_ofReal_mul_of_forall_pos hf.ne (φ := fun ε => K * (A + ε)) (by fun_prop)
    fun ε hε => hbound H (A + ε) (by linarith) ⟨hH, hdiff, norm_fderiv_le_of_le (by linarith)
      hgrad, eLpNorm_two_le_of_le (by linarith) hL2⟩ f hf
  simpa using key

end Strong

/-! ## The `L²` hypothesis from a bounded Fourier multiplier -/

section Fourier

open FourierTransform

variable {n : ℕ}

/-- Parseval-type identity: for `u ∈ L¹` and a Schwartz function `φ`,
`∫ u φ̄ = ∫ 𝓕u (𝓕φ)‾`. -/
lemma integral_mul_conj_eq_fourier {u : EuclideanSpace ℝ (Fin n) → ℂ} (hu : Integrable u)
    (φ : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ) :
    ∫ x, u x * conj (φ x) = ∫ ξ, 𝓕 u ξ * conj (𝓕 (φ : EuclideanSpace ℝ (Fin n) → ℂ) ξ) := by
  have h := VectorFourier.integral_sesq_fourierIntegral_eq_neg_flip (innerSL ℂ)
    (L := innerₗ (EuclideanSpace ℝ (Fin n))) (μ := volume) (ν := volume)
    Real.continuous_fourierChar continuous_inner hu (𝓕 φ).integrable
  have hinv : 𝓕⁻ (𝓕 (φ : EuclideanSpace ℝ (Fin n) → ℂ)) = φ :=
    φ.continuous.fourierInv_fourier_eq φ.integrable (𝓕 φ).integrable
  have hflip : (innerₗ (EuclideanSpace ℝ (Fin n))).flip = innerₗ (EuclideanSpace ℝ (Fin n)) := by
    ext v w; simp
  simp only [innerSL_apply_apply, RCLike.inner_apply, hflip] at h
  have h3 : ∫ ξ, 𝓕 (φ : EuclideanSpace ℝ (Fin n) → ℂ) ξ * conj (𝓕 u ξ) =
      ∫ x, 𝓕⁻ (𝓕 (φ : EuclideanSpace ℝ (Fin n) → ℂ)) x * conj (u x) := h
  rw [hinv] at h3
  have h4 := congrArg conj h3
  rw [← integral_conj, ← integral_conj] at h4
  simp only [map_mul, Complex.conj_conj] at h4
  simp only [mul_comm (conj _)] at h4
  exact h4.symm

/-- Plancherel for Schwartz functions, in `eLpNorm` form. -/
lemma eLpNorm_fourier_schwartz (φ : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ) :
    eLpNorm (𝓕 (φ : EuclideanSpace ℝ (Fin n) → ℂ)) 2 volume = eLpNorm φ 2 volume := by
  have h := SchwartzMap.norm_fourier_toL2_eq φ
  rw [SchwartzMap.norm_toLp, SchwartzMap.norm_toLp] at h
  exact (ENNReal.toReal_eq_toReal_iff' ((𝓕 φ).memLp 2 volume).ne (φ.memLp 2 volume).ne).1 h

/-- Hölder in `L²`: `∫ |a| |b| ≤ ‖a‖₂ ‖b‖₂`. -/
lemma lintegral_enorm_mul_le_eLpNorm_two {α : Type*} [MeasurableSpace α] {μ : Measure α}
    {a b : α → ℂ} (ha : AEStronglyMeasurable a μ) (hb : AEStronglyMeasurable b μ) :
    ∫⁻ x, ‖a x‖ₑ * ‖b x‖ₑ ∂μ ≤ eLpNorm a 2 μ * eLpNorm b 2 μ := by
  have h22 : (2 : ℝ).HolderConjugate 2 := Real.HolderConjugate.two_two
  have e2 : ENNReal.ofReal 2 = 2 := ENNReal.ofReal_ofNat 2
  have h := ENNReal.lintegral_mul_le_Lp_mul_Lq μ h22 ha.enorm hb.enorm
  rw [← e2, eLpNorm_ofReal_eq_lintegral ha two_pos, eLpNorm_ofReal_eq_lintegral hb two_pos]
  exact h

/-- The `L²` bound from the Fourier multiplier bound, for Schwartz inputs. -/
lemma eLpNorm_convolution_schwartz_le {H : EuclideanSpace ℝ (Fin n) → ℂ} (hH : Integrable H)
    {A : ℝ} (hA : ∀ ξ, ‖𝓕 H ξ‖ ≤ A) (g : SchwartzMap (EuclideanSpace ℝ (Fin n)) ℂ) :
    eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (g : EuclideanSpace ℝ (Fin n) → ℂ)) 2
      volume ≤ ENNReal.ofReal A * eLpNorm g 2 volume := by
  have h22 : (2 : ℝ).HolderConjugate 2 := Real.HolderConjugate.two_two
  have e2 : ENNReal.ofReal 2 = 2 := ENNReal.ofReal_ofNat 2
  have hHi := memLp_one_iff_integrable.2 hH
  have hu2 : MemLp (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (g : EuclideanSpace ℝ (Fin n) → ℂ))
      (ENNReal.ofReal 2) volume := by
    rw [e2]; exact memLp_convolution_of_memLp one_le_two hHi (g.memLp 2 volume)
  have hui : Integrable (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume]
      (g : EuclideanSpace ℝ (Fin n) → ℂ)) :=
    memLp_one_iff_integrable.1 (memLp_convolution_of_memLp le_rfl hHi (g.memLp 1 volume))
  have key := eLpNorm_le_of_smooth_dual_test h22 hu2 (A := ENNReal.ofReal A * eLpNorm g 2 volume)
    (fun φ hφs hφc hφ2 => ?_)
  · rwa [e2] at key
  set S := hφc.toSchwartzMap hφs
  have hSφ : (S : EuclideanSpace ℝ (Fin n) → ℂ) = φ := rfl
  rw [e2] at hφ2
  rw [← hSφ, integral_mul_conj_eq_fourier hui S]
  have hconv : ∀ ξ, 𝓕 (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume]
      (g : EuclideanSpace ℝ (Fin n) → ℂ)) ξ = 𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ :=
    Real.fourier_mul_convolution_eq hH g.integrable
  simp_rw [hconv]
  have hgF : AEStronglyMeasurable (𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ)) volume :=
    (𝓕 g).continuous.aestronglyMeasurable
  have hSF : AEStronglyMeasurable (𝓕 (S : EuclideanSpace ℝ (Fin n) → ℂ)) volume :=
    (𝓕 S).continuous.aestronglyMeasurable
  calc ‖∫ ξ, 𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ *
        conj (𝓕 (S : EuclideanSpace ℝ (Fin n) → ℂ) ξ)‖ₑ
      ≤ ∫⁻ ξ, ‖𝓕 H ξ * 𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ *
          conj (𝓕 (S : EuclideanSpace ℝ (Fin n) → ℂ) ξ)‖ₑ := enorm_integral_le_lintegral_enorm _
    _ ≤ ∫⁻ ξ, ENNReal.ofReal A * (‖𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ₑ *
          ‖𝓕 (S : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ₑ) := by
        refine lintegral_mono fun ξ => ?_
        rw [enorm_mul, enorm_mul, RCLike.enorm_conj, mul_assoc]
        refine mul_le_mul_left ?_ _
        rw [← ofReal_norm]; exact ENNReal.ofReal_le_ofReal (hA ξ)
    _ = ENNReal.ofReal A * ∫⁻ ξ, ‖𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ₑ *
          ‖𝓕 (S : EuclideanSpace ℝ (Fin n) → ℂ) ξ‖ₑ :=
        lintegral_const_mul' _ _ ENNReal.ofReal_ne_top
    _ ≤ ENNReal.ofReal A * (eLpNorm (𝓕 (g : EuclideanSpace ℝ (Fin n) → ℂ)) 2 volume *
          eLpNorm (𝓕 (S : EuclideanSpace ℝ (Fin n) → ℂ)) 2 volume) :=
        mul_le_mul_right (lintegral_enorm_mul_le_eLpNorm_two hgF hSF) _
    _ = ENNReal.ofReal A * (eLpNorm g 2 volume * eLpNorm φ 2 volume) := by
        rw [eLpNorm_fourier_schwartz, eLpNorm_fourier_schwartz, hSφ]
    _ ≤ ENNReal.ofReal A * (eLpNorm g 2 volume * 1) :=
        mul_le_mul_right (mul_le_mul_right hφ2 _) _
    _ = ENNReal.ofReal A * eLpNorm g 2 volume := by rw [mul_one]

/-- The `L²` hypothesis of the Calderón–Zygmund theorem from a Fourier multiplier bound
`‖𝓕 H‖_∞ ≤ A` (Plancherel): `‖H * g‖₂ ≤ A ‖g‖₂` for all `g ∈ L²`. -/
theorem eLpNorm_convolution_two_le_of_norm_fourier_le {H : EuclideanSpace ℝ (Fin n) → ℂ}
    (hH : Integrable H) {A : ℝ} (hA : ∀ ξ, ‖𝓕 H ξ‖ ≤ A) :
    ∀ g : EuclideanSpace ℝ (Fin n) → ℂ, MemLp g 2 volume →
      eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume ≤
        ENNReal.ofReal A * eLpNorm g 2 volume := by
  intro g hg
  have hA0 : 0 ≤ A := (norm_nonneg _).trans (hA 0)
  have hHi := memLp_one_iff_integrable.2 hH
  set N := eLpNorm H 1 volume with hN_def
  have hNt : N ≠ ∞ := hHi.ne
  refine ENNReal.le_of_forall_pos_le_add fun ε hε _ => ?_
  set δ : ℝ := ε / (A + N.toReal + 1) with hδ_def
  have hδ : 0 < δ := div_pos (by exact_mod_cast hε) (by positivity)
  obtain ⟨g₀, hg₀c, hg₀s, hg₀⟩ :=
    hg.exist_eLpNorm_sub_le (by norm_num : (2 : ℝ≥0∞) ≠ ∞) one_le_two hδ
  set S := hg₀c.toSchwartzMap hg₀s
  have hSg : (S : EuclideanSpace ℝ (Fin n) → ℂ) = g₀ := rfl
  have hS2 : MemLp g₀ 2 volume := S.memLp 2 volume
  have hdiff2 : MemLp (g - g₀) 2 volume := hg.sub hS2
  have hae : H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g =ᵐ[volume]
      H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g₀ +
        H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (g - g₀) := by
    filter_upwards [ae_convolutionExistsAt_of_memLp one_le_two hHi hS2,
      ae_convolutionExistsAt_of_memLp one_le_two hHi hdiff2] with x h1 h2
    rw [Pi.add_apply, ← h1.distrib_add h2, add_sub_cancel]
  have hg₀le : eLpNorm g₀ 2 volume ≤ eLpNorm g 2 volume + ENNReal.ofReal δ := by
    calc eLpNorm g₀ 2 volume = eLpNorm (g - (g - g₀)) 2 volume := by rw [sub_sub_cancel]
      _ ≤ eLpNorm g 2 volume + eLpNorm (g - g₀) 2 volume := eLpNorm_sub_le one_le_two
      _ ≤ eLpNorm g 2 volume + ENNReal.ofReal δ := add_le_add le_rfl hg₀
  have hfin : (ENNReal.ofReal A + N) * ENNReal.ofReal δ ≤ ε := by
    rw [← ENNReal.ofReal_toReal hNt, ← ENNReal.ofReal_add hA0 ENNReal.toReal_nonneg,
      ← ENNReal.ofReal_mul (by positivity), ← ENNReal.ofReal_coe_nnreal]
    refine ENNReal.ofReal_le_ofReal ?_
    rw [hδ_def, mul_div_assoc']
    rw [div_le_iff₀ (by positivity)]
    have : (0 : ℝ) ≤ ε := ε.2
    nlinarith
  calc eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g) 2 volume
      = eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g₀ +
          H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (g - g₀)) 2 volume := eLpNorm_congr_ae hae
    _ ≤ eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] g₀) 2 volume +
          eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] (g - g₀)) 2 volume :=
        eLpNorm_add_le one_le_two
    _ ≤ ENNReal.ofReal A * eLpNorm g₀ 2 volume + N * eLpNorm (g - g₀) 2 volume := by
        refine add_le_add ?_ (eLpNorm_convolution_le_mul one_le_two hH.1
          hdiff2.aestronglyMeasurable)
        rw [← hSg]; exact eLpNorm_convolution_schwartz_le hH hA S
    _ ≤ ENNReal.ofReal A * (eLpNorm g 2 volume + ENNReal.ofReal δ) + N * ENNReal.ofReal δ :=
        add_le_add (mul_le_mul_right hg₀le _) (mul_le_mul_right hg₀ _)
    _ = ENNReal.ofReal A * eLpNorm g 2 volume + (ENNReal.ofReal A + N) * ENNReal.ofReal δ := by
        ring
    _ ≤ ENNReal.ofReal A * eLpNorm g 2 volume + ε := add_le_add le_rfl hfin

/-- **Calderón–Zygmund theorem, weak type `(1,1)`, Fourier form** (Blueprint Lemma 4.2
(`lem:cz`), first assertion, with the `L²` hypothesis replaced by the multiplier bound
`|Ĥ| ≤ A`, from which it follows by Plancherel). -/
theorem volume_lt_norm_convolution_le_of_norm_fourier_le (hn : 0 < n)
    {H : EuclideanSpace ℝ (Fin n) → ℂ} {A : ℝ} (hH : Integrable H)
    (hdiff : ∀ x ≠ 0, DifferentiableAt ℝ H x)
    (hgrad : ∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1)) (hA : ∀ ξ, ‖𝓕 H ξ‖ ≤ A)
    {f : EuclideanSpace ℝ (Fin n) → ℂ} (hf : MemLp f 1 volume) {t : ℝ} (ht : 0 < t) :
    volume {x | t < ‖(H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) x‖} ≤
      ENNReal.ofReal (czWeakConst n * A / t) * eLpNorm f 1 volume :=
  volume_lt_norm_convolution_le hn ((norm_nonneg _).trans (hA 0)) hH hdiff hgrad
    (eLpNorm_convolution_two_le_of_norm_fourier_le hH hA) hf ht

/-- **Calderón–Zygmund theorem, strong type `(p,p)`, Fourier form** (Blueprint Lemma 4.2
(`lem:cz`), second assertion, with the `L²` hypothesis replaced by the multiplier bound
`|Ĥ| ≤ A`): for `1 < p < ∞` there is `C = C_{n,p} > 0` with `‖H * f‖_p ≤ C A ‖f‖_p`. -/
theorem exists_eLpNorm_convolution_le_of_norm_fourier_le (hn : 0 < n) {p : ℝ} (hp : 1 < p) :
    ∃ C : ℝ, 0 < C ∧ ∀ (H : EuclideanSpace ℝ (Fin n) → ℂ) (A : ℝ), Integrable H →
      (∀ x ≠ 0, DifferentiableAt ℝ H x) → (∀ x ≠ 0, ‖fderiv ℝ H x‖ ≤ A / ‖x‖ ^ (n + 1)) →
      (∀ ξ, ‖𝓕 H ξ‖ ≤ A) →
      ∀ f : EuclideanSpace ℝ (Fin n) → ℂ, MemLp f (ENNReal.ofReal p) volume →
        eLpNorm (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) (ENNReal.ofReal p) volume ≤
          ENNReal.ofReal (C * A) * eLpNorm f (ENNReal.ofReal p) volume := by
  obtain ⟨C, hC, h⟩ := exists_eLpNorm_convolution_le hn hp
  exact ⟨C, hC, fun H A hH hdiff hgrad hA => h H A ((norm_nonneg _).trans (hA 0)) hH hdiff hgrad
    (eLpNorm_convolution_two_le_of_norm_fourier_le hH hA)⟩

end Fourier

end Auto
