/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import DiscreteSW.Auto.Sec6ErrorEstimate

/-!
# The discrete Stein–Wainger maximal operator

This file was automatically generated by Claude.

This file covers §3 (Reduction to major arcs) and the proof of Theorem 1.1 of B. Krause, J. Roos,
*Discrete analogues of maximally modulated singular integrals of Stein–Wainger type: `ℓ^p` bounds
for `p > 1`*, arXiv:2107.14616v2 ("KR II") (the `ℓ^p` bound for `1 < p < ∞`). It contains blueprint
(`blueprints/discrete-sw.tex`) Lemma 12.2 (`lem:coherence`) and Proposition 12.3 (`prop:finiteSW`)
(the second part of §12) and §13: Lemma 13.1 (`lem:absolute`) and Theorem 13.2 (`thm:main`, eq.
(13.2) `eq:MAIN`), the main result `discrete_stein_wainger_lp`.

Formalization of the blueprint `blueprints/discrete-sw.tex` ("The discrete Stein–Wainger maximal
operator: the combined `ℓ^p` bound, `1 < p < ∞`"). The main result is
`discrete_stein_wainger_lp` (Blueprint Theorem 13.2, `thm:main`, eq. (13.2) `eq:MAIN`): for a
profile `Ω` that is smooth on `ℝⁿ ∖ {0}`, homogeneous of degree zero and of mean zero on the unit
sphere (`IsSWProfile`), the kernel `K(x) = Ω(x)|x|^{-n}` (`swKernel`), the radial polynomial
`P(y) = (y₁² + ⋯ + yₙ²)^d` (`radialPolyZ`) and `1 < p < ∞`, the maximal operator
`𝒞 f(x) = sup_{λ ∈ ℝ} |∑_{y ≠ 0} e(λ P(y)) K(y) f(x - y)|` (`swMax`) is bounded on `ℓ^p(ℤⁿ)`.

## File structure

The formalization is split into the following files, in import order, aligned with the sections
of KR II (and KR I); each former blueprint module is one Lean section:

* `DiscreteSW/Auto/Sec2_1Notation.lean` (KR II §2.1; blueprint §1.2, §14.1, §2):
  sections `Foundations` (the objects of the theorem: `latEmbed`, `radialPolyZ`, `eC`,
  `IsSWProfile`, `swKernel`, `swTerm`, `swOp`, `swMax`) and `Tools` (Lemmas 2.1–2.5);
* `DiscreteSW/Auto/Sec2_2ExponentialSums.lean` (KR II §2.2; blueprint §3): section `Arithmetic`,
  elementary rational approximation and cancellation;
* `DiscreteSW/Auto/Sec2_4_2_5MultiplierApproximations.lean` (KR II §§2.4–2.5, KR I §2; blueprint
  Lemma 2.7, §4, §5): sections `BinaryPartialSums` (Lemma 2.7), `RealVariable` (kernel
  construction and the real-variable multiplier estimates) and `Oscillation` (oscillatory
  integrals and a continuous annular maximal estimate);
* `DiscreteSW/Auto/Sec2_3IonescuWainger.lean` (KR II §2.3, KR I §2.1; blueprint §6, §7): sections
  `Sampling` (sampling and finite Fourier bookkeeping) and `RationalFrequency` (the
  rational-frequency multiplier lemma for pairwise coprime blocks);
* `DiscreteSW/Auto/Sec5MajorArcParameters.lean` (KR II §5, KR I §4; blueprint §8): section
  `MinorArcs`, minor parameter arcs and the choice of the exponent;
* `DiscreteSW/Auto/Sec4MainArgument.lean` (KR II §4, KR I §§6–7; blueprint §§9–11): sections
  `Lifting` (the rational lifting operators and their arithmetic bound), `Truncation` (lifted
  maximal truncations) and `Bands` (lifted oscillatory bands and their assembly);
* `DiscreteSW/Auto/Sec6ErrorEstimate.lean` (KR II §6; blueprint Lemma 12.1): the first part of
  section `MajorArcs`, the kernel-side smoothing error;
* `DiscreteSW/Auto/DiscreteSteinWainger.lean` (this file; KR II §3 and Theorem 1.1; blueprint
  Lemma 12.2, Proposition 12.3, §13): the second part of section `MajorArcs` (coherent grouping
  and the uniform finite dyadic estimate) and section `DiscreteSteinWainger` (the operator on all
  of `ℓ^p` and the final theorem).

## Prerequisites

Four self-contained, reusable results are proved in separate files:
* `DiscreteSW/Auto/MarcinkiewiczInterpolation.lean`: the Marcinkiewicz interpolation theorem
  (Blueprint Lemma 2.3, `lem:interpolation`);
* `DiscreteSW/Auto/HardyLittlewoodMaximal.lean`: the Hardy–Littlewood maximal theorem for the
  centered cube maximal functions on `ℝⁿ` and `ℤⁿ` (Blueprint Lemma 2.4, `lem:maximal`);
* `DiscreteSW/Auto/KhintchineInequality.lean`: Khintchine's inequality and the
  Marcinkiewicz–Zygmund square function bound (Blueprint Lemma 2.6, `lem:khintchine`);
* `DiscreteSW/Auto/CalderonZygmund.lean`: the Calderón–Zygmund theorem for integrable kernels
  (Blueprint Lemma 4.2, `lem:cz`), together with supporting results used throughout (Young's
  inequality and dual testing of Blueprint Lemma 2.2, Fatou's lemma for `L^p` norms, and the
  envelope `B_R` of Blueprint Lemma 2.4).
-/

@[expose] public section

namespace Auto

section MajorArcs

/-!
## Coherent grouping and the uniform finite dyadic estimate

Results from §12 ("Kernel-side major-arc approximation and coherent grouping") of
`blueprints/discrete-sw.tex`, second part (Lemma 12.2 and Proposition 12.3). Lemma 12.1 and the
functions `majorH` are in `DiscreteSW/Auto/Sec6ErrorEstimate.lean`.

### Definitions

* `majorExp M j = ⌊M log₂(j+1)⌋` (so `H_j = minorH M j = 2^{majorExp M j}`);
* `IsMajorCenter M j a q`: `a/q` is an admissible center of `X_j` (`1 ≤ q < H_j`, `0 ≤ a < q`,
  `(a, q) = 1`);
* `CoherenceSpec n d Ω p j₀`: `j₀ ≥ j₁` and the three properties (1)–(3) of Lemma 12.2 for all
  `j ≥ j₀`; `coherJ0 n d Ω p = j₀` is the least such integer, and
  `coherJs n d Ω p s = j_s = max(j₀, ⌈2^{s/M}⌉ - 1)`;
* `majorIdx n d Ω p s λ J`: the finite set of `j ∈ [j₀, J]` whose major center (the center of the
  arc of `X_j` containing `λ`) lies in `𝓡_s`.

### Main results

* `coherJ0_spec` (with `exists_coherenceSpec`): Lemma 12.2 (`lem:coherence`), (1)–(3);
* `isMajorCenter_of_mem_liftRat`, `isMajorCenter_of_le_majorExp`, `two_pow_le_minorH_iff`:
  admissibility of `𝓡_s` in `X_j` and the formula for `j_s`;
* `minorArcs_center_unique`: uniqueness of the major center;
* `major_coherence`: the coherent interval `[j_s, b]`, the common center `α` and the common
  representative `μ` with `|μ| < 1/4`, together with `|μ| 2^{Dj} ≤ (j+1)^M` and `L_s ≤ 2^{j/2}`;
* `mem_minorArcs_iff_exists_majorIdx`, `eq_of_mem_majorIdx`: every major index belongs to
  exactly one group `s`;
* `finite_dyadic_stein_wainger`: Blueprint Proposition 12.3 (`prop:finiteSW`), eq. (12.2),
  with the smoothing error `finSW_kernel_error`, the pointwise majorant `finSW_pointwise` and the
  group majorants `finSWMain` (`𝒫_s f` for `s ≥ 1`).

### Proof notes (deviations from the blueprint)

* In Lemma 12.2, property (3) holds for all `s ≤ ⌊M log₂(j+1)⌋` (including `s = 0`), and the
  lower scale needs `d ≥ 1` (for `d = 0` the widths `w_j` increase).
* In Proposition 12.3 the supremum is over `λ ∈ ℝ` (equivalent to `λ ∈ 𝕋` by `1`-periodicity).
  The group index `s` is bounded by `s < 2^s ≤ H_J`, so the major sum is a finite disjoint union
  over `s < H_J + 1`; the main-term majorant is `∑_{s ≥ 0} 𝒫_s f` (with `𝒫_0 := 0`), bounded
  by the countable Minkowski inequality `eLpNorm_tsum_le_count`.
-/

open MeasureTheory Set Real Finset
open scoped FourierTransform ContDiff SchwartzMap Convolution

variable {n d : ℕ} {Ω : EuclideanSpace ℝ (Fin n) → ℂ} {p : ℝ}

/-! ### Blueprint Lemma 12.2 (`lem:coherence`) -/

/-- The exponent `⌊M log₂(j+1)⌋` of `H_j = 2^{⌊M log₂(j+1)⌋}`. -/
noncomputable def majorExp (M j : ℕ) : ℕ := ⌊(M : ℝ) * Real.logb 2 ((j : ℝ) + 1)⌋₊

/-- `H_j = 2^{⌊M log₂(j+1)⌋}`. -/
lemma minorH_eq_two_pow (M j : ℕ) : minorH M j = 2 ^ majorExp M j := rfl

/-- `H_j ≤ (j+1)^M`. -/
lemma minorH_le_pow (M j : ℕ) : (minorH M j : ℝ) ≤ ((j : ℝ) + 1) ^ M := by
  set x : ℝ := (M : ℝ) * Real.logb 2 ((j : ℝ) + 1) with hx
  have hj : (0 : ℝ) < (j : ℝ) + 1 := by positivity
  have hx0 : 0 ≤ x := mul_nonneg (Nat.cast_nonneg _)
    (Real.logb_nonneg (by norm_num) (by linarith [(Nat.cast_nonneg j : (0 : ℝ) ≤ j)]))
  have h2x : (2 : ℝ) ^ x = ((j : ℝ) + 1) ^ M := by
    rw [hx, mul_comm, Real.rpow_mul (by norm_num), Real.rpow_logb (by norm_num) (by norm_num) hj,
      Real.rpow_natCast]
  rw [minorH, Nat.cast_pow, Nat.cast_ofNat, ← h2x, ← Real.rpow_natCast]
  exact Real.rpow_le_rpow_of_exponent_le (by norm_num) (Nat.floor_le hx0)

/-- `s ≤ ⌊M log₂(j+1)⌋ ⟺ j ≥ ⌈2^{s/M}⌉ - 1` (for `M ≥ 1`). -/
lemma le_majorExp_iff {M : ℕ} (hM : 1 ≤ M) (s j : ℕ) :
    s ≤ majorExp M j ↔ ⌈(2 : ℝ) ^ ((s : ℝ) / M)⌉₊ - 1 ≤ j := by
  have hj : (0 : ℝ) < (j : ℝ) + 1 := by positivity
  have hM' : (0 : ℝ) < M := by exact_mod_cast hM
  have hx0 : 0 ≤ (M : ℝ) * Real.logb 2 ((j : ℝ) + 1) := mul_nonneg (Nat.cast_nonneg _)
    (Real.logb_nonneg (by norm_num) (by linarith [(Nat.cast_nonneg j : (0 : ℝ) ≤ j)]))
  rw [majorExp, Nat.le_floor_iff hx0, ← div_le_iff₀' hM',
    Real.le_logb_iff_rpow_le one_lt_two hj,
    show ((j : ℝ) + 1) = ((j + 1 : ℕ) : ℝ) by push_cast; ring, ← Nat.ceil_le]
  omega

/-- Blueprint Lemma 12.2 (`lem:coherence`): `H_j ≥ 2^s ⟺ j ≥ ⌈2^{s/M}⌉ - 1` (for `M ≥ 1`). -/
lemma two_pow_le_minorH_iff {M : ℕ} (hM : 1 ≤ M) (s j : ℕ) :
    2 ^ s ≤ minorH M j ↔ ⌈(2 : ℝ) ^ ((s : ℝ) / M)⌉₊ - 1 ≤ j := by
  rw [minorH_eq_two_pow, Nat.pow_le_pow_iff_right (by norm_num), le_majorExp_iff hM]

/-- Rational separation (Lemma 3.2): two reduced fractions `a/q`, `a'/q'` in `[0, 1)` with
`q, q' < B` and `‖a/q - a'/q'‖_𝕋 < B^{-2}` coincide. -/
lemma reduced_eq_of_norm_lt {a q a' q' : ℕ} (hq : 1 ≤ q) (ha : a < q) (hc : Nat.Coprime a q)
    (hq' : 1 ≤ q') (ha' : a' < q') (hc' : Nat.Coprime a' q') {B : ℝ} (hqB : (q : ℝ) < B)
    (hq'B : (q' : ℝ) < B)
    (h : ‖(((a : ℝ) / q - a' / q' : ℝ) : UnitAddCircle)‖ < 1 / B ^ 2) : a = a' ∧ q = q' := by
  by_contra hne
  have hq0 : (0 : ℝ) < q := by exact_mod_cast hq
  have hq0' : (0 : ℝ) < q' := by exact_mod_cast hq'
  have hnot : ¬ ∃ m : ℤ,
      (((a : ℤ) : ℝ) / ((q : ℤ) : ℝ) - ((a' : ℤ) : ℝ) / ((q' : ℤ) : ℝ) : ℝ) = m := by
    rintro ⟨m, hm⟩
    push_cast at hm
    have h1 : (a : ℝ) / q < 1 := by rw [div_lt_one hq0]; exact_mod_cast ha
    have h2 : (a' : ℝ) / q' < 1 := by rw [div_lt_one hq0']; exact_mod_cast ha'
    have h3 : 0 ≤ (a : ℝ) / q := by positivity
    have h4 : 0 ≤ (a' : ℝ) / q' := by positivity
    have hm1 : (m : ℝ) < 1 := by linarith
    have hm2 : (-1 : ℝ) < m := by linarith
    have hm0 : m = 0 := by
      have : m < 1 := by exact_mod_cast hm1
      have : -1 < m := by exact_mod_cast hm2
      omega
    rw [hm0, Int.cast_zero, sub_eq_zero, div_eq_div_iff hq0.ne' hq0'.ne'] at hm
    have hnat : a * q' = a' * q := by exact_mod_cast hm
    apply hne
    have hd1 : q ∣ a * q' := ⟨a', by rw [hnat, mul_comm]⟩
    have hd2 : q' ∣ a' * q := ⟨a, by rw [← hnat, mul_comm]⟩
    have hqq : q = q' :=
      Nat.dvd_antisymm (hc.symm.dvd_of_dvd_mul_left hd1) (hc'.symm.dvd_of_dvd_mul_left hd2)
    subst hqq
    exact ⟨Nat.eq_of_mul_eq_mul_right (by omega) hnat, rfl⟩
  have hsep := one_div_mul_le_norm_addCircle (a : ℤ) (a' : ℤ)
    (by exact_mod_cast hq : (0 : ℤ) < q) (by exact_mod_cast hq' : (0 : ℤ) < q') hnot
  push_cast at hsep
  have hqq : (q : ℝ) * q' < B ^ 2 := by nlinarith
  have : 1 / B ^ 2 < 1 / ((q : ℝ) * q') := one_div_lt_one_div_of_lt (by positivity) hqq
  linarith

/-- `‖α - β‖_𝕋 ≤ ‖λ - α‖_𝕋 + ‖λ - β‖_𝕋`. -/
lemma norm_sub_centers_le (lam α β : ℝ) :
    ‖((α - β : ℝ) : UnitAddCircle)‖ ≤
      ‖((lam - α : ℝ) : UnitAddCircle)‖ + ‖((lam - β : ℝ) : UnitAddCircle)‖ := by
  have : ((α - β : ℝ) : UnitAddCircle) =
      ((lam - β : ℝ) : UnitAddCircle) - ((lam - α : ℝ) : UnitAddCircle) := by
    rw [← AddCircle.coe_sub]; congr 1; ring
  rw [this, add_comm]
  exact norm_sub_le _ _

/-- Property (3) of Blueprint Lemma 12.2 (`lem:coherence`) for all large `j`:
`v_s ≤ j/2` whenever `s ≤ ⌊M log₂(j+1)⌋`. -/
lemma exists_liftV_le_half (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) :
    ∃ N : ℕ, ∀ j ≥ N, ∀ s : ℕ, s ≤ majorExp (paramM n d Ω p) j →
      (liftV n d Ω p s : ℝ) ≤ (j : ℝ) / 2 := by
  set M := paramM n d Ω p with hMdef
  have hM : (2 : ℝ) ≤ M := by exact_mod_cast two_le_paramM n d Ω p
  set Cs := liftCStar n d Ω p
  have hCs : 0 < Cs := liftCStar_pos
  have hlog2 : 0 < Real.log 2 := Real.log_pos one_lt_two
  set K : ℝ := 2 * Cs * (4 * M / Real.log 2 + 1) with hK
  have hK0 : 0 ≤ K := by positivity
  refine ⟨⌈(4 * K + 4) ^ 4⌉₊, fun j hj s hs => ?_⟩
  set x : ℝ := (j : ℝ) + 1 with hx
  have hx0 : 0 < x := by positivity
  set t : ℝ := x ^ (1 / 4 : ℝ) with ht
  have ht1 : 1 ≤ t := Real.one_le_rpow (by linarith [(Nat.cast_nonneg j : (0 : ℝ) ≤ j)])
    (by norm_num)
  have ht4 : t ^ 4 = x := by
    rw [ht, ← Real.rpow_natCast, ← Real.rpow_mul hx0.le]; norm_num
  have ht2 : x ^ (1 / 2 : ℝ) = t ^ 2 := by
    rw [ht, ← Real.rpow_natCast, ← Real.rpow_mul hx0.le]; norm_num
  have htK : 4 * K + 4 ≤ t := by
    refine le_of_pow_le_pow_left₀ (n := 4) (by norm_num) (by linarith) ?_
    rw [ht4]
    have := Nat.le_ceil ((4 * K + 4) ^ 4)
    have h2 : ((⌈(4 * K + 4) ^ 4⌉₊ : ℕ) : ℝ) ≤ j := by exact_mod_cast hj
    linarith
  have hlogb0 : 0 ≤ Real.logb 2 x := Real.logb_nonneg one_lt_two (by
    linarith [(Nat.cast_nonneg j : (0 : ℝ) ≤ j)])
  have hsR : (s : ℝ) ≤ M * Real.logb 2 x := by
    have h1 : (s : ℝ) ≤ majorExp M j := by exact_mod_cast hs
    exact h1.trans (Nat.floor_le (mul_nonneg (by positivity) hlogb0))
  have hlog : Real.log x ≤ 4 * t := by
    have := Real.log_le_rpow_div hx0.le (by norm_num : (0 : ℝ) < 1 / 4)
    rw [← ht] at this; linarith [show t / (1 / 4) = 4 * t by ring]
  have hs1 : (s : ℝ) + 1 ≤ (4 * M / Real.log 2 + 1) * t := by
    have : M * Real.logb 2 x ≤ 4 * M / Real.log 2 * t := by
      rw [Real.logb, mul_div_assoc', div_mul_eq_mul_div, div_le_div_iff_of_pos_right hlog2]
      nlinarith
    nlinarith
  have hpow : (2 : ℝ) ^ ((s : ℝ) / (2 * M)) ≤ t ^ 2 := by
    rw [← ht2]
    have e : x ^ (1 / 2 : ℝ) = (2 : ℝ) ^ (Real.logb 2 x * (1 / 2)) := by
      rw [Real.rpow_mul (by norm_num), Real.rpow_logb (by norm_num) (by norm_num) hx0]
    rw [e]
    refine Real.rpow_le_rpow_of_exponent_le (by norm_num) ?_
    rw [div_le_iff₀ (by positivity)]
    nlinarith
  have hv : (liftV n d Ω p s : ℝ) ≤ Cs * ((s : ℝ) + 1) * (1 + (2 : ℝ) ^ ((s : ℝ) / (2 * M))) + 1 :=
    (Nat.ceil_lt_add_one (by positivity)).le
  have hv2 : Cs * ((s : ℝ) + 1) * (1 + (2 : ℝ) ^ ((s : ℝ) / (2 * M))) ≤ K * t ^ 3 := by
    have h1 : 1 + (2 : ℝ) ^ ((s : ℝ) / (2 * M)) ≤ 2 * t ^ 2 := by nlinarith
    calc Cs * ((s : ℝ) + 1) * (1 + (2 : ℝ) ^ ((s : ℝ) / (2 * M)))
        ≤ Cs * ((4 * M / Real.log 2 + 1) * t) * (2 * t ^ 2) := by gcongr
      _ = K * t ^ 3 := by rw [hK]; ring
  have hjx : (j : ℝ) = t ^ 4 - 1 := by rw [ht4, hx]; ring
  rw [hjx]
  have h3 : 1 ≤ t ^ 3 := one_le_pow₀ ht1
  have h4 : (4 * K + 4) * t ^ 3 ≤ t * t ^ 3 := mul_le_mul_of_nonneg_right htK (by positivity)
  nlinarith

/-- `w_{j+1} < w_j` once `j + 1 ≥ M` (for `d ≥ 1`). -/
lemma minorW_succ_lt {d M j : ℕ} (hd : 1 ≤ d) (hMj : M ≤ j + 1) :
    minorW d M (j + 1) < minorW d M j := by
  have hj0 : (0 : ℝ) < (j : ℝ) + 1 := by positivity
  have hexp : ((j : ℝ) + 2) ^ M ≤ Real.exp 1 * ((j : ℝ) + 1) ^ M := by
    have h1 : (j : ℝ) + 2 ≤ ((j : ℝ) + 1) * Real.exp (1 / ((j : ℝ) + 1)) := by
      have := Real.add_one_le_exp (1 / ((j : ℝ) + 1))
      calc (j : ℝ) + 2 = ((j : ℝ) + 1) * (1 / ((j : ℝ) + 1) + 1) := by field_simp; ring
        _ ≤ ((j : ℝ) + 1) * Real.exp (1 / ((j : ℝ) + 1)) := by gcongr
    calc ((j : ℝ) + 2) ^ M ≤ (((j : ℝ) + 1) * Real.exp (1 / ((j : ℝ) + 1))) ^ M := by gcongr
      _ = ((j : ℝ) + 1) ^ M * Real.exp (M * (1 / ((j : ℝ) + 1))) := by
          rw [mul_pow, ← Real.exp_nat_mul]
      _ ≤ ((j : ℝ) + 1) ^ M * Real.exp 1 := by
          gcongr
          rw [mul_one_div, div_le_one hj0]
          exact_mod_cast hMj
      _ = _ := by ring
  have he4 : Real.exp 1 < 4 := by have := Real.exp_one_lt_d9; linarith
  have h4 : (4 : ℝ) ≤ 2 ^ (2 * d) := by
    calc (4 : ℝ) = 2 ^ 2 := by norm_num
      _ ≤ 2 ^ (2 * d) := pow_le_pow_right₀ (by norm_num) (by omega)
  rw [minorW, minorW, div_lt_div_iff₀ (by positivity) (by positivity),
    show 2 * d * (j + 1) = 2 * d * j + 2 * d by ring, pow_add]
  push_cast
  rw [show (j : ℝ) + 1 + 1 = (j : ℝ) + 2 by ring]
  have hp : (0 : ℝ) < 2 ^ (2 * d * j) := by positivity
  have hX : (0 : ℝ) < ((j : ℝ) + 1) ^ M := by positivity
  have : ((j : ℝ) + 2) ^ M < ((j : ℝ) + 1) ^ M * 2 ^ (2 * d) := by nlinarith
  nlinarith

/-- Property (1) of Blueprint Lemma 12.2 (`lem:coherence`) for all large `j`. -/
lemma eventually_minorW_bounds {d : ℕ} (hd : 1 ≤ d) (M : ℕ) : ∃ N : ℕ, ∀ j ≥ N,
    minorW d M j < 1 / 4 ∧ minorW d M (j + 1) < minorW d M j ∧
      minorW d M j ≤ ((minorH M j : ℝ) ^ 2)⁻¹ / 16 := by
  obtain ⟨NA, hNA⟩ := minor_eventually_pow_le_two_pow (16 * 2 ^ (3 * M)) (3 * M)
  refine ⟨max (max NA 1) M, fun j hj => ?_⟩
  have hj1 : 1 ≤ j := le_trans (le_max_right _ _) (le_trans (le_max_left _ _) hj)
  have hjA : NA ≤ j := le_trans (le_max_left _ _) (le_trans (le_max_left _ _) hj)
  have hjM : M ≤ j := le_trans (le_max_right _ _) hj
  set X : ℝ := ((j : ℝ) + 1) ^ M with hXdef
  have hX1 : 1 ≤ X := one_le_pow₀ (by linarith [(Nat.cast_nonneg j : (0 : ℝ) ≤ j)])
  have hA : 16 * X ^ 3 ≤ (2 : ℝ) ^ (2 * d * j) := by
    have h1 : (j : ℝ) + 1 ≤ 2 * j := by
      have : (1 : ℝ) ≤ j := by exact_mod_cast hj1
      linarith
    have h2 : X ^ 3 ≤ 2 ^ (3 * M) * (j : ℝ) ^ (3 * M) := by
      rw [hXdef, ← pow_mul, ← mul_pow, show M * 3 = 3 * M by ring]; gcongr
    have h3 := hNA j hjA
    have h4 : (2 : ℝ) ^ j ≤ 2 ^ (2 * d * j) := pow_le_pow_right₀ (by norm_num) (by nlinarith)
    nlinarith
  have hW : minorW d M j ≤ 1 / (16 * X ^ 2) := by
    rw [minorW, div_le_div_iff₀ (by positivity) (by positivity)]
    nlinarith
  have hH : (minorH M j : ℝ) ≤ X := minorH_le_pow M j
  have hH0 : (0 : ℝ) < minorH M j := by rw [minorH]; positivity
  refine ⟨?_, minorW_succ_lt hd (by omega), ?_⟩
  · calc minorW d M j ≤ 1 / (16 * X ^ 2) := hW
      _ ≤ 1 / 16 := by gcongr; nlinarith
      _ < 1 / 4 := by norm_num
  · calc minorW d M j ≤ 1 / (16 * X ^ 2) := hW
      _ ≤ 1 / (16 * (minorH M j : ℝ) ^ 2) := by gcongr
      _ = _ := by field_simp

/-- `a/q` is an admissible center of the major arcs `X_j`: `1 ≤ q < H_j`, `0 ≤ a < q`,
`(a, q) = 1`. -/
def IsMajorCenter (M j a q : ℕ) : Prop :=
  1 ≤ q ∧ q < minorH M j ∧ a < q ∧ Nat.Coprime a q

/-- The requirements on the final lower scale `j₀` of Blueprint Lemma 12.2 (`lem:coherence`):
`j₀ ≥ j₁`, and for every `j ≥ j₀`: (1) `w_j < 1/4`, `w_{j+1} < w_j`, `w_j ≤ H_j^{-2}/16`;
(2) the arcs defining `X_j` are pairwise disjoint (two admissible centers whose arcs share a point
coincide); (3) `v_s ≤ j/2` for `1 ≤ s ≤ ⌊M log₂(j+1)⌋`. -/
def CoherenceSpec (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) (j₀ : ℕ) : Prop :=
  paramJ1 n d Ω p ≤ j₀ ∧ ∀ j ≥ j₀,
    (minorW d (paramM n d Ω p) j < 1 / 4 ∧
      minorW d (paramM n d Ω p) (j + 1) < minorW d (paramM n d Ω p) j ∧
      minorW d (paramM n d Ω p) j ≤ ((minorH (paramM n d Ω p) j : ℝ) ^ 2)⁻¹ / 16) ∧
    (∀ a q a' q' : ℕ, IsMajorCenter (paramM n d Ω p) j a q →
      IsMajorCenter (paramM n d Ω p) j a' q' → ∀ lam : ℝ,
        ‖((lam - a / q : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j →
        ‖((lam - a' / q' : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j →
        a = a' ∧ q = q') ∧
    (∀ s : ℕ, 1 ≤ s → s ≤ majorExp (paramM n d Ω p) j → (liftV n d Ω p s : ℝ) ≤ (j : ℝ) / 2)

/-- Disjointness of the arcs of `X_j` from `w_j ≤ H_j^{-2}/16` (rational separation). -/
lemma arcs_disjoint_of_le {M d j : ℕ}
    (hw : minorW d M j ≤ ((minorH M j : ℝ) ^ 2)⁻¹ / 16) {a q a' q' : ℕ}
    (h : IsMajorCenter M j a q) (h' : IsMajorCenter M j a' q') {lam : ℝ}
    (h1 : ‖((lam - a / q : ℝ) : UnitAddCircle)‖ ≤ minorW d M j)
    (h2 : ‖((lam - a' / q' : ℝ) : UnitAddCircle)‖ ≤ minorW d M j) : a = a' ∧ q = q' := by
  obtain ⟨hq, hqH, ha, hc⟩ := h
  obtain ⟨hq', hqH', ha', hc'⟩ := h'
  have hH0 : (0 : ℝ) < minorH M j := by rw [minorH]; positivity
  refine reduced_eq_of_norm_lt hq ha hc hq' ha' hc' (B := minorH M j) (by exact_mod_cast hqH)
    (by exact_mod_cast hqH') ?_
  calc ‖(((a : ℝ) / q - a' / q' : ℝ) : UnitAddCircle)‖ ≤ minorW d M j + minorW d M j :=
        (norm_sub_centers_le lam _ _).trans (add_le_add h1 h2)
    _ ≤ 2 * (((minorH M j : ℝ) ^ 2)⁻¹ / 16) := by linarith
    _ < 1 / (minorH M j : ℝ) ^ 2 := by
        rw [one_div]; have : 0 < ((minorH M j : ℝ) ^ 2)⁻¹ := by positivity
        linarith

/-- Blueprint Lemma 12.2 (`lem:coherence`), existence of the final lower scale: for `d ≥ 1`
there is `j₀` satisfying `CoherenceSpec`. -/
theorem exists_coherenceSpec {d : ℕ} (hd : 1 ≤ d) (n : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ)
    (p : ℝ) : ∃ j₀, CoherenceSpec n d Ω p j₀ := by
  obtain ⟨N₁, h₁⟩ := eventually_minorW_bounds hd (paramM n d Ω p)
  obtain ⟨N₂, h₂⟩ := exists_liftV_le_half n d Ω p
  refine ⟨max (max N₁ N₂) (paramJ1 n d Ω p), le_max_right _ _, fun j hj => ?_⟩
  have hj₁ : N₁ ≤ j := le_trans (le_max_left _ _) (le_trans (le_max_left _ _) hj)
  have hj₂ : N₂ ≤ j := le_trans (le_max_right _ _) (le_trans (le_max_left _ _) hj)
  obtain hw := h₁ j hj₁
  exact ⟨hw, fun a q a' q' h h' lam hl hl' => arcs_disjoint_of_le hw.2.2 h h' hl hl',
    fun s _ hs => h₂ j hj₂ s hs⟩

/-- The final lower scale `j₀` of Blueprint Lemma 12.2 (`lem:coherence`): the least integer
satisfying `CoherenceSpec` (chosen after all previous constants `M`, `j₁`, `v_s`). -/
noncomputable def coherJ0 (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) : ℕ :=
  sInf {j₀ | CoherenceSpec n d Ω p j₀}

/-- **Blueprint Lemma 12.2 (`lem:coherence`)**, (1)–(3): for `d ≥ 1`, `j₀ = coherJ0 n d Ω p ≥ j₁`
satisfies (1)–(3) for every `j ≥ j₀`. -/
theorem coherJ0_spec (hd : 1 ≤ d) : CoherenceSpec n d Ω p (coherJ0 n d Ω p) :=
  Nat.sInf_mem (exists_coherenceSpec hd n Ω p)

/-- `j_s = max(j₀, ⌈2^{s/M}⌉ - 1)` of Blueprint Lemma 12.2 (`lem:coherence`). -/
noncomputable def coherJs (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) (s : ℕ) : ℕ :=
  max (coherJ0 n d Ω p) (⌈(2 : ℝ) ^ ((s : ℝ) / (paramM n d Ω p : ℝ))⌉₊ - 1)

/-- `M ≥ 1`. -/
lemma major_one_le_paramM : 1 ≤ paramM n d Ω p := le_trans (by norm_num) (two_le_paramM n d Ω p)

/-- Blueprint Lemma 12.2 (`lem:coherence`): `w_j` is decreasing on `[j₀, ∞)`. -/
theorem minorW_antitone (hd : 1 ≤ d) {j j' : ℕ} (hj : coherJ0 n d Ω p ≤ j) (hjj' : j ≤ j') :
    minorW d (paramM n d Ω p) j' ≤ minorW d (paramM n d Ω p) j := by
  induction j', hjj' using Nat.le_induction with
  | base => exact le_rfl
  | succ k hk ih => exact ((coherJ0_spec hd).2 k (hj.trans hk)).1.2.1.le.trans ih

/-- A pair of `𝓡_s` with `q < H_j` forces `1 ≤ s`, `2^s ≤ H_j` and `s ≤ ⌊M log₂(j+1)⌋`
(`H_j` is a power of two). -/
lemma liftRat_bounds_of_lt_minorH {M s j a q : ℕ} (h : (a, q) ∈ liftRat s)
    (hqH : q < minorH M j) : 1 ≤ s ∧ 2 ^ s ≤ minorH M j ∧ s ≤ majorExp M j := by
  obtain ⟨h1, h2, h3, -⟩ := mem_liftRat.1 h
  unfold liftN at h1 h2
  rw [minorH_eq_two_pow] at hqH ⊢
  have hs1 : 1 ≤ s := by
    rcases Nat.eq_zero_or_pos s with hs | hs
    · subst hs; simp at h2; omega
    · exact hs
  have hlt : 2 ^ s < 2 ^ (majorExp M j + 1) := by rw [pow_succ]; omega
  have hs : s ≤ majorExp M j := by
    have := (Nat.pow_lt_pow_iff_right (by norm_num : 1 < 2)).1 hlt; omega
  exact ⟨hs1, Nat.pow_le_pow_right (by norm_num) hs, hs⟩

/-- Blueprint Lemma 12.2 (`lem:coherence`), admissibility: for `j ≥ j_s` every center of `𝓡_s`
(denominator `q ∈ [2^{s-1}, 2^s)`) is allowed in `X_j`. -/
theorem isMajorCenter_of_mem_liftRat {s j a q : ℕ} (hj : coherJs n d Ω p s ≤ j)
    (h : (a, q) ∈ liftRat s) : IsMajorCenter (paramM n d Ω p) j a q := by
  obtain ⟨-, h2, h3, h4⟩ := mem_liftRat.1 h
  have hs : 2 ^ s ≤ minorH (paramM n d Ω p) j :=
    (two_pow_le_minorH_iff major_one_le_paramM s j).2 (le_trans (le_max_right _ _) hj)
  exact ⟨one_le_of_mem_liftRat h, lt_of_lt_of_le h2 hs, h3, h4⟩

/-- Blueprint Lemma 12.2 (`lem:coherence`), admissibility: if `s ≤ ⌊M log₂(j+1)⌋`, every center
of `𝓡_s` is allowed in `X_j`. -/
theorem isMajorCenter_of_le_majorExp {M s j a q : ℕ} (hs : s ≤ majorExp M j)
    (h : (a, q) ∈ liftRat s) : IsMajorCenter M j a q := by
  obtain ⟨-, h2, h3, h4⟩ := mem_liftRat.1 h
  have hs' : 2 ^ s ≤ minorH M j := by
    rw [minorH_eq_two_pow]; exact Nat.pow_le_pow_right (by norm_num) hs
  exact ⟨one_le_of_mem_liftRat h, lt_of_lt_of_le h2 hs', h3, h4⟩

/-- Blueprint Lemma 12.2 (`lem:coherence`), the unique major center: for `d ≥ 1`, `j ≥ j₀` and
`λ ∈ X_j` there is exactly one admissible `(a, q)` with `‖λ - a/q‖_𝕋 ≤ w_j`. -/
theorem minorArcs_center_unique (hd : 1 ≤ d) {j : ℕ} (hj : coherJ0 n d Ω p ≤ j) {lam : ℝ}
    (hlam : lam ∈ minorArcs d (paramM n d Ω p) j) :
    ∃! aq : ℕ × ℕ, IsMajorCenter (paramM n d Ω p) j aq.1 aq.2 ∧
      ‖((lam - aq.1 / aq.2 : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j := by
  obtain ⟨q, a, hq, hqH, ha, hc, hl⟩ := hlam
  refine ⟨(a, q), ⟨⟨hq, hqH, ha, hc⟩, hl⟩, fun aq haq => ?_⟩
  obtain ⟨h1, h2⟩ := ((coherJ0_spec hd).2 j hj).2.1 _ _ _ _ haq.1 ⟨hq, hqH, ha, hc⟩ lam haq.2 hl
  exact Prod.ext h1 h2

/-- Every reduced `a/q ∈ [0, 1)` lies in some `𝓡_s` (`s = ⌊log₂ q⌋ + 1`). -/
lemma exists_mem_liftRat {q : ℕ} (a : ℕ) (hq : 1 ≤ q) (ha : a < q) (hc : Nat.Coprime a q) :
    ∃ s, (a, q) ∈ liftRat s := by
  refine ⟨Nat.log 2 q + 1, mem_liftRat.2 ⟨?_, ?_, ha, hc⟩⟩
  · unfold liftN; rw [pow_succ, mul_comm]
    exact Nat.mul_le_mul_left 2 (Nat.pow_log_le_self 2 (by omega))
  · exact Nat.lt_pow_succ_log_self (by norm_num) q

/-- The sets `𝓡_s` are pairwise disjoint. -/
lemma eq_of_mem_liftRat {a q s s' : ℕ} (h : (a, q) ∈ liftRat s) (h' : (a, q) ∈ liftRat s') :
    s = s' := by
  obtain ⟨h1, h2, -, -⟩ := mem_liftRat.1 h
  obtain ⟨h1', h2', -, -⟩ := mem_liftRat.1 h'
  unfold liftN at h1 h2 h1' h2'
  have e1 : 2 ^ s < 2 ^ (s' + 1) := by rw [pow_succ]; omega
  have e2 : 2 ^ s' < 2 ^ (s + 1) := by rw [pow_succ]; omega
  have := (Nat.pow_lt_pow_iff_right (by norm_num : 1 < 2)).1 e1
  have := (Nat.pow_lt_pow_iff_right (by norm_num : 1 < 2)).1 e2
  omega

open Classical in
/-- The indices `j ∈ [j₀, J]` for which the major center of `λ` at scale `j` belongs to `𝓡_s`
(Blueprint Lemma 12.2 (`lem:coherence`)). -/
noncomputable def majorIdx (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) (s : ℕ)
    (lam : ℝ) (J : ℕ) : Finset ℕ :=
  (Finset.Icc (coherJ0 n d Ω p) J).filter fun j => ∃ aq ∈ liftRat s,
    aq.2 < minorH (paramM n d Ω p) j ∧
      ‖((lam - aq.1 / aq.2 : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j

/-- Membership in `majorIdx`. -/
lemma mem_majorIdx {s : ℕ} {lam : ℝ} {J j : ℕ} :
    j ∈ majorIdx n d Ω p s lam J ↔ coherJ0 n d Ω p ≤ j ∧ j ≤ J ∧ ∃ a q : ℕ, (a, q) ∈ liftRat s ∧
      q < minorH (paramM n d Ω p) j ∧
      ‖((lam - a / q : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j := by
  simp only [majorIdx, Finset.mem_filter, Finset.mem_Icc, Prod.exists, and_assoc]

/-- **Blueprint Lemma 12.2 (`lem:coherence`)**, interval coherence: for `d ≥ 1`, fixed `s`, `λ`
and finite upper scale `J`, either no `j ∈ [j₀, J]` has its major center in `𝓡_s`, or there are
one center `α = a/q ∈ 𝓡_s` (so `s ≥ 1`), one real representative `μ` of `λ - α` with
`|μ| < 1/4`, and `b ≤ J` such that the set of these indices is the interval `[j_s, b]`,
`j_s = max(j₀, ⌈2^{s/M}⌉ - 1)`, and for each such `j`: `a/q` is admissible in `X_j` and is the
unique major center of `λ` at scale `j`, `‖λ - α‖_𝕋 = |μ| ≤ w_j`, `|μ| 2^{Dj} ≤ (j+1)^M`
(`D = 2d`), and `L_s ≤ 2^{j/2}`. -/
theorem major_coherence (hd : 1 ≤ d) (s : ℕ) (lam : ℝ) (J : ℕ) :
    majorIdx n d Ω p s lam J = ∅ ∨
      ∃ (a q : ℕ) (μ : ℝ) (b : ℕ), (a, q) ∈ liftRat s ∧ 1 ≤ s ∧ |μ| < 1 / 4 ∧
        (∃ k : ℤ, lam = a / q + μ + k) ∧ b ≤ J ∧
        majorIdx n d Ω p s lam J = Finset.Icc (coherJs n d Ω p s) b ∧
        ∀ j ∈ majorIdx n d Ω p s lam J,
          IsMajorCenter (paramM n d Ω p) j a q ∧
          (∀ a' q' : ℕ, IsMajorCenter (paramM n d Ω p) j a' q' →
            ‖((lam - a' / q' : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j →
              a' = a ∧ q' = q) ∧
          ‖((lam - a / q : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j ∧
          |μ| ≤ minorW d (paramM n d Ω p) j ∧
          |μ| * (2 : ℝ) ^ (2 * d * j) ≤ ((j : ℝ) + 1) ^ paramM n d Ω p ∧
          (liftL n d Ω p s : ℝ) ≤ (2 : ℝ) ^ ((j : ℝ) / 2) := by
  rcases (majorIdx n d Ω p s lam J).eq_empty_or_nonempty with h | hne
  · exact Or.inl h
  right
  set M := paramM n d Ω p with hMdef
  set S := majorIdx n d Ω p s lam J with hSdef
  have hspec := coherJ0_spec (n := n) (Ω := Ω) (p := p) hd
  obtain ⟨jst, hjst⟩ := hne
  obtain ⟨hj0st, hjJst, a, q, haq, hqH, hδ⟩ := mem_majorIdx.1 hjst
  obtain ⟨hs1, -, -⟩ := liftRat_bounds_of_lt_minorH haq hqH
  obtain ⟨-, hq2, ha, hc⟩ := mem_liftRat.1 haq
  have hq1 : 1 ≤ q := one_le_of_mem_liftRat haq
  set δ := ‖((lam - a / q : ℝ) : UnitAddCircle)‖ with hδdef
  have hws : ∀ j, coherJ0 n d Ω p ≤ j → 2 ^ s ≤ minorH M j →
      minorW d M j ≤ (((2 : ℝ) ^ s) ^ 2)⁻¹ / 16 := by
    intro j hj hsH
    refine ((hspec.2 j hj).1.2.2).trans ?_
    have : ((2 : ℝ) ^ s) ≤ minorH M j := by exact_mod_cast hsH
    gcongr
  have hcenter : ∀ j ∈ S, ∀ a' q' : ℕ, (a', q') ∈ liftRat s → q' < minorH M j →
      ‖((lam - a' / q' : ℝ) : UnitAddCircle)‖ ≤ minorW d M j → a' = a ∧ q' = q := by
    intro j hj a' q' h' hq'H hδ'
    obtain ⟨hj0, -, -⟩ := mem_majorIdx.1 hj
    obtain ⟨-, hsH', -⟩ := liftRat_bounds_of_lt_minorH h' hq'H
    obtain ⟨-, hsHst, -⟩ := liftRat_bounds_of_lt_minorH haq hqH
    obtain ⟨-, hq2', ha', hc'⟩ := mem_liftRat.1 h'
    have e1 := hws j hj0 hsH'
    have e2 := hws jst hj0st hsHst
    have hpos : 0 < (((2 : ℝ) ^ s) ^ 2)⁻¹ := by positivity
    refine reduced_eq_of_norm_lt (one_le_of_mem_liftRat h') ha' hc' hq1 ha hc (B := 2 ^ s)
      (by unfold liftN at hq2'; exact_mod_cast hq2') (by unfold liftN at hq2; exact_mod_cast hq2) ?_
    calc ‖(((a' : ℝ) / q' - a / q : ℝ) : UnitAddCircle)‖ ≤ minorW d M j + minorW d M jst :=
          (norm_sub_centers_le lam _ _).trans (add_le_add hδ' hδ)
      _ < 1 / ((2 : ℝ) ^ s) ^ 2 := by rw [one_div]; linarith
  have hmem : ∀ j, j ∈ S ↔ coherJs n d Ω p s ≤ j ∧ j ≤ J ∧ δ ≤ minorW d M j := by
    intro j
    constructor
    · intro hj
      obtain ⟨hj0, hjJ, a', q', h', hq'H, hδ'⟩ := mem_majorIdx.1 hj
      obtain ⟨rfl, rfl⟩ := hcenter j hj a' q' h' hq'H hδ'
      obtain ⟨-, hsH, -⟩ := liftRat_bounds_of_lt_minorH haq hq'H
      exact ⟨max_le hj0 ((two_pow_le_minorH_iff major_one_le_paramM s j).1 hsH), hjJ, hδ'⟩
    · rintro ⟨hjs, hjJ, hδj⟩
      exact mem_majorIdx.2 ⟨le_trans (le_max_left _ _) hjs, hjJ, a, q, haq,
        (isMajorCenter_of_mem_liftRat hjs haq).2.1, hδj⟩
  set b := S.max' ⟨jst, hjst⟩ with hbdef
  have hb : b ∈ S := S.max'_mem _
  obtain ⟨hbs, hbJ, hδb⟩ := (hmem b).1 hb
  have hSI : S = Finset.Icc (coherJs n d Ω p s) b := by
    ext j
    rw [Finset.mem_Icc]
    constructor
    · intro hj; exact ⟨((hmem j).1 hj).1, S.le_max' j hj⟩
    · rintro ⟨hjs, hjb⟩
      refine (hmem j).2 ⟨hjs, hjb.trans hbJ, hδb.trans ?_⟩
      exact minorW_antitone hd (le_trans (le_max_left _ _) hjs) hjb
  set μ : ℝ := lam - a / q - round (lam - a / q) with hμdef
  have hμδ : |μ| = δ := by rw [hδdef, UnitAddCircle.norm_eq]
  refine ⟨a, q, μ, b, haq, hs1, ?_, ⟨round (lam - a / q), by rw [hμdef]; ring⟩, hbJ, hSI,
    fun j hj => ?_⟩
  · rw [hμδ]; exact lt_of_le_of_lt hδ (hspec.2 jst hj0st).1.1
  obtain ⟨hjs, hjJ, hδj⟩ := (hmem j).1 hj
  have hj0 : coherJ0 n d Ω p ≤ j := le_trans (le_max_left _ _) hjs
  have hadm : IsMajorCenter M j a q := isMajorCenter_of_mem_liftRat hjs haq
  obtain ⟨-, -, hsE⟩ := liftRat_bounds_of_lt_minorH haq hadm.2.1
  refine ⟨hadm, fun a' q' h' hδ' => ?_, hδj, hμδ ▸ hδj, ?_, ?_⟩
  · obtain ⟨h1, h2⟩ := (hspec.2 j hj0).2.1 _ _ _ _ h' hadm lam hδ' hδj
    exact ⟨h1, h2⟩
  · have h1 : |μ| ≤ minorW d M j := hμδ ▸ hδj
    rw [minorW, le_div_iff₀ (by positivity)] at h1
    exact h1
  · have hv := (hspec.2 j hj0).2.2 s hs1 hsE
    rw [liftL, Nat.cast_pow, Nat.cast_ofNat, ← Real.rpow_natCast]
    exact Real.rpow_le_rpow_of_exponent_le (by norm_num) hv

/-- For Blueprint Proposition 12.3: for `j ∈ [j₀, J]`, `λ ∈ X_j` iff `j` is a major index of `λ`
for some group `s`. -/
theorem mem_minorArcs_iff_exists_majorIdx {j J : ℕ} (hj0 : coherJ0 n d Ω p ≤ j) (hjJ : j ≤ J)
    (lam : ℝ) :
    lam ∈ minorArcs d (paramM n d Ω p) j ↔ ∃ s, j ∈ majorIdx n d Ω p s lam J := by
  constructor
  · rintro ⟨q, a, hq, hqH, ha, hc, hl⟩
    obtain ⟨s, hs⟩ := exists_mem_liftRat a hq ha hc
    exact ⟨s, mem_majorIdx.2 ⟨hj0, hjJ, a, q, hs, hqH, hl⟩⟩
  · rintro ⟨s, hs⟩
    obtain ⟨-, -, a, q, haq, hqH, hl⟩ := mem_majorIdx.1 hs
    obtain ⟨-, -, ha, hc⟩ := mem_liftRat.1 haq
    exact ⟨q, a, one_le_of_mem_liftRat haq, hqH, ha, hc, hl⟩

/-- For Blueprint Proposition 12.3: a major index belongs to exactly one group `s`. -/
theorem eq_of_mem_majorIdx (hd : 1 ≤ d) {s s' : ℕ} {lam : ℝ} {J j : ℕ}
    (h : j ∈ majorIdx n d Ω p s lam J) (h' : j ∈ majorIdx n d Ω p s' lam J) : s = s' := by
  obtain ⟨hj0, -, a, q, haq, hqH, hl⟩ := mem_majorIdx.1 h
  obtain ⟨-, -, a', q', haq', hqH', hl'⟩ := mem_majorIdx.1 h'
  obtain ⟨-, -, ha, hc⟩ := mem_liftRat.1 haq
  obtain ⟨-, -, ha', hc'⟩ := mem_liftRat.1 haq'
  obtain ⟨rfl, rfl⟩ := ((coherJ0_spec hd).2 j hj0).2.1 a q a' q'
    ⟨one_le_of_mem_liftRat haq, hqH, ha, hc⟩ ⟨one_le_of_mem_liftRat haq', hqH', ha', hc'⟩ lam hl hl'
  exact eq_of_mem_liftRat haq haq'

/-! ### Blueprint Proposition 12.3 (`prop:finiteSW`) -/

section FiniteSW

open scoped ENNReal

/-- A finitely supported function on `ℤⁿ` lies in every `ℓ^q`. -/
lemma finSW_memLp {f : (Fin n → ℤ) → ℂ} (hf : (Function.support f).Finite) (q : ℝ≥0∞) :
    MemLp f q Measure.count := by
  have hb : MemLp f ∞ Measure.count := by
    refine memLp_top_of_bound AEStronglyMeasurable.of_discrete (∑ z ∈ hf.toFinset, ‖f z‖)
      (ae_of_all _ fun x => ?_)
    by_cases hx : x ∈ Function.support f
    · exact Finset.single_le_sum (f := fun z => ‖f z‖) (fun _ _ => norm_nonneg _)
        (hf.mem_toFinset.2 hx)
    · rw [Function.notMem_support.1 hx, norm_zero]
      exact Finset.sum_nonneg fun _ _ => norm_nonneg _
  exact hb.mono_exponent_of_measure_support_ne_top (s := Function.support f)
    (fun x hx => Function.notMem_support.1 hx) (Measure.count_apply_lt_top.2 hf).ne le_top

/-- The `λ`-independent smoothing-error majorant `(1 + (j+1)^M) 2^{-j/2} (B_{2^j} * |f|)(x)` of the
proof of Blueprint Proposition 12.3 (`prop:finiteSW`). -/
noncomputable def finSWErr (n M j : ℕ) (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) : ℝ≥0∞ :=
  ENNReal.ofReal ((1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2))) *
    ∑' y, ENNReal.ofReal (latEnvelope n (2 ^ j) y) * ‖f (x - y)‖ₑ

/-- The smoothing error of the proof of Blueprint Proposition 12.3 (`prop:finiteSW`), from
Lemma 12.1: if `λ = a/q + μ` in `𝕋`, `|μ| 2^{Dj} ≤ (j+1)^M` and `L_s ≤ 2^{j/2}`, then
`|T_{j,λ} f - Lift_{s,a/q}[Φ_{j,μ}] f| ≤ C (1 + (j+1)^M) 2^{-j/2} (B_{2^j} * |f|)` pointwise. -/
lemma finSW_kernel_error (hΩ : IsSWProfile Ω) (d : ℕ) :
    ∃ Ck : ℝ, 0 ≤ Ck ∧ ∀ (p : ℝ) (s a q : ℕ), 1 ≤ q → ∀ (j M : ℕ) (lam μ : ℝ),
      (∃ k : ℤ, lam = a / q + μ + k) → |μ| * (2 : ℝ) ^ (2 * d * j) ≤ ((j : ℝ) + 1) ^ M →
      (liftL n d Ω p s : ℝ) ≤ (2 : ℝ) ^ ((j : ℝ) / 2) →
      ∀ f : (Fin n → ℤ) → ℂ, Summable (fun z => ‖f z‖) → ∀ x,
        ‖minorOp Ω d j lam f x -
            latMult (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) f x‖ₑ ≤
          ENNReal.ofReal Ck * finSWErr n M j f x := by
  obtain ⟨C, hC, hK⟩ := major_kernel_error (n := n) hΩ d
  refine ⟨C, hC, fun p s a q hq j M lam μ hlam hμ hL f hf x => ?_⟩
  rw [major_kernel_formula hΩ p s a hq j hlam hf x, finSWErr, ← mul_assoc,
    ← ENNReal.ofReal_mul hC, ← ENNReal.tsum_mul_left]
  refine enorm_tsum_le_tsum_enorm.trans (ENNReal.tsum_le_tsum fun y => ?_)
  set U : ℝ := ((j : ℝ) + 1) ^ M with hUdef
  have hU0 : 0 ≤ U := by positivity
  have hU : |μ| * ((2 : ℝ) ^ j) ^ (2 * d) ≤ U := by
    rw [← pow_mul, mul_comm j]; exact hμ
  have hk := hK p s j μ U hU (latEmbed y)
  have hR : (0 : ℝ) < 2 ^ j := by positivity
  have hB : 0 ≤ latEnvelope n (2 ^ j) y := envelope_nonneg hR _
  have hLR : (liftL n d Ω p s : ℝ) / 2 ^ j ≤ (2 : ℝ) ^ (-((j : ℝ) / 2)) := by
    rw [div_le_iff₀ hR, ← Real.rpow_natCast, ← Real.rpow_add two_pos]
    convert hL using 2; ring
  rw [enorm_mul, enorm_mul, ← ofReal_norm (eC _), norm_eC, ENNReal.ofReal_one, one_mul,
    ← ofReal_norm, ← mul_assoc, ← ENNReal.ofReal_mul (by positivity)]
  gcongr
  calc _ ≤ C * (1 + U) * ((liftL n d Ω p s : ℝ) / 2 ^ j) * envelope n (2 ^ j) (latEmbed y) := hk
    _ ≤ C * (1 + U) * (2 : ℝ) ^ (-((j : ℝ) / 2)) * envelope n (2 ^ j) (latEmbed y) := by
        gcongr
    _ = _ := by rw [latEnvelope]; ring

/-- `ℓ^p` bound of the smoothing-error majorant (Young and the uniform lattice sum of `B_{2^j}`). -/
lemma eLpNorm_finSWErr_le {p : ℝ} (hp : 1 < p) (M j : ℕ) (f : (Fin n → ℤ) → ℂ) :
    eLpNorm (finSWErr n M j f) (ENNReal.ofReal p) Measure.count ≤
      ENNReal.ofReal ((1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)) * envelopeConst n) *
        eLpNorm f (ENNReal.ofReal p) Measure.count := by
  have hp1 : (1 : ℝ≥0∞) ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hp.le
  have hR : (0 : ℝ) < 2 ^ j := by positivity
  have hB : ∀ y, 0 ≤ latEnvelope n (2 ^ j) y := fun y => envelope_nonneg hR _
  have hk : ∀ y,
      ‖((latEnvelope n (2 ^ j) y : ℝ) : ℂ)‖ₑ = ENNReal.ofReal (latEnvelope n (2 ^ j) y) :=
    fun y => by rw [← ofReal_norm, Complex.norm_real, Real.norm_of_nonneg (hB y)]
  have e : finSWErr n M j f = fun x =>
      ENNReal.ofReal ((1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2))) *
        ∑' y, ‖((latEnvelope n (2 ^ j) y : ℝ) : ℂ)‖ₑ * ‖f (x - y)‖ₑ := by
    funext x; simp only [finSWErr, hk]
  rw [e, eLpNorm_count_const_mul _ _ (by linarith)]
  refine (mul_le_mul' le_rfl (eLpNorm_tsum_enorm_mul_sub_le hp1 _ f)).trans ?_
  rw [ENNReal.ofReal_mul (p := (1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)))
    (by positivity), mul_assoc]
  refine mul_le_mul' le_rfl (mul_le_mul' ?_ le_rfl)
  rw [eLpNorm_one_eq_lintegral_enorm AEStronglyMeasurable.of_discrete, lintegral_count]
  obtain ⟨hs, hle⟩ := summable_latEnvelope_and_tsum_le (n := n) (R := 2 ^ j)
    (one_le_pow₀ one_le_two)
  simp only [hk]
  rw [← ENNReal.ofReal_tsum_of_nonneg hB hs]
  exact ENNReal.ofReal_le_ofReal hle

/-- The smoothing-error coefficients `(1 + (j+1)^M) 2^{-j/2}` are summable. -/
lemma finSW_summable_err (M : ℕ) :
    Summable fun j : ℕ => (1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)) := by
  obtain ⟨r, hr⟩ : ∃ r : ℝ, r = (2 : ℝ) ^ (-(1 / 2 : ℝ)) := ⟨_, rfl⟩
  have hr0 : 0 < r := by rw [hr]; positivity
  have hr1 : r < 1 := by
    rw [hr]; exact Real.rpow_lt_one_of_one_lt_of_neg (by norm_num) (by norm_num)
  have e : ∀ j : ℕ, (2 : ℝ) ^ (-((j : ℝ) / 2)) = r ^ j := by
    intro j; rw [hr, ← Real.rpow_mul_natCast (by norm_num)]; congr 1; ring
  have h1 : Summable fun j : ℕ => ((j + 1 : ℕ) : ℝ) ^ M * r ^ (j + 1) :=
    (summable_nat_add_iff (f := fun j : ℕ => (j : ℝ) ^ M * r ^ j) 1).2
      (summable_pow_mul_geometric_of_norm_lt_one M
      (by rw [Real.norm_of_nonneg hr0.le]; exact hr1))
  have h2 := summable_geometric_of_lt_one hr0.le hr1
  refine (h2.add (h1.mul_left r⁻¹)).congr fun j => ?_
  rw [e j, pow_succ]
  push_cast
  field_simp

/-- `j ↦ ⌊M log₂(j+1)⌋` is monotone. -/
lemma majorExp_mono (M : ℕ) {j j' : ℕ} (h : j ≤ j') : majorExp M j ≤ majorExp M j' := by
  unfold majorExp
  apply Nat.floor_mono
  have : (j : ℝ) ≤ j' := by exact_mod_cast h
  exact mul_le_mul_of_nonneg_left
    (Real.logb_le_logb_of_le (by norm_num) (by positivity) (by linarith)) (Nat.cast_nonneg _)

/-- The group majorant of the proof of Blueprint Proposition 12.3 (`prop:finiteSW`): `𝒫_s f` for
`s ≥ 1`, and `0` for `s = 0`. -/
noncomputable def finSWMain (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) (s : ℕ)
    (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) : ℝ≥0∞ :=
  if 1 ≤ s then liftedPartialMax n d Ω p s f x else 0

open Classical in
/-- The pointwise majorant of the proof of Blueprint Proposition 12.3 (`prop:finiteSW`): for every
`λ`, `|∑_{j=j₀}^J T_{j,λ} f(x)|` is at most the sum of the minor-arc maximal functions
`sup_{λ' ∉ X_j} |T_{j,λ'} f(x)|`, the smoothing errors, and the group majorants `𝒫_s f(x)`
(a majorant independent of `λ`). -/
lemma finSW_pointwise (hn : 1 ≤ n) (hd : 1 ≤ d) (hΩ : IsSWProfile Ω) {Ck : ℝ}
    (hCk : ∀ (s a q : ℕ), 1 ≤ q → ∀ (j : ℕ) (lam μ : ℝ),
      (∃ k : ℤ, lam = a / q + μ + k) →
      |μ| * (2 : ℝ) ^ (2 * d * j) ≤ ((j : ℝ) + 1) ^ paramM n d Ω p →
      (liftL n d Ω p s : ℝ) ≤ (2 : ℝ) ^ ((j : ℝ) / 2) →
      ∀ f : (Fin n → ℤ) → ℂ, Summable (fun z => ‖f z‖) → ∀ x,
        ‖minorOp Ω d j lam f x -
            latMult (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) f x‖ₑ ≤
          ENNReal.ofReal Ck * finSWErr n (paramM n d Ω p) j f x)
    (J : ℕ) {f : (Fin n → ℤ) → ℂ} (hf : Summable fun z => ‖f z‖) (lam : ℝ) (x : Fin n → ℤ) :
    ‖∑ j ∈ Finset.Icc (coherJ0 n d Ω p) J, minorOp Ω d j lam f x‖ₑ ≤
      ∑ j ∈ Finset.Icc (coherJ0 n d Ω p) J,
          minorSup Ω d j (minorArcs d (paramM n d Ω p) j) f x +
        ∑ j ∈ Finset.Icc (coherJ0 n d Ω p) J,
          ENNReal.ofReal Ck * finSWErr n (paramM n d Ω p) j f x +
        ∑' s, finSWMain n d Ω p s f x := by
  set M := paramM n d Ω p with hMdef
  set A := Finset.Icc (coherJ0 n d Ω p) J with hAdef
  set N := minorH M J + 1 with hNdef
  have hj1 : 1 ≤ coherJ0 n d Ω p := (one_le_paramJ1 hn hd hΩ p).trans (coherJ0_spec hd).1
  have hMaj : A.filter (fun j => lam ∈ minorArcs d M j) =
      (Finset.range N).biUnion (fun s => majorIdx n d Ω p s lam J) := by
    ext j
    simp only [Finset.mem_filter, Finset.mem_biUnion, Finset.mem_range]
    constructor
    · rintro ⟨hjA, hl⟩
      obtain ⟨hj0, hjJ⟩ := Finset.mem_Icc.1 hjA
      obtain ⟨s, hs⟩ := (mem_minorArcs_iff_exists_majorIdx hj0 hjJ lam).1 hl
      refine ⟨s, ?_, hs⟩
      obtain ⟨-, -, a, q, haq, hqH, -⟩ := mem_majorIdx.1 hs
      obtain ⟨-, h2, -⟩ := liftRat_bounds_of_lt_minorH haq hqH
      have h3 : minorH M j ≤ minorH M J := by
        rw [minorH_eq_two_pow, minorH_eq_two_pow]
        exact Nat.pow_le_pow_right (by norm_num) (majorExp_mono M hjJ)
      have h2' : 2 ^ s ≤ minorH M j := h2
      have := Nat.lt_two_pow_self (n := s)
      omega
    · rintro ⟨s, -, hs⟩
      obtain ⟨hj0, hjJ, -⟩ := mem_majorIdx.1 hs
      exact ⟨Finset.mem_Icc.2 ⟨hj0, hjJ⟩,
        (mem_minorArcs_iff_exists_majorIdx hj0 hjJ lam).2 ⟨s, hs⟩⟩
  have hdisj : (↑(Finset.range N) : Set ℕ).PairwiseDisjoint
      (fun s => majorIdx n d Ω p s lam J) := by
    intro s _ s' _ hne
    exact Finset.disjoint_left.2 fun j h h' => hne (eq_of_mem_majorIdx hd h h')
  have hgroup : ∀ s, ‖∑ j ∈ majorIdx n d Ω p s lam J, minorOp Ω d j lam f x‖ₑ ≤
      ∑ j ∈ majorIdx n d Ω p s lam J, ENNReal.ofReal Ck * finSWErr n M j f x +
        finSWMain n d Ω p s f x := by
    intro s
    rcases major_coherence (n := n) (Ω := Ω) (p := p) hd s lam J with
      h | ⟨a, q, μ, b, haq, hs1, -, hlam, -, hI, hprop⟩
    · rw [h, Finset.sum_empty, Finset.sum_empty, enorm_zero]; exact zero_le
    have hq : 1 ≤ q := one_le_of_mem_liftRat haq
    have hsplit : ∑ j ∈ majorIdx n d Ω p s lam J, minorOp Ω d j lam f x =
        ∑ j ∈ majorIdx n d Ω p s lam J, (minorOp Ω d j lam f x -
          latMult (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) f x) +
        ∑ j ∈ Finset.Icc (coherJs n d Ω p s) b,
          latMult (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) f x := by
      rw [← hI, ← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun j _ => by ring
    rw [hsplit]
    refine (enorm_add_le _ _).trans (add_le_add ?_ ?_)
    · refine (enorm_sum_le _ _).trans (Finset.sum_le_sum fun j hj => ?_)
      obtain ⟨-, -, -, -, hμj, hLj⟩ := hprop j hj
      exact hCk s a q hq j lam μ hlam hμj hLj f hf x
    · by_cases hab : coherJs n d Ω p s ≤ b
      · have hlin : ∑ j ∈ Finset.Icc (coherJs n d Ω p s) b,
            latMult (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) f x =
            latMult (liftSym n d Ω p s a q (fun ξ => ∑ j ∈ Finset.Icc (coherJs n d Ω p s) b,
              radialOscPhi Ω d j μ ξ)) f x :=
          (latMult_liftSym_finsetSum _ (m := fun j : ℕ => radialOscPhi Ω d j μ)
            (fun j => (continuous_radialOscPhi_and_le hΩ j μ).1)
            (fun j ξ => (continuous_radialOscPhi_and_le hΩ j μ).2 ξ) hf x).symm
        rw [hlin]; simp only [finSWMain, hs1, ↓reduceIte]
        exact le_iSup₂_of_le (a, q) haq (le_iSup_of_le μ (le_iSup_of_le (coherJs n d Ω p s)
          (le_iSup_of_le b (le_iSup_of_le ⟨hj1.trans (le_max_left _ _), hab⟩ le_rfl))))
      · rw [Finset.Icc_eq_empty hab, Finset.sum_empty, enorm_zero]; exact zero_le
  have hA := Finset.sum_filter_add_sum_filter_not A (fun j => lam ∈ minorArcs d M j)
    (fun j => minorOp Ω d j lam f x)
  rw [← hA]
  refine (enorm_add_le _ _).trans ?_
  have hmaj : ‖∑ j ∈ A.filter (fun j => lam ∈ minorArcs d M j), minorOp Ω d j lam f x‖ₑ ≤
      ∑ j ∈ A, ENNReal.ofReal Ck * finSWErr n M j f x + ∑' s, finSWMain n d Ω p s f x := by
    rw [hMaj, Finset.sum_biUnion hdisj]
    refine (enorm_sum_le _ _).trans ((Finset.sum_le_sum fun s _ => hgroup s).trans ?_)
    rw [Finset.sum_add_distrib, ← Finset.sum_biUnion hdisj, ← hMaj]
    exact add_le_add (Finset.sum_le_sum_of_subset (Finset.filter_subset _ _))
      (ENNReal.sum_le_tsum _)
  have hmin : ‖∑ j ∈ A.filter (fun j => lam ∉ minorArcs d M j), minorOp Ω d j lam f x‖ₑ ≤
      ∑ j ∈ A, minorSup Ω d j (minorArcs d M j) f x := by
    refine (enorm_sum_le _ _).trans ((Finset.sum_le_sum fun j hj => ?_).trans
      (Finset.sum_le_sum_of_subset (Finset.filter_subset _ _)))
    exact le_iSup₂_of_le (f := fun (l : ℝ) (_ : l ∉ minorArcs d M j) => ‖minorOp Ω d j l f x‖ₑ)
      lam (Finset.mem_filter.1 hj).2 le_rfl
  calc _ ≤ (∑ j ∈ A, ENNReal.ofReal Ck * finSWErr n M j f x + ∑' s, finSWMain n d Ω p s f x) +
        ∑ j ∈ A, minorSup Ω d j (minorArcs d M j) f x := add_le_add hmaj hmin
    _ = _ := by ring

/-- `ℓ^p` bound of the group majorant: `‖𝒫_s f‖_p ≤ C ρ^s ‖f‖_p`, `ρ = 2^{-c}` (Theorem 11.3). -/
lemma eLpNorm_finSWMain_le (hn : 1 ≤ n) (hd : 1 ≤ d) (hΩ : IsSWProfile Ω) (hp : 1 < p) :
    ∃ c : ℝ, 0 < c ∧ ∃ C : ℝ, 0 ≤ C ∧ ∀ s : ℕ, ∀ f : (Fin n → ℤ) → ℂ,
      (Function.support f).Finite →
        eLpNorm (finSWMain n d Ω p s f) (ENNReal.ofReal p) Measure.count ≤
          ENNReal.ofReal (C * ((2 : ℝ) ^ (-c)) ^ s) *
            eLpNorm f (ENNReal.ofReal p) Measure.count := by
  obtain ⟨c, hc, C, hC, hP⟩ := lift_partial_sums hn hd hΩ hp
  refine ⟨c, hc, C, hC, fun s f hf => ?_⟩
  by_cases hs : 1 ≤ s
  · have e : finSWMain n d Ω p s f = liftedPartialMax n d Ω p s f := by
      funext x; simp only [finSWMain, hs, ↓reduceIte]
    rw [e, ← Real.rpow_natCast, ← Real.rpow_mul (by norm_num), neg_mul]
    exact hP s hs f hf
  · have e : finSWMain n d Ω p s f = 0 := by
      funext x; simp only [finSWMain, hs, ↓reduceIte, Pi.zero_apply]
    rw [e, eLpNorm_zero]; exact zero_le

/-- **Blueprint Proposition 12.3 (`prop:finiteSW`)**, uniform finite dyadic estimate, eq. (12.2)
(`eq:finiteSW`): for `n, d ≥ 1`, an admissible profile `Ω` and `1 < p < ∞`, with the final lower
scale `j₀ = coherJ0 n d Ω p` of Lemma 12.2, there is `C_p ≥ 0` such that for every integer
`J ≥ j₀` and every finitely supported `f : ℤⁿ → ℂ`,
`‖sup_{λ ∈ 𝕋} |∑_{j=j₀}^J T_{j,λ} f|‖_{ℓ^p} ≤ C_p ‖f‖_{ℓ^p}`
(`C_p` independent of `J` and `f`; the supremum is over `λ ∈ ℝ`, which is the same as over `𝕋`
since `T_{j,λ}` is `1`-periodic in `λ`). -/
theorem finite_dyadic_stein_wainger (hn : 1 ≤ n) (hd : 1 ≤ d) (hΩ : IsSWProfile Ω)
    (hp : 1 < p) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ J ≥ coherJ0 n d Ω p, ∀ f : (Fin n → ℤ) → ℂ,
      (Function.support f).Finite →
        eLpNorm (fun x => ⨆ lam : ℝ,
            ‖∑ j ∈ Finset.Icc (coherJ0 n d Ω p) J, minorOp Ω d j lam f x‖ₑ)
            (ENNReal.ofReal p) Measure.count ≤
          ENNReal.ofReal C * eLpNorm f (ENNReal.ofReal p) Measure.count := by
  obtain ⟨Cm, hCm, hmin⟩ := minor_arc_decay_lp hn hd hΩ hp
  obtain ⟨Ck, hCk, herr⟩ := finSW_kernel_error (n := n) hΩ d
  obtain ⟨c, hc, CP, hCP, hP⟩ := eLpNorm_finSWMain_le hn hd hΩ hp
  set M := paramM n d Ω p with hMdef
  set j₀ := coherJ0 n d Ω p with hj₀
  set ρ : ℝ := (2 : ℝ) ^ (-c) with hρ
  have hρ0 : 0 ≤ ρ := by positivity
  have hρ1 : ρ < 1 := Real.rpow_lt_one_of_one_lt_of_neg (by norm_num) (by linarith)
  have hsum1 : Summable fun j : ℕ => (j : ℝ) ^ (-2 : ℝ) := Real.summable_nat_rpow.2 (by norm_num)
  have hsum2 := finSW_summable_err M
  set S1 := ∑' j : ℕ, (j : ℝ) ^ (-2 : ℝ) with hS1def
  set S2 := ∑' j : ℕ, (1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)) with hS2def
  have hS1 : 0 ≤ S1 := tsum_nonneg fun j => by positivity
  have hS2 : 0 ≤ S2 := tsum_nonneg fun j => by positivity
  have hE0 : 0 ≤ envelopeConst n := by unfold envelopeConst; positivity
  have hρ' : 0 ≤ (1 - ρ)⁻¹ := inv_nonneg.2 (by linarith)
  refine ⟨Cm * S1 + Ck * envelopeConst n * S2 + CP * (1 - ρ)⁻¹, by positivity,
    fun J hJ f hf => ?_⟩
  set nf := eLpNorm f (ENNReal.ofReal p) Measure.count with hnf
  have hp1 : (1 : ℝ≥0∞) ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hp.le
  have hf1 : Summable fun z => ‖f z‖ := summable_of_finite_support hf
  have hfL := finSW_memLp hf (ENNReal.ofReal p)
  set A := Finset.Icc j₀ J with hAdef
  set G1 : (Fin n → ℤ) → ℝ≥0∞ := ∑ j ∈ A, fun x => minorSup Ω d j (minorArcs d M j) f x
    with hG1
  set G2 : (Fin n → ℤ) → ℝ≥0∞ := ∑ j ∈ A, fun x => ENNReal.ofReal Ck * finSWErr n M j f x
    with hG2
  set G3 : (Fin n → ℤ) → ℝ≥0∞ := fun x => ∑' s, finSWMain n d Ω p s f x with hG3
  have hpt : ∀ x, ‖⨆ lam : ℝ, ‖∑ j ∈ A, minorOp Ω d j lam f x‖ₑ‖ₑ ≤ ‖(G1 + G2 + G3) x‖ₑ := by
    intro x
    rw [enorm_eq_self, enorm_eq_self]
    simp only [hG1, hG2, hG3, Pi.add_apply, Finset.sum_apply]
    exact iSup_le fun lam => finSW_pointwise hn hd hΩ
      (fun s a q hq j lam μ hlam hμ hL f hf x => herr p s a q hq j M lam μ hlam hμ hL f hf x)
      J hf1 lam x
  have h1 : eLpNorm G1 (ENNReal.ofReal p) Measure.count ≤ ENNReal.ofReal (Cm * S1) * nf := by
    refine (eLpNorm_sum_le hp1).trans ?_
    calc ∑ j ∈ A, eLpNorm (fun x => minorSup Ω d j (minorArcs d M j) f x)
          (ENNReal.ofReal p) Measure.count
        ≤ ∑ j ∈ A, ENNReal.ofReal (Cm * (j : ℝ) ^ (-2 : ℝ)) * nf :=
          Finset.sum_le_sum fun j hj =>
            hmin j ((coherJ0_spec hd).1.trans (Finset.mem_Icc.1 hj).1) f hfL
      _ = ENNReal.ofReal (∑ j ∈ A, Cm * (j : ℝ) ^ (-2 : ℝ)) * nf := by
          rw [← Finset.sum_mul, ENNReal.ofReal_sum_of_nonneg (fun j _ => by positivity)]
      _ ≤ _ := by
          gcongr
          rw [← Finset.mul_sum]
          gcongr
          exact hsum1.sum_le_tsum A (fun j _ => by positivity)
  have h2 : eLpNorm G2 (ENNReal.ofReal p) Measure.count ≤
      ENNReal.ofReal (Ck * envelopeConst n * S2) * nf := by
    refine (eLpNorm_sum_le hp1).trans ?_
    calc ∑ j ∈ A, eLpNorm (fun x => ENNReal.ofReal Ck * finSWErr n M j f x)
          (ENNReal.ofReal p) Measure.count
        ≤ ∑ j ∈ A, ENNReal.ofReal (Ck * envelopeConst n *
            ((1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)))) * nf := by
          refine Finset.sum_le_sum fun j _ => ?_
          rw [eLpNorm_count_const_mul _ _ (by linarith)]
          refine (mul_le_mul' le_rfl (eLpNorm_finSWErr_le hp M j f)).trans (le_of_eq ?_)
          rw [← mul_assoc, ← ENNReal.ofReal_mul hCk]
          congr 2; ring
      _ = ENNReal.ofReal (∑ j ∈ A, Ck * envelopeConst n *
            ((1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)))) * nf := by
          rw [← Finset.sum_mul, ENNReal.ofReal_sum_of_nonneg (fun j _ => by positivity)]
      _ ≤ _ := by
          gcongr
          rw [← Finset.mul_sum]
          gcongr
          exact hsum2.sum_le_tsum A (fun j _ => by positivity)
  have h3 : eLpNorm G3 (ENNReal.ofReal p) Measure.count ≤
      ENNReal.ofReal (CP * (1 - ρ)⁻¹) * nf := by
    refine (eLpNorm_tsum_le_count hp1 ENNReal.ofReal_ne_top _).trans ?_
    refine (ENNReal.tsum_le_tsum fun s => hP s f hf).trans (le_of_eq ?_)
    rw [ENNReal.tsum_mul_right, ← ENNReal.ofReal_tsum_of_nonneg (fun s => by positivity)
      ((summable_geometric_of_lt_one hρ0 hρ1).mul_left _), tsum_mul_left,
      tsum_geometric_of_lt_one hρ0 hρ1]
  calc eLpNorm (fun x => ⨆ lam : ℝ, ‖∑ j ∈ A, minorOp Ω d j lam f x‖ₑ)
        (ENNReal.ofReal p) Measure.count
      ≤ eLpNorm (G1 + G2 + G3) (ENNReal.ofReal p) Measure.count :=
        eLpNorm_mono_enorm AEStronglyMeasurable.of_discrete hpt
    _ ≤ eLpNorm G1 (ENNReal.ofReal p) Measure.count +
          eLpNorm G2 (ENNReal.ofReal p) Measure.count +
          eLpNorm G3 (ENNReal.ofReal p) Measure.count :=
        (eLpNorm_add_le hp1).trans (add_le_add (eLpNorm_add_le hp1) le_rfl)
    _ ≤ ENNReal.ofReal (Cm * S1) * nf + ENNReal.ofReal (Ck * envelopeConst n * S2) * nf +
          ENNReal.ofReal (CP * (1 - ρ)⁻¹) * nf := by gcongr
    _ = _ := by
        rw [ENNReal.ofReal_add (by positivity) (by positivity),
          ENNReal.ofReal_add (by positivity) (by positivity)]
        ring

end FiniteSW

end MajorArcs

section DiscreteSteinWainger

/-!
## The discrete Stein–Wainger maximal operator

Formalization of the blueprint `blueprints/discrete-sw.tex`
("The discrete Stein–Wainger maximal operator: the combined `ℓ^p` bound, `1 < p < ∞`").

Results from §13 ("The operator on all of `ℓ^p` and the final theorem").

### Main results

* `absolute_convergence_and_parameter_continuity`: Blueprint Lemma 13.1 (`lem:absolute`), with
  eq. (13.1) (`eq:pointwisecontinuity`);
* `eLpNorm_swMax_le_of_finite_support`: the finite-support case of Theorem 13.2;
* `discrete_stein_wainger_lp`: Blueprint Theorem 13.2 (`thm:main`), eq. (13.2) (`eq:MAIN`).

### Proof outline

* The restricted kernel `swLatKernel Ω` (`y ↦ K(y)`, `K(0) = 0`) is in `ℓ^{p'}` since
  `|K(y)| ≤ B |y|^{-n}` (`exists_norm_swKernel_le_div`) and `∑_{y} |y|^{-r} < ∞` for `r > n`
  (`summable_norm_latEmbed_rpow`, from Mathlib's `ZLattice.summable_norm_rpow`); Hölder
  (`tsum_enorm_mul_enorm_sub_le`) gives absolute convergence and (13.1).
* Finite support: by telescoping (`sum_Icc_dyadicKernel`), at `|y| ≤ 2^J` one has
  `K(y) = k_init(y) + ∑_{j=j₀}^{J} K_j(y)` with `k_init(y) = η(2^{1-j₀} y) K(y)`
  (`swInitKernel`, which equals `η K + ∑_{1 ≤ j < j₀} K_j` and has finite support); so
  `T_λ f(x) = ∑_y e(λP(y)) k_init(y) f(x-y) + ∑_{j=j₀}^{J} T_{j,λ} f(x)` for all `λ` once `J` is
  large (`swOp_eq_init_add_minor`). The first part is bounded by `|k_init| * |f|`
  (`eLpNorm_init_le`), the second by Proposition 12.3 (`finite_dyadic_stein_wainger`), and a
  Fatou-type argument over finite sets of points (`eLpNorm_le_of_eventually_le`) concludes.
* General `f ∈ ℓ^p`: truncations to lattice boxes, pointwise convergence of the maximal
  functions from (13.1) (`abs_swMax_sub_le`) and Fatou (`eLpNorm_le_of_tendsto_of_eLpNorm_le`).
-/

open MeasureTheory Filter Topology Set
open scoped ENNReal NNReal

variable {n d : ℕ} {Ω : EuclideanSpace ℝ (Fin n) → ℂ}

/-- Helper: the decay bound `|K(x)| ≤ B |x|^{-n}` for `x ≠ 0`. -/
lemma exists_norm_swKernel_le_div (hΩ : IsSWProfile Ω) :
    ∃ B : ℝ, 0 ≤ B ∧ ∀ x : EuclideanSpace ℝ (Fin n), x ≠ 0 → ‖swKernel Ω x‖ ≤ B / ‖x‖ ^ n := by
  obtain ⟨C, hC⟩ := (isCompact_sphere (0 : EuclideanSpace ℝ (Fin n)) 1).exists_bound_of_continuousOn
    (hΩ.1.continuousOn.mono fun y hy => by
      simp only [mem_sphere_zero_iff_norm] at hy
      simp only [mem_compl_iff, mem_singleton_iff]
      rintro rfl; simp at hy)
  refine ⟨max C 0, le_max_right _ _, fun x hx => ?_⟩
  have hpos : 0 < ‖x‖ := norm_pos_iff.2 hx
  have hmem : ‖x‖⁻¹ • x ∈ Metric.sphere (0 : EuclideanSpace ℝ (Fin n)) 1 := by
    simp [norm_smul, hpos.ne']
  have hΩx : Ω x = Ω (‖x‖⁻¹ • x) := (hΩ.2.1 x hx _ (inv_pos.2 hpos)).symm
  simp only [swKernel, hx, ↓reduceIte]
  rw [norm_div, hΩx]
  simp only [Complex.norm_real, Real.norm_eq_abs, abs_of_pos (pow_pos hpos n)]
  gcongr
  exact (hC _ hmem).trans (le_max_left _ _)

/-- Helper: the integer lattice as a `ℤ`-lattice in `E`. -/
noncomputable abbrev latL (n : ℕ) : Submodule ℤ (EuclideanSpace ℝ (Fin n)) :=
  Submodule.span ℤ (Set.range (EuclideanSpace.basisFun (Fin n) ℝ).toBasis)

/-- Helper: `ι y` lies in the lattice `latL n`. -/
lemma latEmbed_mem_latL (y : Fin n → ℤ) : latEmbed y ∈ latL n := by
  have : latEmbed y = ∑ i, (y i) • (EuclideanSpace.basisFun (Fin n) ℝ).toBasis i := by
    ext j
    simp [Finset.sum_apply, Pi.single_apply]
  rw [this]
  exact Submodule.sum_mem _ fun i _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)


/-- Helper: `∑_{y ∈ ℤⁿ} |y|^r < ∞` for `r < -n` (the term at `0` is `0^r = 0`). -/
lemma summable_norm_latEmbed_rpow {r : ℝ} (hr : r < -n) :
    Summable fun y : Fin n → ℤ => ‖latEmbed y‖ ^ r := by
  have hrank : Module.finrank ℤ (latL n) = n := by
    rw [ZLattice.rank ℝ (latL n)]
    exact finrank_euclideanSpace_fin
  have hs : Summable fun z : latL n => ‖z‖ ^ r :=
    ZLattice.summable_norm_rpow (latL n) r (by rw [hrank]; exact hr)
  have hinj :
      Function.Injective (fun y : Fin n → ℤ => (⟨latEmbed y, latEmbed_mem_latL y⟩ : latL n)) :=
    fun y z h => latEmbed_injective (congrArg Subtype.val h)
  have h2 : Summable ((fun z : latL n => ‖z‖ ^ r) ∘ fun y : Fin n → ℤ =>
      (⟨latEmbed y, latEmbed_mem_latL y⟩ : latL n)) := Summable.comp_injective hs hinj
  exact h2


/-- Helper: `K(ι 0) = 0`. -/
lemma swKernel_latEmbed_zero : swKernel Ω (latEmbed (0 : Fin n → ℤ)) = 0 := by
  have : latEmbed (0 : Fin n → ℤ) = 0 := by ext i; simp
  simp [this, swKernel]

/-- Helper: `∑_{y} |K(y)|^r < ∞` for every real `r > 1`. -/
lemma summable_norm_swKernel_latEmbed_rpow (hΩ : IsSWProfile Ω) {r : ℝ} (hr : 1 < r) :
    Summable fun y : Fin n → ℤ => ‖swKernel Ω (latEmbed y)‖ ^ r := by
  obtain ⟨B, hB0, hB⟩ := exists_norm_swKernel_le_div (n := n) hΩ
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · exact Summable.of_finite
  have hs := (summable_norm_latEmbed_rpow (n := n) (r := -((n : ℝ) * r))
    (by nlinarith [(Nat.one_le_cast (α := ℝ)).2 hn])).mul_left (B ^ r)
  refine hs.of_nonneg_of_le (fun _ => Real.rpow_nonneg (norm_nonneg _) _) fun y => ?_
  by_cases hy : y = 0
  · subst hy
    rw [swKernel_latEmbed_zero, norm_zero, Real.zero_rpow (by linarith)]
    exact mul_nonneg (Real.rpow_nonneg hB0 _) (Real.rpow_nonneg (norm_nonneg _) _)
  have hy' : latEmbed y ≠ 0 := fun h => hy (latEmbed_injective (by rw [h]; ext i; simp))
  have hpos : 0 < ‖latEmbed y‖ := norm_pos_iff.2 hy'
  calc ‖swKernel Ω (latEmbed y)‖ ^ r ≤ (B / ‖latEmbed y‖ ^ n) ^ r :=
        Real.rpow_le_rpow (norm_nonneg _) (hB _ hy') (by linarith)
    _ = B ^ r * ‖latEmbed y‖ ^ (-((n : ℝ) * r)) := by
        rw [Real.div_rpow hB0 (by positivity), ← Real.rpow_natCast, ← Real.rpow_mul hpos.le,
          Real.rpow_neg hpos.le, div_eq_mul_inv]

/-- Helper: Hölder's inequality on `ℤⁿ` in the convolution form
`∑_y |k(y)| |f(x - y)| ≤ ‖k‖_{q} ‖f‖_{p}` (`1/p + 1/q = 1`). -/
lemma tsum_enorm_mul_enorm_sub_le {p q : ℝ} (hpq : p.HolderConjugate q)
    (k f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) :
    ∑' y, ‖k y‖ₑ * ‖f (x - y)‖ₑ ≤
      eLpNorm k (ENNReal.ofReal q) Measure.count * eLpNorm f (ENNReal.ofReal p) Measure.count := by
  have h := ENNReal.lintegral_mul_le_Lp_mul_Lq (Measure.count : Measure (Fin n → ℤ)) hpq.symm
    (f := fun y => ‖k y‖ₑ) (g := fun y => ‖f (x - y)‖ₑ) (measurable_of_countable _).aemeasurable
    (measurable_of_countable _).aemeasurable
  simp only [lintegral_count, Pi.mul_apply] at h
  have ht : ∑' y, ‖f (x - y)‖ₑ ^ p = ∑' y, ‖f y‖ₑ ^ p :=
    (Equiv.subLeft x).tsum_eq (fun y => ‖f y‖ₑ ^ p)
  rw [ht] at h
  refine h.trans (le_of_eq ?_)
  rw [← eLpNorm_enorm k AEStronglyMeasurable.of_discrete,
    ← eLpNorm_enorm f AEStronglyMeasurable.of_discrete, eLpNorm_count_ennreal_eq _ hpq.symm.pos,
    eLpNorm_count_ennreal_eq _ hpq.pos]


/-- The restricted lattice kernel `K 𝟙_{G ∖ {0}}`: `y ↦ K(ι y)` (it vanishes at `y = 0`). -/
noncomputable def swLatKernel (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (y : Fin n → ℤ) : ℂ :=
  swKernel Ω (latEmbed y)

/-- Helper: the restricted kernel lies in `ℓ^q(G)` for every real `q > 1`. -/
lemma memLp_swLatKernel (hΩ : IsSWProfile Ω) {q : ℝ} (hq : 1 < q) :
    MemLp (swLatKernel Ω) (ENNReal.ofReal q) Measure.count := by
  rw [memLp_iff, ← eLpNorm_enorm _ AEStronglyMeasurable.of_discrete,
    eLpNorm_count_ennreal_eq _ (by linarith)]
  have hs : Summable fun y => ‖swLatKernel Ω y‖ ^ q := summable_norm_swKernel_latEmbed_rpow hΩ hq
  have : ∑' y, ‖swLatKernel Ω y‖ₑ ^ q = ENNReal.ofReal (∑' y, ‖swLatKernel Ω y‖ ^ q) := by
    rw [ENNReal.ofReal_tsum_of_nonneg (fun _ => Real.rpow_nonneg (norm_nonneg _) _) hs]
    congr 1; funext y
    rw [← ofReal_norm, ENNReal.ofReal_rpow_of_nonneg (norm_nonneg _) (by linarith)]
  rw [this]
  exact ENNReal.rpow_lt_top_of_nonneg (by positivity) ENNReal.ofReal_ne_top

/-- Helper: the summand at `y = 0` vanishes. -/
lemma swTerm_zero_right (lam : ℝ) (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) :
    swTerm n d Ω lam f x 0 = 0 := by
  simp [swTerm, swKernel_latEmbed_zero]

/-- Helper: `|e(λP(y)) K(y) f(x-y)| = |K(y)| |f(x-y)|`. -/
lemma norm_swTerm (lam : ℝ) (f : (Fin n → ℤ) → ℂ) (x y : Fin n → ℤ) :
    ‖swTerm n d Ω lam f x y‖ = ‖swLatKernel Ω y‖ * ‖f (x - y)‖ := by
  simp [swTerm, swLatKernel, norm_eC]

/-- Helper: extended-norm form of `norm_swTerm`. -/
lemma enorm_swTerm (lam : ℝ) (f : (Fin n → ℤ) → ℂ) (x y : Fin n → ℤ) :
    ‖swTerm n d Ω lam f x y‖ₑ = ‖swLatKernel Ω y‖ₑ * ‖f (x - y)‖ₑ := by
  rw [← ofReal_norm, norm_swTerm, ENNReal.ofReal_mul (norm_nonneg _),
    ofReal_norm, ofReal_norm]

/-- Helper: `T_λ f(x)` as a sum over all of `G` (the term at `y = 0` vanishes). -/
lemma swOp_eq_tsum (lam : ℝ) (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) :
    swOp n d Ω lam f x = ∑' y, swTerm n d Ω lam f x y := by
  have hs : Function.support (swTerm n d Ω lam f x) ⊆ {y | y ≠ 0} := by
    intro y hy h
    exact hy (by rw [h]; exact swTerm_zero_right lam f x)
  exact tsum_subtype_eq_of_support_subset hs

/-- Helper (Hölder, Lemma 13.1): `|T_λ f(x)| ≤ ∑_y |K(y)| |f(x-y)| ≤ ‖K‖_{p'} ‖f‖_p`. -/
lemma enorm_swOp_le {p q : ℝ} (hpq : p.HolderConjugate q) (lam : ℝ) (f : (Fin n → ℤ) → ℂ)
    (x : Fin n → ℤ) :
    ‖swOp n d Ω lam f x‖ₑ ≤
      eLpNorm (swLatKernel Ω) (ENNReal.ofReal q) Measure.count *
        eLpNorm f (ENNReal.ofReal p) Measure.count := by
  rw [swOp_eq_tsum]
  refine enorm_tsum_le_tsum_enorm.trans ?_
  simp_rw [enorm_swTerm]
  exact tsum_enorm_mul_enorm_sub_le hpq _ f x

/-- Helper: absolute summability of `y ↦ e(λP(y)) K(y) f(x-y)` for `f ∈ ℓ^p`, `p > 1`. -/
lemma summable_norm_swTerm (hΩ : IsSWProfile Ω) {p : ℝ} (hp : 1 < p) {f : (Fin n → ℤ) → ℂ}
    (hf : MemLp f (ENNReal.ofReal p) Measure.count) (lam : ℝ) (x : Fin n → ℤ) :
    Summable fun y => ‖swTerm n d Ω lam f x y‖ := by
  have hpq := Real.HolderConjugate.conjExponent hp
  have hK := memLp_swLatKernel hΩ hpq.symm.lt
  have h := tsum_enorm_mul_enorm_sub_le hpq (swLatKernel Ω) f x
  have hfin : ∑' y, (‖swTerm n d Ω lam f x y‖₊ : ℝ≥0∞) ≠ ∞ := by
    refine ne_top_of_le_ne_top (ENNReal.mul_ne_top hK.eLpNorm_ne_top hf.eLpNorm_ne_top) ?_
    refine le_trans (le_of_eq ?_) h
    congr 1; funext y
    rw [← enorm_swTerm (d := d) lam f x y]
    rfl
  have := NNReal.summable_coe.2 (ENNReal.tsum_coe_ne_top_iff_summable.1 hfin)
  simpa using this


/-- Helper: each summand `e(λP(y)) K(y) f(x-y)` is `1`-periodic (indeed `ℤ`-periodic) in `λ`. -/
lemma swTerm_add_int (lam : ℝ) (k : ℤ) (f : (Fin n → ℤ) → ℂ) (x y : Fin n → ℤ) :
    swTerm n d Ω (lam + k) f x y = swTerm n d Ω lam f x y := by
  simp only [swTerm]
  rw [show (lam + k) * (radialPolyZ n d y : ℝ) =
      lam * radialPolyZ n d y + ((k * radialPolyZ n d y : ℤ) : ℝ) by push_cast; ring,
    eC_add, eC_intCast, mul_one]

/-- Helper: `T_{λ+k} f = T_λ f` for `k ∈ ℤ`. -/
lemma swOp_add_int (lam : ℝ) (k : ℤ) (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) :
    swOp n d Ω (lam + k) f x = swOp n d Ω lam f x := by
  simp only [swOp, swTerm_add_int]

/-- Helper: each summand is continuous in `λ`. -/
lemma continuous_swTerm (f : (Fin n → ℤ) → ℂ) (x y : Fin n → ℤ) :
    Continuous fun lam : ℝ => swTerm n d Ω lam f x y := by
  unfold swTerm eC
  fun_prop

/-- **Blueprint Lemma 13.1 (`lem:absolute`)**, absolute convergence and the scalar supremum:
for `1 < p < ∞` (with dual exponent `p' = p/(p-1)`):
* the restricted kernel `K 𝟙_{G ∖ {0}}` (`swLatKernel Ω`, `y ↦ K(y)` with `K(0) = 0`) belongs to
  `ℓ^{p'}(G)`;
* for `f ∈ ℓ^p(G)` and each `x ∈ G`, the series `T_λ f(x) = ∑_{y ≠ 0} e(λP(y)) K(y) f(x-y)` is
  absolutely convergent, and its finite partial sums converge uniformly in `λ ∈ ℝ`;
* `λ ↦ T_λ f(x)` is continuous and `1`-periodic; `|T_λ f(x)|` is bounded in `λ` and attains its
  maximum over `ℝ` at a point of `[0, 1]` (i.e. on `𝕋`); the supremum `𝒞 f(x) = sup_λ |T_λ f(x)|`
  equals the supremum over rational parameters;
* eq. (13.1) (`eq:pointwisecontinuity`): `sup_λ |T_λ (f - g)(x)| ≤ ‖K‖_{ℓ^{p'}(G ∖ 0)} ‖f - g‖_p`
  (stated for arbitrary `f, g`; it is trivial unless the right side is finite). -/
theorem absolute_convergence_and_parameter_continuity (hΩ : IsSWProfile Ω) {p : ℝ} (hp : 1 < p) :
    MemLp (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count ∧
    (∀ f : (Fin n → ℤ) → ℂ, MemLp f (ENNReal.ofReal p) Measure.count → ∀ x : Fin n → ℤ,
      (∀ lam : ℝ, Summable fun y : {y : Fin n → ℤ // y ≠ 0} => ‖swTerm n d Ω lam f x y‖) ∧
      TendstoUniformly (fun (s : Finset {y : Fin n → ℤ // y ≠ 0}) (lam : ℝ) =>
          ∑ y ∈ s, swTerm n d Ω lam f x y) (fun lam => swOp n d Ω lam f x) atTop ∧
      Continuous (fun lam => swOp n d Ω lam f x) ∧
      Function.Periodic (fun lam => swOp n d Ω lam f x) 1 ∧
      BddAbove (Set.range fun lam : ℝ => ‖swOp n d Ω lam f x‖) ∧
      (∃ lam₀ ∈ Set.Icc (0 : ℝ) 1, ∀ lam : ℝ, ‖swOp n d Ω lam f x‖ ≤ ‖swOp n d Ω lam₀ f x‖) ∧
      swMax n d Ω f x = ⨆ r : ℚ, ‖swOp n d Ω (r : ℝ) f x‖) ∧
    ∀ (f g : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ),
      ENNReal.ofReal (swMax n d Ω (f - g) x) ≤
        eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
          eLpNorm (f - g) (ENNReal.ofReal p) Measure.count := by
  have hpq := Real.HolderConjugate.conjExponent hp
  refine ⟨memLp_swLatKernel hΩ hpq.symm.lt, fun f hf x => ?_, fun f g x => ?_⟩
  · set T : ℝ → ℂ := fun lam => swOp n d Ω lam f x with hT
    have hsum : Summable fun y : Fin n → ℤ => ‖swLatKernel Ω y‖ * ‖f (x - y)‖ := by
      simpa only [norm_swTerm] using summable_norm_swTerm (d := d) hΩ hp hf 0 x
    have hu := hsum.subtype {y | y ≠ 0}
    have hbound : ∀ (y : {y : Fin n → ℤ // y ≠ 0}) (lam : ℝ),
        ‖swTerm n d Ω lam f x y‖ ≤ ‖swLatKernel Ω y‖ * ‖f (x - y)‖ :=
      fun y lam => le_of_eq (norm_swTerm lam f x y)
    have hcont : Continuous T :=
      continuous_tsum (fun y => continuous_swTerm f x y) hu hbound
    obtain ⟨lam₀, hlam₀, hmax⟩ := isCompact_Icc.exists_isMaxOn
      (Set.nonempty_Icc.2 (zero_le_one' ℝ)) hcont.norm.continuousOn
    have hmax' : ∀ lam, ‖T lam‖ ≤ ‖T lam₀‖ := by
      intro lam
      have e : T lam = T (Int.fract lam) := by
        rw [hT]
        dsimp only
        rw [← swOp_add_int (Int.fract lam) ⌊lam⌋, Int.fract_add_floor]
      rw [e]
      exact hmax ⟨Int.fract_nonneg lam, (Int.fract_lt_one lam).le⟩
    have hbdd : BddAbove (Set.range fun lam => ‖T lam‖) := ⟨‖T lam₀‖, by
      rintro _ ⟨lam, rfl⟩; exact hmax' lam⟩
    have hbddQ : BddAbove (Set.range fun r : ℚ => ‖T r‖) := ⟨‖T lam₀‖, by
      rintro _ ⟨r, rfl⟩; exact hmax' r⟩
    refine ⟨fun lam => (summable_norm_swTerm hΩ hp hf lam x).subtype _,
      tendstoUniformly_tsum hu hbound, hcont, fun lam => ?_, hbdd, ⟨lam₀, hlam₀, hmax'⟩, ?_⟩
    · simpa using swOp_add_int (d := d) (Ω := Ω) lam 1 f x
    · have h1 : swMax n d Ω f x = ‖T lam₀‖ :=
        le_antisymm (ciSup_le hmax') (le_ciSup hbdd lam₀)
      rw [h1]
      refine le_antisymm ?_ (ciSup_le fun r => hmax' r)
      exact Rat.denseRange_cast.induction_on (p := fun b => ‖T b‖ ≤ ⨆ r : ℚ, ‖T r‖) lam₀
        (isClosed_le hcont.norm continuous_const) (fun r => le_ciSup hbddQ r)
  · set c := eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
      eLpNorm (f - g) (ENNReal.ofReal p) Measure.count
    by_cases hc : c = ∞
    · rw [hc]; exact le_top
    rw [ENNReal.ofReal_le_iff_le_toReal hc]
    refine ciSup_le fun lam => ?_
    have := enorm_swOp_le (d := d) (Ω := Ω) hpq lam (f - g) x
    rw [← ofReal_norm] at this
    exact (ENNReal.ofReal_le_iff_le_toReal hc).1 this


/-! ### The initial kernel and the finite dyadic sums -/

/-- Helper: `K_m(x) = (η(2^{-m} x) - η(2^{1-m} x)) K(x)`. -/
lemma dyadicKernel_eq_sub (m : ℤ) (z : EuclideanSpace ℝ (Fin n)) :
    dyadicKernel Ω m z =
      ((dyadicEta ((2 : ℝ) ^ (-m) • z) - dyadicEta ((2 : ℝ) ^ (1 - m) • z) : ℝ) : ℂ) *
        swKernel Ω z := by
  rw [dyadicKernel, dyadicPsi, smul_smul,
    show (2 : ℝ) * 2 ^ (-m) = 2 ^ (1 - m) by
      rw [sub_eq_add_neg, zpow_add₀ two_ne_zero, zpow_one], mul_comm]

/-- Helper (telescoping, Lemma 4.1): `∑_{j=j₀}^{J} K_j(x) = (η(2^{-J} x) - η(2^{1-j₀} x)) K(x)`. -/
lemma sum_Icc_dyadicKernel (z : EuclideanSpace ℝ (Fin n)) {j₀ J : ℕ} (hJ : j₀ ≤ J) :
    ∑ j ∈ Finset.Icc j₀ J, dyadicKernel Ω (j : ℤ) z =
      ((dyadicEta ((2 : ℝ) ^ (-(J : ℤ)) • z) - dyadicEta ((2 : ℝ) ^ (1 - (j₀ : ℤ)) • z) : ℝ) : ℂ) *
        swKernel Ω z := by
  induction J, hJ using Nat.le_induction with
  | base => rw [Finset.Icc_self, Finset.sum_singleton, dyadicKernel_eq_sub]
  | succ J hJ ih =>
    rw [Finset.sum_Icc_succ_top (by omega), ih, dyadicKernel_eq_sub,
      show (1 : ℤ) - ((J + 1 : ℕ) : ℤ) = -(J : ℤ) by push_cast; ring]
    push_cast
    ring

/-- Helper: for `|x| ≤ 2^J` and `j₀ ≤ J`, `K(x) = η(2^{1-j₀} x) K(x) + ∑_{j=j₀}^{J} K_j(x)`. -/
lemma swKernel_eq_init_add_sum (z : EuclideanSpace ℝ (Fin n)) {j₀ J : ℕ} (hJ : j₀ ≤ J)
    (hz : ‖z‖ ≤ 2 ^ J) :
    swKernel Ω z = ((dyadicEta ((2 : ℝ) ^ (1 - (j₀ : ℤ)) • z) : ℝ) : ℂ) * swKernel Ω z +
      ∑ j ∈ Finset.Icc j₀ J, dyadicKernel Ω (j : ℤ) z := by
  have h1 : dyadicEta ((2 : ℝ) ^ (-(J : ℤ)) • z) = 1 := by
    apply dyadicEta_eq_one
    rw [norm_smul, Real.norm_eq_abs, abs_of_pos (by positivity), zpow_neg, zpow_natCast,
      inv_mul_le_iff₀ (by positivity), mul_one]
    exact hz
  rw [sum_Icc_dyadicKernel z hJ, h1]
  push_cast
  ring

/-- The initial kernel `k_init(y) = η(y)K(y) + ∑_{1 ≤ j < j₀} K_j(y) = η(2^{1-j₀} y) K(y)` of the
proof of Theorem 13.2 (the second form by telescoping; it also covers `j₀ = 0`). -/
noncomputable def swInitKernel (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (j₀ : ℕ) (y : Fin n → ℤ) : ℂ :=
  ((dyadicEta ((2 : ℝ) ^ (1 - (j₀ : ℤ)) • latEmbed y) : ℝ) : ℂ) * swKernel Ω (latEmbed y)

/-- Helper: `k_init` is supported in the finite box `|y|_∞ ≤ 2^{j₀}`. -/
lemma swInitKernel_eq_zero {j₀ : ℕ} {y : Fin n → ℤ} (hy : y ∉ latBox n (2 ^ j₀)) :
    swInitKernel Ω j₀ y = 0 := by
  simp only [latBox, Set.mem_ofPred_eq, not_forall, not_le] at hy
  obtain ⟨i, hi⟩ := hy
  have hi' : (2 : ℝ) ^ j₀ < ‖latEmbed y‖ := by
    calc (2 : ℝ) ^ j₀ < |(y i : ℝ)| := by exact_mod_cast hi
      _ = ‖latEmbed y i‖ := by simp
      _ ≤ ‖latEmbed y‖ := PiLp.norm_apply_le _ _
  rw [swInitKernel, dyadicEta_eq_zero, Complex.ofReal_zero, zero_mul]
  rw [norm_smul, Real.norm_eq_abs, abs_of_pos (by positivity)]
  have h2 : (2 : ℝ) ^ (1 - (j₀ : ℤ)) * (2 : ℝ) ^ j₀ = 2 := by
    rw [← zpow_natCast, ← zpow_add₀ two_ne_zero]; simp
  have hpos : (0 : ℝ) < 2 ^ (1 - (j₀ : ℤ)) := by positivity
  nlinarith


/-- Helper: `|e(t) a b| = |a| |b|`. -/
lemma enorm_eC_mul_mul (t : ℝ) (a b : ℂ) : ‖eC t * a * b‖ₑ = ‖a‖ₑ * ‖b‖ₑ := by
  have : ‖eC t‖ₑ = 1 := by rw [← ofReal_norm, norm_eC, ENNReal.ofReal_one]
  rw [enorm_mul, enorm_mul, this, one_mul]

/-- Helper: for finitely supported `f`, `x ∈ G`, `j₀ ≤ J` and `|x - z| ≤ 2^J` on the support of
`f`, `T_λ f(x) = ∑_y e(λP(y)) k_init(y) f(x-y) + ∑_{j=j₀}^{J} T_{j,λ} f(x)` for every `λ`. -/
lemma swOp_eq_init_add_minor {f : (Fin n → ℤ) → ℂ} (hf : (Function.support f).Finite)
    (x : Fin n → ℤ) {j₀ J : ℕ} (hJ : j₀ ≤ J)
    (hxJ : ∀ z ∈ hf.toFinset, ‖latEmbed (x - z)‖ ≤ 2 ^ J) (lam : ℝ) :
    swOp n d Ω lam f x =
      ∑ y ∈ (latBox_finite n (2 ^ j₀)).toFinset,
          eC (lam * (radialPolyZ n d y : ℝ)) * swInitKernel Ω j₀ y * f (x - y) +
        ∑ j ∈ Finset.Icc j₀ J, minorOp Ω d j lam f x := by
  set Fx := hf.toFinset.image (fun z => x - z) with hFx
  have hF : ∀ y ∉ Fx, f (x - y) = 0 := by
    intro y hy
    by_contra h
    exact hy (Finset.mem_image.2 ⟨x - y, hf.mem_toFinset.2 h, sub_sub_cancel x y⟩)
  rw [swOp_eq_tsum, tsum_eq_sum (s := Fx) (fun y hy => by simp [swTerm, hF y hy])]
  have hmin : ∀ j : ℕ, minorOp Ω d j lam f x = ∑ y ∈ Fx,
      eC (lam * (radialPolyZ n d y : ℝ)) * dyadicKernel Ω j (latEmbed y) * f (x - y) :=
    fun j => tsum_eq_sum (fun y hy => by simp [hF y hy])
  have hI : ∑ y ∈ (latBox_finite n (2 ^ j₀)).toFinset,
        eC (lam * (radialPolyZ n d y : ℝ)) * swInitKernel Ω j₀ y * f (x - y) =
      ∑ y ∈ Fx, eC (lam * (radialPolyZ n d y : ℝ)) * swInitKernel Ω j₀ y * f (x - y) := by
    set g : (Fin n → ℤ) → ℂ := fun y =>
      eC (lam * (radialPolyZ n d y : ℝ)) * swInitKernel Ω j₀ y * f (x - y) with hg
    have h1 : ∑' y, g y = ∑ y ∈ (latBox_finite n (2 ^ j₀)).toFinset, g y := by
      refine tsum_eq_sum (fun y hy => ?_)
      rw [hg]; dsimp only
      rw [swInitKernel_eq_zero (fun h => hy ((latBox_finite n (2 ^ j₀)).mem_toFinset.2 h)),
        mul_zero, zero_mul]
    have h2 : ∑' y, g y = ∑ y ∈ Fx, g y := tsum_eq_sum (fun y hy => by simp [hg, hF y hy])
    exact h1.symm.trans h2
  simp_rw [hmin]
  rw [hI, Finset.sum_comm, ← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun y _ => ?_
  by_cases hy : f (x - y) = 0
  · simp [swTerm, hy]
  have hy' : ‖latEmbed y‖ ≤ 2 ^ J := by
    have := hxJ (x - y) (hf.mem_toFinset.2 hy)
    rwa [sub_sub_cancel] at this
  have e := swKernel_eq_init_add_sum (Ω := Ω) (latEmbed y) hJ hy'
  simp only [swTerm, swInitKernel]
  rw [← Finset.sum_mul, ← Finset.mul_sum]
  conv_lhs => rw [e]
  ring

/-- Helper: `ℓ^p` bound for the initial part, `‖∑_y |k_init(y)| |f(· - y)|‖_p ≤ ‖k_init‖₁ ‖f‖_p`
(`k_init` has finite support). -/
lemma eLpNorm_init_le {p : ℝ} (hp : 1 < p) (S : Finset (Fin n → ℤ)) (k f : (Fin n → ℤ) → ℂ) :
    eLpNorm (fun x => ∑ y ∈ S, ‖k y‖ₑ * ‖f (x - y)‖ₑ) (ENNReal.ofReal p) Measure.count ≤
      ENNReal.ofReal (∑ y ∈ S, ‖k y‖) * eLpNorm f (ENNReal.ofReal p) Measure.count := by
  have hp1 : (1 : ℝ≥0∞) ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hp.le
  have htr : ∀ y, eLpNorm (fun x => ‖f (x - y)‖ₑ) (ENNReal.ofReal p) Measure.count =
      eLpNorm f (ENNReal.ofReal p) Measure.count := by
    intro y
    rw [← eLpNorm_enorm f AEStronglyMeasurable.of_discrete,
      eLpNorm_count_ennreal_eq _ (by linarith),
      eLpNorm_count_ennreal_eq _ (by linarith)]
    congr 1
    exact (Equiv.subRight y).tsum_eq (fun z => ‖‖f z‖ₑ‖ₑ ^ p)
  have e : (fun x => ∑ y ∈ S, ‖k y‖ₑ * ‖f (x - y)‖ₑ) =
      ∑ y ∈ S, fun x => ‖k y‖ₑ * ‖f (x - y)‖ₑ := by
    funext x; simp [Finset.sum_apply]
  rw [e]
  refine (eLpNorm_sum_le hp1).trans (le_of_eq ?_)
  simp_rw [eLpNorm_count_const_mul _ _ (by linarith : (0 : ℝ) < p), htr]
  rw [← Finset.sum_mul, ENNReal.ofReal_sum_of_nonneg (fun _ _ => norm_nonneg _)]
  simp_rw [ofReal_norm]

/-- Helper (Fatou for eventual pointwise majorants on `G`): if `M ≤ F_J` pointwise for all large
`J` (depending on the point) and eventually `‖F_J‖_p ≤ B`, then `‖M‖_p ≤ B`. -/
lemma eLpNorm_le_of_eventually_le {p : ℝ} (hp : 0 < p) (M : (Fin n → ℤ) → ℝ≥0∞)
    (F : ℕ → (Fin n → ℤ) → ℝ≥0∞) (B : ℝ≥0∞)
    (hF : ∀ᶠ J in atTop, eLpNorm (F J) (ENNReal.ofReal p) Measure.count ≤ B)
    (hM : ∀ x, ∀ᶠ J in atTop, M x ≤ F J x) :
    eLpNorm M (ENNReal.ofReal p) Measure.count ≤ B := by
  apply eLpNorm_count_le_of_tsum_rpow_le hp
  rw [ENNReal.tsum_eq_iSup_sum]
  refine iSup_le fun S => ?_
  obtain ⟨J, hJB, hJ⟩ := (hF.and ((Filter.eventually_all_finset S).2 fun x _ => hM x)).exists
  calc ∑ x ∈ S, M x ^ p ≤ ∑ x ∈ S, F J x ^ p :=
        Finset.sum_le_sum fun x hx => ENNReal.rpow_le_rpow (hJ x hx) hp.le
    _ ≤ ∑' x, F J x ^ p := ENNReal.sum_le_tsum S
    _ ≤ B ^ p := tsum_rpow_le_of_eLpNorm_count_le hp hJB


/-- Helper: `0 ≤ 𝒞 f(x)`. -/
lemma swMax_nonneg (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) : 0 ≤ swMax n d Ω f x :=
  Real.iSup_nonneg fun _ => norm_nonneg _

/-- The finite-support case of Theorem 13.2 (`thm:main`): for `n, d ≥ 1`, admissible `Ω` and
`1 < p < ∞` there is `C ≥ 0` with `‖𝒞 f‖_p ≤ C ‖f‖_p` for every finitely supported `f`. -/
theorem eLpNorm_swMax_le_of_finite_support (hn : 1 ≤ n) (hd : 1 ≤ d) (hΩ : IsSWProfile Ω)
    {p : ℝ} (hp : 1 < p) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ f : (Fin n → ℤ) → ℂ, (Function.support f).Finite →
      eLpNorm (swMax n d Ω f) (ENNReal.ofReal p) Measure.count ≤
        ENNReal.ofReal C * eLpNorm f (ENNReal.ofReal p) Measure.count := by
  obtain ⟨C₁, hC₁, hfin⟩ := finite_dyadic_stein_wainger hn hd hΩ hp
  set j₀ := coherJ0 n d Ω p with hj₀
  set S := (latBox_finite n (2 ^ j₀)).toFinset with hS
  set A := ∑ y ∈ S, ‖swInitKernel Ω j₀ y‖ with hA
  have hA0 : 0 ≤ A := Finset.sum_nonneg fun _ _ => norm_nonneg _
  have hp1 : (1 : ℝ≥0∞) ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hp.le
  refine ⟨A + C₁, by positivity, fun f hf => ?_⟩
  set F : ℕ → (Fin n → ℤ) → ℝ≥0∞ := fun J =>
    (fun x => ∑ y ∈ S, ‖swInitKernel Ω j₀ y‖ₑ * ‖f (x - y)‖ₑ) +
      (fun x => ⨆ lam : ℝ, ‖∑ j ∈ Finset.Icc j₀ J, minorOp Ω d j lam f x‖ₑ) with hFdef
  rw [← eLpNorm_enorm (swMax n d Ω f) AEStronglyMeasurable.of_discrete]
  apply eLpNorm_le_of_eventually_le (by linarith) _ F
  · filter_upwards [eventually_ge_atTop j₀] with J hJ
    refine (eLpNorm_add_le hp1).trans ?_
    calc _ ≤ ENNReal.ofReal A * eLpNorm f (ENNReal.ofReal p) Measure.count +
          ENNReal.ofReal C₁ * eLpNorm f (ENNReal.ofReal p) Measure.count :=
          add_le_add (eLpNorm_init_le hp S _ f) (hfin J hJ f hf)
      _ = _ := by rw [ENNReal.ofReal_add hA0 hC₁, add_mul]
  · intro x
    have hev : ∀ᶠ J in atTop, j₀ ≤ J ∧ ∀ z ∈ hf.toFinset, ‖latEmbed (x - z)‖ ≤ 2 ^ J :=
      (eventually_ge_atTop j₀).and ((Filter.eventually_all_finset _).2 fun z _ =>
        (tendsto_pow_atTop_atTop_of_one_lt one_lt_two).eventually_ge_atTop _)
    filter_upwards [hev] with J hJx
    obtain ⟨hJ, hxJ⟩ := hJx
    by_cases htop : F J x = ∞
    · rw [htop]; exact le_top
    rw [Real.enorm_eq_ofReal (swMax_nonneg f x), ENNReal.ofReal_le_iff_le_toReal htop]
    refine ciSup_le fun lam => ?_
    rw [← ENNReal.ofReal_le_iff_le_toReal htop, ofReal_norm,
      swOp_eq_init_add_minor hf x hJ hxJ lam]
    refine (enorm_add_le _ _).trans (add_le_add ?_
      (le_iSup (fun lam => ‖∑ j ∈ Finset.Icc j₀ J, minorOp Ω d j lam f x‖ₑ) lam))
    exact (enorm_sum_le _ _).trans (Finset.sum_le_sum fun y _ => le_of_eq (enorm_eC_mul_mul _ _ _))


/-- Helper: `𝒞 g(x) ≤ 𝒞 f(x) + ‖K‖_{p'} ‖g - f‖_p` for `f, g ∈ ℓ^p` (from (13.1) and linearity). -/
lemma swMax_le_swMax_add (hΩ : IsSWProfile Ω) {p : ℝ} (hp : 1 < p) {f g : (Fin n → ℤ) → ℂ}
    (hf : MemLp f (ENNReal.ofReal p) Measure.count) (hg : MemLp g (ENNReal.ofReal p) Measure.count)
    (x : Fin n → ℤ) :
    swMax n d Ω g x ≤ swMax n d Ω f x +
      (eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
        eLpNorm (g - f) (ENNReal.ofReal p) Measure.count).toReal := by
  have hpq := Real.HolderConjugate.conjExponent hp
  have hK := memLp_swLatKernel hΩ hpq.symm.lt
  have hgf := hg.sub hf
  have hc : eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
      eLpNorm (g - f) (ENNReal.ofReal p) Measure.count ≠ ∞ :=
    ENNReal.mul_ne_top hK.eLpNorm_ne_top hgf.eLpNorm_ne_top
  have hbdd := ((absolute_convergence_and_parameter_continuity (d := d) hΩ hp).2.1 f hf x).2.2.2.2.1
  refine ciSup_le fun lam => ?_
  have hlin : swOp n d Ω lam g x = swOp n d Ω lam f x + swOp n d Ω lam (g - f) x := by
    rw [swOp_eq_tsum, swOp_eq_tsum, swOp_eq_tsum,
      ← (summable_norm_swTerm hΩ hp hf lam x).of_norm.tsum_add
        (summable_norm_swTerm hΩ hp hgf lam x).of_norm]
    congr 1; funext y
    simp only [swTerm, Pi.sub_apply]
    ring
  have h2 : ‖swOp n d Ω lam (g - f) x‖ ≤
      (eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
        eLpNorm (g - f) (ENNReal.ofReal p) Measure.count).toReal := by
    rw [← ENNReal.ofReal_le_iff_le_toReal hc, ofReal_norm]
    exact enorm_swOp_le hpq lam (g - f) x
  rw [hlin]
  exact (norm_add_le _ _).trans (add_le_add (le_ciSup hbdd lam) h2)

/-- Helper: `|𝒞 g(x) - 𝒞 f(x)| ≤ ‖K‖_{p'} ‖g - f‖_p` for `f, g ∈ ℓ^p`. -/
lemma abs_swMax_sub_le (hΩ : IsSWProfile Ω) {p : ℝ} (hp : 1 < p) {f g : (Fin n → ℤ) → ℂ}
    (hf : MemLp f (ENNReal.ofReal p) Measure.count) (hg : MemLp g (ENNReal.ofReal p) Measure.count)
    (x : Fin n → ℤ) :
    |swMax n d Ω g x - swMax n d Ω f x| ≤
      (eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
        eLpNorm (g - f) (ENNReal.ofReal p) Measure.count).toReal := by
  have h1 := swMax_le_swMax_add (d := d) hΩ hp hf hg x
  have h2 := swMax_le_swMax_add (d := d) hΩ hp hg hf x
  rw [eLpNorm_sub_comm f g] at h2
  rw [abs_sub_le_iff]
  constructor <;> linarith

/-- **Blueprint Theorem 13.2 (`thm:main`)**, the combined discrete Stein–Wainger bound, eq. (13.2)
(`eq:MAIN`): let `n, d ≥ 1`, let `Ω` be smooth on `E ∖ {0}`, homogeneous of degree zero, with
integral zero on `S^{n-1}` (`IsSWProfile Ω`), `K(y) = Ω(y)|y|^{-n}` for `y ≠ 0` and
`P(y) = (y₁² + ⋯ + yₙ²)^d`. For every real `1 < p < ∞` there is a finite constant
`C = C_{p,n,d,Ω} ≥ 0` such that for all `f ∈ ℓ^p(ℤⁿ)`:
the series `T_λ f(x) = ∑_{y ∈ ℤⁿ ∖ {0}} e(λP(y)) K(y) f(x-y)` converges (absolutely, Lemma 13.1)
for all `λ ∈ ℝ` and `x`, the family `λ ↦ |T_λ f(x)|` is bounded (so the scalar supremum
`𝒞 f(x) = sup_{λ ∈ ℝ} |T_λ f(x)|` is a genuine supremum), `𝒞 f ∈ ℓ^p`, and
`‖sup_{λ ∈ ℝ} |T_λ f|‖_{ℓ^p} ≤ C ‖f‖_{ℓ^p}`. -/
theorem discrete_stein_wainger_lp {n d : ℕ} (hn : 1 ≤ n) (hd : 1 ≤ d)
    {Ω : EuclideanSpace ℝ (Fin n) → ℂ} (hΩ : IsSWProfile Ω) {p : ℝ} (hp : 1 < p) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ f : (Fin n → ℤ) → ℂ, MemLp f (ENNReal.ofReal p) Measure.count →
      (∀ (lam : ℝ) (x : Fin n → ℤ), Summable fun y : {y : Fin n → ℤ // y ≠ 0} =>
        swTerm n d Ω lam f x y) ∧
      (∀ x, BddAbove (Set.range fun lam : ℝ => ‖swOp n d Ω lam f x‖)) ∧
      MemLp (swMax n d Ω f) (ENNReal.ofReal p) Measure.count ∧
      eLpNorm (swMax n d Ω f) (ENNReal.ofReal p) Measure.count ≤
        ENNReal.ofReal C * eLpNorm f (ENNReal.ofReal p) Measure.count := by
  obtain ⟨C, hC, hfin⟩ := eLpNorm_swMax_le_of_finite_support hn hd hΩ hp
  refine ⟨C, hC, fun f hf => ?_⟩
  have hpq := Real.HolderConjugate.conjExponent hp
  have hK := memLp_swLatKernel hΩ hpq.symm.lt
  have hbound : eLpNorm (swMax n d Ω f) (ENNReal.ofReal p) Measure.count ≤
      ENNReal.ofReal C * eLpNorm f (ENNReal.ofReal p) Measure.count := by
    have hfR : ∀ R : ℕ, MemLp ((latBox n R).indicator f) (ENNReal.ofReal p) Measure.count :=
      fun R => finSW_memLp (support_indicator_latBox_finite n R f) _
    refine eLpNorm_le_of_tendsto_of_eLpNorm_le
      (u := fun R : ℕ => swMax n d Ω ((latBox n R).indicator f))
      (fun R => AEStronglyMeasurable.of_discrete) (ae_of_all _ fun x => ?_) (fun R => ?_)
    · have ht := eLpNorm_sub_indicator_latBox_tendsto ENNReal.ofReal_ne_top hf
      have hc : Tendsto (fun R : ℕ =>
          (eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
            eLpNorm ((latBox n R).indicator f - f) (ENNReal.ofReal p) Measure.count).toReal)
          atTop (𝓝 0) := by
        simp_rw [eLpNorm_sub_comm _ f]
        have h1 := ENNReal.Tendsto.const_mul ht (Or.inr hK.eLpNorm_ne_top)
        rw [mul_zero] at h1
        have h2 := (ENNReal.tendsto_toReal ENNReal.zero_ne_top).comp h1
        exact h2
      rw [tendsto_iff_norm_sub_tendsto_zero]
      exact squeeze_zero (fun _ => norm_nonneg _)
        (fun R => abs_swMax_sub_le (d := d) hΩ hp hf (hfR R) x) hc
    · refine (hfin _ (support_indicator_latBox_finite n R f)).trans ?_
      gcongr
      exact eLpNorm_indicator_le f (latBox_finite n R).measurableSet
  refine ⟨fun lam x => (summable_norm_swTerm hΩ hp hf lam x).of_norm.subtype _,
    fun x => ((absolute_convergence_and_parameter_continuity (d := d) hΩ hp).2.1 f hf x).2.2.2.2.1,
    memLp_iff.2 (lt_of_le_of_lt hbound
      (ENNReal.mul_lt_top ENNReal.ofReal_lt_top hf.eLpNorm_lt_top)),
    hbound⟩

end DiscreteSteinWainger

end Auto
