/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license.
This file was automatically generated by Claude.
-/
import DiscreteSW.Auto.MajorArcs

/-!
# The discrete Stein–Wainger maximal operator

Formalization of the blueprint `blueprints/discrete-sw.tex`
("The discrete Stein–Wainger maximal operator: the combined `ℓ^p` bound, `1 < p < ∞`").

Results from §13 ("The operator on all of `ℓ^p` and the final theorem").

## Main results

* `absolute_convergence_and_parameter_continuity`: Blueprint Lemma 13.1 (`lem:absolute`), with
  eq. (13.1) (`eq:pointwisecontinuity`);
* `eLpNorm_swMax_le_of_finite_support`: the finite-support case of Theorem 13.2;
* `discrete_stein_wainger_lp`: Blueprint Theorem 13.2 (`thm:main`), eq. (13.2) (`eq:MAIN`).

## Proof outline

* The restricted kernel `swLatKernel Ω` (`y ↦ K(y)`, `K(0) = 0`) is in `ℓ^{p'}` since
  `|K(y)| ≤ B |y|^{-n}` (`exists_norm_swKernel_le_div`) and `∑_{y} |y|^{-r} < ∞` for `r > n`
  (`summable_norm_latEmbed_rpow`, from Mathlib's `ZLattice.summable_norm_rpow`); Hölder
  (`tsum_enorm_mul_enorm_sub_le`) gives absolute convergence and (13.1).
* Finite support: by telescoping (`sum_Icc_dyadicKernel`), at `|y| ≤ 2^J` one has
  `K(y) = k_init(y) + ∑_{j=j₀}^{J} K_j(y)` with `k_init(y) = η(2^{1-j₀} y) K(y)`
  (`swInitKernel`, which equals `η K + ∑_{1 ≤ j < j₀} K_j` and has finite support); so
  `T_λ f(x) = ∑_y e(λP(y)) k_init(y) f(x-y) + ∑_{j=j₀}^{J} T_{j,λ} f(x)` for all `λ` once `J` is
  large (`swOp_eq_init_add_minor`). The first part is bounded by `|k_init| * |f|`
  (`eLpNorm_init_le`), the second by Proposition 12.3 (`finite_dyadic_stein_wainger`), and a
  Fatou-type argument over finite sets of points (`eLpNorm_le_of_eventually_le`) concludes.
* General `f ∈ ℓ^p`: truncations to lattice boxes, pointwise convergence of the maximal
  functions from (13.1) (`abs_swMax_sub_le`) and Fatou (`eLpNorm_le_of_tendsto_of_eLpNorm_le`).
-/

namespace Auto

open MeasureTheory Filter Topology Set
open scoped ENNReal NNReal

variable {n d : ℕ} {Ω : EuclideanSpace ℝ (Fin n) → ℂ}

/-- Helper: the decay bound `|K(x)| ≤ B |x|^{-n}` for `x ≠ 0`. -/
lemma exists_norm_swKernel_le_div (hΩ : IsSWProfile Ω) :
    ∃ B : ℝ, 0 ≤ B ∧ ∀ x : EuclideanSpace ℝ (Fin n), x ≠ 0 → ‖swKernel Ω x‖ ≤ B / ‖x‖ ^ n := by
  obtain ⟨C, hC⟩ := (isCompact_sphere (0 : EuclideanSpace ℝ (Fin n)) 1).exists_bound_of_continuousOn
    (hΩ.1.continuousOn.mono fun y hy => by
      simp only [mem_sphere_zero_iff_norm] at hy
      simp only [mem_compl_iff, mem_singleton_iff]
      rintro rfl; simp at hy)
  refine ⟨max C 0, le_max_right _ _, fun x hx => ?_⟩
  have hpos : 0 < ‖x‖ := norm_pos_iff.2 hx
  have hmem : ‖x‖⁻¹ • x ∈ Metric.sphere (0 : EuclideanSpace ℝ (Fin n)) 1 := by
    simp [norm_smul, hpos.ne']
  have hΩx : Ω x = Ω (‖x‖⁻¹ • x) := (hΩ.2.1 x hx _ (inv_pos.2 hpos)).symm
  simp only [swKernel, hx, ↓reduceIte]
  rw [norm_div, hΩx]
  simp only [Complex.norm_real, Real.norm_eq_abs, abs_of_pos (pow_pos hpos n)]
  gcongr
  exact (hC _ hmem).trans (le_max_left _ _)

/-- Helper: the integer lattice as a `ℤ`-lattice in `E`. -/
noncomputable abbrev latL (n : ℕ) : Submodule ℤ (EuclideanSpace ℝ (Fin n)) :=
  Submodule.span ℤ (Set.range (EuclideanSpace.basisFun (Fin n) ℝ).toBasis)

/-- Helper: `ι y` lies in the lattice `latL n`. -/
lemma latEmbed_mem_latL (y : Fin n → ℤ) : latEmbed y ∈ latL n := by
  have : latEmbed y = ∑ i, (y i) • (EuclideanSpace.basisFun (Fin n) ℝ).toBasis i := by
    ext j
    simp [Finset.sum_apply, Pi.single_apply]
  rw [this]
  exact Submodule.sum_mem _ fun i _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)


/-- Helper: `∑_{y ∈ ℤⁿ} |y|^r < ∞` for `r < -n` (the term at `0` is `0^r = 0`). -/
lemma summable_norm_latEmbed_rpow {r : ℝ} (hr : r < -n) :
    Summable fun y : Fin n → ℤ => ‖latEmbed y‖ ^ r := by
  have hrank : Module.finrank ℤ (latL n) = n := by
    rw [ZLattice.rank ℝ (latL n)]
    exact finrank_euclideanSpace_fin
  have hs : Summable fun z : latL n => ‖z‖ ^ r :=
    ZLattice.summable_norm_rpow (latL n) r (by rw [hrank]; exact hr)
  have hinj : Function.Injective (fun y : Fin n → ℤ => (⟨latEmbed y, latEmbed_mem_latL y⟩ : latL n)) :=
    fun y z h => latEmbed_injective (congrArg Subtype.val h)
  have h2 : Summable ((fun z : latL n => ‖z‖ ^ r) ∘ fun y : Fin n → ℤ =>
      (⟨latEmbed y, latEmbed_mem_latL y⟩ : latL n)) := Summable.comp_injective hs hinj
  exact h2


/-- Helper: `K(ι 0) = 0`. -/
lemma swKernel_latEmbed_zero : swKernel Ω (latEmbed (0 : Fin n → ℤ)) = 0 := by
  have : latEmbed (0 : Fin n → ℤ) = 0 := by ext i; simp
  simp [this, swKernel]

/-- Helper: `∑_{y} |K(y)|^r < ∞` for every real `r > 1`. -/
lemma summable_norm_swKernel_latEmbed_rpow (hΩ : IsSWProfile Ω) {r : ℝ} (hr : 1 < r) :
    Summable fun y : Fin n → ℤ => ‖swKernel Ω (latEmbed y)‖ ^ r := by
  obtain ⟨B, hB0, hB⟩ := exists_norm_swKernel_le_div (n := n) hΩ
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · exact Summable.of_finite
  have hs := (summable_norm_latEmbed_rpow (n := n) (r := -((n : ℝ) * r))
    (by nlinarith [(Nat.one_le_cast (α := ℝ)).2 hn])).mul_left (B ^ r)
  refine hs.of_nonneg_of_le (fun _ => Real.rpow_nonneg (norm_nonneg _) _) fun y => ?_
  by_cases hy : y = 0
  · subst hy
    rw [swKernel_latEmbed_zero, norm_zero, Real.zero_rpow (by linarith)]
    exact mul_nonneg (Real.rpow_nonneg hB0 _) (Real.rpow_nonneg (norm_nonneg _) _)
  have hy' : latEmbed y ≠ 0 := fun h => hy (latEmbed_injective (by rw [h]; ext i; simp))
  have hpos : 0 < ‖latEmbed y‖ := norm_pos_iff.2 hy'
  calc ‖swKernel Ω (latEmbed y)‖ ^ r ≤ (B / ‖latEmbed y‖ ^ n) ^ r :=
        Real.rpow_le_rpow (norm_nonneg _) (hB _ hy') (by linarith)
    _ = B ^ r * ‖latEmbed y‖ ^ (-((n : ℝ) * r)) := by
        rw [Real.div_rpow hB0 (by positivity), ← Real.rpow_natCast, ← Real.rpow_mul hpos.le,
          Real.rpow_neg hpos.le, div_eq_mul_inv]

/-- Helper: Hölder's inequality on `ℤⁿ` in the convolution form
`∑_y |k(y)| |f(x - y)| ≤ ‖k‖_{q} ‖f‖_{p}` (`1/p + 1/q = 1`). -/
lemma tsum_enorm_mul_enorm_sub_le {p q : ℝ} (hpq : p.HolderConjugate q)
    (k f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) :
    ∑' y, ‖k y‖ₑ * ‖f (x - y)‖ₑ ≤
      eLpNorm k (ENNReal.ofReal q) Measure.count * eLpNorm f (ENNReal.ofReal p) Measure.count := by
  have h := ENNReal.lintegral_mul_le_Lp_mul_Lq (Measure.count : Measure (Fin n → ℤ)) hpq.symm
    (f := fun y => ‖k y‖ₑ) (g := fun y => ‖f (x - y)‖ₑ) (measurable_of_countable _).aemeasurable
    (measurable_of_countable _).aemeasurable
  simp only [lintegral_count, Pi.mul_apply] at h
  have ht : ∑' y, ‖f (x - y)‖ₑ ^ p = ∑' y, ‖f y‖ₑ ^ p :=
    (Equiv.subLeft x).tsum_eq (fun y => ‖f y‖ₑ ^ p)
  rw [ht] at h
  refine h.trans (le_of_eq ?_)
  rw [← eLpNorm_enorm k AEStronglyMeasurable.of_discrete, ← eLpNorm_enorm f AEStronglyMeasurable.of_discrete, eLpNorm_count_ennreal_eq _ hpq.symm.pos,
    eLpNorm_count_ennreal_eq _ hpq.pos]


/-- The restricted lattice kernel `K 𝟙_{G ∖ {0}}`: `y ↦ K(ι y)` (it vanishes at `y = 0`). -/
noncomputable def swLatKernel (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (y : Fin n → ℤ) : ℂ :=
  swKernel Ω (latEmbed y)

/-- Helper: the restricted kernel lies in `ℓ^q(G)` for every real `q > 1`. -/
lemma memLp_swLatKernel (hΩ : IsSWProfile Ω) {q : ℝ} (hq : 1 < q) :
    MemLp (swLatKernel Ω) (ENNReal.ofReal q) Measure.count := by
  rw [memLp_iff, ← eLpNorm_enorm _ AEStronglyMeasurable.of_discrete, eLpNorm_count_ennreal_eq _ (by linarith)]
  have hs : Summable fun y => ‖swLatKernel Ω y‖ ^ q := summable_norm_swKernel_latEmbed_rpow hΩ hq
  have : ∑' y, ‖swLatKernel Ω y‖ₑ ^ q = ENNReal.ofReal (∑' y, ‖swLatKernel Ω y‖ ^ q) := by
    rw [ENNReal.ofReal_tsum_of_nonneg (fun _ => Real.rpow_nonneg (norm_nonneg _) _) hs]
    congr 1; funext y
    rw [← ofReal_norm, ENNReal.ofReal_rpow_of_nonneg (norm_nonneg _) (by linarith)]
  rw [this]
  exact ENNReal.rpow_lt_top_of_nonneg (by positivity) ENNReal.ofReal_ne_top

/-- Helper: the summand at `y = 0` vanishes. -/
lemma swTerm_zero_right (lam : ℝ) (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) :
    swTerm n d Ω lam f x 0 = 0 := by
  simp [swTerm, swKernel_latEmbed_zero]

/-- Helper: `|e(λP(y)) K(y) f(x-y)| = |K(y)| |f(x-y)|`. -/
lemma norm_swTerm (lam : ℝ) (f : (Fin n → ℤ) → ℂ) (x y : Fin n → ℤ) :
    ‖swTerm n d Ω lam f x y‖ = ‖swLatKernel Ω y‖ * ‖f (x - y)‖ := by
  simp [swTerm, swLatKernel, norm_eC]

/-- Helper: extended-norm form of `norm_swTerm`. -/
lemma enorm_swTerm (lam : ℝ) (f : (Fin n → ℤ) → ℂ) (x y : Fin n → ℤ) :
    ‖swTerm n d Ω lam f x y‖ₑ = ‖swLatKernel Ω y‖ₑ * ‖f (x - y)‖ₑ := by
  rw [← ofReal_norm, norm_swTerm, ENNReal.ofReal_mul (norm_nonneg _),
    ofReal_norm, ofReal_norm]

/-- Helper: `T_λ f(x)` as a sum over all of `G` (the term at `y = 0` vanishes). -/
lemma swOp_eq_tsum (lam : ℝ) (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) :
    swOp n d Ω lam f x = ∑' y, swTerm n d Ω lam f x y := by
  have hs : Function.support (swTerm n d Ω lam f x) ⊆ {y | y ≠ 0} := by
    intro y hy h
    exact hy (by rw [h]; exact swTerm_zero_right lam f x)
  exact tsum_subtype_eq_of_support_subset hs

/-- Helper (Hölder, Lemma 13.1): `|T_λ f(x)| ≤ ∑_y |K(y)| |f(x-y)| ≤ ‖K‖_{p'} ‖f‖_p`. -/
lemma enorm_swOp_le {p q : ℝ} (hpq : p.HolderConjugate q) (lam : ℝ) (f : (Fin n → ℤ) → ℂ)
    (x : Fin n → ℤ) :
    ‖swOp n d Ω lam f x‖ₑ ≤
      eLpNorm (swLatKernel Ω) (ENNReal.ofReal q) Measure.count *
        eLpNorm f (ENNReal.ofReal p) Measure.count := by
  rw [swOp_eq_tsum]
  refine enorm_tsum_le_tsum_enorm.trans ?_
  simp_rw [enorm_swTerm]
  exact tsum_enorm_mul_enorm_sub_le hpq _ f x

/-- Helper: absolute summability of `y ↦ e(λP(y)) K(y) f(x-y)` for `f ∈ ℓ^p`, `p > 1`. -/
lemma summable_norm_swTerm (hΩ : IsSWProfile Ω) {p : ℝ} (hp : 1 < p) {f : (Fin n → ℤ) → ℂ}
    (hf : MemLp f (ENNReal.ofReal p) Measure.count) (lam : ℝ) (x : Fin n → ℤ) :
    Summable fun y => ‖swTerm n d Ω lam f x y‖ := by
  have hpq := Real.HolderConjugate.conjExponent hp
  have hK := memLp_swLatKernel hΩ hpq.symm.lt
  have h := tsum_enorm_mul_enorm_sub_le hpq (swLatKernel Ω) f x
  have hfin : ∑' y, (‖swTerm n d Ω lam f x y‖₊ : ℝ≥0∞) ≠ ∞ := by
    refine ne_top_of_le_ne_top (ENNReal.mul_ne_top hK.eLpNorm_ne_top hf.eLpNorm_ne_top) ?_
    refine le_trans (le_of_eq ?_) h
    congr 1; funext y
    rw [← enorm_swTerm (d := d) lam f x y]
    rfl
  have := NNReal.summable_coe.2 (ENNReal.tsum_coe_ne_top_iff_summable.1 hfin)
  simpa using this


/-- Helper: each summand `e(λP(y)) K(y) f(x-y)` is `1`-periodic (indeed `ℤ`-periodic) in `λ`. -/
lemma swTerm_add_int (lam : ℝ) (k : ℤ) (f : (Fin n → ℤ) → ℂ) (x y : Fin n → ℤ) :
    swTerm n d Ω (lam + k) f x y = swTerm n d Ω lam f x y := by
  simp only [swTerm]
  rw [show (lam + k) * (radialPolyZ n d y : ℝ) =
      lam * radialPolyZ n d y + ((k * radialPolyZ n d y : ℤ) : ℝ) by push_cast; ring,
    eC_add, eC_intCast, mul_one]

/-- Helper: `T_{λ+k} f = T_λ f` for `k ∈ ℤ`. -/
lemma swOp_add_int (lam : ℝ) (k : ℤ) (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) :
    swOp n d Ω (lam + k) f x = swOp n d Ω lam f x := by
  simp only [swOp, swTerm_add_int]

/-- Helper: each summand is continuous in `λ`. -/
lemma continuous_swTerm (f : (Fin n → ℤ) → ℂ) (x y : Fin n → ℤ) :
    Continuous fun lam : ℝ => swTerm n d Ω lam f x y := by
  unfold swTerm eC
  fun_prop

/-- **Blueprint Lemma 13.1 (`lem:absolute`)**, absolute convergence and the scalar supremum:
for `1 < p < ∞` (with dual exponent `p' = p/(p-1)`):
* the restricted kernel `K 𝟙_{G ∖ {0}}` (`swLatKernel Ω`, `y ↦ K(y)` with `K(0) = 0`) belongs to
  `ℓ^{p'}(G)`;
* for `f ∈ ℓ^p(G)` and each `x ∈ G`, the series `T_λ f(x) = ∑_{y ≠ 0} e(λP(y)) K(y) f(x-y)` is
  absolutely convergent, and its finite partial sums converge uniformly in `λ ∈ ℝ`;
* `λ ↦ T_λ f(x)` is continuous and `1`-periodic; `|T_λ f(x)|` is bounded in `λ` and attains its
  maximum over `ℝ` at a point of `[0, 1]` (i.e. on `𝕋`); the supremum `𝒞 f(x) = sup_λ |T_λ f(x)|`
  equals the supremum over rational parameters;
* eq. (13.1) (`eq:pointwisecontinuity`): `sup_λ |T_λ (f - g)(x)| ≤ ‖K‖_{ℓ^{p'}(G ∖ 0)} ‖f - g‖_p`
  (stated for arbitrary `f, g`; it is trivial unless the right side is finite). -/
theorem absolute_convergence_and_parameter_continuity (hΩ : IsSWProfile Ω) {p : ℝ} (hp : 1 < p) :
    MemLp (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count ∧
    (∀ f : (Fin n → ℤ) → ℂ, MemLp f (ENNReal.ofReal p) Measure.count → ∀ x : Fin n → ℤ,
      (∀ lam : ℝ, Summable fun y : {y : Fin n → ℤ // y ≠ 0} => ‖swTerm n d Ω lam f x y‖) ∧
      TendstoUniformly (fun (s : Finset {y : Fin n → ℤ // y ≠ 0}) (lam : ℝ) =>
          ∑ y ∈ s, swTerm n d Ω lam f x y) (fun lam => swOp n d Ω lam f x) atTop ∧
      Continuous (fun lam => swOp n d Ω lam f x) ∧
      Function.Periodic (fun lam => swOp n d Ω lam f x) 1 ∧
      BddAbove (Set.range fun lam : ℝ => ‖swOp n d Ω lam f x‖) ∧
      (∃ lam₀ ∈ Set.Icc (0 : ℝ) 1, ∀ lam : ℝ, ‖swOp n d Ω lam f x‖ ≤ ‖swOp n d Ω lam₀ f x‖) ∧
      swMax n d Ω f x = ⨆ r : ℚ, ‖swOp n d Ω (r : ℝ) f x‖) ∧
    ∀ (f g : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ),
      ENNReal.ofReal (swMax n d Ω (f - g) x) ≤
        eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
          eLpNorm (f - g) (ENNReal.ofReal p) Measure.count := by
  have hpq := Real.HolderConjugate.conjExponent hp
  refine ⟨memLp_swLatKernel hΩ hpq.symm.lt, fun f hf x => ?_, fun f g x => ?_⟩
  · set T : ℝ → ℂ := fun lam => swOp n d Ω lam f x with hT
    have hsum : Summable fun y : Fin n → ℤ => ‖swLatKernel Ω y‖ * ‖f (x - y)‖ := by
      simpa only [norm_swTerm] using summable_norm_swTerm (d := d) hΩ hp hf 0 x
    have hu := hsum.subtype {y | y ≠ 0}
    have hbound : ∀ (y : {y : Fin n → ℤ // y ≠ 0}) (lam : ℝ),
        ‖swTerm n d Ω lam f x y‖ ≤ ‖swLatKernel Ω y‖ * ‖f (x - y)‖ :=
      fun y lam => le_of_eq (norm_swTerm lam f x y)
    have hcont : Continuous T :=
      continuous_tsum (fun y => continuous_swTerm f x y) hu hbound
    obtain ⟨lam₀, hlam₀, hmax⟩ := isCompact_Icc.exists_isMaxOn
      (Set.nonempty_Icc.2 (zero_le_one' ℝ)) hcont.norm.continuousOn
    have hmax' : ∀ lam, ‖T lam‖ ≤ ‖T lam₀‖ := by
      intro lam
      have e : T lam = T (Int.fract lam) := by
        rw [hT]
        dsimp only
        rw [← swOp_add_int (Int.fract lam) ⌊lam⌋, Int.fract_add_floor]
      rw [e]
      exact hmax ⟨Int.fract_nonneg lam, (Int.fract_lt_one lam).le⟩
    have hbdd : BddAbove (Set.range fun lam => ‖T lam‖) := ⟨‖T lam₀‖, by
      rintro _ ⟨lam, rfl⟩; exact hmax' lam⟩
    have hbddQ : BddAbove (Set.range fun r : ℚ => ‖T r‖) := ⟨‖T lam₀‖, by
      rintro _ ⟨r, rfl⟩; exact hmax' r⟩
    refine ⟨fun lam => (summable_norm_swTerm hΩ hp hf lam x).subtype _,
      tendstoUniformly_tsum hu hbound, hcont, fun lam => ?_, hbdd, ⟨lam₀, hlam₀, hmax'⟩, ?_⟩
    · simpa using swOp_add_int (d := d) (Ω := Ω) lam 1 f x
    · have h1 : swMax n d Ω f x = ‖T lam₀‖ :=
        le_antisymm (ciSup_le hmax') (le_ciSup hbdd lam₀)
      rw [h1]
      refine le_antisymm ?_ (ciSup_le fun r => hmax' r)
      exact Rat.denseRange_cast.induction_on (p := fun b => ‖T b‖ ≤ ⨆ r : ℚ, ‖T r‖) lam₀
        (isClosed_le hcont.norm continuous_const) (fun r => le_ciSup hbddQ r)
  · set c := eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
      eLpNorm (f - g) (ENNReal.ofReal p) Measure.count
    by_cases hc : c = ∞
    · rw [hc]; exact le_top
    rw [ENNReal.ofReal_le_iff_le_toReal hc]
    refine ciSup_le fun lam => ?_
    have := enorm_swOp_le (d := d) (Ω := Ω) hpq lam (f - g) x
    rw [← ofReal_norm] at this
    exact (ENNReal.ofReal_le_iff_le_toReal hc).1 this


/-! ### The initial kernel and the finite dyadic sums -/

/-- Helper: `K_m(x) = (η(2^{-m} x) - η(2^{1-m} x)) K(x)`. -/
lemma dyadicKernel_eq_sub (m : ℤ) (z : EuclideanSpace ℝ (Fin n)) :
    dyadicKernel Ω m z =
      ((dyadicEta ((2 : ℝ) ^ (-m) • z) - dyadicEta ((2 : ℝ) ^ (1 - m) • z) : ℝ) : ℂ) *
        swKernel Ω z := by
  rw [dyadicKernel, dyadicPsi, smul_smul,
    show (2 : ℝ) * 2 ^ (-m) = 2 ^ (1 - m) by
      rw [sub_eq_add_neg, zpow_add₀ two_ne_zero, zpow_one], mul_comm]

/-- Helper (telescoping, Lemma 4.1): `∑_{j=j₀}^{J} K_j(x) = (η(2^{-J} x) - η(2^{1-j₀} x)) K(x)`. -/
lemma sum_Icc_dyadicKernel (z : EuclideanSpace ℝ (Fin n)) {j₀ J : ℕ} (hJ : j₀ ≤ J) :
    ∑ j ∈ Finset.Icc j₀ J, dyadicKernel Ω (j : ℤ) z =
      ((dyadicEta ((2 : ℝ) ^ (-(J : ℤ)) • z) - dyadicEta ((2 : ℝ) ^ (1 - (j₀ : ℤ)) • z) : ℝ) : ℂ) *
        swKernel Ω z := by
  induction J, hJ using Nat.le_induction with
  | base => rw [Finset.Icc_self, Finset.sum_singleton, dyadicKernel_eq_sub]
  | succ J hJ ih =>
    rw [Finset.sum_Icc_succ_top (by omega), ih, dyadicKernel_eq_sub,
      show (1 : ℤ) - ((J + 1 : ℕ) : ℤ) = -(J : ℤ) by push_cast; ring]
    push_cast
    ring

/-- Helper: for `|x| ≤ 2^J` and `j₀ ≤ J`, `K(x) = η(2^{1-j₀} x) K(x) + ∑_{j=j₀}^{J} K_j(x)`. -/
lemma swKernel_eq_init_add_sum (z : EuclideanSpace ℝ (Fin n)) {j₀ J : ℕ} (hJ : j₀ ≤ J)
    (hz : ‖z‖ ≤ 2 ^ J) :
    swKernel Ω z = ((dyadicEta ((2 : ℝ) ^ (1 - (j₀ : ℤ)) • z) : ℝ) : ℂ) * swKernel Ω z +
      ∑ j ∈ Finset.Icc j₀ J, dyadicKernel Ω (j : ℤ) z := by
  have h1 : dyadicEta ((2 : ℝ) ^ (-(J : ℤ)) • z) = 1 := by
    apply dyadicEta_eq_one
    rw [norm_smul, Real.norm_eq_abs, abs_of_pos (by positivity), zpow_neg, zpow_natCast,
      inv_mul_le_iff₀ (by positivity), mul_one]
    exact hz
  rw [sum_Icc_dyadicKernel z hJ, h1]
  push_cast
  ring

/-- The initial kernel `k_init(y) = η(y)K(y) + ∑_{1 ≤ j < j₀} K_j(y) = η(2^{1-j₀} y) K(y)` of the
proof of Theorem 13.2 (the second form by telescoping; it also covers `j₀ = 0`). -/
noncomputable def swInitKernel (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (j₀ : ℕ) (y : Fin n → ℤ) : ℂ :=
  ((dyadicEta ((2 : ℝ) ^ (1 - (j₀ : ℤ)) • latEmbed y) : ℝ) : ℂ) * swKernel Ω (latEmbed y)

/-- Helper: `k_init` is supported in the finite box `|y|_∞ ≤ 2^{j₀}`. -/
lemma swInitKernel_eq_zero {j₀ : ℕ} {y : Fin n → ℤ} (hy : y ∉ latBox n (2 ^ j₀)) :
    swInitKernel Ω j₀ y = 0 := by
  simp only [latBox, Set.mem_ofPred_eq, not_forall, not_le] at hy
  obtain ⟨i, hi⟩ := hy
  have hi' : (2 : ℝ) ^ j₀ < ‖latEmbed y‖ := by
    calc (2 : ℝ) ^ j₀ < |(y i : ℝ)| := by exact_mod_cast hi
      _ = ‖latEmbed y i‖ := by simp
      _ ≤ ‖latEmbed y‖ := PiLp.norm_apply_le _ _
  rw [swInitKernel, dyadicEta_eq_zero, Complex.ofReal_zero, zero_mul]
  rw [norm_smul, Real.norm_eq_abs, abs_of_pos (by positivity)]
  have h2 : (2 : ℝ) ^ (1 - (j₀ : ℤ)) * (2 : ℝ) ^ j₀ = 2 := by
    rw [← zpow_natCast, ← zpow_add₀ two_ne_zero]; simp
  have hpos : (0 : ℝ) < 2 ^ (1 - (j₀ : ℤ)) := by positivity
  nlinarith


/-- Helper: `|e(t) a b| = |a| |b|`. -/
lemma enorm_eC_mul_mul (t : ℝ) (a b : ℂ) : ‖eC t * a * b‖ₑ = ‖a‖ₑ * ‖b‖ₑ := by
  have : ‖eC t‖ₑ = 1 := by rw [← ofReal_norm, norm_eC, ENNReal.ofReal_one]
  rw [enorm_mul, enorm_mul, this, one_mul]

/-- Helper: for finitely supported `f`, `x ∈ G`, `j₀ ≤ J` and `|x - z| ≤ 2^J` on the support of
`f`, `T_λ f(x) = ∑_y e(λP(y)) k_init(y) f(x-y) + ∑_{j=j₀}^{J} T_{j,λ} f(x)` for every `λ`. -/
lemma swOp_eq_init_add_minor {f : (Fin n → ℤ) → ℂ} (hf : (Function.support f).Finite)
    (x : Fin n → ℤ) {j₀ J : ℕ} (hJ : j₀ ≤ J)
    (hxJ : ∀ z ∈ hf.toFinset, ‖latEmbed (x - z)‖ ≤ 2 ^ J) (lam : ℝ) :
    swOp n d Ω lam f x =
      ∑ y ∈ (latBox_finite n (2 ^ j₀)).toFinset,
          eC (lam * (radialPolyZ n d y : ℝ)) * swInitKernel Ω j₀ y * f (x - y) +
        ∑ j ∈ Finset.Icc j₀ J, minorOp Ω d j lam f x := by
  set Fx := hf.toFinset.image (fun z => x - z) with hFx
  have hF : ∀ y ∉ Fx, f (x - y) = 0 := by
    intro y hy
    by_contra h
    exact hy (Finset.mem_image.2 ⟨x - y, hf.mem_toFinset.2 h, sub_sub_cancel x y⟩)
  rw [swOp_eq_tsum, tsum_eq_sum (s := Fx) (fun y hy => by simp [swTerm, hF y hy])]
  have hmin : ∀ j : ℕ, minorOp Ω d j lam f x = ∑ y ∈ Fx,
      eC (lam * (radialPolyZ n d y : ℝ)) * dyadicKernel Ω j (latEmbed y) * f (x - y) :=
    fun j => tsum_eq_sum (fun y hy => by simp [hF y hy])
  have hI : ∑ y ∈ (latBox_finite n (2 ^ j₀)).toFinset,
        eC (lam * (radialPolyZ n d y : ℝ)) * swInitKernel Ω j₀ y * f (x - y) =
      ∑ y ∈ Fx, eC (lam * (radialPolyZ n d y : ℝ)) * swInitKernel Ω j₀ y * f (x - y) := by
    set g : (Fin n → ℤ) → ℂ := fun y =>
      eC (lam * (radialPolyZ n d y : ℝ)) * swInitKernel Ω j₀ y * f (x - y) with hg
    have h1 : ∑' y, g y = ∑ y ∈ (latBox_finite n (2 ^ j₀)).toFinset, g y := by
      refine tsum_eq_sum (fun y hy => ?_)
      rw [hg]; dsimp only
      rw [swInitKernel_eq_zero (fun h => hy ((latBox_finite n (2 ^ j₀)).mem_toFinset.2 h)),
        mul_zero, zero_mul]
    have h2 : ∑' y, g y = ∑ y ∈ Fx, g y := tsum_eq_sum (fun y hy => by simp [hg, hF y hy])
    exact h1.symm.trans h2
  simp_rw [hmin]
  rw [hI, Finset.sum_comm, ← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun y _ => ?_
  by_cases hy : f (x - y) = 0
  · simp [swTerm, hy]
  have hy' : ‖latEmbed y‖ ≤ 2 ^ J := by
    have := hxJ (x - y) (hf.mem_toFinset.2 hy)
    rwa [sub_sub_cancel] at this
  have e := swKernel_eq_init_add_sum (Ω := Ω) (latEmbed y) hJ hy'
  simp only [swTerm, swInitKernel]
  rw [← Finset.sum_mul, ← Finset.mul_sum]
  conv_lhs => rw [e]
  ring

/-- Helper: `ℓ^p` bound for the initial part, `‖∑_y |k_init(y)| |f(· - y)|‖_p ≤ ‖k_init‖₁ ‖f‖_p`
(`k_init` has finite support). -/
lemma eLpNorm_init_le {p : ℝ} (hp : 1 < p) (S : Finset (Fin n → ℤ)) (k f : (Fin n → ℤ) → ℂ) :
    eLpNorm (fun x => ∑ y ∈ S, ‖k y‖ₑ * ‖f (x - y)‖ₑ) (ENNReal.ofReal p) Measure.count ≤
      ENNReal.ofReal (∑ y ∈ S, ‖k y‖) * eLpNorm f (ENNReal.ofReal p) Measure.count := by
  have hp1 : (1 : ℝ≥0∞) ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hp.le
  have htr : ∀ y, eLpNorm (fun x => ‖f (x - y)‖ₑ) (ENNReal.ofReal p) Measure.count =
      eLpNorm f (ENNReal.ofReal p) Measure.count := by
    intro y
    rw [← eLpNorm_enorm f AEStronglyMeasurable.of_discrete, eLpNorm_count_ennreal_eq _ (by linarith),
      eLpNorm_count_ennreal_eq _ (by linarith)]
    congr 1
    exact (Equiv.subRight y).tsum_eq (fun z => ‖‖f z‖ₑ‖ₑ ^ p)
  have e : (fun x => ∑ y ∈ S, ‖k y‖ₑ * ‖f (x - y)‖ₑ) =
      ∑ y ∈ S, fun x => ‖k y‖ₑ * ‖f (x - y)‖ₑ := by
    funext x; simp [Finset.sum_apply]
  rw [e]
  refine (eLpNorm_sum_le hp1).trans (le_of_eq ?_)
  simp_rw [eLpNorm_count_const_mul _ _ (by linarith : (0 : ℝ) < p), htr]
  rw [← Finset.sum_mul, ENNReal.ofReal_sum_of_nonneg (fun _ _ => norm_nonneg _)]
  simp_rw [ofReal_norm]

/-- Helper (Fatou for eventual pointwise majorants on `G`): if `M ≤ F_J` pointwise for all large
`J` (depending on the point) and eventually `‖F_J‖_p ≤ B`, then `‖M‖_p ≤ B`. -/
lemma eLpNorm_le_of_eventually_le {p : ℝ} (hp : 0 < p) (M : (Fin n → ℤ) → ℝ≥0∞)
    (F : ℕ → (Fin n → ℤ) → ℝ≥0∞) (B : ℝ≥0∞)
    (hF : ∀ᶠ J in atTop, eLpNorm (F J) (ENNReal.ofReal p) Measure.count ≤ B)
    (hM : ∀ x, ∀ᶠ J in atTop, M x ≤ F J x) :
    eLpNorm M (ENNReal.ofReal p) Measure.count ≤ B := by
  apply eLpNorm_count_le_of_tsum_rpow_le hp
  rw [ENNReal.tsum_eq_iSup_sum]
  refine iSup_le fun S => ?_
  obtain ⟨J, hJB, hJ⟩ := (hF.and ((Filter.eventually_all_finset S).2 fun x _ => hM x)).exists
  calc ∑ x ∈ S, M x ^ p ≤ ∑ x ∈ S, F J x ^ p :=
        Finset.sum_le_sum fun x hx => ENNReal.rpow_le_rpow (hJ x hx) hp.le
    _ ≤ ∑' x, F J x ^ p := ENNReal.sum_le_tsum S
    _ ≤ B ^ p := tsum_rpow_le_of_eLpNorm_count_le hp hJB


/-- Helper: `0 ≤ 𝒞 f(x)`. -/
lemma swMax_nonneg (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) : 0 ≤ swMax n d Ω f x :=
  Real.iSup_nonneg fun _ => norm_nonneg _

/-- The finite-support case of Theorem 13.2 (`thm:main`): for `n, d ≥ 1`, admissible `Ω` and
`1 < p < ∞` there is `C ≥ 0` with `‖𝒞 f‖_p ≤ C ‖f‖_p` for every finitely supported `f`. -/
theorem eLpNorm_swMax_le_of_finite_support (hn : 1 ≤ n) (hd : 1 ≤ d) (hΩ : IsSWProfile Ω)
    {p : ℝ} (hp : 1 < p) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ f : (Fin n → ℤ) → ℂ, (Function.support f).Finite →
      eLpNorm (swMax n d Ω f) (ENNReal.ofReal p) Measure.count ≤
        ENNReal.ofReal C * eLpNorm f (ENNReal.ofReal p) Measure.count := by
  obtain ⟨C₁, hC₁, hfin⟩ := finite_dyadic_stein_wainger hn hd hΩ hp
  set j₀ := coherJ0 n d Ω p with hj₀
  set S := (latBox_finite n (2 ^ j₀)).toFinset with hS
  set A := ∑ y ∈ S, ‖swInitKernel Ω j₀ y‖ with hA
  have hA0 : 0 ≤ A := Finset.sum_nonneg fun _ _ => norm_nonneg _
  have hp1 : (1 : ℝ≥0∞) ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hp.le
  refine ⟨A + C₁, by positivity, fun f hf => ?_⟩
  set F : ℕ → (Fin n → ℤ) → ℝ≥0∞ := fun J =>
    (fun x => ∑ y ∈ S, ‖swInitKernel Ω j₀ y‖ₑ * ‖f (x - y)‖ₑ) +
      (fun x => ⨆ lam : ℝ, ‖∑ j ∈ Finset.Icc j₀ J, minorOp Ω d j lam f x‖ₑ) with hFdef
  rw [← eLpNorm_enorm (swMax n d Ω f) AEStronglyMeasurable.of_discrete]
  apply eLpNorm_le_of_eventually_le (by linarith) _ F
  · filter_upwards [eventually_ge_atTop j₀] with J hJ
    refine (eLpNorm_add_le hp1).trans ?_
    calc _ ≤ ENNReal.ofReal A * eLpNorm f (ENNReal.ofReal p) Measure.count +
          ENNReal.ofReal C₁ * eLpNorm f (ENNReal.ofReal p) Measure.count :=
          add_le_add (eLpNorm_init_le hp S _ f) (hfin J hJ f hf)
      _ = _ := by rw [ENNReal.ofReal_add hA0 hC₁, add_mul]
  · intro x
    have hev : ∀ᶠ J in atTop, j₀ ≤ J ∧ ∀ z ∈ hf.toFinset, ‖latEmbed (x - z)‖ ≤ 2 ^ J :=
      (eventually_ge_atTop j₀).and ((Filter.eventually_all_finset _).2 fun z _ =>
        (tendsto_pow_atTop_atTop_of_one_lt one_lt_two).eventually_ge_atTop _)
    filter_upwards [hev] with J hJx
    obtain ⟨hJ, hxJ⟩ := hJx
    by_cases htop : F J x = ∞
    · rw [htop]; exact le_top
    rw [Real.enorm_eq_ofReal (swMax_nonneg f x), ENNReal.ofReal_le_iff_le_toReal htop]
    refine ciSup_le fun lam => ?_
    rw [← ENNReal.ofReal_le_iff_le_toReal htop, ofReal_norm,
      swOp_eq_init_add_minor hf x hJ hxJ lam]
    refine (enorm_add_le _ _).trans (add_le_add ?_
      (le_iSup (fun lam => ‖∑ j ∈ Finset.Icc j₀ J, minorOp Ω d j lam f x‖ₑ) lam))
    exact (enorm_sum_le _ _).trans (Finset.sum_le_sum fun y _ => le_of_eq (enorm_eC_mul_mul _ _ _))


/-- Helper: `𝒞 g(x) ≤ 𝒞 f(x) + ‖K‖_{p'} ‖g - f‖_p` for `f, g ∈ ℓ^p` (from (13.1) and linearity). -/
lemma swMax_le_swMax_add (hΩ : IsSWProfile Ω) {p : ℝ} (hp : 1 < p) {f g : (Fin n → ℤ) → ℂ}
    (hf : MemLp f (ENNReal.ofReal p) Measure.count) (hg : MemLp g (ENNReal.ofReal p) Measure.count)
    (x : Fin n → ℤ) :
    swMax n d Ω g x ≤ swMax n d Ω f x +
      (eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
        eLpNorm (g - f) (ENNReal.ofReal p) Measure.count).toReal := by
  have hpq := Real.HolderConjugate.conjExponent hp
  have hK := memLp_swLatKernel hΩ hpq.symm.lt
  have hgf := hg.sub hf
  have hc : eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
      eLpNorm (g - f) (ENNReal.ofReal p) Measure.count ≠ ∞ :=
    ENNReal.mul_ne_top hK.eLpNorm_ne_top hgf.eLpNorm_ne_top
  have hbdd := ((absolute_convergence_and_parameter_continuity (d := d) hΩ hp).2.1 f hf x).2.2.2.2.1
  refine ciSup_le fun lam => ?_
  have hlin : swOp n d Ω lam g x = swOp n d Ω lam f x + swOp n d Ω lam (g - f) x := by
    rw [swOp_eq_tsum, swOp_eq_tsum, swOp_eq_tsum,
      ← (summable_norm_swTerm hΩ hp hf lam x).of_norm.tsum_add
        (summable_norm_swTerm hΩ hp hgf lam x).of_norm]
    congr 1; funext y
    simp only [swTerm, Pi.sub_apply]
    ring
  have h2 : ‖swOp n d Ω lam (g - f) x‖ ≤
      (eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
        eLpNorm (g - f) (ENNReal.ofReal p) Measure.count).toReal := by
    rw [← ENNReal.ofReal_le_iff_le_toReal hc, ofReal_norm]
    exact enorm_swOp_le hpq lam (g - f) x
  rw [hlin]
  exact (norm_add_le _ _).trans (add_le_add (le_ciSup hbdd lam) h2)

/-- Helper: `|𝒞 g(x) - 𝒞 f(x)| ≤ ‖K‖_{p'} ‖g - f‖_p` for `f, g ∈ ℓ^p`. -/
lemma abs_swMax_sub_le (hΩ : IsSWProfile Ω) {p : ℝ} (hp : 1 < p) {f g : (Fin n → ℤ) → ℂ}
    (hf : MemLp f (ENNReal.ofReal p) Measure.count) (hg : MemLp g (ENNReal.ofReal p) Measure.count)
    (x : Fin n → ℤ) :
    |swMax n d Ω g x - swMax n d Ω f x| ≤
      (eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
        eLpNorm (g - f) (ENNReal.ofReal p) Measure.count).toReal := by
  have h1 := swMax_le_swMax_add (d := d) hΩ hp hf hg x
  have h2 := swMax_le_swMax_add (d := d) hΩ hp hg hf x
  rw [eLpNorm_sub_comm f g] at h2
  rw [abs_sub_le_iff]
  constructor <;> linarith

/-- **Blueprint Theorem 13.2 (`thm:main`)**, the combined discrete Stein–Wainger bound, eq. (13.2)
(`eq:MAIN`): let `n, d ≥ 1`, let `Ω` be smooth on `E ∖ {0}`, homogeneous of degree zero, with
integral zero on `S^{n-1}` (`IsSWProfile Ω`), `K(y) = Ω(y)|y|^{-n}` for `y ≠ 0` and
`P(y) = (y₁² + ⋯ + yₙ²)^d`. For every real `1 < p < ∞` there is a finite constant
`C = C_{p,n,d,Ω} ≥ 0` such that for all `f ∈ ℓ^p(ℤⁿ)`:
the series `T_λ f(x) = ∑_{y ∈ ℤⁿ ∖ {0}} e(λP(y)) K(y) f(x-y)` converges (absolutely, Lemma 13.1)
for all `λ ∈ ℝ` and `x`, the family `λ ↦ |T_λ f(x)|` is bounded (so the scalar supremum
`𝒞 f(x) = sup_{λ ∈ ℝ} |T_λ f(x)|` is a genuine supremum), `𝒞 f ∈ ℓ^p`, and
`‖sup_{λ ∈ ℝ} |T_λ f|‖_{ℓ^p} ≤ C ‖f‖_{ℓ^p}`. -/
theorem discrete_stein_wainger_lp {n d : ℕ} (hn : 1 ≤ n) (hd : 1 ≤ d)
    {Ω : EuclideanSpace ℝ (Fin n) → ℂ} (hΩ : IsSWProfile Ω) {p : ℝ} (hp : 1 < p) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ f : (Fin n → ℤ) → ℂ, MemLp f (ENNReal.ofReal p) Measure.count →
      (∀ (lam : ℝ) (x : Fin n → ℤ), Summable fun y : {y : Fin n → ℤ // y ≠ 0} =>
        swTerm n d Ω lam f x y) ∧
      (∀ x, BddAbove (Set.range fun lam : ℝ => ‖swOp n d Ω lam f x‖)) ∧
      MemLp (swMax n d Ω f) (ENNReal.ofReal p) Measure.count ∧
      eLpNorm (swMax n d Ω f) (ENNReal.ofReal p) Measure.count ≤
        ENNReal.ofReal C * eLpNorm f (ENNReal.ofReal p) Measure.count := by
  obtain ⟨C, hC, hfin⟩ := eLpNorm_swMax_le_of_finite_support hn hd hΩ hp
  refine ⟨C, hC, fun f hf => ?_⟩
  have hpq := Real.HolderConjugate.conjExponent hp
  have hK := memLp_swLatKernel hΩ hpq.symm.lt
  have hbound : eLpNorm (swMax n d Ω f) (ENNReal.ofReal p) Measure.count ≤
      ENNReal.ofReal C * eLpNorm f (ENNReal.ofReal p) Measure.count := by
    have hfR : ∀ R : ℕ, MemLp ((latBox n R).indicator f) (ENNReal.ofReal p) Measure.count :=
      fun R => finSW_memLp (support_indicator_latBox_finite n R f) _
    refine eLpNorm_le_of_tendsto_of_eLpNorm_le
      (u := fun R : ℕ => swMax n d Ω ((latBox n R).indicator f))
      (fun R => AEStronglyMeasurable.of_discrete) (ae_of_all _ fun x => ?_) (fun R => ?_)
    · have ht := eLpNorm_sub_indicator_latBox_tendsto ENNReal.ofReal_ne_top hf
      have hc : Tendsto (fun R : ℕ =>
          (eLpNorm (swLatKernel Ω) (ENNReal.ofReal p.conjExponent) Measure.count *
            eLpNorm ((latBox n R).indicator f - f) (ENNReal.ofReal p) Measure.count).toReal)
          atTop (𝓝 0) := by
        simp_rw [eLpNorm_sub_comm _ f]
        have h1 := ENNReal.Tendsto.const_mul ht (Or.inr hK.eLpNorm_ne_top)
        rw [mul_zero] at h1
        have h2 := (ENNReal.tendsto_toReal ENNReal.zero_ne_top).comp h1
        exact h2
      rw [tendsto_iff_norm_sub_tendsto_zero]
      exact squeeze_zero (fun _ => norm_nonneg _)
        (fun R => abs_swMax_sub_le (d := d) hΩ hp hf (hfR R) x) hc
    · refine (hfin _ (support_indicator_latBox_finite n R f)).trans ?_
      gcongr
      exact eLpNorm_indicator_le f (latBox_finite n R).measurableSet
  refine ⟨fun lam x => (summable_norm_swTerm hΩ hp hf lam x).of_norm.subtype _,
    fun x => ((absolute_convergence_and_parameter_continuity (d := d) hΩ hp).2.1 f hf x).2.2.2.2.1,
    memLp_iff.2 (lt_of_le_of_lt hbound (ENNReal.mul_lt_top ENNReal.ofReal_lt_top hf.eLpNorm_lt_top)),
    hbound⟩

end Auto
