/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license.
This file was automatically generated by Claude.
-/
import Mathlib

/-!
# Foundations: the objects of the discrete Stein–Wainger theorem

Definitions from §1.2 ("Types, measures, and Fourier signs") and §14.1 ("Concrete types and
representations") of `blueprints/discrete-sw.tex`:

* the lattice `G = ℤⁿ` as `Fin n → ℤ` and the Euclidean space `E = ℝⁿ` as
  `EuclideanSpace ℝ (Fin n)`, with the coordinatewise embedding `latEmbed`;
* the radial polynomial `P(x) = (x₁² + ⋯ + xₙ²)^d`, in an integer version `radialPolyZ` and a real
  version `radialPoly`, related by `radialPoly_latEmbed`;
* the character `e(t) = exp(2πit)` (`eC`);
* the admissibility predicate `IsSWProfile` for `Ω` (smooth off zero, homogeneous of degree zero,
  zero mean on the unit sphere);
* the kernel `K(x) = Ω(x)|x|^{-n}` with `K(0) = 0` (`swKernel`), the modulated operators `T_λ`
  (`swOp`) and the maximal operator `𝒞 f = sup_λ |T_λ f|` (`swMax`).
-/

namespace Auto

open MeasureTheory Real
open scoped ContDiff

/-- The coordinatewise embedding `ℤⁿ ↪ ℝⁿ` of blueprint §1.2 (`G ↪ E`). -/
noncomputable def latEmbed {n : ℕ} (y : Fin n → ℤ) : EuclideanSpace ℝ (Fin n) :=
  WithLp.toLp 2 (fun i => (y i : ℝ))

@[simp] lemma latEmbed_apply {n : ℕ} (y : Fin n → ℤ) (i : Fin n) :
    latEmbed y i = (y i : ℝ) := rfl

/-- The integer-valued radial polynomial `P_ℤ(y) = (∑ᵢ yᵢ²)^d` of blueprint §14.1. -/
def radialPolyZ (n d : ℕ) (y : Fin n → ℤ) : ℤ := (∑ i, y i ^ 2) ^ d

/-- The real radial polynomial `P(x) = (x₁² + ⋯ + xₙ²)^d` of blueprint §1.2. -/
noncomputable def radialPoly (n d : ℕ) (x : EuclideanSpace ℝ (Fin n)) : ℝ := (∑ i, x i ^ 2) ^ d

/-- Blueprint §14.1: `P_ℝ(ι y) = cast (P_ℤ(y))`. -/
lemma radialPoly_latEmbed (n d : ℕ) (y : Fin n → ℤ) :
    radialPoly n d (latEmbed y) = (radialPolyZ n d y : ℝ) := by
  simp [radialPoly, radialPolyZ]

/-- Blueprint §14.1: `P_ℝ(x) = ‖x‖^{2d}`. -/
lemma radialPoly_eq_norm_pow (n d : ℕ) (x : EuclideanSpace ℝ (Fin n)) :
    radialPoly n d x = ‖x‖ ^ (2 * d) := by
  rw [radialPoly, pow_mul, EuclideanSpace.norm_sq_eq]
  simp [Real.norm_eq_abs, sq_abs]

/-- The character `e(t) = exp(2πit)` of blueprint §1.2. -/
noncomputable def eC (t : ℝ) : ℂ := Complex.exp (2 * π * Complex.I * t)

/-- The hypotheses on `Ω` in Theorem 13.2 (`thm:main`): `Ω` is smooth on `E ∖ {0}`, homogeneous of
degree zero, and has integral zero on the unit sphere `S^{n-1}` (with respect to the sphere measure
`volume.toSphere`, the cone construction of Lemma 4.1). -/
def IsSWProfile {n : ℕ} (Ω : EuclideanSpace ℝ (Fin n) → ℂ) : Prop :=
  ContDiffOn ℝ ∞ Ω {0}ᶜ ∧
  (∀ x : EuclideanSpace ℝ (Fin n), x ≠ 0 → ∀ t : ℝ, 0 < t → Ω (t • x) = Ω x) ∧
  ∫ θ, Ω θ ∂(volume.toSphere : Measure (Metric.sphere (0 : EuclideanSpace ℝ (Fin n)) 1)) = 0

/-- The Calderón–Zygmund kernel `K(x) = Ω(x)|x|^{-n}` for `x ≠ 0`, with `K(0) = 0`
(blueprint §4 and Theorem 13.2). -/
noncomputable def swKernel {n : ℕ} (Ω : EuclideanSpace ℝ (Fin n) → ℂ)
    (x : EuclideanSpace ℝ (Fin n)) : ℂ :=
  if x = 0 then 0 else Ω x / ((‖x‖ ^ n : ℝ) : ℂ)

/-- The summand `e(λ P(y)) K(y) f(x - y)` of the modulated singular integral in Theorem 13.2. -/
noncomputable def swTerm (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (lam : ℝ)
    (f : (Fin n → ℤ) → ℂ) (x y : Fin n → ℤ) : ℂ :=
  eC (lam * (radialPolyZ n d y : ℝ)) * swKernel Ω (latEmbed y) * f (x - y)

/-- The modulated discrete singular integral
`T_λ f(x) = ∑_{y ∈ ℤⁿ ∖ {0}} e(λ P(y)) K(y) f(x - y)` of Lemma 13.1 and Theorem 13.2. -/
noncomputable def swOp (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (lam : ℝ)
    (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) : ℂ :=
  ∑' y : {y : Fin n → ℤ // y ≠ 0}, swTerm n d Ω lam f x y

/-- The discrete Stein–Wainger maximal operator `𝒞 f(x) = sup_{λ ∈ ℝ} |T_λ f(x)|`
(Theorem 13.2; the supremum is over a scalar real parameter). -/
noncomputable def swMax (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ)
    (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) : ℝ :=
  ⨆ lam : ℝ, ‖swOp n d Ω lam f x‖

end Auto
