/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license.
This file was automatically generated by Claude.
-/
import DiscreteSW.Auto.Bands

/-!
# Kernel-side major-arc approximation and coherent grouping

Results from §12 ("Kernel-side major-arc approximation and coherent grouping") of
`blueprints/discrete-sw.tex`.

## Definitions

* `majorH Ω d j μ = h_{j,μ} = e(μ P) K_j` (so `radialOscPhi Ω d j μ = 𝓕 h_{j,μ}`);
* `majorExp M j = ⌊M log₂(j+1)⌋` (so `H_j = minorH M j = 2^{majorExp M j}`);
* `IsMajorCenter M j a q`: `a/q` is an admissible center of `X_j` (`1 ≤ q < H_j`, `0 ≤ a < q`,
  `(a, q) = 1`);
* `CoherenceSpec n d Ω p j₀`: `j₀ ≥ j₁` and the three properties (1)–(3) of Lemma 12.2 for all
  `j ≥ j₀`; `coherJ0 n d Ω p = j₀` is the least such integer, and
  `coherJs n d Ω p s = j_s = max(j₀, ⌈2^{s/M}⌉ - 1)`;
* `majorIdx n d Ω p s λ J`: the finite set of `j ∈ [j₀, J]` whose major center (the center of the
  arc of `X_j` containing `λ`) lies in `𝓡_s`.

## Main results

* `major_kernel_error`: Blueprint Lemma 12.1 (`lem:kernelerror`), eq. (12.1);
* `latKernel_liftSym_radialOscPhi`, `major_kernel_formula`: Lemma 12.1, the lattice kernel formula;
* `coherJ0_spec` (with `exists_coherenceSpec`): Lemma 12.2 (`lem:coherence`), (1)–(3);
* `isMajorCenter_of_mem_liftRat`, `isMajorCenter_of_le_majorExp`, `two_pow_le_minorH_iff`:
  admissibility of `𝓡_s` in `X_j` and the formula for `j_s`;
* `minorArcs_center_unique`: uniqueness of the major center;
* `major_coherence`: the coherent interval `[j_s, b]`, the common center `α` and the common
  representative `μ` with `|μ| < 1/4`, together with `|μ| 2^{Dj} ≤ (j+1)^M` and `L_s ≤ 2^{j/2}`;
* `mem_minorArcs_iff_exists_majorIdx`, `eq_of_mem_majorIdx`: every major index belongs to
  exactly one group `s`;
* `finite_dyadic_stein_wainger`: Blueprint Proposition 12.3 (`prop:finiteSW`), eq. (12.2),
  with the smoothing error `finSW_kernel_error`, the pointwise majorant `finSW_pointwise` and the
  group majorants `finSWMain` (`𝒫_s f` for `s ≥ 1`).

## Proof notes (deviations from the blueprint)

* Lemma 12.1 is proved without the hypotheses `j ≥ 1` and `L_s ≤ R` (they are not needed), and
  the kernel formula holds for every `α = a/q` with `q ≥ 1` (not only `α ∈ 𝓡_s`). The gradient
  bound is replaced by the equivalent Lipschitz bound `|h(y) - h(y - z)| ≤ C (1 + U) R^{-n-1}|z|`
  (`exists_majorH_bounds`), and the first moment bound `∫ |z| |φ_s(z)| ≤ C L_s` is used in the
  pointwise form `|z| |φ_s(z)| ≤ C L_s B_{L_s}(z)` (`norm_mul_norm_liftPhi_le`).
* In Lemma 12.2, property (3) holds for all `s ≤ ⌊M log₂(j+1)⌋` (including `s = 0`), and the
  lower scale needs `d ≥ 1` (for `d = 0` the widths `w_j` increase).
* In Proposition 12.3 the supremum is over `λ ∈ ℝ` (equivalent to `λ ∈ 𝕋` by `1`-periodicity).
  The group index `s` is bounded by `s < 2^s ≤ H_J`, so the major sum is a finite disjoint union
  over `s < H_J + 1`; the main-term majorant is `∑_{s ≥ 0} 𝒫_s f` (with `𝒫_0 := 0`), bounded
  by the countable Minkowski inequality `eLpNorm_tsum_le_count`.
-/

namespace Auto

open MeasureTheory Set Real Finset
open scoped FourierTransform ContDiff SchwartzMap Convolution

variable {n d : ℕ} {Ω : EuclideanSpace ℝ (Fin n) → ℂ} {p : ℝ}

/-! ### Blueprint Lemma 12.1 (`lem:kernelerror`) -/

/-- `h_{j,μ}(x) = e(μ P(x)) K_j(x)` of Blueprint Lemma 12.1 (`lem:kernelerror`). -/
noncomputable def majorH (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (d : ℕ) (j : ℤ) (μ : ℝ)
    (x : EuclideanSpace ℝ (Fin n)) : ℂ :=
  eC (μ * radialPoly n d x) * dyadicKernel Ω j x

/-- `Φ_{j,μ} = 𝓕 h_{j,μ}`. -/
lemma radialOscPhi_eq_fourier_majorH (j : ℤ) (μ : ℝ) :
    radialOscPhi Ω d j μ = 𝓕 (majorH Ω d j μ) := rfl

/-- `φ_s` is the Schwartz function `𝓕⁻ χ_s`. -/
lemma coe_fourierInv_liftChiSchwartz (s : ℕ) :
    ((𝓕⁻ (liftChiSchwartz n d Ω p s) : 𝓢(EuclideanSpace ℝ (Fin n), ℂ)) :
      EuclideanSpace ℝ (Fin n) → ℂ) = liftPhi n d Ω p s := by
  rw [SchwartzMap.fourierInv_coe]; rfl

/-- `φ_s` is integrable. -/
lemma integrable_liftPhi (s : ℕ) : Integrable (liftPhi n d Ω p s) := by
  rw [← coe_fourierInv_liftChiSchwartz]; exact SchwartzMap.integrable _

/-- `∫ φ_s = χ_s(0) = 1` (Fourier inversion). -/
lemma integral_liftPhi (s : ℕ) : ∫ x, liftPhi n d Ω p s x = 1 := by
  have key : 𝓕 (liftPhi n d Ω p s) = fun ξ => (liftChi n d Ω p s ξ : ℂ) := by
    rw [← coe_fourierInv_liftChiSchwartz, ← SchwartzMap.fourier_coe,
      FourierTransform.fourier_fourierInv_eq]; rfl
  have h := congrFun key 0
  rw [fourier_eq_integral_eC] at h
  simp only [inner_zero_right, neg_zero, eC_zero, one_mul] at h
  rw [h, liftChi, smul_zero, liftCutoff_eq_one (fun i => by simp)]
  simp

/-- First-moment decay of `φ_s`: `|z| |φ_s(z)| ≤ K L_s B_{L_s}(z)` with `K` depending only on
`n` (from the Schwartz decay of `𝓕⁻ χ` of order `n + 2` and scaling). -/
lemma norm_mul_norm_liftPhi_le (n : ℕ) :
    ∃ K : ℝ, 0 ≤ K ∧ ∀ (d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) (s : ℕ)
      (z : EuclideanSpace ℝ (Fin n)),
      ‖z‖ * ‖liftPhi n d Ω p s z‖ ≤ K * (liftL n d Ω p s : ℝ) * envelope n (liftL n d Ω p s) z := by
  obtain ⟨K, hK, hKb⟩ := exists_schwartz_decay (arithPhiS n) (n + 2)
  refine ⟨K, hK, fun d Ω p s z => ?_⟩
  have hL := liftL_pos (n := n) (d := d) (Ω := Ω) (p := p) s
  set L : ℝ := (liftL n d Ω p s : ℝ)
  rw [arith_liftPhi_eq_dilateL]
  have h1 := norm_dilateL_le (fun x => (hKb x).1) hL z
  set t : ℝ := ‖z‖ / L with ht
  have ht0 : 0 ≤ t := by positivity
  have hz : ‖z‖ = L * t := by rw [ht]; field_simp
  rw [envelope, hz]
  calc L * t * ‖dilateL (⇑(arithPhiS n)) L z‖
      ≤ L * t * (K * ((L ^ n)⁻¹ * ((1 + t) ^ (n + 2))⁻¹)) := by
        gcongr
    _ = K * L * ((L ^ n)⁻¹ * ((1 + t) ^ (n + 1))⁻¹) * (t / (1 + t)) := by
        field_simp; ring
    _ ≤ K * L * ((L ^ n)⁻¹ * ((1 + t) ^ (n + 1))⁻¹) * 1 := by
        gcongr
        rw [div_le_one (by positivity)]; linarith
    _ = _ := by rw [mul_one, ← hz, ← ht]

/-- The scalar inequality `|μ| D (3R)^{D-1} R ≤ D 3^D U` from `|μ| R^D ≤ U`. -/
lemma major_phase_scalar {D : ℕ} {μ R U : ℝ} (hR : 0 < R) (hU : |μ| * R ^ D ≤ U) :
    |μ| * D * (3 * R) ^ (D - 1) * R ≤ D * 3 ^ D * U := by
  rcases D with _ | k
  · simp
  · have hU0 : 0 ≤ U := le_trans (by positivity) hU
    rw [Nat.add_sub_cancel, mul_pow]
    have e : |μ| * ((k + 1 : ℕ) : ℝ) * (3 ^ k * R ^ k) * R =
        ((k + 1 : ℕ) : ℝ) * 3 ^ k * (|μ| * R ^ (k + 1)) := by ring
    rw [e, pow_succ 3 k]
    have h3 : (3 : ℝ) ^ k * U ≤ 3 ^ k * 3 * U := by nlinarith [pow_pos (by norm_num : (0:ℝ) < 3) k]
    calc ((k + 1 : ℕ) : ℝ) * 3 ^ k * (|μ| * R ^ (k + 1)) ≤ ((k + 1 : ℕ) : ℝ) * 3 ^ k * U := by
          gcongr
      _ ≤ ((k + 1 : ℕ) : ℝ) * (3 ^ k * 3) * U := by
          rw [mul_assoc, mul_assoc]; gcongr

/-- Size and Lipschitz bounds for `h_{j,μ} = e(μP) K_j` with `|μ| R^D ≤ U`, `R = 2^j`:
`|h| ≤ C₀ R^{-n}` and `|h(y) - h(y - z)| ≤ A (1 + U) R^{-n-1} |z|`. -/
lemma exists_majorH_bounds (hΩ : IsSWProfile Ω) (d : ℕ) :
    ∃ C₀ A : ℝ, 0 ≤ C₀ ∧ 0 ≤ A ∧ ∀ (j : ℕ) (μ U : ℝ), |μ| * ((2 : ℝ) ^ j) ^ (2 * d) ≤ U →
      (∀ x, ‖majorH Ω d j μ x‖ ≤ C₀ / ((2 : ℝ) ^ j) ^ n) ∧
      ∀ y z, ‖majorH Ω d j μ y - majorH Ω d j μ (y - z)‖ ≤
        A * (1 + U) * ‖z‖ / ((2 : ℝ) ^ j) ^ (n + 1) := by
  obtain ⟨C₀, C₁, hC₀, hC₁, hK⟩ := minor_kernel_bounds (Ω := Ω) hΩ
  set D := 2 * d with hD
  refine ⟨C₀, 2 * π * D * 3 ^ D * C₀ + C₁ + 2 * C₀, hC₀, by positivity, fun j μ U hU => ?_⟩
  set R : ℝ := 2 ^ j with hRdef
  have hR : 0 < R := by positivity
  have hU0 : 0 ≤ U := le_trans (by positivity) hU
  have hnorm : ∀ x, ‖majorH Ω d j μ x‖ ≤ C₀ / R ^ n := fun x => by
    rw [majorH, norm_mul, norm_eC, one_mul]; exact (hK j).1 x
  refine ⟨hnorm, fun y z => ?_⟩
  have hRn : 0 < R ^ (n + 1) := by positivity
  have hz0 : 0 ≤ ‖z‖ := norm_nonneg z
  rw [le_div_iff₀ hRn]
  by_cases hz : R ≤ ‖z‖
  · calc ‖majorH Ω d j μ y - majorH Ω d j μ (y - z)‖ * R ^ (n + 1)
        ≤ (C₀ / R ^ n + C₀ / R ^ n) * R ^ (n + 1) := by
          gcongr; exact (norm_sub_le _ _).trans (add_le_add (hnorm _) (hnorm _))
      _ = 2 * C₀ * R := by rw [pow_succ]; field_simp; ring
      _ ≤ 2 * C₀ * ‖z‖ := by gcongr
      _ ≤ (2 * π * D * 3 ^ D * C₀ + C₁ + 2 * C₀) * (1 + U) * ‖z‖ := by
          have : 0 ≤ 2 * π * D * 3 ^ D * C₀ := by positivity
          nlinarith [mul_nonneg hC₀ hU0, mul_nonneg (mul_nonneg this hU0) hz0,
            mul_nonneg (mul_nonneg hC₁ hU0) hz0, mul_nonneg hC₁ hz0, mul_nonneg this hz0,
            mul_nonneg (mul_nonneg hC₀ hU0) hz0]
  push Not at hz
  set e1 := eC (μ * radialPoly n d y)
  set e2 := eC (μ * radialPoly n d (y - z))
  have hsplit : majorH Ω d j μ y - majorH Ω d j μ (y - z) =
      (e1 - e2) * dyadicKernel Ω j y + e2 * (dyadicKernel Ω j y - dyadicKernel Ω j (y - z)) := by
    simp only [majorH, e1, e2]; ring
  have hsecond : ‖e2 * (dyadicKernel Ω j y - dyadicKernel Ω j (y - z))‖ ≤ C₁ / R ^ (n + 1) * ‖z‖ := by
    rw [norm_mul, norm_eC, one_mul]
    have := (hK j).2 y (y - z)
    rwa [sub_sub_cancel] at this
  have hfirst : ‖(e1 - e2) * dyadicKernel Ω j y‖ * R ^ (n + 1) ≤
      2 * π * D * 3 ^ D * C₀ * U * ‖z‖ := by
    by_cases hKy : dyadicKernel Ω j y = 0
    · rw [hKy, mul_zero, norm_zero, zero_mul]; positivity
    have hy : ‖y‖ < 2 * R := by
      have := (support_dyadicKernel (Ω := Ω) (j : ℤ) hKy).2
      rwa [zpow_add_one₀ two_ne_zero, zpow_natCast, mul_comm] at this
    have hyz : ‖y - z‖ ≤ 3 * R := by
      have := norm_sub_le y z; linarith
    have hP : |radialPoly n d y - radialPoly n d (y - z)| ≤ ‖z‖ * D * (3 * R) ^ (D - 1) := by
      rw [radialPoly_eq_norm_pow, radialPoly_eq_norm_pow]
      refine (abs_pow_sub_pow_le _ _ _).trans ?_
      have h1 : |‖y‖ - ‖y - z‖| ≤ ‖z‖ := by
        have := abs_norm_sub_norm_le y (y - z); rwa [sub_sub_cancel] at this
      have h2 : max |‖y‖| |‖y - z‖| ≤ 3 * R := by
        rw [abs_norm, abs_norm]; exact max_le (by linarith) hyz
      gcongr
    have he : ‖e1 - e2‖ ≤ 2 * π * (|μ| * (‖z‖ * D * (3 * R) ^ (D - 1))) := by
      refine (norm_eC_sub_eC_le _ _).trans ?_
      rw [← mul_sub, abs_mul]
      gcongr
    have hKb := (hK j).1 y
    have hsc := major_phase_scalar (D := D) hR hU
    calc ‖(e1 - e2) * dyadicKernel Ω j y‖ * R ^ (n + 1)
        ≤ 2 * π * (|μ| * (‖z‖ * D * (3 * R) ^ (D - 1))) * (C₀ / R ^ n) * R ^ (n + 1) := by
          rw [norm_mul]; gcongr
      _ = 2 * π * C₀ * ‖z‖ * (|μ| * D * (3 * R) ^ (D - 1) * R) := by
          rw [pow_succ]; field_simp
      _ ≤ 2 * π * C₀ * ‖z‖ * (D * 3 ^ D * U) := by gcongr
      _ = 2 * π * D * 3 ^ D * C₀ * U * ‖z‖ := by ring
  rw [hsplit]
  have hs2 : ‖e2 * (dyadicKernel Ω j y - dyadicKernel Ω j (y - z))‖ * R ^ (n + 1) ≤ C₁ * ‖z‖ := by
    have := mul_le_mul_of_nonneg_right hsecond hRn.le
    rwa [div_mul_eq_mul_div, div_mul_eq_mul_div, mul_div_assoc, div_self hRn.ne', mul_one] at this
  calc ‖(e1 - e2) * dyadicKernel Ω j y + e2 * (dyadicKernel Ω j y - dyadicKernel Ω j (y - z))‖ *
        R ^ (n + 1)
      ≤ (‖(e1 - e2) * dyadicKernel Ω j y‖ +
          ‖e2 * (dyadicKernel Ω j y - dyadicKernel Ω j (y - z))‖) * R ^ (n + 1) := by
        gcongr; exact norm_add_le _ _
    _ ≤ 2 * π * D * 3 ^ D * C₀ * U * ‖z‖ + C₁ * ‖z‖ := by rw [add_mul]; exact add_le_add hfirst hs2
    _ ≤ (2 * π * D * 3 ^ D * C₀ + C₁ + 2 * C₀) * (1 + U) * ‖z‖ := by
        have : 0 ≤ 2 * π * D * 3 ^ D * C₀ := by positivity
        nlinarith [mul_nonneg (mul_nonneg this hU0) hz0, mul_nonneg (mul_nonneg hC₁ hU0) hz0,
          mul_nonneg hC₁ hz0, mul_nonneg this hz0, mul_nonneg (mul_nonneg hC₀ hU0) hz0,
          mul_nonneg hC₀ hz0]

/-- `B_R(y) ≥ R^{-n} 5^{-n-1}` for `|y| ≤ 4R`. -/
lemma envelope_ge_of_le_four_mul {R : ℝ} (hR : 0 < R) {y : EuclideanSpace ℝ (Fin n)}
    (hy : ‖y‖ ≤ 4 * R) : (R ^ n)⁻¹ * ((5 : ℝ) ^ (n + 1))⁻¹ ≤ envelope n R y := by
  unfold envelope
  have h1 : ‖y‖ / R ≤ 4 := by rw [div_le_iff₀ hR]; linarith
  gcongr
  linarith

/-- `B_R(y) ≥ R 2^{-n-1} |y|^{-n-1}` for `|y| ≥ R`. -/
lemma envelope_ge_of_le_norm {R : ℝ} (hR : 0 < R) {y : EuclideanSpace ℝ (Fin n)}
    (hy : R ≤ ‖y‖) : R / (2 ^ (n + 1) * ‖y‖ ^ (n + 1)) ≤ envelope n R y := by
  have hy0 : 0 < ‖y‖ := lt_of_lt_of_le hR hy
  have e : envelope n R y = R / (R + ‖y‖) ^ (n + 1) := by
    unfold envelope
    rw [show 1 + ‖y‖ / R = (R + ‖y‖) / R by field_simp, div_pow, pow_succ R n]
    field_simp
  rw [e, ← mul_pow]
  gcongr
  linarith

/-- `B_L(w) ≤ L |w|^{-n-1}` for `w ≠ 0`. -/
lemma envelope_le_div_norm_pow {L : ℝ} (hL : 0 < L) {w : EuclideanSpace ℝ (Fin n)}
    (hw : 0 < ‖w‖) : envelope n L w ≤ L / ‖w‖ ^ (n + 1) := by
  have e : envelope n L w = L / (L + ‖w‖) ^ (n + 1) := by
    unfold envelope
    rw [show 1 + ‖w‖ / L = (L + ‖w‖) / L by field_simp, div_pow, pow_succ L n]
    field_simp
  rw [e]
  gcongr
  linarith

/-- **Blueprint Lemma 12.1 (`lem:kernelerror`)**, eq. (12.1): for a Stein–Wainger profile `Ω`
and `d`, there is `C ≥ 0` (independent of `p`, `s`, `j`, `μ`, `U`) such that, with `R = 2^j`,
`h_{j,μ} = e(μ P) K_j` and `φ_s = 𝓕⁻ χ_s`, whenever `|μ| R^D ≤ U` (`D = 2d`),
`|h_{j,μ}(y) - (h_{j,μ} *_E φ_s)(y)| ≤ C (1 + U) (L_s / R) B_R(y)` for all `y ∈ E` (hence on `G`).
(The blueprint's hypotheses `j ≥ 1`, `1 ≤ L_s ≤ R` are not needed; `L_s ≥ 1` always holds.) -/
theorem major_kernel_error (hΩ : IsSWProfile Ω) (d : ℕ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ (p : ℝ) (s j : ℕ) (μ U : ℝ), |μ| * ((2 : ℝ) ^ j) ^ (2 * d) ≤ U →
      ∀ y : EuclideanSpace ℝ (Fin n),
        ‖majorH Ω d j μ y -
            (majorH Ω d j μ ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] liftPhi n d Ω p s) y‖ ≤
          C * (1 + U) * ((liftL n d Ω p s : ℝ) / 2 ^ j) * envelope n (2 ^ j) y := by
  obtain ⟨C₀, A, hC₀, hA, hH⟩ := exists_majorH_bounds hΩ d
  obtain ⟨Kφ, hKφ, hmom⟩ := norm_mul_norm_liftPhi_le n
  obtain ⟨Cφ, hCφ, hφ⟩ := norm_liftPhi_le n
  obtain ⟨CL1, hCL1⟩ := dyadicKernel_L1 hΩ
  have hCn : 0 ≤ envelopeConst n := by unfold envelopeConst; positivity
  have hCL0 : 0 ≤ CL1 := (integral_nonneg fun _ => norm_nonneg _).trans (hCL1 0).2.1
  refine ⟨A * Kφ * envelopeConst n * 5 ^ (n + 1) + CL1 * Cφ * 4 ^ (n + 1), by positivity,
    fun p s j μ U hU y => ?_⟩
  obtain ⟨hHb, hHl⟩ := hH j μ U hU
  set R : ℝ := 2 ^ j with hRdef
  set L : ℝ := (liftL n d Ω p s : ℝ) with hLdef
  set h := majorH Ω d j μ with hhdef
  set φ := liftPhi n d Ω p s with hφdef
  have hR : 0 < R := by positivity
  have hL : 0 < L := liftL_pos s
  have hU0 : 0 ≤ U := le_trans (by positivity) hU
  have hconv : (h ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] φ) y = ∫ t, h t * φ (y - t) := by
    rw [convolution_def]; rfl
  have hhc : Continuous h := by
    have : Continuous fun x : EuclideanSpace ℝ (Fin n) => eC (μ * radialPoly n d x) := by
      unfold radialPoly eC; fun_prop
    exact this.mul (contDiff_dyadicKernel hΩ j).continuous
  have hCpos : 0 ≤ A * Kφ * envelopeConst n * 5 ^ (n + 1) := by positivity
  have hCpos' : 0 ≤ CL1 * Cφ * 4 ^ (n + 1) := by positivity
  have hE0 : 0 ≤ envelope n R y := envelope_nonneg hR y
  by_cases hy : ‖y‖ ≤ 4 * R
  · have hconv' : (h ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] φ) y = ∫ z, h (y - z) * φ z := by
      rw [hconv, ← integral_sub_left_eq_self (fun t => h t * φ (y - t)) volume y]
      simp_rw [sub_sub_cancel]
    have hint1 : Integrable fun z => h (y - z) * φ z :=
      (integrable_liftPhi s).bdd_mul (hhc.comp (continuous_const.sub continuous_id)).aestronglyMeasurable
        (ae_of_all _ fun z => hHb _)
    have hint2 : Integrable fun z => h y * φ z := (integrable_liftPhi s).const_mul _
    have hrep : h y - (h ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] φ) y =
        ∫ z, (h y - h (y - z)) * φ z := by
      simp_rw [sub_mul]
      rw [hconv', integral_sub hint2 hint1, integral_const_mul, hφdef, integral_liftPhi, mul_one]
    obtain ⟨hEi, hEI⟩ := integrable_envelope_and_integral_le (n := n) hL
    have hbound : ∀ z, ‖(h y - h (y - z)) * φ z‖ ≤
        A * (1 + U) / R ^ (n + 1) * (Kφ * L * envelope n L z) := by
      intro z; rw [norm_mul]
      calc ‖h y - h (y - z)‖ * ‖φ z‖ ≤ (A * (1 + U) * ‖z‖ / R ^ (n + 1)) * ‖φ z‖ := by
            gcongr; exact hHl y z
        _ = A * (1 + U) / R ^ (n + 1) * (‖z‖ * ‖φ z‖) := by ring
        _ ≤ _ := mul_le_mul_of_nonneg_left (hmom d Ω p s z) (by positivity)
    have hI : ‖h y - (h ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] φ) y‖ ≤
        A * (1 + U) / R ^ (n + 1) * (Kφ * L * envelopeConst n) := by
      rw [hrep]
      refine (norm_integral_le_of_norm_le ((hEi.const_mul (Kφ * L)).const_mul _)
        (ae_of_all _ hbound)).trans ?_
      rw [integral_const_mul, integral_const_mul]
      gcongr
    have hE := envelope_ge_of_le_four_mul hR hy
    calc ‖h y - (h ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] φ) y‖
        ≤ A * (1 + U) / R ^ (n + 1) * (Kφ * L * envelopeConst n) := hI
      _ = A * Kφ * envelopeConst n * 5 ^ (n + 1) * (1 + U) * (L / R) *
            ((R ^ n)⁻¹ * ((5 : ℝ) ^ (n + 1))⁻¹) := by
          rw [pow_succ R n]; field_simp
      _ ≤ A * Kφ * envelopeConst n * 5 ^ (n + 1) * (1 + U) * (L / R) * envelope n R y := by
          gcongr
      _ ≤ _ := by gcongr; exact le_add_of_nonneg_right hCpos'
  · push Not at hy
    have hy0 : 0 < ‖y‖ := by linarith
    have hhy : h y = 0 := by
      simp only [hhdef, majorH]
      rw [dyadicKernel_eq_zero_of_le, mul_zero]
      rw [zpow_add_one₀ two_ne_zero, zpow_natCast]; linarith
    rw [hhy, zero_sub, norm_neg, hconv]
    set B : ℝ := Cφ * L * 2 ^ (n + 1) / ‖y‖ ^ (n + 1) with hB
    have hbound : ∀ t, ‖h t * φ (y - t)‖ ≤ ‖h t‖ * B := by
      intro t; rw [norm_mul]
      by_cases ht : dyadicKernel Ω j t = 0
      · have : h t = 0 := by simp [hhdef, majorH, ht]
        rw [this, norm_zero, zero_mul, zero_mul]
      have htR : ‖t‖ < 2 * R := by
        have := (support_dyadicKernel (Ω := Ω) (j : ℤ) ht).2
        rwa [zpow_add_one₀ two_ne_zero, zpow_natCast, mul_comm] at this
      have hyt : ‖y‖ / 2 ≤ ‖y - t‖ := by have := norm_sub_norm_le y t; linarith
      have hyt0 : 0 < ‖y - t‖ := by linarith
      gcongr
      calc ‖φ (y - t)‖ ≤ Cφ * envelope n L (y - t) := (hφ d Ω p s).1 _
        _ ≤ Cφ * (L / ‖y - t‖ ^ (n + 1)) := by gcongr; exact envelope_le_div_norm_pow hL hyt0
        _ ≤ Cφ * (L / (‖y‖ / 2) ^ (n + 1)) := by gcongr
        _ = B := by rw [div_pow, hB]; field_simp
    have hhi : Integrable fun t => ‖h t‖ := (integrable_oscKernel hΩ d j μ).norm
    refine (norm_integral_le_of_norm_le (hhi.mul_const B) (ae_of_all _ hbound)).trans ?_
    rw [integral_mul_const]
    have hnorm_int : ∫ t, ‖h t‖ = ∫ t, ‖dyadicKernel Ω j t‖ := by
      congr 1; funext t; simp [hhdef, majorH, norm_eC]
    have hL1 : ∫ t, ‖h t‖ ≤ CL1 := hnorm_int ▸ (hCL1 j).2.1
    have hE := envelope_ge_of_le_norm (n := n) hR (by linarith : R ≤ ‖y‖)
    have hB0 : 0 ≤ B := by positivity
    calc (∫ t, ‖h t‖) * B ≤ CL1 * B := by gcongr
      _ = CL1 * Cφ * 4 ^ (n + 1) * (L / R) * (R / (2 ^ (n + 1) * ‖y‖ ^ (n + 1))) := by
          rw [hB, show (4 : ℝ) = 2 * 2 by norm_num, mul_pow]; field_simp
      _ ≤ CL1 * Cφ * 4 ^ (n + 1) * (L / R) * envelope n R y := by gcongr
      _ ≤ CL1 * Cφ * 4 ^ (n + 1) * (1 + U) * (L / R) * envelope n R y := by
          have : 0 ≤ CL1 * Cφ * 4 ^ (n + 1) * (L / R) * envelope n R y := by positivity
          nlinarith [mul_nonneg this hU0]
      _ ≤ _ := by gcongr; exact le_add_of_nonneg_left hCpos

/-- `|m̌(y)| ≤ ∫_{[0,1)ⁿ} |m|`. -/
lemma norm_latKernel_le_integral (m : EuclideanSpace ℝ (Fin n) → ℂ) (y : Fin n → ℤ) :
    ‖latKernel m y‖ ≤ ∫ ξ in torusCube n, ‖m ξ‖ := by
  unfold latKernel
  refine (norm_integral_le_integral_norm _).trans (le_of_eq ?_)
  congr 1; funext ξ; rw [norm_mul, norm_eC, mul_one]

/-- If `λ = α + μ` modulo `ℤ`, then `e(λ P(y)) = e(α P(y)) e(μ P(y))` for `y ∈ G` (since
`P(y) ∈ ℤ`). -/
lemma eC_mul_radialPolyZ_of_eq_add (d : ℕ) {α μ lam : ℝ} (hlam : ∃ k : ℤ, lam = α + μ + k)
    (y : Fin n → ℤ) :
    eC (lam * (radialPolyZ n d y : ℝ)) =
      eC (α * (radialPolyZ n d y : ℝ)) * eC (μ * radialPoly n d (latEmbed y)) := by
  obtain ⟨k, rfl⟩ := hlam
  rw [radialPoly_latEmbed, ← eC_add]
  have : (α + μ + k) * (radialPolyZ n d y : ℝ) =
      α * (radialPolyZ n d y : ℝ) + μ * (radialPolyZ n d y : ℝ) + ((k * radialPolyZ n d y : ℤ) : ℝ) := by
    push_cast; ring
  rw [this, eC_add, eC_intCast, mul_one]

/-- Blueprint Lemma 12.1 (`lem:kernelerror`), via eq. (`eq:liftkernel`): for `α = a/q`, `q ≥ 1`,
the kernel of `Lift_{s,α}[Φ_{j,μ}]` is `e(α P(y)) (h_{j,μ} *_E φ_s)(y)` for every `y ∈ G`. -/
theorem latKernel_liftSym_radialOscPhi (hΩ : IsSWProfile Ω) (p : ℝ) (s a : ℕ) {q : ℕ}
    (hq : 1 ≤ q) (j : ℤ) (μ : ℝ) (y : Fin n → ℤ) :
    latKernel (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) y =
      eC ((a : ℝ) / q * (radialPolyZ n d y : ℝ)) *
        (majorH Ω d j μ ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] liftPhi n d Ω p s)
          (latEmbed y) := by
  have hH : Integrable (majorH Ω d j μ) := integrable_oscKernel hΩ d j μ
  obtain ⟨hFc, hFb⟩ := continuous_fourier_and_norm_le hH
  rw [radialOscPhi_eq_fourier_majorH,
    latKernel_liftSym_of_bdd s a hq hFc.aestronglyMeasurable (fun ξ _ => hFb ξ) y,
    fourierInv_fourier_mul_liftChi hH]

/-- **Blueprint Lemma 12.1 (`lem:kernelerror`)**, lattice kernel formula: if `λ = α + μ` in `𝕋`
(`λ - a/q - μ ∈ ℤ`), with `α = a/q`, `q ≥ 1` (in particular `α ∈ 𝓡_s`), then for every
`f ∈ ℓ¹(G)` (e.g. finitely supported) and `x ∈ G`,
`T_{j,λ} f(x) - Lift_{s,α}[Φ_{j,μ}](D) f(x) =
  ∑_y e(α P(y)) [h_{j,μ}(y) - (h_{j,μ} *_E φ_s)(y)] f(x - y)`,
i.e. the lattice convolution kernel of `T_{j,λ} - Lift_{s,α}[Φ_{j,μ}](D)` is
`e(α P(y)) [h_{j,μ}(y) - (h_{j,μ} *_E φ_s)(y)]`, including its value at `y = 0`. -/
theorem major_kernel_formula (hΩ : IsSWProfile Ω) (p : ℝ) (s a : ℕ) {q : ℕ} (hq : 1 ≤ q)
    (j : ℕ) {lam μ : ℝ} (hlam : ∃ k : ℤ, lam = a / q + μ + k) {f : (Fin n → ℤ) → ℂ}
    (hf : Summable fun z => ‖f z‖) (x : Fin n → ℤ) :
    minorOp Ω d j lam f x - latMult (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) f x =
      ∑' y, eC ((a : ℝ) / q * (radialPolyZ n d y : ℝ)) *
        (majorH Ω d j μ (latEmbed y) -
          (majorH Ω d j μ ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] liftPhi n d Ω p s)
            (latEmbed y)) * f (x - y) := by
  set H := majorH Ω d j μ with hHdef
  have hH : Integrable H := integrable_oscKernel hΩ d j μ
  obtain ⟨hFc, hFb⟩ := continuous_fourier_and_norm_le hH
  have hint : IntegrableOn (liftSym n d Ω p s a q (𝓕 H)) (torusCube n) :=
    integrableOn_liftSym (integrable_mul_liftChi hFc.aestronglyMeasurable (fun ξ _ => hFb ξ))
  have hker : ∀ y, latKernel (liftSym n d Ω p s a q (𝓕 H)) y =
      eC ((a : ℝ) / q * (radialPolyZ n d y : ℝ)) *
        (H ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] liftPhi n d Ω p s) (latEmbed y) := by
    intro y
    rw [← radialOscPhi_eq_fourier_majorH]
    exact latKernel_liftSym_radialOscPhi hΩ p s a hq j μ y
  rw [radialOscPhi_eq_fourier_majorH, latMult_eq_latConv hint hf, latConv, minorOp]
  have hs1 : Summable fun y : Fin n → ℤ =>
      eC (lam * (radialPolyZ n d y : ℝ)) * dyadicKernel Ω j (latEmbed y) * f (x - y) := by
    refine summable_of_ne_finset_zero (s := minorBox n (2 * 2 ^ j)) fun y hy => ?_
    rw [minor_kernel_eq_zero j hy, mul_zero, zero_mul]
  have hfx : Summable fun y => ‖f (x - y)‖ :=
    (Equiv.subLeft x).summable_iff.2 hf
  have hs2 : Summable fun y => latKernel (liftSym n d Ω p s a q (𝓕 H)) y * f (x - y) := by
    refine Summable.of_norm_bounded (hfx.mul_left (∫ ξ in torusCube n,
      ‖liftSym n d Ω p s a q (𝓕 H) ξ‖)) fun y => ?_
    rw [norm_mul]
    exact mul_le_mul_of_nonneg_right (norm_latKernel_le_integral _ y) (norm_nonneg _)
  rw [← hs1.tsum_sub hs2]
  refine tsum_congr fun y => ?_
  rw [hker, eC_mul_radialPolyZ_of_eq_add d hlam y, hHdef, majorH]
  ring

/-! ### Blueprint Lemma 12.2 (`lem:coherence`) -/

/-- The exponent `⌊M log₂(j+1)⌋` of `H_j = 2^{⌊M log₂(j+1)⌋}`. -/
noncomputable def majorExp (M j : ℕ) : ℕ := ⌊(M : ℝ) * Real.logb 2 ((j : ℝ) + 1)⌋₊

/-- `H_j = 2^{⌊M log₂(j+1)⌋}`. -/
lemma minorH_eq_two_pow (M j : ℕ) : minorH M j = 2 ^ majorExp M j := rfl

/-- `H_j ≤ (j+1)^M`. -/
lemma minorH_le_pow (M j : ℕ) : (minorH M j : ℝ) ≤ ((j : ℝ) + 1) ^ M := by
  set x : ℝ := (M : ℝ) * Real.logb 2 ((j : ℝ) + 1) with hx
  have hj : (0 : ℝ) < (j : ℝ) + 1 := by positivity
  have hx0 : 0 ≤ x := mul_nonneg (Nat.cast_nonneg _)
    (Real.logb_nonneg (by norm_num) (by linarith [(Nat.cast_nonneg j : (0 : ℝ) ≤ j)]))
  have h2x : (2 : ℝ) ^ x = ((j : ℝ) + 1) ^ M := by
    rw [hx, mul_comm, Real.rpow_mul (by norm_num), Real.rpow_logb (by norm_num) (by norm_num) hj,
      Real.rpow_natCast]
  rw [minorH, Nat.cast_pow, Nat.cast_ofNat, ← h2x, ← Real.rpow_natCast]
  exact Real.rpow_le_rpow_of_exponent_le (by norm_num) (Nat.floor_le hx0)

/-- `s ≤ ⌊M log₂(j+1)⌋ ⟺ j ≥ ⌈2^{s/M}⌉ - 1` (for `M ≥ 1`). -/
lemma le_majorExp_iff {M : ℕ} (hM : 1 ≤ M) (s j : ℕ) :
    s ≤ majorExp M j ↔ ⌈(2 : ℝ) ^ ((s : ℝ) / M)⌉₊ - 1 ≤ j := by
  have hj : (0 : ℝ) < (j : ℝ) + 1 := by positivity
  have hM' : (0 : ℝ) < M := by exact_mod_cast hM
  have hx0 : 0 ≤ (M : ℝ) * Real.logb 2 ((j : ℝ) + 1) := mul_nonneg (Nat.cast_nonneg _)
    (Real.logb_nonneg (by norm_num) (by linarith [(Nat.cast_nonneg j : (0 : ℝ) ≤ j)]))
  rw [majorExp, Nat.le_floor_iff hx0, ← div_le_iff₀' hM',
    Real.le_logb_iff_rpow_le one_lt_two hj,
    show ((j : ℝ) + 1) = ((j + 1 : ℕ) : ℝ) by push_cast; ring, ← Nat.ceil_le]
  omega

/-- Blueprint Lemma 12.2 (`lem:coherence`): `H_j ≥ 2^s ⟺ j ≥ ⌈2^{s/M}⌉ - 1` (for `M ≥ 1`). -/
lemma two_pow_le_minorH_iff {M : ℕ} (hM : 1 ≤ M) (s j : ℕ) :
    2 ^ s ≤ minorH M j ↔ ⌈(2 : ℝ) ^ ((s : ℝ) / M)⌉₊ - 1 ≤ j := by
  rw [minorH_eq_two_pow, Nat.pow_le_pow_iff_right (by norm_num), le_majorExp_iff hM]

/-- Rational separation (Lemma 3.2): two reduced fractions `a/q`, `a'/q'` in `[0, 1)` with
`q, q' < B` and `‖a/q - a'/q'‖_𝕋 < B^{-2}` coincide. -/
lemma reduced_eq_of_norm_lt {a q a' q' : ℕ} (hq : 1 ≤ q) (ha : a < q) (hc : Nat.Coprime a q)
    (hq' : 1 ≤ q') (ha' : a' < q') (hc' : Nat.Coprime a' q') {B : ℝ} (hqB : (q : ℝ) < B)
    (hq'B : (q' : ℝ) < B)
    (h : ‖(((a : ℝ) / q - a' / q' : ℝ) : UnitAddCircle)‖ < 1 / B ^ 2) : a = a' ∧ q = q' := by
  by_contra hne
  have hq0 : (0 : ℝ) < q := by exact_mod_cast hq
  have hq0' : (0 : ℝ) < q' := by exact_mod_cast hq'
  have hnot : ¬ ∃ m : ℤ, (((a : ℤ) : ℝ) / ((q : ℤ) : ℝ) - ((a' : ℤ) : ℝ) / ((q' : ℤ) : ℝ) : ℝ) = m := by
    rintro ⟨m, hm⟩
    push_cast at hm
    have h1 : (a : ℝ) / q < 1 := by rw [div_lt_one hq0]; exact_mod_cast ha
    have h2 : (a' : ℝ) / q' < 1 := by rw [div_lt_one hq0']; exact_mod_cast ha'
    have h3 : 0 ≤ (a : ℝ) / q := by positivity
    have h4 : 0 ≤ (a' : ℝ) / q' := by positivity
    have hm1 : (m : ℝ) < 1 := by linarith
    have hm2 : (-1 : ℝ) < m := by linarith
    have hm0 : m = 0 := by
      have : m < 1 := by exact_mod_cast hm1
      have : -1 < m := by exact_mod_cast hm2
      omega
    rw [hm0, Int.cast_zero, sub_eq_zero, div_eq_div_iff hq0.ne' hq0'.ne'] at hm
    have hnat : a * q' = a' * q := by exact_mod_cast hm
    apply hne
    have hd1 : q ∣ a * q' := ⟨a', by rw [hnat, mul_comm]⟩
    have hd2 : q' ∣ a' * q := ⟨a, by rw [← hnat, mul_comm]⟩
    have hqq : q = q' :=
      Nat.dvd_antisymm (hc.symm.dvd_of_dvd_mul_left hd1) (hc'.symm.dvd_of_dvd_mul_left hd2)
    subst hqq
    exact ⟨Nat.eq_of_mul_eq_mul_right (by omega) hnat, rfl⟩
  have hsep := one_div_mul_le_norm_addCircle (a : ℤ) (a' : ℤ)
    (by exact_mod_cast hq : (0 : ℤ) < q) (by exact_mod_cast hq' : (0 : ℤ) < q') hnot
  push_cast at hsep
  have hqq : (q : ℝ) * q' < B ^ 2 := by nlinarith
  have : 1 / B ^ 2 < 1 / ((q : ℝ) * q') := one_div_lt_one_div_of_lt (by positivity) hqq
  linarith

/-- `‖α - β‖_𝕋 ≤ ‖λ - α‖_𝕋 + ‖λ - β‖_𝕋`. -/
lemma norm_sub_centers_le (lam α β : ℝ) :
    ‖((α - β : ℝ) : UnitAddCircle)‖ ≤
      ‖((lam - α : ℝ) : UnitAddCircle)‖ + ‖((lam - β : ℝ) : UnitAddCircle)‖ := by
  have : ((α - β : ℝ) : UnitAddCircle) =
      ((lam - β : ℝ) : UnitAddCircle) - ((lam - α : ℝ) : UnitAddCircle) := by
    rw [← AddCircle.coe_sub]; congr 1; ring
  rw [this, add_comm]
  exact norm_sub_le _ _

/-- Property (3) of Blueprint Lemma 12.2 (`lem:coherence`) for all large `j`:
`v_s ≤ j/2` whenever `s ≤ ⌊M log₂(j+1)⌋`. -/
lemma exists_liftV_le_half (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) :
    ∃ N : ℕ, ∀ j ≥ N, ∀ s : ℕ, s ≤ majorExp (paramM n d Ω p) j →
      (liftV n d Ω p s : ℝ) ≤ (j : ℝ) / 2 := by
  set M := paramM n d Ω p with hMdef
  have hM : (2 : ℝ) ≤ M := by exact_mod_cast two_le_paramM n d Ω p
  set Cs := liftCStar n d Ω p
  have hCs : 0 < Cs := liftCStar_pos
  have hlog2 : 0 < Real.log 2 := Real.log_pos one_lt_two
  set K : ℝ := 2 * Cs * (4 * M / Real.log 2 + 1) with hK
  have hK0 : 0 ≤ K := by positivity
  refine ⟨⌈(4 * K + 4) ^ 4⌉₊, fun j hj s hs => ?_⟩
  set x : ℝ := (j : ℝ) + 1 with hx
  have hx0 : 0 < x := by positivity
  set t : ℝ := x ^ (1 / 4 : ℝ) with ht
  have ht1 : 1 ≤ t := Real.one_le_rpow (by linarith [(Nat.cast_nonneg j : (0 : ℝ) ≤ j)])
    (by norm_num)
  have ht4 : t ^ 4 = x := by
    rw [ht, ← Real.rpow_natCast, ← Real.rpow_mul hx0.le]; norm_num
  have ht2 : x ^ (1 / 2 : ℝ) = t ^ 2 := by
    rw [ht, ← Real.rpow_natCast, ← Real.rpow_mul hx0.le]; norm_num
  have htK : 4 * K + 4 ≤ t := by
    refine le_of_pow_le_pow_left₀ (n := 4) (by norm_num) (by linarith) ?_
    rw [ht4]
    have := Nat.le_ceil ((4 * K + 4) ^ 4)
    have h2 : ((⌈(4 * K + 4) ^ 4⌉₊ : ℕ) : ℝ) ≤ j := by exact_mod_cast hj
    linarith
  have hlogb0 : 0 ≤ Real.logb 2 x := Real.logb_nonneg one_lt_two (by
    linarith [(Nat.cast_nonneg j : (0 : ℝ) ≤ j)])
  have hsR : (s : ℝ) ≤ M * Real.logb 2 x := by
    have h1 : (s : ℝ) ≤ majorExp M j := by exact_mod_cast hs
    exact h1.trans (Nat.floor_le (mul_nonneg (by positivity) hlogb0))
  have hlog : Real.log x ≤ 4 * t := by
    have := Real.log_le_rpow_div hx0.le (by norm_num : (0 : ℝ) < 1 / 4)
    rw [← ht] at this; linarith [show t / (1 / 4) = 4 * t by ring]
  have hs1 : (s : ℝ) + 1 ≤ (4 * M / Real.log 2 + 1) * t := by
    have : M * Real.logb 2 x ≤ 4 * M / Real.log 2 * t := by
      rw [Real.logb, mul_div_assoc', div_mul_eq_mul_div, div_le_div_iff_of_pos_right hlog2]
      nlinarith
    nlinarith
  have hpow : (2 : ℝ) ^ ((s : ℝ) / (2 * M)) ≤ t ^ 2 := by
    rw [← ht2]
    have e : x ^ (1 / 2 : ℝ) = (2 : ℝ) ^ (Real.logb 2 x * (1 / 2)) := by
      rw [Real.rpow_mul (by norm_num), Real.rpow_logb (by norm_num) (by norm_num) hx0]
    rw [e]
    refine Real.rpow_le_rpow_of_exponent_le (by norm_num) ?_
    rw [div_le_iff₀ (by positivity)]
    nlinarith
  have hv : (liftV n d Ω p s : ℝ) ≤ Cs * ((s : ℝ) + 1) * (1 + (2 : ℝ) ^ ((s : ℝ) / (2 * M))) + 1 :=
    (Nat.ceil_lt_add_one (by positivity)).le
  have hv2 : Cs * ((s : ℝ) + 1) * (1 + (2 : ℝ) ^ ((s : ℝ) / (2 * M))) ≤ K * t ^ 3 := by
    have h1 : 1 + (2 : ℝ) ^ ((s : ℝ) / (2 * M)) ≤ 2 * t ^ 2 := by nlinarith
    calc Cs * ((s : ℝ) + 1) * (1 + (2 : ℝ) ^ ((s : ℝ) / (2 * M)))
        ≤ Cs * ((4 * M / Real.log 2 + 1) * t) * (2 * t ^ 2) := by gcongr
      _ = K * t ^ 3 := by rw [hK]; ring
  have hjx : (j : ℝ) = t ^ 4 - 1 := by rw [ht4, hx]; ring
  rw [hjx]
  have h3 : 1 ≤ t ^ 3 := one_le_pow₀ ht1
  have h4 : (4 * K + 4) * t ^ 3 ≤ t * t ^ 3 := mul_le_mul_of_nonneg_right htK (by positivity)
  nlinarith

/-- `w_{j+1} < w_j` once `j + 1 ≥ M` (for `d ≥ 1`). -/
lemma minorW_succ_lt {d M j : ℕ} (hd : 1 ≤ d) (hMj : M ≤ j + 1) :
    minorW d M (j + 1) < minorW d M j := by
  have hj0 : (0 : ℝ) < (j : ℝ) + 1 := by positivity
  have hexp : ((j : ℝ) + 2) ^ M ≤ Real.exp 1 * ((j : ℝ) + 1) ^ M := by
    have h1 : (j : ℝ) + 2 ≤ ((j : ℝ) + 1) * Real.exp (1 / ((j : ℝ) + 1)) := by
      have := Real.add_one_le_exp (1 / ((j : ℝ) + 1))
      calc (j : ℝ) + 2 = ((j : ℝ) + 1) * (1 / ((j : ℝ) + 1) + 1) := by field_simp; ring
        _ ≤ ((j : ℝ) + 1) * Real.exp (1 / ((j : ℝ) + 1)) := by gcongr
    calc ((j : ℝ) + 2) ^ M ≤ (((j : ℝ) + 1) * Real.exp (1 / ((j : ℝ) + 1))) ^ M := by gcongr
      _ = ((j : ℝ) + 1) ^ M * Real.exp (M * (1 / ((j : ℝ) + 1))) := by
          rw [mul_pow, ← Real.exp_nat_mul]
      _ ≤ ((j : ℝ) + 1) ^ M * Real.exp 1 := by
          gcongr
          rw [mul_one_div, div_le_one hj0]
          exact_mod_cast hMj
      _ = _ := by ring
  have he4 : Real.exp 1 < 4 := by have := Real.exp_one_lt_d9; linarith
  have h4 : (4 : ℝ) ≤ 2 ^ (2 * d) := by
    calc (4 : ℝ) = 2 ^ 2 := by norm_num
      _ ≤ 2 ^ (2 * d) := pow_le_pow_right₀ (by norm_num) (by omega)
  rw [minorW, minorW, div_lt_div_iff₀ (by positivity) (by positivity),
    show 2 * d * (j + 1) = 2 * d * j + 2 * d by ring, pow_add]
  push_cast
  rw [show (j : ℝ) + 1 + 1 = (j : ℝ) + 2 by ring]
  have hp : (0 : ℝ) < 2 ^ (2 * d * j) := by positivity
  have hX : (0 : ℝ) < ((j : ℝ) + 1) ^ M := by positivity
  have : ((j : ℝ) + 2) ^ M < ((j : ℝ) + 1) ^ M * 2 ^ (2 * d) := by nlinarith
  nlinarith

/-- Property (1) of Blueprint Lemma 12.2 (`lem:coherence`) for all large `j`. -/
lemma eventually_minorW_bounds {d : ℕ} (hd : 1 ≤ d) (M : ℕ) : ∃ N : ℕ, ∀ j ≥ N,
    minorW d M j < 1 / 4 ∧ minorW d M (j + 1) < minorW d M j ∧
      minorW d M j ≤ ((minorH M j : ℝ) ^ 2)⁻¹ / 16 := by
  obtain ⟨NA, hNA⟩ := minor_eventually_pow_le_two_pow (16 * 2 ^ (3 * M)) (3 * M)
  refine ⟨max (max NA 1) M, fun j hj => ?_⟩
  have hj1 : 1 ≤ j := le_trans (le_max_right _ _) (le_trans (le_max_left _ _) hj)
  have hjA : NA ≤ j := le_trans (le_max_left _ _) (le_trans (le_max_left _ _) hj)
  have hjM : M ≤ j := le_trans (le_max_right _ _) hj
  set X : ℝ := ((j : ℝ) + 1) ^ M with hXdef
  have hX1 : 1 ≤ X := one_le_pow₀ (by linarith [(Nat.cast_nonneg j : (0 : ℝ) ≤ j)])
  have hA : 16 * X ^ 3 ≤ (2 : ℝ) ^ (2 * d * j) := by
    have h1 : (j : ℝ) + 1 ≤ 2 * j := by
      have : (1 : ℝ) ≤ j := by exact_mod_cast hj1
      linarith
    have h2 : X ^ 3 ≤ 2 ^ (3 * M) * (j : ℝ) ^ (3 * M) := by
      rw [hXdef, ← pow_mul, ← mul_pow, show M * 3 = 3 * M by ring]; gcongr
    have h3 := hNA j hjA
    have h4 : (2 : ℝ) ^ j ≤ 2 ^ (2 * d * j) := pow_le_pow_right₀ (by norm_num) (by nlinarith)
    nlinarith
  have hW : minorW d M j ≤ 1 / (16 * X ^ 2) := by
    rw [minorW, div_le_div_iff₀ (by positivity) (by positivity)]
    nlinarith
  have hH : (minorH M j : ℝ) ≤ X := minorH_le_pow M j
  have hH0 : (0 : ℝ) < minorH M j := by rw [minorH]; positivity
  refine ⟨?_, minorW_succ_lt hd (by omega), ?_⟩
  · calc minorW d M j ≤ 1 / (16 * X ^ 2) := hW
      _ ≤ 1 / 16 := by gcongr; nlinarith
      _ < 1 / 4 := by norm_num
  · calc minorW d M j ≤ 1 / (16 * X ^ 2) := hW
      _ ≤ 1 / (16 * (minorH M j : ℝ) ^ 2) := by gcongr
      _ = _ := by field_simp

/-- `a/q` is an admissible center of the major arcs `X_j`: `1 ≤ q < H_j`, `0 ≤ a < q`,
`(a, q) = 1`. -/
def IsMajorCenter (M j a q : ℕ) : Prop :=
  1 ≤ q ∧ q < minorH M j ∧ a < q ∧ Nat.Coprime a q

/-- The requirements on the final lower scale `j₀` of Blueprint Lemma 12.2 (`lem:coherence`):
`j₀ ≥ j₁`, and for every `j ≥ j₀`: (1) `w_j < 1/4`, `w_{j+1} < w_j`, `w_j ≤ H_j^{-2}/16`;
(2) the arcs defining `X_j` are pairwise disjoint (two admissible centers whose arcs share a point
coincide); (3) `v_s ≤ j/2` for `1 ≤ s ≤ ⌊M log₂(j+1)⌋`. -/
def CoherenceSpec (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) (j₀ : ℕ) : Prop :=
  paramJ1 n d Ω p ≤ j₀ ∧ ∀ j ≥ j₀,
    (minorW d (paramM n d Ω p) j < 1 / 4 ∧
      minorW d (paramM n d Ω p) (j + 1) < minorW d (paramM n d Ω p) j ∧
      minorW d (paramM n d Ω p) j ≤ ((minorH (paramM n d Ω p) j : ℝ) ^ 2)⁻¹ / 16) ∧
    (∀ a q a' q' : ℕ, IsMajorCenter (paramM n d Ω p) j a q →
      IsMajorCenter (paramM n d Ω p) j a' q' → ∀ lam : ℝ,
        ‖((lam - a / q : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j →
        ‖((lam - a' / q' : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j →
        a = a' ∧ q = q') ∧
    (∀ s : ℕ, 1 ≤ s → s ≤ majorExp (paramM n d Ω p) j → (liftV n d Ω p s : ℝ) ≤ (j : ℝ) / 2)

/-- Disjointness of the arcs of `X_j` from `w_j ≤ H_j^{-2}/16` (rational separation). -/
lemma arcs_disjoint_of_le {M d j : ℕ}
    (hw : minorW d M j ≤ ((minorH M j : ℝ) ^ 2)⁻¹ / 16) {a q a' q' : ℕ}
    (h : IsMajorCenter M j a q) (h' : IsMajorCenter M j a' q') {lam : ℝ}
    (h1 : ‖((lam - a / q : ℝ) : UnitAddCircle)‖ ≤ minorW d M j)
    (h2 : ‖((lam - a' / q' : ℝ) : UnitAddCircle)‖ ≤ minorW d M j) : a = a' ∧ q = q' := by
  obtain ⟨hq, hqH, ha, hc⟩ := h
  obtain ⟨hq', hqH', ha', hc'⟩ := h'
  have hH0 : (0 : ℝ) < minorH M j := by rw [minorH]; positivity
  refine reduced_eq_of_norm_lt hq ha hc hq' ha' hc' (B := minorH M j) (by exact_mod_cast hqH)
    (by exact_mod_cast hqH') ?_
  calc ‖(((a : ℝ) / q - a' / q' : ℝ) : UnitAddCircle)‖ ≤ minorW d M j + minorW d M j :=
        (norm_sub_centers_le lam _ _).trans (add_le_add h1 h2)
    _ ≤ 2 * (((minorH M j : ℝ) ^ 2)⁻¹ / 16) := by linarith
    _ < 1 / (minorH M j : ℝ) ^ 2 := by
        rw [one_div]; have : 0 < ((minorH M j : ℝ) ^ 2)⁻¹ := by positivity
        linarith

/-- Blueprint Lemma 12.2 (`lem:coherence`), existence of the final lower scale: for `d ≥ 1`
there is `j₀` satisfying `CoherenceSpec`. -/
theorem exists_coherenceSpec {d : ℕ} (hd : 1 ≤ d) (n : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ)
    (p : ℝ) : ∃ j₀, CoherenceSpec n d Ω p j₀ := by
  obtain ⟨N₁, h₁⟩ := eventually_minorW_bounds hd (paramM n d Ω p)
  obtain ⟨N₂, h₂⟩ := exists_liftV_le_half n d Ω p
  refine ⟨max (max N₁ N₂) (paramJ1 n d Ω p), le_max_right _ _, fun j hj => ?_⟩
  have hj₁ : N₁ ≤ j := le_trans (le_max_left _ _) (le_trans (le_max_left _ _) hj)
  have hj₂ : N₂ ≤ j := le_trans (le_max_right _ _) (le_trans (le_max_left _ _) hj)
  obtain hw := h₁ j hj₁
  exact ⟨hw, fun a q a' q' h h' lam hl hl' => arcs_disjoint_of_le hw.2.2 h h' hl hl',
    fun s _ hs => h₂ j hj₂ s hs⟩

/-- The final lower scale `j₀` of Blueprint Lemma 12.2 (`lem:coherence`): the least integer
satisfying `CoherenceSpec` (chosen after all previous constants `M`, `j₁`, `v_s`). -/
noncomputable def coherJ0 (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) : ℕ :=
  sInf {j₀ | CoherenceSpec n d Ω p j₀}

/-- **Blueprint Lemma 12.2 (`lem:coherence`)**, (1)–(3): for `d ≥ 1`, `j₀ = coherJ0 n d Ω p ≥ j₁`
satisfies (1)–(3) for every `j ≥ j₀`. -/
theorem coherJ0_spec (hd : 1 ≤ d) : CoherenceSpec n d Ω p (coherJ0 n d Ω p) :=
  Nat.sInf_mem (exists_coherenceSpec hd n Ω p)

/-- `j_s = max(j₀, ⌈2^{s/M}⌉ - 1)` of Blueprint Lemma 12.2 (`lem:coherence`). -/
noncomputable def coherJs (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) (s : ℕ) : ℕ :=
  max (coherJ0 n d Ω p) (⌈(2 : ℝ) ^ ((s : ℝ) / (paramM n d Ω p : ℝ))⌉₊ - 1)

/-- `M ≥ 1`. -/
lemma major_one_le_paramM : 1 ≤ paramM n d Ω p := le_trans (by norm_num) (two_le_paramM n d Ω p)

/-- Blueprint Lemma 12.2 (`lem:coherence`): `w_j` is decreasing on `[j₀, ∞)`. -/
theorem minorW_antitone (hd : 1 ≤ d) {j j' : ℕ} (hj : coherJ0 n d Ω p ≤ j) (hjj' : j ≤ j') :
    minorW d (paramM n d Ω p) j' ≤ minorW d (paramM n d Ω p) j := by
  induction j', hjj' using Nat.le_induction with
  | base => exact le_rfl
  | succ k hk ih => exact ((coherJ0_spec hd).2 k (hj.trans hk)).1.2.1.le.trans ih

/-- A pair of `𝓡_s` with `q < H_j` forces `1 ≤ s`, `2^s ≤ H_j` and `s ≤ ⌊M log₂(j+1)⌋`
(`H_j` is a power of two). -/
lemma liftRat_bounds_of_lt_minorH {M s j a q : ℕ} (h : (a, q) ∈ liftRat s)
    (hqH : q < minorH M j) : 1 ≤ s ∧ 2 ^ s ≤ minorH M j ∧ s ≤ majorExp M j := by
  obtain ⟨h1, h2, h3, -⟩ := mem_liftRat.1 h
  unfold liftN at h1 h2
  rw [minorH_eq_two_pow] at hqH ⊢
  have hs1 : 1 ≤ s := by
    rcases Nat.eq_zero_or_pos s with hs | hs
    · subst hs; simp at h2; omega
    · exact hs
  have hlt : 2 ^ s < 2 ^ (majorExp M j + 1) := by rw [pow_succ]; omega
  have hs : s ≤ majorExp M j := by
    have := (Nat.pow_lt_pow_iff_right (by norm_num : 1 < 2)).1 hlt; omega
  exact ⟨hs1, Nat.pow_le_pow_right (by norm_num) hs, hs⟩

/-- Blueprint Lemma 12.2 (`lem:coherence`), admissibility: for `j ≥ j_s` every center of `𝓡_s`
(denominator `q ∈ [2^{s-1}, 2^s)`) is allowed in `X_j`. -/
theorem isMajorCenter_of_mem_liftRat {s j a q : ℕ} (hj : coherJs n d Ω p s ≤ j)
    (h : (a, q) ∈ liftRat s) : IsMajorCenter (paramM n d Ω p) j a q := by
  obtain ⟨-, h2, h3, h4⟩ := mem_liftRat.1 h
  have hs : 2 ^ s ≤ minorH (paramM n d Ω p) j :=
    (two_pow_le_minorH_iff major_one_le_paramM s j).2 (le_trans (le_max_right _ _) hj)
  exact ⟨one_le_of_mem_liftRat h, lt_of_lt_of_le h2 hs, h3, h4⟩

/-- Blueprint Lemma 12.2 (`lem:coherence`), admissibility: if `s ≤ ⌊M log₂(j+1)⌋`, every center
of `𝓡_s` is allowed in `X_j`. -/
theorem isMajorCenter_of_le_majorExp {M s j a q : ℕ} (hs : s ≤ majorExp M j)
    (h : (a, q) ∈ liftRat s) : IsMajorCenter M j a q := by
  obtain ⟨-, h2, h3, h4⟩ := mem_liftRat.1 h
  have hs' : 2 ^ s ≤ minorH M j := by
    rw [minorH_eq_two_pow]; exact Nat.pow_le_pow_right (by norm_num) hs
  exact ⟨one_le_of_mem_liftRat h, lt_of_lt_of_le h2 hs', h3, h4⟩

/-- Blueprint Lemma 12.2 (`lem:coherence`), the unique major center: for `d ≥ 1`, `j ≥ j₀` and
`λ ∈ X_j` there is exactly one admissible `(a, q)` with `‖λ - a/q‖_𝕋 ≤ w_j`. -/
theorem minorArcs_center_unique (hd : 1 ≤ d) {j : ℕ} (hj : coherJ0 n d Ω p ≤ j) {lam : ℝ}
    (hlam : lam ∈ minorArcs d (paramM n d Ω p) j) :
    ∃! aq : ℕ × ℕ, IsMajorCenter (paramM n d Ω p) j aq.1 aq.2 ∧
      ‖((lam - aq.1 / aq.2 : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j := by
  obtain ⟨q, a, hq, hqH, ha, hc, hl⟩ := hlam
  refine ⟨(a, q), ⟨⟨hq, hqH, ha, hc⟩, hl⟩, fun aq haq => ?_⟩
  obtain ⟨h1, h2⟩ := ((coherJ0_spec hd).2 j hj).2.1 _ _ _ _ haq.1 ⟨hq, hqH, ha, hc⟩ lam haq.2 hl
  exact Prod.ext h1 h2

/-- Every reduced `a/q ∈ [0, 1)` lies in some `𝓡_s` (`s = ⌊log₂ q⌋ + 1`). -/
lemma exists_mem_liftRat {q : ℕ} (a : ℕ) (hq : 1 ≤ q) (ha : a < q) (hc : Nat.Coprime a q) :
    ∃ s, (a, q) ∈ liftRat s := by
  refine ⟨Nat.log 2 q + 1, mem_liftRat.2 ⟨?_, ?_, ha, hc⟩⟩
  · unfold liftN; rw [pow_succ, mul_comm]
    exact Nat.mul_le_mul_left 2 (Nat.pow_log_le_self 2 (by omega))
  · exact Nat.lt_pow_succ_log_self (by norm_num) q

/-- The sets `𝓡_s` are pairwise disjoint. -/
lemma eq_of_mem_liftRat {a q s s' : ℕ} (h : (a, q) ∈ liftRat s) (h' : (a, q) ∈ liftRat s') :
    s = s' := by
  obtain ⟨h1, h2, -, -⟩ := mem_liftRat.1 h
  obtain ⟨h1', h2', -, -⟩ := mem_liftRat.1 h'
  unfold liftN at h1 h2 h1' h2'
  have e1 : 2 ^ s < 2 ^ (s' + 1) := by rw [pow_succ]; omega
  have e2 : 2 ^ s' < 2 ^ (s + 1) := by rw [pow_succ]; omega
  have := (Nat.pow_lt_pow_iff_right (by norm_num : 1 < 2)).1 e1
  have := (Nat.pow_lt_pow_iff_right (by norm_num : 1 < 2)).1 e2
  omega

open Classical in
/-- The indices `j ∈ [j₀, J]` for which the major center of `λ` at scale `j` belongs to `𝓡_s`
(Blueprint Lemma 12.2 (`lem:coherence`)). -/
noncomputable def majorIdx (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) (s : ℕ)
    (lam : ℝ) (J : ℕ) : Finset ℕ :=
  (Finset.Icc (coherJ0 n d Ω p) J).filter fun j => ∃ aq ∈ liftRat s,
    aq.2 < minorH (paramM n d Ω p) j ∧
      ‖((lam - aq.1 / aq.2 : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j

/-- Membership in `majorIdx`. -/
lemma mem_majorIdx {s : ℕ} {lam : ℝ} {J j : ℕ} :
    j ∈ majorIdx n d Ω p s lam J ↔ coherJ0 n d Ω p ≤ j ∧ j ≤ J ∧ ∃ a q : ℕ, (a, q) ∈ liftRat s ∧
      q < minorH (paramM n d Ω p) j ∧
      ‖((lam - a / q : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j := by
  simp only [majorIdx, Finset.mem_filter, Finset.mem_Icc, Prod.exists, and_assoc]

/-- **Blueprint Lemma 12.2 (`lem:coherence`)**, interval coherence: for `d ≥ 1`, fixed `s`, `λ`
and finite upper scale `J`, either no `j ∈ [j₀, J]` has its major center in `𝓡_s`, or there are
one center `α = a/q ∈ 𝓡_s` (so `s ≥ 1`), one real representative `μ` of `λ - α` with
`|μ| < 1/4`, and `b ≤ J` such that the set of these indices is the interval `[j_s, b]`,
`j_s = max(j₀, ⌈2^{s/M}⌉ - 1)`, and for each such `j`: `a/q` is admissible in `X_j` and is the
unique major center of `λ` at scale `j`, `‖λ - α‖_𝕋 = |μ| ≤ w_j`, `|μ| 2^{Dj} ≤ (j+1)^M`
(`D = 2d`), and `L_s ≤ 2^{j/2}`. -/
theorem major_coherence (hd : 1 ≤ d) (s : ℕ) (lam : ℝ) (J : ℕ) :
    majorIdx n d Ω p s lam J = ∅ ∨
      ∃ (a q : ℕ) (μ : ℝ) (b : ℕ), (a, q) ∈ liftRat s ∧ 1 ≤ s ∧ |μ| < 1 / 4 ∧
        (∃ k : ℤ, lam = a / q + μ + k) ∧ b ≤ J ∧
        majorIdx n d Ω p s lam J = Finset.Icc (coherJs n d Ω p s) b ∧
        ∀ j ∈ majorIdx n d Ω p s lam J,
          IsMajorCenter (paramM n d Ω p) j a q ∧
          (∀ a' q' : ℕ, IsMajorCenter (paramM n d Ω p) j a' q' →
            ‖((lam - a' / q' : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j →
              a' = a ∧ q' = q) ∧
          ‖((lam - a / q : ℝ) : UnitAddCircle)‖ ≤ minorW d (paramM n d Ω p) j ∧
          |μ| ≤ minorW d (paramM n d Ω p) j ∧
          |μ| * (2 : ℝ) ^ (2 * d * j) ≤ ((j : ℝ) + 1) ^ paramM n d Ω p ∧
          (liftL n d Ω p s : ℝ) ≤ (2 : ℝ) ^ ((j : ℝ) / 2) := by
  rcases (majorIdx n d Ω p s lam J).eq_empty_or_nonempty with h | hne
  · exact Or.inl h
  right
  set M := paramM n d Ω p with hMdef
  set S := majorIdx n d Ω p s lam J with hSdef
  have hspec := coherJ0_spec (n := n) (Ω := Ω) (p := p) hd
  obtain ⟨jst, hjst⟩ := hne
  obtain ⟨hj0st, hjJst, a, q, haq, hqH, hδ⟩ := mem_majorIdx.1 hjst
  obtain ⟨hs1, -, -⟩ := liftRat_bounds_of_lt_minorH haq hqH
  obtain ⟨-, hq2, ha, hc⟩ := mem_liftRat.1 haq
  have hq1 : 1 ≤ q := one_le_of_mem_liftRat haq
  set δ := ‖((lam - a / q : ℝ) : UnitAddCircle)‖ with hδdef
  have hws : ∀ j, coherJ0 n d Ω p ≤ j → 2 ^ s ≤ minorH M j →
      minorW d M j ≤ (((2 : ℝ) ^ s) ^ 2)⁻¹ / 16 := by
    intro j hj hsH
    refine ((hspec.2 j hj).1.2.2).trans ?_
    have : ((2 : ℝ) ^ s) ≤ minorH M j := by exact_mod_cast hsH
    gcongr
  have hcenter : ∀ j ∈ S, ∀ a' q' : ℕ, (a', q') ∈ liftRat s → q' < minorH M j →
      ‖((lam - a' / q' : ℝ) : UnitAddCircle)‖ ≤ minorW d M j → a' = a ∧ q' = q := by
    intro j hj a' q' h' hq'H hδ'
    obtain ⟨hj0, -, -⟩ := mem_majorIdx.1 hj
    obtain ⟨-, hsH', -⟩ := liftRat_bounds_of_lt_minorH h' hq'H
    obtain ⟨-, hsHst, -⟩ := liftRat_bounds_of_lt_minorH haq hqH
    obtain ⟨-, hq2', ha', hc'⟩ := mem_liftRat.1 h'
    have e1 := hws j hj0 hsH'
    have e2 := hws jst hj0st hsHst
    have hpos : 0 < (((2 : ℝ) ^ s) ^ 2)⁻¹ := by positivity
    refine reduced_eq_of_norm_lt (one_le_of_mem_liftRat h') ha' hc' hq1 ha hc (B := 2 ^ s)
      (by unfold liftN at hq2'; exact_mod_cast hq2') (by unfold liftN at hq2; exact_mod_cast hq2) ?_
    calc ‖(((a' : ℝ) / q' - a / q : ℝ) : UnitAddCircle)‖ ≤ minorW d M j + minorW d M jst :=
          (norm_sub_centers_le lam _ _).trans (add_le_add hδ' hδ)
      _ < 1 / ((2 : ℝ) ^ s) ^ 2 := by rw [one_div]; linarith
  have hmem : ∀ j, j ∈ S ↔ coherJs n d Ω p s ≤ j ∧ j ≤ J ∧ δ ≤ minorW d M j := by
    intro j
    constructor
    · intro hj
      obtain ⟨hj0, hjJ, a', q', h', hq'H, hδ'⟩ := mem_majorIdx.1 hj
      obtain ⟨rfl, rfl⟩ := hcenter j hj a' q' h' hq'H hδ'
      obtain ⟨-, hsH, -⟩ := liftRat_bounds_of_lt_minorH haq hq'H
      exact ⟨max_le hj0 ((two_pow_le_minorH_iff major_one_le_paramM s j).1 hsH), hjJ, hδ'⟩
    · rintro ⟨hjs, hjJ, hδj⟩
      exact mem_majorIdx.2 ⟨le_trans (le_max_left _ _) hjs, hjJ, a, q, haq,
        (isMajorCenter_of_mem_liftRat hjs haq).2.1, hδj⟩
  set b := S.max' ⟨jst, hjst⟩ with hbdef
  have hb : b ∈ S := S.max'_mem _
  obtain ⟨hbs, hbJ, hδb⟩ := (hmem b).1 hb
  have hSI : S = Finset.Icc (coherJs n d Ω p s) b := by
    ext j
    rw [Finset.mem_Icc]
    constructor
    · intro hj; exact ⟨((hmem j).1 hj).1, S.le_max' j hj⟩
    · rintro ⟨hjs, hjb⟩
      refine (hmem j).2 ⟨hjs, hjb.trans hbJ, hδb.trans ?_⟩
      exact minorW_antitone hd (le_trans (le_max_left _ _) hjs) hjb
  set μ : ℝ := lam - a / q - round (lam - a / q) with hμdef
  have hμδ : |μ| = δ := by rw [hδdef, UnitAddCircle.norm_eq]
  refine ⟨a, q, μ, b, haq, hs1, ?_, ⟨round (lam - a / q), by rw [hμdef]; ring⟩, hbJ, hSI,
    fun j hj => ?_⟩
  · rw [hμδ]; exact lt_of_le_of_lt hδ (hspec.2 jst hj0st).1.1
  obtain ⟨hjs, hjJ, hδj⟩ := (hmem j).1 hj
  have hj0 : coherJ0 n d Ω p ≤ j := le_trans (le_max_left _ _) hjs
  have hadm : IsMajorCenter M j a q := isMajorCenter_of_mem_liftRat hjs haq
  obtain ⟨-, -, hsE⟩ := liftRat_bounds_of_lt_minorH haq hadm.2.1
  refine ⟨hadm, fun a' q' h' hδ' => ?_, hδj, hμδ ▸ hδj, ?_, ?_⟩
  · obtain ⟨h1, h2⟩ := (hspec.2 j hj0).2.1 _ _ _ _ h' hadm lam hδ' hδj
    exact ⟨h1, h2⟩
  · have h1 : |μ| ≤ minorW d M j := hμδ ▸ hδj
    rw [minorW, le_div_iff₀ (by positivity)] at h1
    exact h1
  · have hv := (hspec.2 j hj0).2.2 s hs1 hsE
    rw [liftL, Nat.cast_pow, Nat.cast_ofNat, ← Real.rpow_natCast]
    exact Real.rpow_le_rpow_of_exponent_le (by norm_num) hv

/-- For Blueprint Proposition 12.3: for `j ∈ [j₀, J]`, `λ ∈ X_j` iff `j` is a major index of `λ`
for some group `s`. -/
theorem mem_minorArcs_iff_exists_majorIdx {j J : ℕ} (hj0 : coherJ0 n d Ω p ≤ j) (hjJ : j ≤ J)
    (lam : ℝ) :
    lam ∈ minorArcs d (paramM n d Ω p) j ↔ ∃ s, j ∈ majorIdx n d Ω p s lam J := by
  constructor
  · rintro ⟨q, a, hq, hqH, ha, hc, hl⟩
    obtain ⟨s, hs⟩ := exists_mem_liftRat a hq ha hc
    exact ⟨s, mem_majorIdx.2 ⟨hj0, hjJ, a, q, hs, hqH, hl⟩⟩
  · rintro ⟨s, hs⟩
    obtain ⟨-, -, a, q, haq, hqH, hl⟩ := mem_majorIdx.1 hs
    obtain ⟨-, -, ha, hc⟩ := mem_liftRat.1 haq
    exact ⟨q, a, one_le_of_mem_liftRat haq, hqH, ha, hc, hl⟩

/-- For Blueprint Proposition 12.3: a major index belongs to exactly one group `s`. -/
theorem eq_of_mem_majorIdx (hd : 1 ≤ d) {s s' : ℕ} {lam : ℝ} {J j : ℕ}
    (h : j ∈ majorIdx n d Ω p s lam J) (h' : j ∈ majorIdx n d Ω p s' lam J) : s = s' := by
  obtain ⟨hj0, -, a, q, haq, hqH, hl⟩ := mem_majorIdx.1 h
  obtain ⟨-, -, a', q', haq', hqH', hl'⟩ := mem_majorIdx.1 h'
  obtain ⟨-, -, ha, hc⟩ := mem_liftRat.1 haq
  obtain ⟨-, -, ha', hc'⟩ := mem_liftRat.1 haq'
  obtain ⟨rfl, rfl⟩ := ((coherJ0_spec hd).2 j hj0).2.1 a q a' q'
    ⟨one_le_of_mem_liftRat haq, hqH, ha, hc⟩ ⟨one_le_of_mem_liftRat haq', hqH', ha', hc'⟩ lam hl hl'
  exact eq_of_mem_liftRat haq haq'

/-! ### Blueprint Proposition 12.3 (`prop:finiteSW`) -/

section FiniteSW

open scoped ENNReal

/-- A finitely supported function on `ℤⁿ` lies in every `ℓ^q`. -/
lemma finSW_memLp {f : (Fin n → ℤ) → ℂ} (hf : (Function.support f).Finite) (q : ℝ≥0∞) :
    MemLp f q Measure.count := by
  have hb : MemLp f ∞ Measure.count := by
    refine memLp_top_of_bound AEStronglyMeasurable.of_discrete (∑ z ∈ hf.toFinset, ‖f z‖)
      (ae_of_all _ fun x => ?_)
    by_cases hx : x ∈ Function.support f
    · exact Finset.single_le_sum (f := fun z => ‖f z‖) (fun _ _ => norm_nonneg _)
        (hf.mem_toFinset.2 hx)
    · rw [Function.notMem_support.1 hx, norm_zero]
      exact Finset.sum_nonneg fun _ _ => norm_nonneg _
  exact hb.mono_exponent_of_measure_support_ne_top (s := Function.support f)
    (fun x hx => Function.notMem_support.1 hx) (Measure.count_apply_lt_top.2 hf).ne le_top

/-- The `λ`-independent smoothing-error majorant `(1 + (j+1)^M) 2^{-j/2} (B_{2^j} * |f|)(x)` of the
proof of Blueprint Proposition 12.3 (`prop:finiteSW`). -/
noncomputable def finSWErr (n M j : ℕ) (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) : ℝ≥0∞ :=
  ENNReal.ofReal ((1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2))) *
    ∑' y, ENNReal.ofReal (latEnvelope n (2 ^ j) y) * ‖f (x - y)‖ₑ

/-- The smoothing error of the proof of Blueprint Proposition 12.3 (`prop:finiteSW`), from
Lemma 12.1: if `λ = a/q + μ` in `𝕋`, `|μ| 2^{Dj} ≤ (j+1)^M` and `L_s ≤ 2^{j/2}`, then
`|T_{j,λ} f - Lift_{s,a/q}[Φ_{j,μ}] f| ≤ C (1 + (j+1)^M) 2^{-j/2} (B_{2^j} * |f|)` pointwise. -/
lemma finSW_kernel_error (hΩ : IsSWProfile Ω) (d : ℕ) :
    ∃ Ck : ℝ, 0 ≤ Ck ∧ ∀ (p : ℝ) (s a q : ℕ), 1 ≤ q → ∀ (j M : ℕ) (lam μ : ℝ),
      (∃ k : ℤ, lam = a / q + μ + k) → |μ| * (2 : ℝ) ^ (2 * d * j) ≤ ((j : ℝ) + 1) ^ M →
      (liftL n d Ω p s : ℝ) ≤ (2 : ℝ) ^ ((j : ℝ) / 2) →
      ∀ f : (Fin n → ℤ) → ℂ, Summable (fun z => ‖f z‖) → ∀ x,
        ‖minorOp Ω d j lam f x -
            latMult (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) f x‖ₑ ≤
          ENNReal.ofReal Ck * finSWErr n M j f x := by
  obtain ⟨C, hC, hK⟩ := major_kernel_error (n := n) hΩ d
  refine ⟨C, hC, fun p s a q hq j M lam μ hlam hμ hL f hf x => ?_⟩
  rw [major_kernel_formula hΩ p s a hq j hlam hf x, finSWErr, ← mul_assoc,
    ← ENNReal.ofReal_mul hC, ← ENNReal.tsum_mul_left]
  refine enorm_tsum_le_tsum_enorm.trans (ENNReal.tsum_le_tsum fun y => ?_)
  set U : ℝ := ((j : ℝ) + 1) ^ M with hUdef
  have hU0 : 0 ≤ U := by positivity
  have hU : |μ| * ((2 : ℝ) ^ j) ^ (2 * d) ≤ U := by
    rw [← pow_mul, mul_comm j]; exact hμ
  have hk := hK p s j μ U hU (latEmbed y)
  have hR : (0 : ℝ) < 2 ^ j := by positivity
  have hB : 0 ≤ latEnvelope n (2 ^ j) y := envelope_nonneg hR _
  have hLR : (liftL n d Ω p s : ℝ) / 2 ^ j ≤ (2 : ℝ) ^ (-((j : ℝ) / 2)) := by
    rw [div_le_iff₀ hR, ← Real.rpow_natCast, ← Real.rpow_add two_pos]
    convert hL using 2; ring
  rw [enorm_mul, enorm_mul, ← ofReal_norm (eC _), norm_eC, ENNReal.ofReal_one, one_mul,
    ← ofReal_norm, ← mul_assoc, ← ENNReal.ofReal_mul (by positivity)]
  gcongr
  calc _ ≤ C * (1 + U) * ((liftL n d Ω p s : ℝ) / 2 ^ j) * envelope n (2 ^ j) (latEmbed y) := hk
    _ ≤ C * (1 + U) * (2 : ℝ) ^ (-((j : ℝ) / 2)) * envelope n (2 ^ j) (latEmbed y) := by
        gcongr
    _ = _ := by rw [latEnvelope]; ring

/-- `ℓ^p` bound of the smoothing-error majorant (Young and the uniform lattice sum of `B_{2^j}`). -/
lemma eLpNorm_finSWErr_le {p : ℝ} (hp : 1 < p) (M j : ℕ) (f : (Fin n → ℤ) → ℂ) :
    eLpNorm (finSWErr n M j f) (ENNReal.ofReal p) Measure.count ≤
      ENNReal.ofReal ((1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)) * envelopeConst n) *
        eLpNorm f (ENNReal.ofReal p) Measure.count := by
  have hp1 : (1 : ℝ≥0∞) ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hp.le
  have hR : (0 : ℝ) < 2 ^ j := by positivity
  have hB : ∀ y, 0 ≤ latEnvelope n (2 ^ j) y := fun y => envelope_nonneg hR _
  have hk : ∀ y, ‖((latEnvelope n (2 ^ j) y : ℝ) : ℂ)‖ₑ = ENNReal.ofReal (latEnvelope n (2 ^ j) y) :=
    fun y => by rw [← ofReal_norm, Complex.norm_real, Real.norm_of_nonneg (hB y)]
  have e : finSWErr n M j f = fun x =>
      ENNReal.ofReal ((1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2))) *
        ∑' y, ‖((latEnvelope n (2 ^ j) y : ℝ) : ℂ)‖ₑ * ‖f (x - y)‖ₑ := by
    funext x; simp only [finSWErr, hk]
  rw [e, eLpNorm_count_const_mul _ _ (by linarith)]
  refine (mul_le_mul' le_rfl (eLpNorm_tsum_enorm_mul_sub_le hp1 _ f)).trans ?_
  rw [ENNReal.ofReal_mul (p := (1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)))
    (by positivity), mul_assoc]
  refine mul_le_mul' le_rfl (mul_le_mul' ?_ le_rfl)
  rw [eLpNorm_one_eq_lintegral_enorm AEStronglyMeasurable.of_discrete, lintegral_count]
  obtain ⟨hs, hle⟩ := summable_latEnvelope_and_tsum_le (n := n) (R := 2 ^ j)
    (one_le_pow₀ one_le_two)
  simp only [hk]
  rw [← ENNReal.ofReal_tsum_of_nonneg hB hs]
  exact ENNReal.ofReal_le_ofReal hle

/-- The smoothing-error coefficients `(1 + (j+1)^M) 2^{-j/2}` are summable. -/
lemma finSW_summable_err (M : ℕ) :
    Summable fun j : ℕ => (1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)) := by
  obtain ⟨r, hr⟩ : ∃ r : ℝ, r = (2 : ℝ) ^ (-(1 / 2 : ℝ)) := ⟨_, rfl⟩
  have hr0 : 0 < r := by rw [hr]; positivity
  have hr1 : r < 1 := by
    rw [hr]; exact Real.rpow_lt_one_of_one_lt_of_neg (by norm_num) (by norm_num)
  have e : ∀ j : ℕ, (2 : ℝ) ^ (-((j : ℝ) / 2)) = r ^ j := by
    intro j; rw [hr, ← Real.rpow_mul_natCast (by norm_num)]; congr 1; ring
  have h1 : Summable fun j : ℕ => ((j + 1 : ℕ) : ℝ) ^ M * r ^ (j + 1) :=
    (summable_nat_add_iff (f := fun j : ℕ => (j : ℝ) ^ M * r ^ j) 1).2
      (summable_pow_mul_geometric_of_norm_lt_one M
      (by rw [Real.norm_of_nonneg hr0.le]; exact hr1))
  have h2 := summable_geometric_of_lt_one hr0.le hr1
  refine (h2.add (h1.mul_left r⁻¹)).congr fun j => ?_
  rw [e j, pow_succ]
  push_cast
  field_simp

/-- `j ↦ ⌊M log₂(j+1)⌋` is monotone. -/
lemma majorExp_mono (M : ℕ) {j j' : ℕ} (h : j ≤ j') : majorExp M j ≤ majorExp M j' := by
  unfold majorExp
  apply Nat.floor_mono
  have : (j : ℝ) ≤ j' := by exact_mod_cast h
  exact mul_le_mul_of_nonneg_left
    (Real.logb_le_logb_of_le (by norm_num) (by positivity) (by linarith)) (Nat.cast_nonneg _)

/-- The group majorant of the proof of Blueprint Proposition 12.3 (`prop:finiteSW`): `𝒫_s f` for
`s ≥ 1`, and `0` for `s = 0`. -/
noncomputable def finSWMain (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (p : ℝ) (s : ℕ)
    (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) : ℝ≥0∞ :=
  if 1 ≤ s then liftedPartialMax n d Ω p s f x else 0

open Classical in
/-- The pointwise majorant of the proof of Blueprint Proposition 12.3 (`prop:finiteSW`): for every
`λ`, `|∑_{j=j₀}^J T_{j,λ} f(x)|` is at most the sum of the minor-arc maximal functions
`sup_{λ' ∉ X_j} |T_{j,λ'} f(x)|`, the smoothing errors, and the group majorants `𝒫_s f(x)`
(a majorant independent of `λ`). -/
lemma finSW_pointwise (hn : 1 ≤ n) (hd : 1 ≤ d) (hΩ : IsSWProfile Ω) {Ck : ℝ}
    (hCk : ∀ (s a q : ℕ), 1 ≤ q → ∀ (j : ℕ) (lam μ : ℝ),
      (∃ k : ℤ, lam = a / q + μ + k) →
      |μ| * (2 : ℝ) ^ (2 * d * j) ≤ ((j : ℝ) + 1) ^ paramM n d Ω p →
      (liftL n d Ω p s : ℝ) ≤ (2 : ℝ) ^ ((j : ℝ) / 2) →
      ∀ f : (Fin n → ℤ) → ℂ, Summable (fun z => ‖f z‖) → ∀ x,
        ‖minorOp Ω d j lam f x -
            latMult (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) f x‖ₑ ≤
          ENNReal.ofReal Ck * finSWErr n (paramM n d Ω p) j f x)
    (J : ℕ) {f : (Fin n → ℤ) → ℂ} (hf : Summable fun z => ‖f z‖) (lam : ℝ) (x : Fin n → ℤ) :
    ‖∑ j ∈ Finset.Icc (coherJ0 n d Ω p) J, minorOp Ω d j lam f x‖ₑ ≤
      ∑ j ∈ Finset.Icc (coherJ0 n d Ω p) J,
          minorSup Ω d j (minorArcs d (paramM n d Ω p) j) f x +
        ∑ j ∈ Finset.Icc (coherJ0 n d Ω p) J,
          ENNReal.ofReal Ck * finSWErr n (paramM n d Ω p) j f x +
        ∑' s, finSWMain n d Ω p s f x := by
  set M := paramM n d Ω p with hMdef
  set A := Finset.Icc (coherJ0 n d Ω p) J with hAdef
  set N := minorH M J + 1 with hNdef
  have hj1 : 1 ≤ coherJ0 n d Ω p := (one_le_paramJ1 hn hd hΩ p).trans (coherJ0_spec hd).1
  have hMaj : A.filter (fun j => lam ∈ minorArcs d M j) =
      (Finset.range N).biUnion (fun s => majorIdx n d Ω p s lam J) := by
    ext j
    simp only [Finset.mem_filter, Finset.mem_biUnion, Finset.mem_range]
    constructor
    · rintro ⟨hjA, hl⟩
      obtain ⟨hj0, hjJ⟩ := Finset.mem_Icc.1 hjA
      obtain ⟨s, hs⟩ := (mem_minorArcs_iff_exists_majorIdx hj0 hjJ lam).1 hl
      refine ⟨s, ?_, hs⟩
      obtain ⟨-, -, a, q, haq, hqH, -⟩ := mem_majorIdx.1 hs
      obtain ⟨-, h2, -⟩ := liftRat_bounds_of_lt_minorH haq hqH
      have h3 : minorH M j ≤ minorH M J := by
        rw [minorH_eq_two_pow, minorH_eq_two_pow]
        exact Nat.pow_le_pow_right (by norm_num) (majorExp_mono M hjJ)
      have h2' : 2 ^ s ≤ minorH M j := h2
      have := Nat.lt_two_pow_self (n := s)
      omega
    · rintro ⟨s, -, hs⟩
      obtain ⟨hj0, hjJ, -⟩ := mem_majorIdx.1 hs
      exact ⟨Finset.mem_Icc.2 ⟨hj0, hjJ⟩,
        (mem_minorArcs_iff_exists_majorIdx hj0 hjJ lam).2 ⟨s, hs⟩⟩
  have hdisj : (↑(Finset.range N) : Set ℕ).PairwiseDisjoint
      (fun s => majorIdx n d Ω p s lam J) := by
    intro s _ s' _ hne
    exact Finset.disjoint_left.2 fun j h h' => hne (eq_of_mem_majorIdx hd h h')
  have hgroup : ∀ s, ‖∑ j ∈ majorIdx n d Ω p s lam J, minorOp Ω d j lam f x‖ₑ ≤
      ∑ j ∈ majorIdx n d Ω p s lam J, ENNReal.ofReal Ck * finSWErr n M j f x +
        finSWMain n d Ω p s f x := by
    intro s
    rcases major_coherence (n := n) (Ω := Ω) (p := p) hd s lam J with
      h | ⟨a, q, μ, b, haq, hs1, -, hlam, -, hI, hprop⟩
    · rw [h, Finset.sum_empty, Finset.sum_empty, enorm_zero]; exact zero_le
    have hq : 1 ≤ q := one_le_of_mem_liftRat haq
    have hsplit : ∑ j ∈ majorIdx n d Ω p s lam J, minorOp Ω d j lam f x =
        ∑ j ∈ majorIdx n d Ω p s lam J, (minorOp Ω d j lam f x -
          latMult (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) f x) +
        ∑ j ∈ Finset.Icc (coherJs n d Ω p s) b,
          latMult (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) f x := by
      rw [← hI, ← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun j _ => by ring
    rw [hsplit]
    refine (enorm_add_le _ _).trans (add_le_add ?_ ?_)
    · refine (enorm_sum_le _ _).trans (Finset.sum_le_sum fun j hj => ?_)
      obtain ⟨-, -, -, -, hμj, hLj⟩ := hprop j hj
      exact hCk s a q hq j lam μ hlam hμj hLj f hf x
    · by_cases hab : coherJs n d Ω p s ≤ b
      · have hlin : ∑ j ∈ Finset.Icc (coherJs n d Ω p s) b,
            latMult (liftSym n d Ω p s a q (radialOscPhi Ω d j μ)) f x =
            latMult (liftSym n d Ω p s a q (fun ξ => ∑ j ∈ Finset.Icc (coherJs n d Ω p s) b,
              radialOscPhi Ω d j μ ξ)) f x :=
          (latMult_liftSym_finsetSum _ (m := fun j : ℕ => radialOscPhi Ω d j μ)
            (fun j => (continuous_radialOscPhi_and_le hΩ j μ).1)
            (fun j ξ => (continuous_radialOscPhi_and_le hΩ j μ).2 ξ) hf x).symm
        rw [hlin]; simp only [finSWMain, hs1, ↓reduceIte]
        exact le_iSup₂_of_le (a, q) haq (le_iSup_of_le μ (le_iSup_of_le (coherJs n d Ω p s)
          (le_iSup_of_le b (le_iSup_of_le ⟨hj1.trans (le_max_left _ _), hab⟩ le_rfl))))
      · rw [Finset.Icc_eq_empty hab, Finset.sum_empty, enorm_zero]; exact zero_le
  have hA := Finset.sum_filter_add_sum_filter_not A (fun j => lam ∈ minorArcs d M j)
    (fun j => minorOp Ω d j lam f x)
  rw [← hA]
  refine (enorm_add_le _ _).trans ?_
  have hmaj : ‖∑ j ∈ A.filter (fun j => lam ∈ minorArcs d M j), minorOp Ω d j lam f x‖ₑ ≤
      ∑ j ∈ A, ENNReal.ofReal Ck * finSWErr n M j f x + ∑' s, finSWMain n d Ω p s f x := by
    rw [hMaj, Finset.sum_biUnion hdisj]
    refine (enorm_sum_le _ _).trans ((Finset.sum_le_sum fun s _ => hgroup s).trans ?_)
    rw [Finset.sum_add_distrib, ← Finset.sum_biUnion hdisj, ← hMaj]
    exact add_le_add (Finset.sum_le_sum_of_subset (Finset.filter_subset _ _))
      (ENNReal.sum_le_tsum _)
  have hmin : ‖∑ j ∈ A.filter (fun j => lam ∉ minorArcs d M j), minorOp Ω d j lam f x‖ₑ ≤
      ∑ j ∈ A, minorSup Ω d j (minorArcs d M j) f x := by
    refine (enorm_sum_le _ _).trans ((Finset.sum_le_sum fun j hj => ?_).trans
      (Finset.sum_le_sum_of_subset (Finset.filter_subset _ _)))
    exact le_iSup₂_of_le (f := fun (l : ℝ) (_ : l ∉ minorArcs d M j) => ‖minorOp Ω d j l f x‖ₑ)
      lam (Finset.mem_filter.1 hj).2 le_rfl
  calc _ ≤ (∑ j ∈ A, ENNReal.ofReal Ck * finSWErr n M j f x + ∑' s, finSWMain n d Ω p s f x) +
        ∑ j ∈ A, minorSup Ω d j (minorArcs d M j) f x := add_le_add hmaj hmin
    _ = _ := by ring

/-- `ℓ^p` bound of the group majorant: `‖𝒫_s f‖_p ≤ C ρ^s ‖f‖_p`, `ρ = 2^{-c}` (Theorem 11.3). -/
lemma eLpNorm_finSWMain_le (hn : 1 ≤ n) (hd : 1 ≤ d) (hΩ : IsSWProfile Ω) (hp : 1 < p) :
    ∃ c : ℝ, 0 < c ∧ ∃ C : ℝ, 0 ≤ C ∧ ∀ s : ℕ, ∀ f : (Fin n → ℤ) → ℂ,
      (Function.support f).Finite →
        eLpNorm (finSWMain n d Ω p s f) (ENNReal.ofReal p) Measure.count ≤
          ENNReal.ofReal (C * ((2 : ℝ) ^ (-c)) ^ s) *
            eLpNorm f (ENNReal.ofReal p) Measure.count := by
  obtain ⟨c, hc, C, hC, hP⟩ := lift_partial_sums hn hd hΩ hp
  refine ⟨c, hc, C, hC, fun s f hf => ?_⟩
  by_cases hs : 1 ≤ s
  · have e : finSWMain n d Ω p s f = liftedPartialMax n d Ω p s f := by
      funext x; simp only [finSWMain, hs, ↓reduceIte]
    rw [e, ← Real.rpow_natCast, ← Real.rpow_mul (by norm_num), neg_mul]
    exact hP s hs f hf
  · have e : finSWMain n d Ω p s f = 0 := by
      funext x; simp only [finSWMain, hs, ↓reduceIte, Pi.zero_apply]
    rw [e, eLpNorm_zero]; exact zero_le

/-- **Blueprint Proposition 12.3 (`prop:finiteSW`)**, uniform finite dyadic estimate, eq. (12.2)
(`eq:finiteSW`): for `n, d ≥ 1`, an admissible profile `Ω` and `1 < p < ∞`, with the final lower
scale `j₀ = coherJ0 n d Ω p` of Lemma 12.2, there is `C_p ≥ 0` such that for every integer
`J ≥ j₀` and every finitely supported `f : ℤⁿ → ℂ`,
`‖sup_{λ ∈ 𝕋} |∑_{j=j₀}^J T_{j,λ} f|‖_{ℓ^p} ≤ C_p ‖f‖_{ℓ^p}`
(`C_p` independent of `J` and `f`; the supremum is over `λ ∈ ℝ`, which is the same as over `𝕋`
since `T_{j,λ}` is `1`-periodic in `λ`). -/
theorem finite_dyadic_stein_wainger (hn : 1 ≤ n) (hd : 1 ≤ d) (hΩ : IsSWProfile Ω)
    (hp : 1 < p) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ J ≥ coherJ0 n d Ω p, ∀ f : (Fin n → ℤ) → ℂ,
      (Function.support f).Finite →
        eLpNorm (fun x => ⨆ lam : ℝ,
            ‖∑ j ∈ Finset.Icc (coherJ0 n d Ω p) J, minorOp Ω d j lam f x‖ₑ)
            (ENNReal.ofReal p) Measure.count ≤
          ENNReal.ofReal C * eLpNorm f (ENNReal.ofReal p) Measure.count := by
  obtain ⟨Cm, hCm, hmin⟩ := minor_arc_decay_lp hn hd hΩ hp
  obtain ⟨Ck, hCk, herr⟩ := finSW_kernel_error (n := n) hΩ d
  obtain ⟨c, hc, CP, hCP, hP⟩ := eLpNorm_finSWMain_le hn hd hΩ hp
  set M := paramM n d Ω p with hMdef
  set j₀ := coherJ0 n d Ω p with hj₀
  set ρ : ℝ := (2 : ℝ) ^ (-c) with hρ
  have hρ0 : 0 ≤ ρ := by positivity
  have hρ1 : ρ < 1 := Real.rpow_lt_one_of_one_lt_of_neg (by norm_num) (by linarith)
  have hsum1 : Summable fun j : ℕ => (j : ℝ) ^ (-2 : ℝ) := Real.summable_nat_rpow.2 (by norm_num)
  have hsum2 := finSW_summable_err M
  set S1 := ∑' j : ℕ, (j : ℝ) ^ (-2 : ℝ) with hS1def
  set S2 := ∑' j : ℕ, (1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)) with hS2def
  have hS1 : 0 ≤ S1 := tsum_nonneg fun j => by positivity
  have hS2 : 0 ≤ S2 := tsum_nonneg fun j => by positivity
  have hE0 : 0 ≤ envelopeConst n := by unfold envelopeConst; positivity
  have hρ' : 0 ≤ (1 - ρ)⁻¹ := inv_nonneg.2 (by linarith)
  refine ⟨Cm * S1 + Ck * envelopeConst n * S2 + CP * (1 - ρ)⁻¹, by positivity,
    fun J hJ f hf => ?_⟩
  set nf := eLpNorm f (ENNReal.ofReal p) Measure.count with hnf
  have hp1 : (1 : ℝ≥0∞) ≤ ENNReal.ofReal p := by
    rw [← ENNReal.ofReal_one]; exact ENNReal.ofReal_le_ofReal hp.le
  have hf1 : Summable fun z => ‖f z‖ := summable_of_finite_support hf
  have hfL := finSW_memLp hf (ENNReal.ofReal p)
  set A := Finset.Icc j₀ J with hAdef
  set G1 : (Fin n → ℤ) → ℝ≥0∞ := ∑ j ∈ A, fun x => minorSup Ω d j (minorArcs d M j) f x
    with hG1
  set G2 : (Fin n → ℤ) → ℝ≥0∞ := ∑ j ∈ A, fun x => ENNReal.ofReal Ck * finSWErr n M j f x
    with hG2
  set G3 : (Fin n → ℤ) → ℝ≥0∞ := fun x => ∑' s, finSWMain n d Ω p s f x with hG3
  have hpt : ∀ x, ‖⨆ lam : ℝ, ‖∑ j ∈ A, minorOp Ω d j lam f x‖ₑ‖ₑ ≤ ‖(G1 + G2 + G3) x‖ₑ := by
    intro x
    rw [enorm_eq_self, enorm_eq_self]
    simp only [hG1, hG2, hG3, Pi.add_apply, Finset.sum_apply]
    exact iSup_le fun lam => finSW_pointwise hn hd hΩ
      (fun s a q hq j lam μ hlam hμ hL f hf x => herr p s a q hq j M lam μ hlam hμ hL f hf x)
      J hf1 lam x
  have h1 : eLpNorm G1 (ENNReal.ofReal p) Measure.count ≤ ENNReal.ofReal (Cm * S1) * nf := by
    refine (eLpNorm_sum_le hp1).trans ?_
    calc ∑ j ∈ A, eLpNorm (fun x => minorSup Ω d j (minorArcs d M j) f x)
          (ENNReal.ofReal p) Measure.count
        ≤ ∑ j ∈ A, ENNReal.ofReal (Cm * (j : ℝ) ^ (-2 : ℝ)) * nf :=
          Finset.sum_le_sum fun j hj =>
            hmin j ((coherJ0_spec hd).1.trans (Finset.mem_Icc.1 hj).1) f hfL
      _ = ENNReal.ofReal (∑ j ∈ A, Cm * (j : ℝ) ^ (-2 : ℝ)) * nf := by
          rw [← Finset.sum_mul, ENNReal.ofReal_sum_of_nonneg (fun j _ => by positivity)]
      _ ≤ _ := by
          gcongr
          rw [← Finset.mul_sum]
          gcongr
          exact hsum1.sum_le_tsum A (fun j _ => by positivity)
  have h2 : eLpNorm G2 (ENNReal.ofReal p) Measure.count ≤
      ENNReal.ofReal (Ck * envelopeConst n * S2) * nf := by
    refine (eLpNorm_sum_le hp1).trans ?_
    calc ∑ j ∈ A, eLpNorm (fun x => ENNReal.ofReal Ck * finSWErr n M j f x)
          (ENNReal.ofReal p) Measure.count
        ≤ ∑ j ∈ A, ENNReal.ofReal (Ck * envelopeConst n *
            ((1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)))) * nf := by
          refine Finset.sum_le_sum fun j _ => ?_
          rw [eLpNorm_count_const_mul _ _ (by linarith)]
          refine (mul_le_mul' le_rfl (eLpNorm_finSWErr_le hp M j f)).trans (le_of_eq ?_)
          rw [← mul_assoc, ← ENNReal.ofReal_mul hCk]
          congr 2; ring
      _ = ENNReal.ofReal (∑ j ∈ A, Ck * envelopeConst n *
            ((1 + ((j : ℝ) + 1) ^ M) * (2 : ℝ) ^ (-((j : ℝ) / 2)))) * nf := by
          rw [← Finset.sum_mul, ENNReal.ofReal_sum_of_nonneg (fun j _ => by positivity)]
      _ ≤ _ := by
          gcongr
          rw [← Finset.mul_sum]
          gcongr
          exact hsum2.sum_le_tsum A (fun j _ => by positivity)
  have h3 : eLpNorm G3 (ENNReal.ofReal p) Measure.count ≤
      ENNReal.ofReal (CP * (1 - ρ)⁻¹) * nf := by
    refine (eLpNorm_tsum_le_count hp1 ENNReal.ofReal_ne_top _).trans ?_
    refine (ENNReal.tsum_le_tsum fun s => hP s f hf).trans (le_of_eq ?_)
    rw [ENNReal.tsum_mul_right, ← ENNReal.ofReal_tsum_of_nonneg (fun s => by positivity)
      ((summable_geometric_of_lt_one hρ0 hρ1).mul_left _), tsum_mul_left,
      tsum_geometric_of_lt_one hρ0 hρ1]
  calc eLpNorm (fun x => ⨆ lam : ℝ, ‖∑ j ∈ A, minorOp Ω d j lam f x‖ₑ)
        (ENNReal.ofReal p) Measure.count
      ≤ eLpNorm (G1 + G2 + G3) (ENNReal.ofReal p) Measure.count :=
        eLpNorm_mono_enorm AEStronglyMeasurable.of_discrete hpt
    _ ≤ eLpNorm G1 (ENNReal.ofReal p) Measure.count +
          eLpNorm G2 (ENNReal.ofReal p) Measure.count +
          eLpNorm G3 (ENNReal.ofReal p) Measure.count :=
        (eLpNorm_add_le hp1).trans (add_le_add (eLpNorm_add_le hp1) le_rfl)
    _ ≤ ENNReal.ofReal (Cm * S1) * nf + ENNReal.ofReal (Ck * envelopeConst n * S2) * nf +
          ENNReal.ofReal (CP * (1 - ρ)⁻¹) * nf := by gcongr
    _ = _ := by
        rw [ENNReal.ofReal_add (by positivity) (by positivity),
          ENNReal.ofReal_add (by positivity) (by positivity)]
        ring

end FiniteSW

end Auto
