/- Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license.
This file was automatically generated by Claude.
-/
import DiscreteSW.Auto.Oscillation

/-!
# Sampling and finite Fourier bookkeeping

Results from §6 ("Sampling and finite Fourier bookkeeping") of `blueprints/discrete-sw.tex`,
together with the lattice/torus Fourier conventions of §1.2 used by all later sections.

## Conventions (Mathlib sign)

`E = EuclideanSpace ℝ (Fin n)`, `G = Fin n → ℤ`, `ι = latEmbed`. Torus symbols are functions
`m : E → ℂ` (typically `ι(G)`-periodic), integrated over the unit cube
`torusCube n = [0,1)ⁿ` with `volume` (mass one, `volume_torusCube`).
* `latFT f ξ = ∑_z f(z) e(-z · ξ)` (the blueprint's `f̂` with `ξ ↦ -ξ`);
* `latKernel m y = ∫_{[0,1)ⁿ} m(ξ) e(y · ξ) dξ` (inverse Fourier coefficients);
* `latMult m f x = ∫_{[0,1)ⁿ} m(ξ) f̂(ξ) e(x · ξ) dξ` (the multiplier `m(D)`);
* `periodize m ξ = ∑_k m(ξ - k)`;
* `latModulate β f x = e(x · β) f(x)` (the modulation `M_β` of eq. (1.1)).

## Torus infrastructure

* `isAddFundamentalDomain_torusCube`: `[0,1)ⁿ` is a fundamental domain of the lattice
  (`torusLattice n`, identified with `range latEmbed` by `mem_torusLattice`);
  `setIntegral_torusCube_comp_add` (translation invariance of torus integrals of periodic
  functions), `hasSum_setIntegral_torusCube_add`/`_sub` (tiling `E` by lattice translates),
  `locallyIntegrable_of_periodic`.
* (0a) `integral_torusCube_eC`: `∫ e(k · ξ) = δ_{k0}`.
* (0b) `latMult_eq_latConv`: `m(D) f = m̌ * f` for `f ∈ ℓ¹`, `m` integrable on the torus.
* (0c) `latKernel_latFT`: Fourier inversion for `u ∈ ℓ¹`.
* (0d) `integral_latFT_mul_conj`, `integral_norm_sq_latFT`: Parseval for `u, v ∈ ℓ¹`.
* (0e) `summable_and_tsum_norm_sq_latMult_le`: `‖m(D) f‖_{ℓ²} ≤ A ‖f‖_{ℓ²}` for `|m| ≤ A`
  (Bessel's inequality for the orthonormal characters `torusChar`).

## Blueprint Lemma 6.1 (`lem:fourierbook`)

* periodization: `periodize_add_latEmbed`, `integrableOn_periodize`,
  `locallyIntegrable_periodize`, `latKernel_periodize` (`(m_per)ˇ(y) = 𝓕⁻ m (y)`);
* rapid decrease: `exists_norm_fourierInv_latEmbed_le`, `summable_norm_fourierInv_latEmbed`
  (Schwartz `m`), `fourierInv_latEmbed_rapidDecay_of_hasCompactSupport` (smooth compactly
  supported `m`);
* modulation (1.1): `latMult_comp_sub` (`[m(· - β)](D) = M_β m(D) M_{-β}` in the Mathlib sign);
* products: `latFT_mul_eq_integral` (`(uv)^ = û * v̂` on the torus), `latFT_mul_eq_zero_of_not_mem`,
  `latFT_prod_eq_zero_of_not_mem` (Fourier support of a product is in `S_1 + ⋯ + S_l + ℤⁿ`),
  `latFT_conj_eq_zero_of_not_mem` (conjugation reflects supports), `tsum_prod_eq_zero`,
  `tsum_mul_conj_eq_zero`, `tsum_prod_mul_conj_prod_eq_zero` (orthogonality).
-/

namespace Auto

open MeasureTheory Set Real
open scoped Pointwise ComplexConjugate FourierTransform ContDiff SchwartzMap

variable {n : ℕ}

/-! ### The unit cube and the lattice -/

/-- The unit cube `[0,1)ⁿ ⊂ E`, a fundamental domain of `ι(G)`; torus integrals are taken over it
with respect to `volume` (mass one, `volume_torusCube`). -/
def torusCube (n : ℕ) : Set (EuclideanSpace ℝ (Fin n)) := {ξ | ∀ i, 0 ≤ ξ i ∧ ξ i < 1}

/-- The lattice `ι(G) = ℤⁿ ⊂ E` as the `ℤ`-span of the standard basis (used to access Mathlib's
fundamental-domain API; `mem_torusLattice` identifies it with the range of `latEmbed`). -/
noncomputable def torusLattice (n : ℕ) : Submodule ℤ (EuclideanSpace ℝ (Fin n)) :=
  Submodule.span ℤ (range (EuclideanSpace.basisFun (Fin n) ℝ).toBasis)

instance : Countable (torusLattice n) := by unfold torusLattice; infer_instance

/-- `v ∈ ι(G)` iff `v = ι k` for some `k ∈ ℤⁿ`. -/
lemma mem_torusLattice {v : EuclideanSpace ℝ (Fin n)} :
    v ∈ torusLattice n ↔ ∃ k : Fin n → ℤ, latEmbed k = v := by
  unfold torusLattice
  rw [Module.Basis.mem_span_iff_repr_mem]
  simp only [OrthonormalBasis.coe_toBasis_repr_apply, EuclideanSpace.basisFun_repr,
    algebraMap_int_eq, eq_intCast, mem_range]
  constructor
  · intro h
    choose k hk using h
    exact ⟨k, PiLp.ext fun i => by simp [hk i]⟩
  · rintro ⟨k, rfl⟩ i
    exact ⟨k i, by simp⟩

lemma latEmbed_injective : Function.Injective (latEmbed (n := n)) := by
  intro k j h
  funext i
  have := congrArg (fun v : EuclideanSpace ℝ (Fin n) => v i) h
  simpa using this

/-- The bijection `ℤⁿ ≃ ι(ℤⁿ)`. -/
noncomputable def latEquiv (n : ℕ) : (Fin n → ℤ) ≃ torusLattice n :=
  Equiv.ofBijective (fun k => ⟨latEmbed k, mem_torusLattice.2 ⟨k, rfl⟩⟩)
    ⟨fun k j h => latEmbed_injective (congrArg Subtype.val h),
     fun l => by obtain ⟨k, hk⟩ := mem_torusLattice.1 l.2; exact ⟨k, Subtype.ext hk⟩⟩

@[simp] lemma coe_latEquiv (k : Fin n → ℤ) : ((latEquiv n k : torusLattice n) :
    EuclideanSpace ℝ (Fin n)) = latEmbed k := rfl

lemma torusCube_eq_fundamentalDomain :
    torusCube n = ZSpan.fundamentalDomain (EuclideanSpace.basisFun (Fin n) ℝ).toBasis := by
  ext ξ; simp [torusCube, ZSpan.mem_fundamentalDomain]

/-- `[0,1)ⁿ` is a fundamental domain for `ι(G)` acting on `E` by translation. -/
lemma isAddFundamentalDomain_torusCube :
    IsAddFundamentalDomain (torusLattice n) (torusCube n) volume := by
  rw [torusCube_eq_fundamentalDomain]; exact ZSpan.isAddFundamentalDomain _ _

lemma measurableSet_torusCube : MeasurableSet (torusCube n) := by
  rw [torusCube_eq_fundamentalDomain]; exact ZSpan.fundamentalDomain_measurableSet _

/-- The torus `[0,1)ⁿ` has mass one. -/
lemma volume_torusCube : volume (torusCube n) = 1 := by
  have h : torusCube n = (WithLp.ofLp (p := 2)) ⁻¹' Set.pi univ (fun _ : Fin n => Ico (0 : ℝ) 1) := by
    ext ξ; simp [torusCube]
  rw [h, (PiLp.volume_preserving_ofLp (Fin n)).measure_preimage
    (MeasurableSet.univ_pi fun _ => measurableSet_Ico).nullMeasurableSet]
  simp [volume_pi, Measure.pi_pi]

instance : VAddInvariantMeasure (torusLattice n) (EuclideanSpace ℝ (Fin n)) volume :=
  inferInstanceAs <| VAddInvariantMeasure (torusLattice n).toAddSubgroup _ _

instance : IsFiniteMeasure (volume.restrict (torusCube n)) :=
  isFiniteMeasure_restrict.2 (by rw [volume_torusCube]; exact ENNReal.one_ne_top)

lemma inner_latEmbed_latEmbed (k j : Fin n → ℤ) :
    inner ℝ (latEmbed k) (latEmbed j) = ((∑ i, k i * j i : ℤ) : ℝ) := by
  simp [PiLp.inner_apply, mul_comm]

/-- `e(k · j) = 1` for `k, j ∈ ℤⁿ`. -/
lemma eC_inner_latEmbed_latEmbed (k j : Fin n → ℤ) :
    eC (inner ℝ (latEmbed k) (latEmbed j)) = 1 := by
  rw [inner_latEmbed_latEmbed, eC_intCast]

/-- Integrals of `ι(G)`-periodic functions over `[0,1)ⁿ` are translation invariant. -/
theorem setIntegral_torusCube_comp_add {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]
    {g : EuclideanSpace ℝ (Fin n) → F} (hg : ∀ ξ (k : Fin n → ℤ), g (ξ + latEmbed k) = g ξ)
    (a : EuclideanSpace ℝ (Fin n)) :
    ∫ ξ in torusCube n, g (ξ + a) = ∫ ξ in torusCube n, g ξ := by
  have hinv : ∀ (l : torusLattice n) (x : EuclideanSpace ℝ (Fin n)), g (l +ᵥ x) = g x := by
    intro l x
    obtain ⟨k, hk⟩ := mem_torusLattice.1 l.2
    change g ((l : EuclideanSpace ℝ (Fin n)) + x) = g x
    rw [← hk, add_comm, hg]
  have h1 := (isAddFundamentalDomain_torusCube.vadd_of_comm a).setIntegral_eq
    isAddFundamentalDomain_torusCube hinv
  rw [← h1, ← Set.image_vadd]
  simp only [vadd_eq_add]
  rw [(measurePreserving_add_left volume a).setIntegral_image_emb (measurableEmbedding_addLeft a)]
  simp_rw [add_comm a]

/-- Tiling `E` by the translates of `[0,1)ⁿ`: for integrable `F`,
`∑_{k ∈ ℤⁿ} ∫_{[0,1)ⁿ} F(ξ + k) dξ = ∫_E F`, with absolute convergence. -/
theorem hasSum_setIntegral_torusCube_add {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]
    [CompleteSpace F] {g : EuclideanSpace ℝ (Fin n) → F} (hg : Integrable g) :
    HasSum (fun k : Fin n → ℤ => ∫ ξ in torusCube n, g (ξ + latEmbed k)) (∫ ξ, g ξ) := by
  have hfd := isAddFundamentalDomain_torusCube (n := n)
  have hl := hfd.lintegral_eq_tsum'' (fun x => ‖g x‖ₑ)
  have hi := hfd.integral_eq_tsum'' g hg
  have hv : ∀ (l : torusLattice n) (x : EuclideanSpace ℝ (Fin n)),
      l +ᵥ x = x + (l : EuclideanSpace ℝ (Fin n)) := fun l x => add_comm _ _
  simp_rw [hv] at hl hi
  rw [← (latEquiv n).tsum_eq] at hl hi
  simp only [coe_latEquiv] at hl hi
  rw [hi]
  refine Summable.hasSum ?_
  have hfin : ∑' k : Fin n → ℤ, ∫⁻ ξ in torusCube n, ‖g (ξ + latEmbed k)‖ₑ ≠ ⊤ := by
    rw [← hl]; exact hg.2.ne
  refine Summable.of_norm_bounded (ENNReal.summable_toReal hfin) fun k => ?_
  rw [← toReal_enorm]
  exact ENNReal.toReal_mono (ne_top_of_le_ne_top hfin (ENNReal.le_tsum (f := fun k : Fin n → ℤ =>
      ∫⁻ ξ in torusCube n, ‖g (ξ + latEmbed k)‖ₑ) k))
    (enorm_integral_le_lintegral_enorm _)

/-! ### Characters -/

@[fun_prop] lemma continuous_eC : Continuous eC := by unfold eC; fun_prop

lemma eC_zero : eC 0 = 1 := by simp [eC]

lemma eC_neg (t : ℝ) : eC (-t) = (eC t)⁻¹ := by
  unfold eC; rw [← Complex.exp_neg]; congr 1; push_cast; ring

lemma latEmbed_zero : latEmbed (0 : Fin n → ℤ) = 0 := by
  ext i; simp

lemma latEmbed_add (k j : Fin n → ℤ) : latEmbed (k + j) = latEmbed k + latEmbed j := by
  ext i; simp

lemma latEmbed_neg (k : Fin n → ℤ) : latEmbed (-k) = -latEmbed k := by
  ext i; simp

lemma latEmbed_sub (k j : Fin n → ℤ) : latEmbed (k - j) = latEmbed k - latEmbed j := by
  ext i; simp

/-- The character `ξ ↦ e(k · ξ)` is `ι(G)`-periodic. -/
lemma eC_inner_add_latEmbed (y k : Fin n → ℤ) (ξ : EuclideanSpace ℝ (Fin n)) :
    eC (inner ℝ (latEmbed y) (ξ + latEmbed k)) = eC (inner ℝ (latEmbed y) ξ) := by
  rw [inner_add_right, eC_add, eC_inner_latEmbed_latEmbed, mul_one]

/-- Blueprint §1.2, orthogonality of characters on `𝕋ⁿ = [0,1)ⁿ`:
`∫_{[0,1)ⁿ} e(k · ξ) dξ = 1` if `k = 0` and `0` otherwise. -/
theorem integral_torusCube_eC (k : Fin n → ℤ) :
    ∫ ξ in torusCube n, eC (inner ℝ (latEmbed k) ξ) = if k = 0 then 1 else 0 := by
  split_ifs with hk
  · subst hk
    simp [latEmbed_zero, eC_zero, measureReal_def, volume_torusCube]
  · obtain ⟨i, hi⟩ : ∃ i, k i ≠ 0 := by
      by_contra h; push Not at h; exact hk (funext h)
    set a : EuclideanSpace ℝ (Fin n) := EuclideanSpace.single i (1 / (2 * (k i : ℝ)))
    have hki : (k i : ℝ) ≠ 0 := by exact_mod_cast hi
    have ha : inner ℝ (latEmbed k) a = 1 / 2 := by
      simp only [a, EuclideanSpace.inner_single_right, latEmbed_apply, conj_trivial]
      field_simp
    have hhalf : eC (1 / 2) = -1 := by
      unfold eC
      rw [show (2 * (π : ℂ) * Complex.I * ((1 / 2 : ℝ) : ℂ)) = π * Complex.I by push_cast; ring]
      exact Complex.exp_pi_mul_I
    have h := setIntegral_torusCube_comp_add (g := fun ξ => eC (inner ℝ (latEmbed k) ξ))
      (fun ξ j => eC_inner_add_latEmbed k j ξ) a
    simp only [inner_add_right, eC_add, ha, hhalf, integral_mul_const] at h
    linear_combination (-(1 / 2 : ℂ)) * h

/-! ### Lattice Fourier transform, kernels, multipliers, periodization -/

/-- The lattice Fourier transform `f̂(ξ) = ∑_{z ∈ ℤⁿ} f(z) e(-z · ξ)` (Mathlib sign; `ι(G)`-periodic
in `ξ`). It is a genuine (absolutely convergent) series for `f ∈ ℓ¹`. -/
noncomputable def latFT (f : (Fin n → ℤ) → ℂ) (ξ : EuclideanSpace ℝ (Fin n)) : ℂ :=
  ∑' z, f z * eC (-(inner ℝ (latEmbed z) ξ))

/-- The inverse Fourier coefficients `m̌(y) = ∫_{[0,1)ⁿ} m(ξ) e(y · ξ) dξ` of a torus symbol `m`. -/
noncomputable def latKernel (m : EuclideanSpace ℝ (Fin n) → ℂ) (y : Fin n → ℤ) : ℂ :=
  ∫ ξ in torusCube n, m ξ * eC (inner ℝ (latEmbed y) ξ)

/-- The lattice Fourier multiplier `m(D) f(x) = ∫_{[0,1)ⁿ} m(ξ) f̂(ξ) e(x · ξ) dξ`. -/
noncomputable def latMult (m : EuclideanSpace ℝ (Fin n) → ℂ) (f : (Fin n → ℤ) → ℂ)
    (x : Fin n → ℤ) : ℂ :=
  ∫ ξ in torusCube n, m ξ * latFT f ξ * eC (inner ℝ (latEmbed x) ξ)

/-- The periodization `m_per(ξ) = ∑_{k ∈ ℤⁿ} m(ξ - k)` of a Euclidean symbol `m`. -/
noncomputable def periodize (m : EuclideanSpace ℝ (Fin n) → ℂ) (ξ : EuclideanSpace ℝ (Fin n)) :
    ℂ :=
  ∑' k : Fin n → ℤ, m (ξ - latEmbed k)

/-- The modulation `M_β f(x) = e(x · β) f(x)` on `ℤⁿ` (blueprint eq. (1.1)). -/
noncomputable def latModulate (β : EuclideanSpace ℝ (Fin n)) (f : (Fin n → ℤ) → ℂ)
    (x : Fin n → ℤ) : ℂ :=
  eC (inner ℝ (latEmbed x) β) * f x

lemma norm_latFT_term (f : (Fin n → ℤ) → ℂ) (ξ : EuclideanSpace ℝ (Fin n)) (z : Fin n → ℤ) :
    ‖f z * eC (-(inner ℝ (latEmbed z) ξ))‖ = ‖f z‖ := by
  rw [norm_mul, norm_eC, mul_one]

lemma summable_latFT_term {f : (Fin n → ℤ) → ℂ} (hf : Summable fun z => ‖f z‖)
    (ξ : EuclideanSpace ℝ (Fin n)) :
    Summable fun z => f z * eC (-(inner ℝ (latEmbed z) ξ)) :=
  Summable.of_norm (by simpa only [norm_latFT_term] using hf)

/-- `‖f̂(ξ)‖ ≤ ‖f‖₁`. -/
lemma norm_latFT_le {f : (Fin n → ℤ) → ℂ} (hf : Summable fun z => ‖f z‖)
    (ξ : EuclideanSpace ℝ (Fin n)) : ‖latFT f ξ‖ ≤ ∑' z, ‖f z‖ := by
  refine (norm_tsum_le_tsum_norm ?_).trans (le_of_eq ?_)
  · simpa only [norm_latFT_term] using hf
  · simp only [norm_latFT_term]

/-- `f̂` is continuous for `f ∈ ℓ¹`. -/
lemma continuous_latFT {f : (Fin n → ℤ) → ℂ} (hf : Summable fun z => ‖f z‖) :
    Continuous (latFT f) :=
  continuous_tsum (fun z => by fun_prop [continuous_eC]) hf
    fun z ξ => le_of_eq (norm_latFT_term f ξ z)

/-- `f̂` is `ι(G)`-periodic. -/
lemma latFT_add_latEmbed (f : (Fin n → ℤ) → ℂ) (ξ : EuclideanSpace ℝ (Fin n))
    (k : Fin n → ℤ) : latFT f (ξ + latEmbed k) = latFT f ξ := by
  unfold latFT
  congr 1; funext z
  rw [eC_neg, eC_neg, eC_inner_add_latEmbed]

/-- `(M_β f)^(ξ) = f̂(ξ - β)`. -/
lemma latFT_latModulate (β : EuclideanSpace ℝ (Fin n)) (f : (Fin n → ℤ) → ℂ)
    (ξ : EuclideanSpace ℝ (Fin n)) : latFT (latModulate β f) ξ = latFT f (ξ - β) := by
  unfold latFT latModulate
  congr 1; funext z
  rw [inner_sub_right, show ∀ a b : ℝ, -(a - b) = b + -a from fun a b => by ring, eC_add]
  ring

/-- Conjugation reflects the Fourier transform: `(f̄)^(ξ) = conj (f̂(-ξ))`. -/
lemma latFT_conj (f : (Fin n → ℤ) → ℂ) (ξ : EuclideanSpace ℝ (Fin n)) :
    latFT (fun x => conj (f x)) ξ = conj (latFT f (-ξ)) := by
  unfold latFT
  rw [Complex.conj_tsum]
  congr 1; funext z
  simp only [map_mul, conj_eC, inner_neg_right, neg_neg]

/-- `∑_x f(x) = f̂(0)`. -/
lemma tsum_eq_latFT_zero (f : (Fin n → ℤ) → ℂ) : ∑' x, f x = latFT f 0 := by
  simp [latFT, eC_zero]

/-- Exchange of the lattice sum defining `f̂` with a torus integral: for `f ∈ ℓ¹` and `h`
integrable on `[0,1)ⁿ`, `∫ f̂ h = ∑_z f(z) ∫ e(-z · ξ) h(ξ) dξ`. -/
theorem integral_latFT_mul {f : (Fin n → ℤ) → ℂ} (hf : Summable fun z => ‖f z‖)
    {h : EuclideanSpace ℝ (Fin n) → ℂ} (hh : IntegrableOn h (torusCube n)) :
    ∫ ξ in torusCube n, latFT f ξ * h ξ =
      ∑' z, f z * ∫ ξ in torusCube n, eC (-(inner ℝ (latEmbed z) ξ)) * h ξ := by
  have hint : ∀ z : Fin n → ℤ, Integrable
      (fun ξ => f z * eC (-(inner ℝ (latEmbed z) ξ)) * h ξ) (volume.restrict (torusCube n)) :=
    fun z => hh.bdd_mul (c := ‖f z‖) (by fun_prop [continuous_eC])
      (Filter.Eventually.of_forall fun ξ => le_of_eq (norm_latFT_term f ξ z))
  have hnorm : ∀ z : Fin n → ℤ, ∫ ξ in torusCube n,
      ‖f z * eC (-(inner ℝ (latEmbed z) ξ)) * h ξ‖ = ‖f z‖ * ∫ ξ in torusCube n, ‖h ξ‖ := by
    intro z
    simp_rw [norm_mul, norm_eC, mul_one]
    exact integral_const_mul _ _
  have := integral_tsum_of_summable_integral_norm hint
    (by simp_rw [hnorm]; exact hf.mul_right _)
  simp_rw [latFT, ← tsum_mul_right]
  rw [← this]
  congr 1; funext z
  simp_rw [mul_assoc]
  exact integral_const_mul _ _


/-! ### Fourier bookkeeping on `𝕋ⁿ`: inversion, kernels, Parseval, the `ℓ²` bound -/

lemma integrableOn_torusCube_of_bound {F : Type*} [NormedAddCommGroup F]
    {g : EuclideanSpace ℝ (Fin n) → F}
    (hg : AEStronglyMeasurable g (volume.restrict (torusCube n))) (C : ℝ)
    (hC : ∀ ξ ∈ torusCube n, ‖g ξ‖ ≤ C) : IntegrableOn g (torusCube n) :=
  Integrable.of_bound hg C (ae_restrict_of_forall_mem measurableSet_torusCube hC)

lemma integrableOn_eC_inner (y : Fin n → ℤ) (s : ℝ) :
    IntegrableOn (fun ξ => eC (s * inner ℝ (latEmbed y) ξ)) (torusCube n) :=
  integrableOn_torusCube_of_bound (by fun_prop) 1 fun ξ _ => le_of_eq (norm_eC _)

/-- Orthogonality in the form `∫ e(-z · ξ) e(y · ξ) dξ = δ_{zy}`. -/
lemma integral_torusCube_eC_neg_mul_eC (z y : Fin n → ℤ) :
    ∫ ξ in torusCube n, eC (-(inner ℝ (latEmbed z) ξ)) * eC (inner ℝ (latEmbed y) ξ) =
      if z = y then 1 else 0 := by
  have : ∀ ξ, eC (-(inner ℝ (latEmbed z) ξ)) * eC (inner ℝ (latEmbed y) ξ) =
      eC (inner ℝ (latEmbed (y - z)) ξ) := fun ξ => by
    rw [← eC_add, latEmbed_sub, inner_sub_left]; ring_nf
  simp_rw [this, integral_torusCube_eC, sub_eq_zero, eq_comm]

/-- Fourier inversion on `ℤⁿ` (bookkeeping fact (0c)): for `u ∈ ℓ¹`, the inverse Fourier
coefficients of `û` are `u`, i.e. `∫_{[0,1)ⁿ} û(ξ) e(y · ξ) dξ = u(y)`. -/
theorem latKernel_latFT {u : (Fin n → ℤ) → ℂ} (hu : Summable fun z => ‖u z‖) :
    latKernel (latFT u) = u := by
  funext y
  unfold latKernel
  rw [integral_latFT_mul hu (by simpa using integrableOn_eC_inner y 1)]
  simp_rw [integral_torusCube_eC_neg_mul_eC, mul_ite, mul_one, mul_zero]
  exact tsum_ite_eq y u

/-- Bookkeeping fact (0b): for `f ∈ ℓ¹` (in particular finitely supported `f`) and a symbol `m`
integrable on `[0,1)ⁿ` (in particular bounded and measurable), `m(D) f = m̌ * f`, where
`m̌ = latKernel m`. -/
theorem latMult_eq_latConv {m : EuclideanSpace ℝ (Fin n) → ℂ} (hm : IntegrableOn m (torusCube n))
    {f : (Fin n → ℤ) → ℂ} (hf : Summable fun z => ‖f z‖) :
    latMult m f = latConv (latKernel m) f := by
  funext x
  have hmx : IntegrableOn (fun ξ => m ξ * eC (inner ℝ (latEmbed x) ξ)) (torusCube n) := by
    have := hm.bdd_mul (f := fun ξ => eC (inner ℝ (latEmbed x) ξ)) (c := 1) (by fun_prop)
      (Filter.Eventually.of_forall fun ξ => le_of_eq (norm_eC _))
    simp only [mul_comm] at this; exact this
  have h1 : latMult m f x = ∫ ξ in torusCube n, latFT f ξ * (m ξ * eC (inner ℝ (latEmbed x) ξ)) := by
    unfold latMult; congr 1; funext ξ; ring
  rw [h1, integral_latFT_mul hf hmx, latConv, ← (Equiv.subLeft x).tsum_eq]
  congr 1; funext z
  simp only [Equiv.subLeft_apply, latKernel]
  rw [mul_comm]
  congr 1; congr 1; funext ξ
  rw [latEmbed_sub, inner_sub_left, neg_sub, mul_left_comm, ← eC_add, sub_add_cancel]

/-- Parseval on `ℤⁿ`, polarized form (bookkeeping fact (0d)): for `u, v ∈ ℓ¹`,
`∫_{[0,1)ⁿ} û · conj v̂ = ∑_x u(x) conj (v(x))`. -/
theorem integral_latFT_mul_conj {u v : (Fin n → ℤ) → ℂ} (hu : Summable fun z => ‖u z‖)
    (hv : Summable fun z => ‖v z‖) :
    ∫ ξ in torusCube n, latFT u ξ * conj (latFT v ξ) = ∑' x, u x * conj (v x) := by
  have hint : IntegrableOn (fun ξ => conj (latFT v ξ)) (torusCube n) :=
    integrableOn_torusCube_of_bound
      (Complex.continuous_conj.comp (continuous_latFT hv)).aestronglyMeasurable
      (∑' z, ‖v z‖) fun ξ _ => by rw [Complex.norm_conj]; exact norm_latFT_le hv ξ
  rw [integral_latFT_mul hu hint]
  congr 1; funext z
  congr 1
  have : ∀ ξ, eC (-(inner ℝ (latEmbed z) ξ)) * conj (latFT v ξ) =
      conj (latFT v ξ * eC (inner ℝ (latEmbed z) ξ)) := fun ξ => by
    rw [map_mul, conj_eC, mul_comm]
  simp_rw [this]
  rw [integral_conj, ← latKernel, latKernel_latFT hv]

/-- Parseval on `ℤⁿ` (bookkeeping fact (0d)): for `u ∈ ℓ¹`, `∫_{[0,1)ⁿ} |û|² = ∑_x |u(x)|²`. -/
theorem integral_norm_sq_latFT {u : (Fin n → ℤ) → ℂ} (hu : Summable fun z => ‖u z‖) :
    ∫ ξ in torusCube n, ‖latFT u ξ‖ ^ 2 = ∑' x, ‖u x‖ ^ 2 := by
  have h := integral_latFT_mul_conj hu hu
  simp_rw [Complex.mul_conj'] at h
  have h2 : ((∫ ξ in torusCube n, ‖latFT u ξ‖ ^ 2 : ℝ) : ℂ) = ((∑' x, ‖u x‖ ^ 2 : ℝ) : ℂ) := by
    rw [Complex.ofReal_tsum, ← integral_complex_ofReal]; push_cast; exact h
  exact_mod_cast h2


/-- The characters `ξ ↦ e(y · ξ)` as elements of `L²([0,1)ⁿ)`. -/
noncomputable def torusChar (n : ℕ) (y : Fin n → ℤ) :
    Lp ℂ 2 (volume.restrict (torusCube n)) :=
  (MemLp.of_bound (by fun_prop) 1 (Filter.Eventually.of_forall fun ξ =>
    le_of_eq (norm_eC (inner ℝ (latEmbed y) ξ)))).toLp (fun ξ => eC (inner ℝ (latEmbed y) ξ))

/-- The characters `e(y · ξ)`, `y ∈ ℤⁿ`, are orthonormal in `L²([0,1)ⁿ)`. -/
lemma orthonormal_torusChar : Orthonormal ℂ (torusChar n) := by
  rw [orthonormal_iff_ite]
  intro z y
  rw [L2.inner_def, ← integral_torusCube_eC_neg_mul_eC z y]
  refine integral_congr_ae ?_
  filter_upwards [MemLp.coeFn_toLp (μ := volume.restrict (torusCube n)) (p := 2)
      (f := fun ξ => eC (inner ℝ (latEmbed z) ξ)) (MemLp.of_bound (by fun_prop) 1
        (Filter.Eventually.of_forall fun ξ => le_of_eq (norm_eC _))),
    MemLp.coeFn_toLp (μ := volume.restrict (torusCube n)) (p := 2)
      (f := fun ξ => eC (inner ℝ (latEmbed y) ξ)) (MemLp.of_bound (by fun_prop) 1
        (Filter.Eventually.of_forall fun ξ => le_of_eq (norm_eC _)))] with ξ hz hy
  simp only [torusChar] at *
  rw [hz, hy, RCLike.inner_apply', conj_eC]

/-- Bookkeeping fact (0e), the `ℓ²` bound for lattice multipliers: if `m` is a.e. strongly
measurable on `[0,1)ⁿ` with `|m| ≤ A` there, then for `f ∈ ℓ¹` (in particular finitely supported
`f`), `x ↦ m(D) f(x)` is square summable and `∑_x |m(D) f(x)|² ≤ A² ∑_x |f(x)|²`. -/
theorem summable_and_tsum_norm_sq_latMult_le {m : EuclideanSpace ℝ (Fin n) → ℂ} {A : ℝ}
    (hm : AEStronglyMeasurable m (volume.restrict (torusCube n)))
    (hA : ∀ ξ ∈ torusCube n, ‖m ξ‖ ≤ A) {f : (Fin n → ℤ) → ℂ} (hf : Summable fun z => ‖f z‖) :
    Summable (fun x => ‖latMult m f x‖ ^ 2) ∧
      ∑' x, ‖latMult m f x‖ ^ 2 ≤ A ^ 2 * ∑' x, ‖f x‖ ^ 2 := by
  set μ := volume.restrict (torusCube n)
  set B := ∑' z, ‖f z‖
  have hg_meas : AEStronglyMeasurable (fun ξ => m ξ * latFT f ξ) μ :=
    hm.mul (continuous_latFT hf).aestronglyMeasurable
  have hbound : ∀ ξ ∈ torusCube n, ‖m ξ * latFT f ξ‖ ≤ A * ‖latFT f ξ‖ := fun ξ hξ => by
    rw [norm_mul]; exact mul_le_mul_of_nonneg_right (hA ξ hξ) (norm_nonneg _)
  have hgL : MemLp (fun ξ => m ξ * latFT f ξ) 2 μ :=
    MemLp.of_bound hg_meas (|A| * B) (ae_restrict_of_forall_mem measurableSet_torusCube
      fun ξ hξ => (hbound ξ hξ).trans (mul_le_mul (le_abs_self A) (norm_latFT_le hf ξ)
        (norm_nonneg _) (abs_nonneg A)))
  set g := hgL.toLp
  have hcoe := hgL.coeFn_toLp
  -- the inner products are the values of `m(D) f`
  have hinner : ∀ y, inner ℂ (torusChar n y) g = latMult m f (-y) := by
    intro y
    rw [L2.inner_def, latMult]
    refine integral_congr_ae ?_
    filter_upwards [hcoe, MemLp.coeFn_toLp (μ := μ) (p := 2)
      (f := fun ξ => eC (inner ℝ (latEmbed y) ξ)) (MemLp.of_bound (by fun_prop) 1
        (Filter.Eventually.of_forall fun ξ => le_of_eq (norm_eC _)))] with ξ hg hy
    simp only [torusChar] at *
    rw [hg, hy, RCLike.inner_apply', conj_eC, latEmbed_neg, inner_neg_left]
    ring
  -- the norm of `g`
  have hnorm : ‖g‖ ^ 2 = ∫ ξ in torusCube n, ‖m ξ * latFT f ξ‖ ^ 2 := by
    rw [@norm_sq_eq_re_inner ℂ, L2.inner_def]
    have : ∫ ξ, (inner ℂ (g ξ) (g ξ) : ℂ) ∂μ =
        ((∫ ξ in torusCube n, ‖m ξ * latFT f ξ‖ ^ 2 : ℝ) : ℂ) := by
      rw [← integral_complex_ofReal]
      refine integral_congr_ae ?_
      filter_upwards [hcoe] with ξ hξ
      rw [hξ, inner_self_eq_norm_sq_to_K]; push_cast; rfl
    rw [this]; exact Complex.ofReal_re _
  have hle : ∫ ξ in torusCube n, ‖m ξ * latFT f ξ‖ ^ 2 ≤
      ∫ ξ in torusCube n, A ^ 2 * ‖latFT f ξ‖ ^ 2 := by
    refine integral_mono_of_nonneg (Filter.Eventually.of_forall fun ξ => sq_nonneg _) ?_ ?_
    · refine integrableOn_torusCube_of_bound
        ((continuous_const.mul ((continuous_latFT hf).norm.pow 2)).aestronglyMeasurable)
        (A ^ 2 * B ^ 2) fun ξ _ => ?_
      rw [Real.norm_of_nonneg (by positivity)]
      gcongr
      exact norm_latFT_le hf ξ
    · refine ae_restrict_of_forall_mem measurableSet_torusCube fun ξ hξ => ?_
      show ‖m ξ * latFT f ξ‖ ^ 2 ≤ A ^ 2 * ‖latFT f ξ‖ ^ 2
      rw [← mul_pow]
      exact pow_le_pow_left₀ (norm_nonneg _) (hbound ξ hξ) 2
  have hparse := integral_norm_sq_latFT hf
  have hsum := (orthonormal_torusChar (n := n)).inner_products_summable g
  have htsum := (orthonormal_torusChar (n := n)).tsum_inner_products_le g
  simp_rw [hinner] at hsum htsum
  refine ⟨(Equiv.neg _).summable_iff.1 hsum, ?_⟩
  rw [← (Equiv.neg (Fin n → ℤ)).tsum_eq]
  refine htsum.trans ?_
  rw [hnorm, ← hparse, ← integral_const_mul]
  exact hle


/-! ### Blueprint Lemma 6.1, periodization -/

/-- Integrability of a pointwise series from summability of the `L¹` norms (in `[0, ∞]`). -/
theorem integrable_tsum_of_lintegral_ne_top {α F : Type*} [MeasurableSpace α] {μ : Measure α}
    [NormedAddCommGroup F] [CompleteSpace F] {ι : Type*} [Countable ι] {g : ι → α → F}
    (hg : ∀ i, AEStronglyMeasurable (g i) μ) (hfin : ∑' i, ∫⁻ a, ‖g i a‖ₑ ∂μ ≠ ⊤) :
    Integrable (fun a => ∑' i, g i a) μ := by
  have hmeas : ∀ i, AEMeasurable (fun a => ‖g i a‖ₑ) μ := fun i => (hg i).enorm
  have hlt : ∫⁻ a, ∑' i, ‖g i a‖ₑ ∂μ ≠ ⊤ := by rwa [lintegral_tsum hmeas]
  have hae : ∀ᵐ a ∂μ, ∑' i, ‖g i a‖ₑ ≠ ⊤ :=
    (ae_lt_top' (AEMeasurable.tsum hmeas) hlt).mono fun a h => h.ne
  have hsum : ∀ᵐ a ∂μ, Summable fun i => g i a := by
    filter_upwards [hae] with a ha
    refine Summable.of_norm ?_
    have : Summable fun i => (‖g i a‖₊ : ℝ) := by
      simp_rw [enorm_eq_nnnorm] at ha
      exact NNReal.summable_coe.2 (ENNReal.tsum_coe_ne_top_iff_summable.1 ha)
    simpa using this
  have hmeas' : AEStronglyMeasurable (fun a => ∑' i, g i a) μ := by
    refine aestronglyMeasurable_of_tendsto_ae (Filter.atTop : Filter (Finset ι))
      (f := fun s a => ∑ i ∈ s, g i a) (fun s => Finset.aestronglyMeasurable_fun_sum s
        fun i _ => hg i) ?_
    filter_upwards [hsum] with a ha
    exact ha.hasSum
  refine ⟨hmeas', ?_⟩
  exact lt_of_le_of_lt (lintegral_mono fun a => enorm_tsum_le_tsum_enorm) (lt_top_iff_ne_top.2 hlt)

/-- Tiling with `ξ - k` in place of `ξ + k`. -/
theorem hasSum_setIntegral_torusCube_sub {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]
    [CompleteSpace F] {g : EuclideanSpace ℝ (Fin n) → F} (hg : Integrable g) :
    HasSum (fun k : Fin n → ℤ => ∫ ξ in torusCube n, g (ξ - latEmbed k)) (∫ ξ, g ξ) := by
  rw [← (Equiv.neg (Fin n → ℤ)).hasSum_iff]
  convert hasSum_setIntegral_torusCube_add hg using 3 with k ξ
  simp [latEmbed_neg, sub_eq_add_neg]

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), periodization: `m_per` is `ι(G)`-periodic. -/
theorem periodize_add_latEmbed (m : EuclideanSpace ℝ (Fin n) → ℂ)
    (ξ : EuclideanSpace ℝ (Fin n)) (j : Fin n → ℤ) :
    periodize m (ξ + latEmbed j) = periodize m ξ := by
  rw [periodize, ← (Equiv.addLeft j).tsum_eq]
  simp only [Equiv.coe_addLeft, latEmbed_add, periodize]
  congr 1; funext k; congr 1; abel

lemma integrableOn_comp_sub_latEmbed {m : EuclideanSpace ℝ (Fin n) → ℂ} (hm : Integrable m)
    (k : Fin n → ℤ) : IntegrableOn (fun ξ => m (ξ - latEmbed k)) (torusCube n) :=
  (hm.comp_sub_right (latEmbed k)).integrableOn

lemma tsum_lintegral_torusCube_ne_top {m : EuclideanSpace ℝ (Fin n) → ℂ} (hm : Integrable m) :
    ∑' k : Fin n → ℤ, ∫⁻ ξ in torusCube n, ‖m (ξ - latEmbed k)‖ₑ ≠ ⊤ := by
  have h := isAddFundamentalDomain_torusCube.lintegral_eq_tsum'' (fun x => ‖m x‖ₑ)
  have hv : ∀ (l : torusLattice n) (x : EuclideanSpace ℝ (Fin n)),
      l +ᵥ x = x + (l : EuclideanSpace ℝ (Fin n)) := fun l x => add_comm _ _
  simp_rw [hv] at h
  rw [← (latEquiv n).tsum_eq, ← (Equiv.neg (Fin n → ℤ)).tsum_eq] at h
  simp only [coe_latEquiv, Equiv.neg_apply, latEmbed_neg, ← sub_eq_add_neg] at h
  rw [← h]; exact hm.2.ne

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), periodization: for integrable `m`, `m_per` is
integrable on the torus `[0,1)ⁿ`. -/
theorem integrableOn_periodize {m : EuclideanSpace ℝ (Fin n) → ℂ} (hm : Integrable m) :
    IntegrableOn (periodize m) (torusCube n) :=
  integrable_tsum_of_lintegral_ne_top (fun k => (integrableOn_comp_sub_latEmbed hm k).1)
    (tsum_lintegral_torusCube_ne_top hm)

/-- An `ι(G)`-periodic function integrable on `[0,1)ⁿ` is locally integrable on `E`. -/
theorem locallyIntegrable_of_periodic {F : Type*} [NormedAddCommGroup F]
    {g : EuclideanSpace ℝ (Fin n) → F} (hg : ∀ ξ (k : Fin n → ℤ), g (ξ + latEmbed k) = g ξ)
    (hint : IntegrableOn g (torusCube n)) : LocallyIntegrable g := by
  have hinv : ∀ (l : torusLattice n) (x : EuclideanSpace ℝ (Fin n)), g (l +ᵥ x) = g x := by
    intro l x
    obtain ⟨k, hk⟩ := mem_torusLattice.1 l.2
    change g ((l : EuclideanSpace ℝ (Fin n)) + x) = g x
    rw [← hk, add_comm, hg]
  intro x
  set c : EuclideanSpace ℝ (Fin n) := WithLp.toLp 2 (fun _ => (1 / 2 : ℝ))
  refine ⟨(x - c) +ᵥ torusCube n, ?_, ?_⟩
  · refine Filter.mem_of_superset (Metric.ball_mem_nhds x (by norm_num : (0 : ℝ) < 1 / 2)) ?_
    intro ξ hξ
    rw [Set.mem_vadd_set_iff_neg_vadd_mem, vadd_eq_add]
    intro i
    have hi : |ξ i - x i| < 1 / 2 := by
      have := PiLp.norm_apply_le (ξ - x) i
      rw [Metric.mem_ball, dist_eq_norm] at hξ
      simp only [PiLp.sub_apply, Real.norm_eq_abs] at this
      linarith
    simp only [PiLp.add_apply, PiLp.neg_apply, PiLp.sub_apply, c]
    constructor <;> linarith [abs_lt.1 hi]
  · exact ((isAddFundamentalDomain_torusCube.vadd_of_comm (x - c)).integrableOn_iff
      isAddFundamentalDomain_torusCube hinv).2 hint

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), periodization: for integrable `m`, `m_per` is
locally integrable on `E`. -/
theorem locallyIntegrable_periodize {m : EuclideanSpace ℝ (Fin n) → ℂ} (hm : Integrable m) :
    LocallyIntegrable (periodize m) :=
  locallyIntegrable_of_periodic (periodize_add_latEmbed m) (integrableOn_periodize hm)

lemma fourierChar_eq_eC (t : ℝ) : ((𝐞 t : Circle) : ℂ) = eC t := by
  rw [Real.fourierChar_apply, eC]; congr 1; push_cast; ring

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), periodization: for an integrable Euclidean symbol
`m`, the `y`-th inverse Fourier coefficient of `m_per` is the inverse Fourier transform of `m`
at `y`: `∫_{[0,1)ⁿ} m_per(ξ) e(y · ξ) dξ = 𝓕⁻ m (y)` for every `y ∈ ℤⁿ`. -/
theorem latKernel_periodize {m : EuclideanSpace ℝ (Fin n) → ℂ} (hm : Integrable m)
    (y : Fin n → ℤ) : latKernel (periodize m) y = 𝓕⁻ m (latEmbed y) := by
  set H : EuclideanSpace ℝ (Fin n) → ℂ := fun η => m η * eC (inner ℝ (latEmbed y) η)
  have hH : Integrable H := hm.mul_bdd (c := 1) (by fun_prop)
    (Filter.Eventually.of_forall fun ξ => le_of_eq (norm_eC _))
  have hF : 𝓕⁻ m (latEmbed y) = ∫ η, H η := by
    rw [Real.fourierInv_eq]
    congr 1; funext η
    rw [Circle.smul_def, fourierChar_eq_eC, real_inner_comm, smul_eq_mul, mul_comm]
  have hterm : ∀ k : Fin n → ℤ, ∀ ξ, m (ξ - latEmbed k) * eC (inner ℝ (latEmbed y) ξ) =
      H (ξ - latEmbed k) := fun k ξ => by
    simp only [H, sub_eq_add_neg, ← latEmbed_neg, eC_inner_add_latEmbed]
  have hint : ∀ k : Fin n → ℤ, Integrable (fun ξ => H (ξ - latEmbed k))
      (volume.restrict (torusCube n)) := fun k => (hH.comp_sub_right (latEmbed k)).integrableOn
  have hsum : Summable fun k : Fin n → ℤ => ∫ ξ in torusCube n, ‖H (ξ - latEmbed k)‖ :=
    (hasSum_setIntegral_torusCube_sub hH.norm).summable
  rw [hF, ← (hasSum_setIntegral_torusCube_sub hH).tsum_eq,
    integral_tsum_of_summable_integral_norm hint hsum, latKernel]
  congr 1; funext ξ
  rw [periodize, ← tsum_mul_right]
  simp_rw [hterm]

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), rapid decrease: for a Schwartz symbol `m`, the
lattice sequence `y ↦ 𝓕⁻ m (y)` is rapidly decreasing:
`∀ N, ∃ C, ∀ y ∈ ℤⁿ, |𝓕⁻ m (y)| ≤ C (1 + |y|)^{-N}`. -/
theorem exists_norm_fourierInv_latEmbed_le (m : 𝓢(EuclideanSpace ℝ (Fin n), ℂ)) (N : ℕ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ y : Fin n → ℤ,
      ‖𝓕⁻ (m : EuclideanSpace ℝ (Fin n) → ℂ) (latEmbed y)‖ ≤ C * ((1 + ‖latEmbed y‖) ^ N)⁻¹ := by
  obtain ⟨K, hK, hKb⟩ := exists_schwartz_decay (𝓕⁻ m) N
  refine ⟨K, hK, fun y => ?_⟩
  have h := (hKb (latEmbed y)).1
  rw [SchwartzMap.fourierInv_coe] at h
  rw [le_mul_inv_iff₀ (by positivity), mul_comm]
  exact h

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), rapid decrease, `ℓ¹` consequence: for a Schwartz
symbol `m`, `y ↦ 𝓕⁻ m (y)` is absolutely summable over `ℤⁿ`. -/
theorem summable_norm_fourierInv_latEmbed (m : 𝓢(EuclideanSpace ℝ (Fin n), ℂ)) :
    Summable fun y : Fin n → ℤ => ‖𝓕⁻ (m : EuclideanSpace ℝ (Fin n) → ℂ) (latEmbed y)‖ := by
  obtain ⟨C, hC, h⟩ := exists_norm_fourierInv_latEmbed_le m (n + 1)
  refine Summable.of_nonneg_of_le (fun _ => norm_nonneg _) h ?_
  refine ((summable_latEnvelope_and_tsum_le (n := n) le_rfl).1.mul_left C).congr fun y => ?_
  simp [latEnvelope, envelope]

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), rapid decrease for smooth compactly supported
symbols: `∀ N, ∃ C, ∀ y ∈ ℤⁿ, |𝓕⁻ m (y)| ≤ C (1 + |y|)^{-N}`, and `y ↦ 𝓕⁻ m (y)` is in `ℓ¹`. -/
theorem fourierInv_latEmbed_rapidDecay_of_hasCompactSupport {m : EuclideanSpace ℝ (Fin n) → ℂ}
    (hsm : ContDiff ℝ ∞ m) (hcs : HasCompactSupport m) :
    (∀ N : ℕ, ∃ C : ℝ, 0 ≤ C ∧ ∀ y : Fin n → ℤ,
      ‖𝓕⁻ m (latEmbed y)‖ ≤ C * ((1 + ‖latEmbed y‖) ^ N)⁻¹) ∧
    Summable fun y : Fin n → ℤ => ‖𝓕⁻ m (latEmbed y)‖ :=
  ⟨exists_norm_fourierInv_latEmbed_le (hcs.toSchwartzMap hsm),
    summable_norm_fourierInv_latEmbed (hcs.toSchwartzMap hsm)⟩


/-! ### Blueprint Lemma 6.1, modulation -/

/-- Blueprint Lemma 6.1 (`lem:fourierbook`) and eq. (1.1) (`eq:modulation`), in the Mathlib sign
convention (`f̂(ξ) = ∑ f(x) e(-x · ξ)`, which is the blueprint's convention reflected by
`ξ ↦ -ξ`): for an `ι(G)`-periodic symbol `m`, every `β ∈ E` and every `f`,
`[m(· - β)](D) = M_β m(D) M_{-β}`, where `M_β f(x) = e(x · β) f(x)`. -/
theorem latMult_comp_sub {m : EuclideanSpace ℝ (Fin n) → ℂ}
    (hm : ∀ ξ (k : Fin n → ℤ), m (ξ + latEmbed k) = m ξ) (β : EuclideanSpace ℝ (Fin n))
    (f : (Fin n → ℤ) → ℂ) :
    latMult (fun ξ => m (ξ - β)) f = latModulate β (latMult m (latModulate (-β) f)) := by
  funext x
  set g : EuclideanSpace ℝ (Fin n) → ℂ :=
    fun ξ => m ξ * latFT f (ξ + β) * eC (inner ℝ (latEmbed x) (ξ + β))
  have hg : ∀ ξ (k : Fin n → ℤ), g (ξ + latEmbed k) = g ξ := fun ξ k => by
    simp only [g, add_right_comm ξ (latEmbed k) β, hm, latFT_add_latEmbed, eC_inner_add_latEmbed]
  have h1 := setIntegral_torusCube_comp_add hg (-β)
  simp only [g, ← sub_eq_add_neg, sub_add_cancel] at h1
  rw [latMult, h1, latModulate, latMult, ← integral_const_mul]
  congr 1; funext ξ
  rw [latFT_latModulate, sub_neg_eq_add, inner_add_right, eC_add]
  ring

/-! ### Blueprint Lemma 6.1, Fourier supports of products -/

lemma summable_norm_mul {u v : (Fin n → ℤ) → ℂ} (hu : Summable fun z => ‖u z‖)
    (hv : Summable fun z => ‖v z‖) : Summable fun z => ‖u z * v z‖ := by
  refine Summable.of_nonneg_of_le (fun _ => norm_nonneg _) (fun z => ?_)
    (hu.mul_right (∑' w, ‖v w‖))
  rw [norm_mul]
  exact mul_le_mul_of_nonneg_left (hv.le_tsum z fun j _ => norm_nonneg _) (norm_nonneg _)

/-- The Fourier transform of a product is the torus convolution of the Fourier transforms:
for `u, v ∈ ℓ¹`, `(uv)^(ξ) = ∫_{[0,1)ⁿ} û(ζ) v̂(ξ - ζ) dζ`. -/
theorem latFT_mul_eq_integral {u v : (Fin n → ℤ) → ℂ} (hu : Summable fun z => ‖u z‖)
    (hv : Summable fun z => ‖v z‖) (ξ : EuclideanSpace ℝ (Fin n)) :
    latFT (fun x => u x * v x) ξ = ∫ ζ in torusCube n, latFT u ζ * latFT v (ξ - ζ) := by
  have hcu := continuous_latFT hu
  set F : (Fin n → ℤ) → EuclideanSpace ℝ (Fin n) → ℂ :=
    fun x ζ => latFT u ζ * (v x * eC (-(inner ℝ (latEmbed x) (ξ - ζ))))
  have hint : ∀ x, Integrable (F x) (volume.restrict (torusCube n)) := fun x =>
    integrableOn_torusCube_of_bound (by fun_prop) ((∑' z, ‖u z‖) * ‖v x‖) fun ζ _ => by
      simp only [F, norm_mul, norm_eC, mul_one]
      exact mul_le_mul_of_nonneg_right (norm_latFT_le hu ζ) (norm_nonneg _)
  have hnorm : ∀ x, ∫ ζ in torusCube n, ‖F x ζ‖ = (∫ ζ in torusCube n, ‖latFT u ζ‖) * ‖v x‖ :=
    fun x => by simp only [F, norm_mul, norm_eC, mul_one]; exact integral_mul_const _ _
  have hsum : Summable fun x => ∫ ζ in torusCube n, ‖F x ζ‖ := by
    simp_rw [hnorm]; exact hv.mul_left _
  have hRHS : ∫ ζ in torusCube n, latFT u ζ * latFT v (ξ - ζ) =
      ∫ ζ in torusCube n, ∑' x, F x ζ := by
    congr 1; funext ζ
    show _ = ∑' x, latFT u ζ * (v x * eC (-(inner ℝ (latEmbed x) (ξ - ζ))))
    rw [tsum_mul_left]; rfl
  rw [hRHS, ← integral_tsum_of_summable_integral_norm hint hsum, latFT]
  congr 1; funext x
  have hF : ∀ ζ, F x ζ = v x * eC (-(inner ℝ (latEmbed x) ξ)) *
      (latFT u ζ * eC (inner ℝ (latEmbed x) ζ)) := fun ζ => by
    simp only [F]
    rw [inner_sub_right, show ∀ a b : ℝ, -(a - b) = b + -a from fun a b => by ring, eC_add]
    ring
  simp_rw [hF]
  rw [integral_const_mul, ← latKernel, latKernel_latFT hu]
  ring

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), two factors: for `u, v ∈ ℓ¹` whose Fourier
transforms vanish off `S` and `T` respectively, `(uv)^` vanishes off the Minkowski sum `S + T`. -/
theorem latFT_mul_eq_zero_of_not_mem {u v : (Fin n → ℤ) → ℂ} (hu : Summable fun z => ‖u z‖)
    (hv : Summable fun z => ‖v z‖) {S T : Set (EuclideanSpace ℝ (Fin n))}
    (hS : ∀ ξ ∉ S, latFT u ξ = 0) (hT : ∀ ξ ∉ T, latFT v ξ = 0) {ξ : EuclideanSpace ℝ (Fin n)}
    (hξ : ξ ∉ S + T) : latFT (fun x => u x * v x) ξ = 0 := by
  rw [latFT_mul_eq_integral hu hv]
  have h0 : ∀ ζ, latFT u ζ * latFT v (ξ - ζ) = 0 := by
    intro ζ
    by_cases hζ : ζ ∈ S
    · have : ξ - ζ ∉ T := fun h => hξ (by simpa using Set.add_mem_add hζ h)
      rw [hT _ this, mul_zero]
    · rw [hS _ hζ, zero_mul]
  simp [h0]

lemma zero_mem_range_latEmbed : (0 : EuclideanSpace ℝ (Fin n)) ∈ range (latEmbed (n := n)) :=
  ⟨0, latEmbed_zero⟩

lemma subset_add_range_latEmbed (A : Set (EuclideanSpace ℝ (Fin n))) :
    A ⊆ A + range (latEmbed (n := n)) :=
  fun a ha => ⟨a, ha, 0, zero_mem_range_latEmbed, add_zero a⟩

lemma range_latEmbed_add_self :
    range (latEmbed (n := n)) + range (latEmbed (n := n)) = range (latEmbed (n := n)) := by
  refine Set.Subset.antisymm ?_ ?_
  · rintro _ ⟨_, ⟨a, rfl⟩, _, ⟨b, rfl⟩, rfl⟩
    exact ⟨a + b, latEmbed_add a b⟩
  · exact fun v hv => ⟨v, hv, 0, zero_mem_range_latEmbed, add_zero v⟩

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), products: if `u_i ∈ ℓ¹` (`i ∈ s`, `s` nonempty and
finite) and `û_i` vanishes off `S_i`, then `∏ u_i ∈ ℓ¹` and `(∏_i u_i)^` vanishes off
`S_1 + ⋯ + S_l + ℤⁿ` (the Minkowski sum modulo the lattice). Conjugated factors are covered via
`latFT_conj_eq_zero_of_not_mem`. -/
theorem latFT_prod_eq_zero_of_not_mem {ι : Type*} {s : Finset ι} (hs : s.Nonempty)
    {u : ι → (Fin n → ℤ) → ℂ} {S : ι → Set (EuclideanSpace ℝ (Fin n))}
    (hu : ∀ i ∈ s, Summable fun z => ‖u i z‖) (hS : ∀ i ∈ s, ∀ ξ ∉ S i, latFT (u i) ξ = 0) :
    (Summable fun z => ‖∏ i ∈ s, u i z‖) ∧
      ∀ ξ ∉ (∑ i ∈ s, S i) + range (latEmbed (n := n)),
        latFT (fun z => ∏ i ∈ s, u i z) ξ = 0 := by
  induction hs using Finset.Nonempty.cons_induction with
  | singleton a =>
    simp only [Finset.prod_singleton, Finset.sum_singleton]
    refine ⟨hu a (Finset.mem_singleton_self a), fun ξ hξ => ?_⟩
    exact hS a (Finset.mem_singleton_self a) ξ fun h => hξ (subset_add_range_latEmbed _ h)
  | cons a t hat ht ih =>
    have hu' : ∀ i ∈ t, Summable fun z => ‖u i z‖ := fun i hi => hu i (Finset.mem_cons_of_mem hi)
    have hS' : ∀ i ∈ t, ∀ ξ ∉ S i, latFT (u i) ξ = 0 := fun i hi =>
      hS i (Finset.mem_cons_of_mem hi)
    obtain ⟨ih1, ih2⟩ := ih hu' hS'
    have ha := hu a (Finset.mem_cons_self a t)
    simp only [Finset.prod_cons, Finset.sum_cons]
    refine ⟨summable_norm_mul ha ih1, fun ξ hξ => ?_⟩
    refine latFT_mul_eq_zero_of_not_mem ha ih1 (hS a (Finset.mem_cons_self a t)) ih2 ?_
    rwa [← add_assoc]

/-- Conjugation reflects Fourier supports: if `û` vanishes off `S`, then `(ū)^` vanishes off
`-S`. -/
theorem latFT_conj_eq_zero_of_not_mem {u : (Fin n → ℤ) → ℂ} {S : Set (EuclideanSpace ℝ (Fin n))}
    (hS : ∀ ξ ∉ S, latFT u ξ = 0) : ∀ ξ ∉ -S, latFT (fun x => conj (u x)) ξ = 0 := by
  intro ξ hξ
  rw [latFT_conj, hS (-ξ) (by simpa using hξ), map_zero]

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), "in particular": under the hypotheses of
`latFT_prod_eq_zero_of_not_mem`, if `0 ∉ S_1 + ⋯ + S_l + ℤⁿ` then `∑_{x ∈ ℤⁿ} ∏_i u_i(x) = 0`. -/
theorem tsum_prod_eq_zero {ι : Type*} {s : Finset ι} (hs : s.Nonempty)
    {u : ι → (Fin n → ℤ) → ℂ} {S : ι → Set (EuclideanSpace ℝ (Fin n))}
    (hu : ∀ i ∈ s, Summable fun z => ‖u i z‖) (hS : ∀ i ∈ s, ∀ ξ ∉ S i, latFT (u i) ξ = 0)
    (h0 : (0 : EuclideanSpace ℝ (Fin n)) ∉ (∑ i ∈ s, S i) + range (latEmbed (n := n))) :
    ∑' x, ∏ i ∈ s, u i x = 0 := by
  rw [tsum_eq_latFT_zero]
  exact (latFT_prod_eq_zero_of_not_mem hs hu hS).2 0 h0

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), orthogonality: for `u, v ∈ ℓ¹` with `û` vanishing
off `S`, `v̂` vanishing off `T`, and `(S + ℤⁿ) ∩ T = ∅` (disjoint Fourier supports modulo the
lattice), `∑_x u(x) conj (v(x)) = 0`. -/
theorem tsum_mul_conj_eq_zero {u v : (Fin n → ℤ) → ℂ} (hu : Summable fun z => ‖u z‖)
    (hv : Summable fun z => ‖v z‖) {S T : Set (EuclideanSpace ℝ (Fin n))}
    (hS : ∀ ξ ∉ S, latFT u ξ = 0) (hT : ∀ ξ ∉ T, latFT v ξ = 0)
    (hST : Disjoint (S + range (latEmbed (n := n))) T) :
    ∑' x, u x * conj (v x) = 0 := by
  rw [tsum_eq_latFT_zero]
  refine latFT_mul_eq_zero_of_not_mem hu (by simpa using hv) hS
    (latFT_conj_eq_zero_of_not_mem hT) ?_
  rintro ⟨a, ha, b, hb, hab⟩
  have hb' : -b ∈ T := hb
  rw [add_eq_zero_iff_eq_neg] at hab
  subst hab
  exact Set.disjoint_left.1 hST (subset_add_range_latEmbed S ha) hb'

/-- Blueprint Lemma 6.1 (`lem:fourierbook`), orthogonality of products: if `u_i, v_j ∈ ℓ¹`,
`û_i` vanishes off `S_i` and `v̂_j` off `T_j`, and the Fourier supports
`∑ S_i + ℤⁿ` and `∑ T_j + ℤⁿ` of the two products are disjoint, then the products are orthogonal
in `ℓ²`: `∑_x (∏_i u_i(x)) conj (∏_j v_j(x)) = 0`. -/
theorem tsum_prod_mul_conj_prod_eq_zero {ι κ : Type*} {s : Finset ι} {t : Finset κ}
    (hs : s.Nonempty) (ht : t.Nonempty)
    {u : ι → (Fin n → ℤ) → ℂ} {S : ι → Set (EuclideanSpace ℝ (Fin n))}
    (hu : ∀ i ∈ s, Summable fun z => ‖u i z‖) (hS : ∀ i ∈ s, ∀ ξ ∉ S i, latFT (u i) ξ = 0)
    {v : κ → (Fin n → ℤ) → ℂ} {T : κ → Set (EuclideanSpace ℝ (Fin n))}
    (hv : ∀ j ∈ t, Summable fun z => ‖v j z‖) (hT : ∀ j ∈ t, ∀ ξ ∉ T j, latFT (v j) ξ = 0)
    (hST : Disjoint ((∑ i ∈ s, S i) + range (latEmbed (n := n)))
      ((∑ j ∈ t, T j) + range (latEmbed (n := n)))) :
    ∑' x, (∏ i ∈ s, u i x) * conj (∏ j ∈ t, v j x) = 0 := by
  obtain ⟨hU1, hU2⟩ := latFT_prod_eq_zero_of_not_mem hs hu hS
  obtain ⟨hV1, hV2⟩ := latFT_prod_eq_zero_of_not_mem ht hv hT
  refine tsum_mul_conj_eq_zero hU1 hV1 hU2 hV2 ?_
  rwa [add_assoc, range_latEmbed_add_self]

end Auto
