/-
Copyright (c) 2026 Joris Roos. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib
public import DiscreteSW.Auto.MarcinkiewiczInterpolation
public import DiscreteSW.Auto.HardyLittlewoodMaximal
public import DiscreteSW.Auto.CalderonZygmund

/-!
# Notation and elementary tools (KR II §2.1)

This file was automatically generated by Claude.

This file covers §2.1 (Notation) of B. Krause, J. Roos, *Discrete analogues of maximally modulated
singular integrals of Stein–Wainger type: `ℓ^p` bounds for `p > 1`*, arXiv:2107.14616v2 ("KR II"),
together with the elementary norm, maximal and duality tools used throughout that paper and its
predecessor B. Krause, J. Roos, *Discrete analogues of maximally modulated singular integrals of
Stein–Wainger type*, arXiv:1907.00405v3 ("KR I") (KR I §2, Preliminaries). It contains the objects
of the main theorem from blueprint (`blueprints/discrete-sw.tex`) §1.2 and §14.1 (`latEmbed`,
`radialPolyZ`, `radialPoly`, `eC`, `IsSWProfile`, `swKernel`, `swTerm`, `swOp`, `swMax`) and the
blueprint §2 items Lemma 2.1 (`lem:finite`), Lemma 2.2 (`lem:young`), the envelope half of Lemma 2.4
(`lem:maximal`) and Lemma 2.5 (`lem:ttstar`). Lemma 2.7 (`lem:binary`, KR II §2.4) is in
`DiscreteSW/Auto/Sec2_4_2_5MultiplierApproximations.lean`; Lemmas 2.3, 2.4 (maximal bounds) and 2.6
are the prerequisites `MarcinkiewiczInterpolation`, `HardyLittlewoodMaximal` and
`KhintchineInequality`.

## Sections

* `Foundations` (blueprint §1.2, §14.1): the objects of the theorem (`latEmbed`, `radialPolyZ`,
  `eC`, `IsSWProfile`, `swKernel`, `swTerm`, `swOp`, `swMax`);
* `Tools` (blueprint §2): elementary norm, maximal and randomization tools (Lemmas 2.1–2.6).
-/

@[expose] public section

namespace Auto

section Foundations

/-!
## Foundations: the objects of the discrete Stein–Wainger theorem

Definitions from §1.2 ("Types, measures, and Fourier signs") and §14.1 ("Concrete types and
representations") of `blueprints/discrete-sw.tex`:

* the lattice `G = ℤⁿ` as `Fin n → ℤ` and the Euclidean space `E = ℝⁿ` as
  `EuclideanSpace ℝ (Fin n)`, with the coordinatewise embedding `latEmbed`;
* the radial polynomial `P(x) = (x₁² + ⋯ + xₙ²)^d`, in an integer version `radialPolyZ` and a real
  version `radialPoly`, related by `radialPoly_latEmbed`;
* the character `e(t) = exp(2πit)` (`eC`);
* the admissibility predicate `IsSWProfile` for `Ω` (smooth off zero, homogeneous of degree zero,
  zero mean on the unit sphere);
* the kernel `K(x) = Ω(x)|x|^{-n}` with `K(0) = 0` (`swKernel`), the modulated operators `T_λ`
  (`swOp`) and the maximal operator `𝒞 f = sup_λ |T_λ f|` (`swMax`).
-/

open MeasureTheory Real
open scoped ContDiff

/-- The coordinatewise embedding `ℤⁿ ↪ ℝⁿ` of blueprint §1.2 (`G ↪ E`). -/
noncomputable def latEmbed {n : ℕ} (y : Fin n → ℤ) : EuclideanSpace ℝ (Fin n) :=
  WithLp.toLp 2 (fun i => (y i : ℝ))

@[simp] lemma latEmbed_apply {n : ℕ} (y : Fin n → ℤ) (i : Fin n) :
    latEmbed y i = (y i : ℝ) := rfl

/-- The integer-valued radial polynomial `P_ℤ(y) = (∑ᵢ yᵢ²)^d` of blueprint §14.1. -/
def radialPolyZ (n d : ℕ) (y : Fin n → ℤ) : ℤ := (∑ i, y i ^ 2) ^ d

/-- The real radial polynomial `P(x) = (x₁² + ⋯ + xₙ²)^d` of blueprint §1.2. -/
noncomputable def radialPoly (n d : ℕ) (x : EuclideanSpace ℝ (Fin n)) : ℝ := (∑ i, x i ^ 2) ^ d

/-- Blueprint §14.1: `P_ℝ(ι y) = cast (P_ℤ(y))`. -/
lemma radialPoly_latEmbed (n d : ℕ) (y : Fin n → ℤ) :
    radialPoly n d (latEmbed y) = (radialPolyZ n d y : ℝ) := by
  simp [radialPoly, radialPolyZ]

/-- Blueprint §14.1: `P_ℝ(x) = ‖x‖^{2d}`. -/
lemma radialPoly_eq_norm_pow (n d : ℕ) (x : EuclideanSpace ℝ (Fin n)) :
    radialPoly n d x = ‖x‖ ^ (2 * d) := by
  rw [radialPoly, pow_mul, EuclideanSpace.norm_sq_eq]
  simp [Real.norm_eq_abs, sq_abs]

/-- The character `e(t) = exp(2πit)` of blueprint §1.2. -/
noncomputable def eC (t : ℝ) : ℂ := Complex.exp (2 * π * Complex.I * t)

/-- The hypotheses on `Ω` in Theorem 13.2 (`thm:main`): `Ω` is smooth on `E ∖ {0}`, homogeneous of
degree zero, and has integral zero on the unit sphere `S^{n-1}` (with respect to the sphere measure
`volume.toSphere`, the cone construction of Lemma 4.1). -/
def IsSWProfile {n : ℕ} (Ω : EuclideanSpace ℝ (Fin n) → ℂ) : Prop :=
  ContDiffOn ℝ ∞ Ω {0}ᶜ ∧
  (∀ x : EuclideanSpace ℝ (Fin n), x ≠ 0 → ∀ t : ℝ, 0 < t → Ω (t • x) = Ω x) ∧
  ∫ θ, Ω θ ∂(volume.toSphere : Measure (Metric.sphere (0 : EuclideanSpace ℝ (Fin n)) 1)) = 0

/-- The Calderón–Zygmund kernel `K(x) = Ω(x)|x|^{-n}` for `x ≠ 0`, with `K(0) = 0`
(blueprint §4 and Theorem 13.2). -/
noncomputable def swKernel {n : ℕ} (Ω : EuclideanSpace ℝ (Fin n) → ℂ)
    (x : EuclideanSpace ℝ (Fin n)) : ℂ :=
  if x = 0 then 0 else Ω x / ((‖x‖ ^ n : ℝ) : ℂ)

/-- The summand `e(λ P(y)) K(y) f(x - y)` of the modulated singular integral in Theorem 13.2. -/
noncomputable def swTerm (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (lam : ℝ)
    (f : (Fin n → ℤ) → ℂ) (x y : Fin n → ℤ) : ℂ :=
  eC (lam * (radialPolyZ n d y : ℝ)) * swKernel Ω (latEmbed y) * f (x - y)

/-- The modulated discrete singular integral
`T_λ f(x) = ∑_{y ∈ ℤⁿ ∖ {0}} e(λ P(y)) K(y) f(x - y)` of Lemma 13.1 and Theorem 13.2. -/
noncomputable def swOp (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ) (lam : ℝ)
    (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) : ℂ :=
  ∑' y : {y : Fin n → ℤ // y ≠ 0}, swTerm n d Ω lam f x y

/-- The discrete Stein–Wainger maximal operator `𝒞 f(x) = sup_{λ ∈ ℝ} |T_λ f(x)|`
(Theorem 13.2; the supremum is over a scalar real parameter). -/
noncomputable def swMax (n d : ℕ) (Ω : EuclideanSpace ℝ (Fin n) → ℂ)
    (f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) : ℝ :=
  ⨆ lam : ℝ, ‖swOp n d Ω lam f x‖

end Foundations

section Tools

/-!
## Elementary norm, maximal, and randomization tools

Results from §2 ("Elementary norm, maximal, and randomization tools") of
`blueprints/discrete-sw.tex`.

### Lemma 2.1 (`lem:finite`): finite reductions and extension

* `eLpNorm_sub_indicator_latBox_tendsto`: finite-support truncations `f 𝟙_{|x|_∞ ≤ R}` converge
  to `f` in `ℓ^p(ℤⁿ)` for `p < ∞` (`latBox_finite` records that the boxes are finite);
* `eLpNorm_le_of_tendsto_of_eLpNorm_le`: Fatou's lemma for `L^p` norms (proved among the
  supporting results of `DiscreteSW/Auto/CalderonZygmund.lean`);
* `eLpNorm_iSup_le_of_finset_count`, `eLpNorm_ciSup_norm_le_of_finset_count`: finite-family
  maximal bounds imply the bound for the supremum over an arbitrary family, for counting measure;
* `eLpNorm_iSup_le_of_finset_countable`: the same for a countable family on any measure space;
* `exists_unique_extension_of_dense`: bounded linear maps on dense subspaces extend uniquely.

### Lemma 2.2 (`lem:young`): Young, dual testing, and subsequences

* `eLpNorm_convolution_le_mul`, `ae_convolutionExistsAt_of_memLp`, `memLp_convolution_of_memLp`:
  Young's inequality `‖k * f‖_p ≤ ‖k‖₁ ‖f‖_p` (`1 ≤ p ≤ ∞`) on any abelian measurable group with
  an invariant s-finite measure (proved among the supporting results of
  `DiscreteSW/Auto/CalderonZygmund.lean`), specialized here in `young_convolution_euclidean`
  (on `E = ℝⁿ`) and `young_latConv` (on `G = ℤⁿ`, for the lattice convolution `latConv`);
* `enorm_integral_mul_conj_le` (Hölder), `eLpNorm_le_of_dual_test`: dual testing with bounded
  tests of finite-measure support, and `eLpNorm_le_of_smooth_dual_test` with smooth compactly
  supported tests (proved among the supporting results of `DiscreteSW/Auto/CalderonZygmund.lean`);
  `eLpNorm_eq_iSup_dual_test`: the equality form of dual testing;
* `exists_subseq_ae_tendsto_of_eLpNorm_tendsto`: `L^p` convergence has an a.e. convergent
  subsequence.

### Lemma 2.3 (`lem:interpolation`): distributional interpolation

Proved as the reusable prerequisite `DiscreteSW/Auto/MarcinkiewiczInterpolation.lean`
(general normed input/output groups, which covers the finite-dimensional vector version):
`eLpNorm_rpow_eq_lintegral_distributionFunction` (layer cake), `eLpNorm_le_of_hasWeakTypeOn`
(weak `(a,a)` + weak `(b,b)`), `eLpNorm_le_of_hasWeakTypeOn_of_linfty` (weak `(a,a)` + `L^∞`),
`HasStrongTypeOn.hasWeakTypeOn` (strong bounds may replace weak ones).

### Lemma 2.4 (`lem:maximal`): the elementary maximal function and the envelope `B_R`

The maximal bounds are proved in `DiscreteSW/Auto/HardyLittlewoodMaximal.lean`
(`cubeMaximalEuclidean`, `cubeMaximalInt`). For the envelope
`B_R(x) = R^{-n}(1 + |x|/R)^{-n-1}` (`envelope`, defined with its constant `envelopeConst`
among the supporting results of `DiscreteSW/Auto/CalderonZygmund.lean`; lattice version
`latEnvelope`):

* `integrable_envelope_and_integral_le`, `summable_latEnvelope_and_tsum_le`: the Euclidean
  integral and the lattice sum of `B_R` are at most `C_n = envelopeConst n`;
* `lintegral_envelope_mul_le_cubeMaximalEuclidean` (in `DiscreteSW/Auto/CalderonZygmund.lean`),
  `tsum_envelope_mul_le_cubeMaximalInt`: `B_R * |f| ≤ C_n 𝖬 f` on `E` and on `G` (first half
  of (2.1));
* `envelope_conv_le`: `B_R *_E B_L ≤ C B_{max(R,L)}` (second half of (2.1)).

### Lemma 2.5 (`lem:ttstar`): Schur, Hilbert–Schmidt, and linearization

* `eLpNorm_lintegral_kernel_le_schur`, `eLpNorm_integral_kernel_le_schur`: the Schur test
  `‖Hg‖₂ ≤ √(AB) ‖g‖₂` on s-finite measure spaces (majorant and integral forms);
* `eLpNorm_lintegral_kernel_le_hilbertSchmidt`, `eLpNorm_integral_kernel_le_hilbertSchmidt`:
  `‖Hg‖₂ ≤ ‖H‖_{L²(X × Y)} ‖g‖₂`;
* `norm_sq_eq_norm_comp_adjoint`: `‖T‖² = ‖TT*‖` (and `‖T*‖ = ‖T‖`, `‖T‖² = ‖T*T‖`);
* `exists_linearization`, `eLpNorm_finset_sup_le_of_linearization`,
  `eLpNorm_finset_sup_le_of_linearization_op`: measurable maximizing selections and the bound
  of finite maximal functions by uniform bounds for all linearizations.

### Lemma 2.6 (`lem:khintchine`): Rademacher square functions

Proved as the reusable prerequisite `DiscreteSW/Auto/KhintchineInequality.lean` (vectors in a
real or complex inner product space): `khintchine_upper` and `khintchine_lower` (the upper and
lower Khintchine inequalities for `0 < p < ∞`), and `marcinkiewicz_zygmund_square_function`
(with the variant `marcinkiewicz_zygmund_square_function_of_addMonoidHom`), the
`ℓ²`-valued extension of `L^p` bounds for additive operators.

### Lemma 2.7 (`lem:binary`): binary partial sums

* `binary_maximal_inequality` (proved in `DiscreteSW/Auto/Sec2_4_2_5MultiplierApproximations.lean`,
  KR II §2.4): `max_{J ≤ 2^L} |∑_{j ≤ J} u_j|` is bounded by the sum over the dyadic scales
  `l ≤ L` of the `ℓ²` norms of the interval sums over `I_{l,k}`.
-/

open MeasureTheory Filter Topology Set
open scoped ENNReal NNReal

/-! ### Lemma 2.1, first assertion -/

/-- The lattice box `{x ∈ ℤⁿ : |x|_∞ ≤ R}` used for finite-support truncations. -/
def latBox (n R : ℕ) : Set (Fin n → ℤ) := {x | ∀ i, |x i| ≤ (R : ℤ)}

/-- The lattice box `{x ∈ ℤⁿ : |x|_∞ ≤ R}` is finite, so truncations to it have finite support. -/
theorem latBox_finite (n R : ℕ) : (latBox n R).Finite := by
  have : latBox n R = Set.pi Set.univ (fun _ => Set.Icc (-(R : ℤ)) R) := by
    ext x
    simp only [latBox, Set.mem_ofPred_eq, Set.mem_univ_pi, Set.mem_Icc, abs_le]
  rw [this]
  exact Set.Finite.pi fun _ => Set.finite_Icc _ _

/-- Truncations of a function to a lattice box have finite support. -/
theorem support_indicator_latBox_finite {F : Type*} [Zero F] (n R : ℕ) (f : (Fin n → ℤ) → F) :
    (Function.support ((latBox n R).indicator f)).Finite :=
  (latBox_finite n R).subset Set.support_indicator_subset

/-- Blueprint Lemma 2.1 (`lem:finite`), first assertion (density of finite support in
`ℓ^p(G)`): for `f ∈ ℓ^p(ℤⁿ)` with `p < ∞` (in particular for `1 ≤ p < ∞`), the finite-support
truncations `f_R = f 𝟙_{|x|_∞ ≤ R}` satisfy `‖f - f_R‖_p → 0` as `R → ∞`. -/
theorem eLpNorm_sub_indicator_latBox_tendsto {n : ℕ} {F : Type*} [NormedAddCommGroup F]
    {p : ℝ≥0∞} (hp : p ≠ ∞) {f : (Fin n → ℤ) → F} (hf : MemLp f p Measure.count) :
    Tendsto (fun R : ℕ => eLpNorm (f - (latBox n R).indicator f) p Measure.count)
      atTop (𝓝 0) := by
  rcases eq_or_ne p 0 with rfl | hp0
  · simp [eLpNorm_exponent_zero AEStronglyMeasurable.of_discrete]
  have hr : 0 < p.toReal := ENNReal.toReal_pos hp0 hp
  simp_rw [← Set.indicator_compl,
    eLpNorm_eq_lintegral_rpow_enorm_toReal hp0 hp AEStronglyMeasurable.of_discrete]
  have hlim : Tendsto (fun R : ℕ => ∫⁻ x, ‖(latBox n R)ᶜ.indicator f x‖ₑ ^ p.toReal
      ∂Measure.count) atTop (𝓝 (∫⁻ _x : Fin n → ℤ, (0 : ℝ≥0∞) ∂Measure.count)) := by
    refine tendsto_lintegral_of_dominated_convergence (fun x => ‖f x‖ₑ ^ p.toReal)
      (fun R => measurable_of_countable
        (fun x => ‖(latBox n R)ᶜ.indicator f x‖ₑ ^ p.toReal))
      (fun R => Eventually.of_forall fun x => ?_) ?_
      (Eventually.of_forall fun x => ?_)
    · by_cases hx : x ∈ (latBox n R)ᶜ
      · simp [Set.indicator_of_mem hx]
      · simp [Set.indicator_of_notMem hx, ENNReal.zero_rpow_of_pos hr]
    · exact (lintegral_rpow_enorm_lt_top_of_eLpNorm_lt_top hp0 hp hf.eLpNorm_lt_top).ne
    · refine tendsto_const_nhds.congr' ?_
      rw [EventuallyEq, eventually_atTop]
      refine ⟨Finset.univ.sup fun i => (x i).natAbs, fun R hR => ?_⟩
      have hx : x ∈ latBox n R := by
        intro i
        have : (x i).natAbs ≤ R :=
          le_trans (Finset.le_sup (f := fun i => (x i).natAbs) (Finset.mem_univ i)) hR
        rw [Int.abs_eq_natAbs]; exact_mod_cast this
      simp [Set.indicator_of_notMem (Set.notMem_compl_iff.mpr hx), ENNReal.zero_rpow_of_pos hr]
  simp only [lintegral_zero] at hlim
  have hc := (ENNReal.continuous_rpow_const (y := 1 / p.toReal)).tendsto 0
  rw [ENNReal.zero_rpow_of_pos (by positivity)] at hc
  exact hc.comp hlim

/-! ### Lemma 2.1, second assertion

Fatou's lemma for `L^p` norms, `eLpNorm_le_of_tendsto_of_eLpNorm_le`, is proved among the
supporting results of `DiscreteSW/Auto/CalderonZygmund.lean`. -/

/-! ### Lemma 2.1, third and fourth assertions -/

/-- The supremum of a family equals the directed supremum of its finite maxima. -/
lemma iSup_eq_iSup_finset_sup {ι : Type*} (g : ι → ℝ≥0∞) :
    ⨆ a, g a = ⨆ F : Finset ι, F.sup g := by
  rw [iSup_eq_iSup_finset]
  simp_rw [Finset.sup_eq_iSup]

/-- For `0 < r`, `(⨆ a, g a) ^ r = ⨆ F, (max_{a ∈ F} g a) ^ r`. -/
lemma iSup_rpow_eq_iSup_finset {ι : Type*} (g : ι → ℝ≥0∞) {r : ℝ} (hr : 0 < r) :
    (⨆ a, g a) ^ r = ⨆ F : Finset ι, (F.sup g) ^ r := by
  rw [iSup_eq_iSup_finset_sup]
  exact Monotone.map_iSup_of_continuousAt (ENNReal.continuous_rpow_const.continuousAt)
    (ENNReal.monotone_rpow_of_nonneg hr.le) (ENNReal.zero_rpow_of_pos hr)

/-- Reduction of an `eLpNorm` bound (`p ≠ 0, ∞`) to a bound on the integral of the `p`-th power. -/
lemma eLpNorm_ennreal_le_iff {α : Type*} [MeasurableSpace α] {μ : Measure α} {p : ℝ≥0∞}
    (hp0 : p ≠ 0) (hp : p ≠ ∞) (h : α → ℝ≥0∞) (hh : AEMeasurable h μ) (B : ℝ≥0∞) :
    eLpNorm h p μ ≤ B ↔ ∫⁻ x, h x ^ p.toReal ∂μ ≤ B ^ p.toReal := by
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hp0 hp hh.aestronglyMeasurable]
  simp only [enorm_eq_self]
  rw [one_div]
  exact ENNReal.rpow_inv_le_iff (ENNReal.toReal_pos hp0 hp)

/-- Blueprint Lemma 2.1 (`lem:finite`), third assertion (on `G`, stated for counting measure on any
countable type with measurable singletons): for an arbitrary family `g a : α → [0, ∞]` (think
`g a x = |T_a f(x)|`) and `p < ∞`, if
`‖max_{a ∈ F} g a‖_p ≤ B` for every finite `F`, then `‖sup_a g a‖_p ≤ B`, where the supremum is
the pointwise defined extended nonnegative number. -/
theorem eLpNorm_iSup_le_of_finset_count {α ι : Type*} [MeasurableSpace α]
    [MeasurableSingletonClass α] [Countable α] {p : ℝ≥0∞} (hp : p ≠ ∞) (g : ι → α → ℝ≥0∞) (B : ℝ≥0∞)
    (hB : ∀ F : Finset ι, eLpNorm (fun x => F.sup fun a => g a x) p Measure.count ≤ B) :
    eLpNorm (fun x => ⨆ a, g a x) p Measure.count ≤ B := by
  rcases eq_or_ne p 0 with rfl | hp0
  · simp [eLpNorm_exponent_zero AEStronglyMeasurable.of_discrete]
  have hr : 0 < p.toReal := ENNReal.toReal_pos hp0 hp
  rw [eLpNorm_ennreal_le_iff hp0 hp _ AEStronglyMeasurable.of_discrete.aemeasurable,
    lintegral_count]
  simp_rw [eLpNorm_ennreal_le_iff hp0 hp _ AEStronglyMeasurable.of_discrete.aemeasurable,
    lintegral_count] at hB
  rw [ENNReal.tsum_eq_iSup_sum]
  refine iSup_le fun S => ?_
  simp_rw [iSup_rpow_eq_iSup_finset _ hr]
  rw [ENNReal.finsetSum_iSup_of_monotone]
  · refine iSup_le fun F => le_trans ?_ (hB F)
    exact ENNReal.sum_le_tsum S
  · intro x F F' hFF'
    exact ENNReal.rpow_le_rpow (Finset.sup_mono hFF') hr.le

/-- Blueprint Lemma 2.1 (`lem:finite`), third assertion, real-valued form on `G = ℤⁿ`: for a
family `T a : ℤⁿ → ℂ` with `sup_a |T a x| < ∞` for every `x` and `p < ∞`, if
`‖max(0, max_{a ∈ F} |T a|)‖_p ≤ B` for every finite `F`, then `‖sup_a |T a|‖_p ≤ B`. -/
theorem eLpNorm_ciSup_norm_le_of_finset_count {n : ℕ} {ι : Type*} {p : ℝ≥0∞} (hp : p ≠ ∞)
    (T : ι → (Fin n → ℤ) → ℂ) (hbdd : ∀ x, BddAbove (range fun a => ‖T a x‖)) (B : ℝ≥0∞)
    (hB : ∀ F : Finset ι,
      eLpNorm (fun x => ((F.sup fun a => ‖T a x‖₊ : ℝ≥0) : ℝ)) p Measure.count ≤ B) :
    eLpNorm (fun x => ⨆ a, ‖T a x‖) p Measure.count ≤ B := by
  have key := eLpNorm_iSup_le_of_finset_count hp (fun a x => ‖T a x‖ₑ) B (fun F => by
    have h := hB F
    rw [← eLpNorm_enorm _ AEStronglyMeasurable.of_discrete] at h
    convert h using 2
    funext x
    rw [Real.enorm_eq_ofReal (NNReal.coe_nonneg _), ENNReal.ofReal_coe_nnreal,
      ENNReal.coe_finset_sup]
    rfl)
  rw [← eLpNorm_enorm _ AEStronglyMeasurable.of_discrete]
  convert key using 2
  funext x
  have hbdd' : BddAbove (range fun a => ‖T a x‖₊) := by
    obtain ⟨M, hM⟩ := hbdd x
    refine ⟨⟨max M 0, le_max_right _ _⟩, ?_⟩
    rintro _ ⟨a, rfl⟩
    change ‖T a x‖ ≤ max M 0
    exact (hM ⟨a, rfl⟩).trans (le_max_left _ _)
  have : (⨆ a, ‖T a x‖) = ((⨆ a, ‖T a x‖₊ : ℝ≥0) : ℝ) := by
    rw [NNReal.coe_iSup]; rfl
  rw [this, Real.enorm_eq_ofReal (NNReal.coe_nonneg _), ENNReal.ofReal_coe_nnreal,
    ENNReal.coe_iSup hbdd']
  rfl

/-- Blueprint Lemma 2.1 (`lem:finite`), fourth assertion (on `E`, stated for any measure space):
for a countable family of a.e.-measurable `g a : α → [0, ∞]` and `p < ∞`, if
`‖max_{a ∈ F} g a‖_p ≤ B` for every finite `F`, then `‖sup_a g a‖_p ≤ B`. -/
theorem eLpNorm_iSup_le_of_finset_countable {α ι : Type*} [MeasurableSpace α] {μ : Measure α}
    [Countable ι] {p : ℝ≥0∞} (hp : p ≠ ∞) (g : ι → α → ℝ≥0∞) (hg : ∀ a, AEMeasurable (g a) μ)
    (B : ℝ≥0∞) (hB : ∀ F : Finset ι, eLpNorm (fun x => F.sup fun a => g a x) p μ ≤ B) :
    eLpNorm (fun x => ⨆ a, g a x) p μ ≤ B := by
  classical
  have hfin : ∀ F : Finset ι, AEMeasurable (fun x => F.sup fun a => g a x) μ := by
    intro F
    simp_rw [Finset.sup_eq_iSup]
    exact AEMeasurable.biSup _ F.countable_toSet fun a _ => hg a
  have hsup : AEMeasurable (fun x => ⨆ a, g a x) μ := AEMeasurable.iSup hg
  rcases eq_or_ne p 0 with rfl | hp0
  · simp [eLpNorm_exponent_zero hsup.aestronglyMeasurable]
  have hr : 0 < p.toReal := ENNReal.toReal_pos hp0 hp
  rw [eLpNorm_ennreal_le_iff hp0 hp _ hsup]
  have hB' := fun F => (eLpNorm_ennreal_le_iff hp0 hp _ (hfin F) B).1 (hB F)
  simp_rw [iSup_rpow_eq_iSup_finset _ hr]
  rw [lintegral_iSup_directed]
  · exact iSup_le hB'
  · intro F
    exact (hfin F).pow_const _
  · intro F F'
    refine ⟨F ∪ F', fun x => ?_, fun x => ?_⟩
    · exact ENNReal.rpow_le_rpow (Finset.sup_mono Finset.subset_union_left) hr.le
    · exact ENNReal.rpow_le_rpow (Finset.sup_mono Finset.subset_union_right) hr.le

/-! ### Lemma 2.1, fifth assertion -/

/-- Blueprint Lemma 2.1 (`lem:finite`), fifth assertion (extension): a linear map `T` on a dense
subspace `S` of a normed space `X`, into a complete normed space, with `‖T s‖ ≤ C ‖s‖`, extends
to a continuous linear map `T'` on `X` with `‖T' x‖ ≤ C ‖x‖`; the extension is unique among all
continuous maps `X → F` agreeing with `T` on `S`. -/
theorem exists_unique_extension_of_dense {𝕜 X F : Type*} [NontriviallyNormedField 𝕜]
    [NormedAddCommGroup X] [NormedSpace 𝕜 X] [NormedAddCommGroup F] [NormedSpace 𝕜 F]
    [CompleteSpace F] {S : Submodule 𝕜 X} (hS : Dense (S : Set X)) (T : S →ₗ[𝕜] F) (C : ℝ)
    (hT : ∀ s, ‖T s‖ ≤ C * ‖s‖) :
    ∃ T' : X →L[𝕜] F, (∀ s : S, T' s = T s) ∧ (∀ x, ‖T' x‖ ≤ C * ‖x‖) ∧
      ∀ g : X → F, Continuous g → (∀ s : S, g s = T s) → g = T' := by
  set T₀ : S →L[𝕜] F := T.mkContinuous C hT
  have hdense : DenseRange (S.subtypeL) := by
    simpa [DenseRange, Submodule.coe_subtype,
      Subtype.range_coe_subtype] using hS
  have hind : IsUniformInducing (S.subtypeL) := isUniformEmbedding_subtype_val.isUniformInducing
  set T' := T₀.extend S.subtypeL
  have hext : ∀ s : S, T' s = T s := fun s => by
    have := ContinuousLinearMap.extend_eq T₀ hdense hind s
    simpa [T₀] using this
  have huniq : ∀ g : X → F, Continuous g → (∀ s : S, g s = T s) → g = T' := by
    intro g hg hgs
    refine Continuous.ext_on hS hg T'.continuous ?_
    intro y hy
    exact (hgs ⟨y, hy⟩).trans (hext ⟨y, hy⟩).symm
  refine ⟨T', hext, fun x => ?_, huniq⟩
  have hcl : IsClosed {x : X | ‖T' x‖ ≤ C * ‖x‖} :=
    isClosed_le (continuous_norm.comp T'.continuous) (continuous_const.mul continuous_norm)
  have hsub : (S : Set X) ⊆ {x : X | ‖T' x‖ ≤ C * ‖x‖} := by
    intro y hy
    have := hext ⟨y, hy⟩
    simp only [Set.mem_ofPred_eq]
    rw [this]
    exact hT ⟨y, hy⟩
  have := closure_minimal hsub hcl
  rw [hS.closure_eq] at this
  exact this (Set.mem_univ x)

/-! ## Lemma 2.2 (`lem:young`): Young, dual testing, and subsequences -/

open scoped Convolution ComplexConjugate

/-! ### Lemma 2.2, first assertion (Young's inequality)

The general forms `eLpNorm_lintegral_enorm_mul_sub_le`, `eLpNorm_convolution_le_mul`,
`ae_convolutionExistsAt_of_memLp` and `memLp_convolution_of_memLp` (on any abelian measurable
group with an invariant s-finite measure) are proved among the supporting results of
`DiscreteSW/Auto/CalderonZygmund.lean`; they are specialized to `E` and `G` here. -/

/-! ### Young on `E = ℝⁿ` -/

/-- Blueprint Lemma 2.2 (`lem:young`), first assertion on `E`: for `1 ≤ p ≤ ∞`, `k ∈ L¹(ℝⁿ)` and
`f ∈ L^p(ℝⁿ)`, the convolution integral `k * f(x) = ∫ k(y) f(x - y) dy` converges absolutely for
a.e. `x`, and `‖k * f‖_p ≤ ‖k‖₁ ‖f‖_p` (in particular `k * f ∈ L^p`). -/
theorem young_convolution_euclidean {n : ℕ} {p : ℝ≥0∞} (hp : 1 ≤ p)
    {k f : EuclideanSpace ℝ (Fin n) → ℂ} (hk : MemLp k 1 volume) (hf : MemLp f p volume) :
    (∀ᵐ x ∂volume, ConvolutionExistsAt k f x (ContinuousLinearMap.mul ℂ ℂ) volume) ∧
      eLpNorm (k ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) p volume ≤
        eLpNorm k 1 volume * eLpNorm f p volume ∧
      MemLp (k ⋆[ContinuousLinearMap.mul ℂ ℂ, volume] f) p volume :=
  ⟨ae_convolutionExistsAt_of_memLp hp hk hf,
    eLpNorm_convolution_le_mul hp hk.aestronglyMeasurable hf.aestronglyMeasurable,
    memLp_convolution_of_memLp hp hk hf⟩

/-! ### Young on `G = ℤⁿ` -/

/-- The lattice convolution `k * f(x) = ∑_{y ∈ ℤⁿ} k(y) f(x - y)` on `G = ℤⁿ`. -/
noncomputable def latConv {n : ℕ} (k f : (Fin n → ℤ) → ℂ) (x : Fin n → ℤ) : ℂ :=
  ∑' y, k y * f (x - y)

/-- The lattice convolution is the measure-theoretic convolution for counting measure. -/
theorem latConv_eq_convolution {n : ℕ} (k f : (Fin n → ℤ) → ℂ) :
    latConv k f = k ⋆[ContinuousLinearMap.mul ℂ ℂ, Measure.count] f := by
  funext x
  rw [convolution_def, latConv]
  simp only [ContinuousLinearMap.mul_apply']
  by_cases h : Integrable (fun y => k y * f (x - y)) Measure.count
  · rw [integral_countable h]
    simp
  · rw [integral_undef h, tsum_eq_zero_of_not_summable]
    intro hs
    exact h (integrable_count_iff.2 (summable_norm_iff.2 hs))

/-- Blueprint Lemma 2.2 (`lem:young`), first assertion on `G`, nonnegative form: for
`1 ≤ p ≤ ∞` and arbitrary `k, f : ℤⁿ → ℂ`,
`‖∑_y |k(y)| |f(· - y)|‖_p ≤ ‖k‖₁ ‖f‖_p` (both sides in `[0, ∞]`). -/
theorem eLpNorm_tsum_enorm_mul_sub_le {n : ℕ} {p : ℝ≥0∞} (hp : 1 ≤ p)
    (k f : (Fin n → ℤ) → ℂ) :
    eLpNorm (fun x => ∑' y, ‖k y‖ₑ * ‖f (x - y)‖ₑ) p Measure.count ≤
      eLpNorm k 1 Measure.count * eLpNorm f p Measure.count := by
  simpa only [lintegral_count] using eLpNorm_lintegral_enorm_mul_sub_le (μ := Measure.count) hp
    (AEStronglyMeasurable.of_discrete (f := k)) (AEStronglyMeasurable.of_discrete (f := f))

/-- Blueprint Lemma 2.2 (`lem:young`), first assertion on `G`: for `1 ≤ p ≤ ∞`, `k ∈ ℓ¹(ℤⁿ)` and
`f ∈ ℓ^p(ℤⁿ)`, the series `k * f(x) = ∑_y k(y) f(x - y)` is (absolutely) summable for every
`x`, and `‖k * f‖_p ≤ ‖k‖₁ ‖f‖_p` (in particular `k * f ∈ ℓ^p`). -/
theorem young_latConv {n : ℕ} {p : ℝ≥0∞} (hp : 1 ≤ p) {k f : (Fin n → ℤ) → ℂ}
    (hk : MemLp k 1 Measure.count) (hf : MemLp f p Measure.count) :
    (∀ x, Summable fun y => k y * f (x - y)) ∧
      eLpNorm (latConv k f) p Measure.count ≤
        eLpNorm k 1 Measure.count * eLpNorm f p Measure.count ∧
      MemLp (latConv k f) p Measure.count := by
  refine ⟨fun x => ?_, ?_, ?_⟩
  · have h := Measure.ae_count_iff.1 (ae_convolutionExistsAt_of_memLp hp hk hf) x
    have h' : Integrable (fun y => k y * f (x - y)) Measure.count := by
      simpa only [ConvolutionExistsAt, ContinuousLinearMap.mul_apply'] using h
    exact summable_norm_iff.1 (integrable_count_iff.1 h')
  · rw [latConv_eq_convolution]
    exact eLpNorm_convolution_le_mul hp AEStronglyMeasurable.of_discrete
      AEStronglyMeasurable.of_discrete
  · rw [latConv_eq_convolution]
    exact memLp_convolution_of_memLp hp hk hf

/-! ### Lemma 2.2, second assertion (dual testing)

Hölder's inequality `enorm_integral_mul_conj_le` and the dual-testing bounds
`eLpNorm_le_of_dual_test` and `eLpNorm_le_of_smooth_dual_test` are proved among the supporting
results of `DiscreteSW/Auto/CalderonZygmund.lean`. -/

section Duality

variable {α : Type*} [MeasurableSpace α] {μ : Measure α}

/-- Blueprint Lemma 2.2 (`lem:young`), second assertion (dual testing, equality form): on a
σ-finite measure space, for Hölder conjugate `1 < p < ∞`, `q = p'`, and any a.e. strongly
measurable `h` (the norm may be infinite), `‖h‖_p` is the supremum of `|∫ h ḡ|` over measurable
bounded `g` with `μ(supp g) < ∞`, `‖g‖_q ≤ 1` and `h ḡ` integrable. -/
theorem eLpNorm_eq_iSup_dual_test [SigmaFinite μ] {p q : ℝ} (hpq : p.HolderConjugate q)
    {h : α → ℂ} (hh : AEStronglyMeasurable h μ) :
    eLpNorm h (ENNReal.ofReal p) μ =
      ⨆ (g : α → ℂ) (_ : Measurable g) (_ : ∃ C, ∀ x, ‖g x‖ ≤ C)
        (_ : μ (Function.support g) < ∞) (_ : eLpNorm g (ENNReal.ofReal q) μ ≤ 1)
        (_ : Integrable (fun x => h x * conj (g x)) μ), ‖∫ x, h x * conj (g x) ∂μ‖ₑ := by
  refine le_antisymm (eLpNorm_le_of_dual_test hpq hh fun g h1 h2 h3 h4 h5 =>
    le_iSup_of_le g <| le_iSup_of_le h1 <| le_iSup_of_le h2 <| le_iSup_of_le h3 <|
      le_iSup_of_le h4 <| le_iSup_of_le h5 le_rfl) ?_
  refine iSup_le fun g => iSup_le fun hgm => iSup_le fun _ => iSup_le fun _ =>
    iSup_le fun hgq => iSup_le fun _ => ?_
  calc ‖∫ x, h x * conj (g x) ∂μ‖ₑ
      ≤ eLpNorm h (ENNReal.ofReal p) μ * eLpNorm g (ENNReal.ofReal q) μ :=
        enorm_integral_mul_conj_le hpq hh hgm.aestronglyMeasurable
    _ ≤ eLpNorm h (ENNReal.ofReal p) μ * 1 := mul_le_mul_right hgq _
    _ = eLpNorm h (ENNReal.ofReal p) μ := mul_one _

end Duality

/-! ### Subsequences -/

/-- Blueprint Lemma 2.2 (`lem:young`), third assertion: if `h_k → h` in `L^p` (`p ≠ 0`), i.e.
`‖h_k - h‖_p → 0`, then a subsequence converges to `h` almost everywhere. -/
theorem exists_subseq_ae_tendsto_of_eLpNorm_tendsto {α E : Type*} [MeasurableSpace α]
    {μ : Measure α} [NormedAddCommGroup E] {p : ℝ≥0∞} (hp : p ≠ 0) {h : ℕ → α → E}
    {g : α → E} (hlim : Tendsto (fun k => eLpNorm (h k - g) p μ) atTop (𝓝 0)) :
    ∃ φ : ℕ → ℕ, StrictMono φ ∧ ∀ᵐ x ∂μ, Tendsto (fun j => h (φ j) x) atTop (𝓝 (g x)) :=
  (tendstoInMeasure_of_tendsto_eLpNorm hp hlim).exists_seq_tendsto_ae

/-! ## Lemma 2.4 (`lem:maximal`), second half: the envelope `B_R`

The envelope `envelope`, its constant `envelopeConst`, the bound
`lintegral_envelope_mul_le_cubeMaximalEuclidean` (`B_R * |f| ≤ C_n 𝖬 f` on `E`),
`lintegral_envelope_le` (`∫ B_R ≤ C_n`) and `volume_euclideanCube` are proved among the
supporting results of `DiscreteSW/Auto/CalderonZygmund.lean`. -/

/-- The lattice envelope `B_R(y)`, `y ∈ ℤⁿ`, of Blueprint Lemma 2.4 (`lem:maximal`): the
envelope evaluated at the embedded point `latEmbed y` (Euclidean norm). -/
noncomputable def latEnvelope (n : ℕ) (R : ℝ) (y : Fin n → ℤ) : ℝ := envelope n R (latEmbed y)

/-- The envelope is nonnegative. -/
lemma envelope_nonneg {n : ℕ} {R : ℝ} (hR : 0 < R) (x : EuclideanSpace ℝ (Fin n)) :
    0 ≤ envelope n R x := by
  unfold envelope; positivity

/-- For `R > 0`, the envelope is continuous. -/
lemma continuous_envelope (n : ℕ) {R : ℝ} (hR : 0 < R) : Continuous (envelope n R) := by
  unfold envelope
  refine continuous_const.mul (Continuous.inv₀ (by fun_prop) fun x => by positivity)

/-- The lattice cube of radius `⌈r⌉` has at most `(5r)^n` points when `r ≥ 1`. -/
lemma count_intCube_ceil_le {n : ℕ} (x : Fin n → ℤ) {r : ℝ} (hr : 1 ≤ r) :
    Measure.count (intCube x ⌈r⌉₊) ≤ ENNReal.ofReal ((5 * r) ^ n) := by
  rw [intCube_eq_closedBall, count_closedBall_int n x (Nat.cast_nonneg _), Int.floor_natCast]
  have h1 : (2 * (⌈r⌉₊ : ℤ) + 1).toNat = 2 * ⌈r⌉₊ + 1 := by omega
  rw [h1, ← ENNReal.ofReal_natCast]
  refine ENNReal.ofReal_le_ofReal ?_
  push_cast
  refine pow_le_pow_left₀ (by positivity) ?_ n
  have := Nat.ceil_lt_add_one (show 0 ≤ r by linarith)
  linarith

/-- On `G`: `∑_{|y|_∞ ≤ N} |f(x - y)| ≤ #(cube of radius N) · 𝖬 f(x)`. -/
lemma setLIntegral_intCube_le {F : Type*} [NormedAddCommGroup F] {n : ℕ}
    (f : (Fin n → ℤ) → F) (x : Fin n → ℤ) (N : ℕ) :
    ∫⁻ y in intCube 0 N, ‖f (x - y)‖ₑ ∂Measure.count ≤
      Measure.count (intCube x N) * cubeMaximalInt n f x := by
  have e1 : ∫⁻ y in intCube 0 N, ‖f (x - y)‖ₑ ∂Measure.count =
      ∫⁻ z in intCube x N, ‖f z‖ₑ ∂Measure.count := by
    rw [← lintegral_indicator (MeasurableSet.of_discrete),
      ← lintegral_indicator (MeasurableSet.of_discrete), lintegral_count, lintegral_count]
    conv_rhs => rw [← (Equiv.subLeft x).tsum_eq]
    congr 1; funext y
    have : y ∈ intCube 0 N ↔ x - y ∈ intCube x N := by
      simp [intCube, abs_sub_comm]
    simp only [Equiv.subLeft_apply]
    by_cases hy : y ∈ intCube 0 N
    · rw [indicator_of_mem hy, indicator_of_mem (this.1 hy)]
    · rw [indicator_of_notMem hy, indicator_of_notMem (fun h => hy (this.2 h))]
  rw [e1]
  have h0 : Measure.count (intCube x N) ≠ 0 := by
    rw [Measure.count_ne_zero_iff]; exact ⟨x, fun i => by simp⟩
  have ht : Measure.count (intCube x N) ≠ ∞ := by
    rw [intCube_eq_closedBall, count_closedBall_int n x (Nat.cast_nonneg _)]
    exact ENNReal.natCast_ne_top _
  rw [← ENNReal.mul_inv_cancel_left (b := ∫⁻ z in intCube x N, ‖f z‖ₑ ∂Measure.count) h0 ht]
  gcongr
  exact le_iSup (fun R : ℕ => (Measure.count (intCube x R))⁻¹ *
    ∫⁻ y in intCube x R, ‖f y‖ₑ ∂Measure.count) N

/-- On `G`: `B_R(y) ≤ ∑_k a_k 𝟙_{|y|_∞ ≤ ⌈2^k R⌉}(y)`. -/
lemma envelope_le_tsum_indicator_int {n : ℕ} {R : ℝ} (hR : 0 < R) (y : Fin n → ℤ) :
    ENNReal.ofReal (latEnvelope n R y) ≤ ∑' k, (intCube 0 ⌈2 ^ k * R⌉₊).indicator
      (fun _ => ENNReal.ofReal (envelopeCoeff n R k)) y := by
  obtain ⟨k, hk1, hk2⟩ := exists_envelope_le_coeff hR (latEmbed y)
  have hy : y ∈ intCube 0 ⌈2 ^ k * R⌉₊ := fun i => by
    have h1 : |(y i : ℝ)| ≤ 2 ^ k * R := by
      simpa [Real.norm_eq_abs] using (PiLp.norm_apply_le (latEmbed y) i).trans hk1
    have h2 : |(y i : ℝ)| ≤ (⌈2 ^ k * R⌉₊ : ℝ) := h1.trans (Nat.le_ceil _)
    simp only [Pi.zero_apply, sub_zero]
    exact_mod_cast h2
  refine le_trans ?_ (ENNReal.le_tsum k)
  rw [indicator_of_mem hy]
  exact ENNReal.ofReal_le_ofReal hk2

/-- Blueprint Lemma 2.4 (`lem:maximal`), equation (2.1) (`eq:envelope`), first inequality on
`G`: for `R ≥ 1`, `x ∈ ℤⁿ` and any `f`,
`(B_R * |f|)(x) = ∑_y B_R(y) |f(x - y)| ≤ C_n 𝖬 f(x)`, with `𝖬` the lattice cube maximal
function `cubeMaximalInt` (integer radii) and `C_n = envelopeConst n`. -/
theorem tsum_envelope_mul_le_cubeMaximalInt {F : Type*} [NormedAddCommGroup F] {n : ℕ}
    {R : ℝ} (hR : 1 ≤ R) (f : (Fin n → ℤ) → F) (x : Fin n → ℤ) :
    ∑' y, ENNReal.ofReal (latEnvelope n R y) * ‖f (x - y)‖ₑ ≤
      ENNReal.ofReal (envelopeConst n) * cubeMaximalInt n f x := by
  have hR0 : 0 < R := by linarith
  rw [← lintegral_count]
  refine (lintegral_mul_le_tsum_setLIntegral Measure.count
    (AEMeasurable.of_discrete (f := fun y => ‖f (x - y)‖ₑ))
    (fun k => MeasurableSet.of_discrete (s := intCube 0 ⌈2 ^ k * R⌉₊)) _
    (envelope_le_tsum_indicator_int hR0)).trans ?_
  rw [← tsum_envelopeCoeff_mul n hR0]
  refine ENNReal.tsum_le_tsum fun k => ?_
  gcongr
  refine (setLIntegral_intCube_le f x _).trans ?_
  gcongr
  exact count_intCube_ceil_le x (one_le_mul_of_one_le_of_one_le (one_le_pow₀ one_le_two) hR)

/-- Blueprint Lemma 2.4 (`lem:maximal`), bound for the Euclidean integral of `B_R`: for `R > 0`
(in particular `R ≥ 1`), `B_R` is integrable on `E` and `∫ B_R ≤ C_n`, with `C_n = envelopeConst n`
independent of `R`. -/
theorem integrable_envelope_and_integral_le {n : ℕ} {R : ℝ} (hR : 0 < R) :
    Integrable (envelope n R) volume ∧ ∫ x, envelope n R x ≤ envelopeConst n := by
  have hC : 0 ≤ envelopeConst n := by unfold envelopeConst; positivity
  have hnn : 0 ≤ᵐ[volume] envelope n R := Eventually.of_forall (envelope_nonneg hR)
  have hint : Integrable (envelope n R) volume :=
    ⟨(continuous_envelope n hR).aestronglyMeasurable, (hasFiniteIntegral_iff_ofReal hnn).2
      ((lintegral_envelope_le hR).trans_lt ENNReal.ofReal_lt_top)⟩
  refine ⟨hint, ?_⟩
  rw [integral_eq_lintegral_of_nonneg_ae hnn hint.aestronglyMeasurable]
  exact ENNReal.toReal_le_of_le_ofReal hC (lintegral_envelope_le hR)

/-- Blueprint Lemma 2.4 (`lem:maximal`), bound for the lattice sum of `B_R`: for `R ≥ 1`,
`y ↦ B_R(y)` is summable on `ℤⁿ` and `∑_y B_R(y) ≤ C_n`, with `C_n = envelopeConst n`
independent of `R`. -/
theorem summable_latEnvelope_and_tsum_le {n : ℕ} {R : ℝ} (hR : 1 ≤ R) :
    Summable (latEnvelope n R) ∧ ∑' y, latEnvelope n R y ≤ envelopeConst n := by
  have hR0 : 0 < R := by linarith
  have hC : 0 ≤ envelopeConst n := by unfold envelopeConst; positivity
  have h := tsum_envelope_mul_le_cubeMaximalInt hR (fun _ : Fin n → ℤ => (1 : ℝ)) 0
  simp only [enorm_one, mul_one] at h
  have h' : ∑' y : Fin n → ℤ, ENNReal.ofReal (envelope n R (latEmbed y)) ≤
      ENNReal.ofReal (envelopeConst n) := by
    refine h.trans (mul_le_of_le_one_right zero_le (iSup_le fun N => ?_))
    simp
  have hfin : ∑' y : Fin n → ℤ, ENNReal.ofReal (envelope n R (latEmbed y)) ≠ ∞ :=
    (h'.trans_lt ENNReal.ofReal_lt_top).ne
  have heq : latEnvelope n R =
      fun y => (ENNReal.ofReal (envelope n R (latEmbed y))).toReal := by
    funext y; rw [latEnvelope, ENNReal.toReal_ofReal (envelope_nonneg hR0 _)]
  rw [heq]
  refine ⟨ENNReal.summable_toReal hfin, ?_⟩
  rw [← ENNReal.tsum_toReal_eq fun _ => ENNReal.ofReal_ne_top]
  exact ENNReal.toReal_le_of_le_ofReal hC h'

/-- If `R + |x| ≤ c (R + |u|)`, then `B_R(u) ≤ c^{n+1} B_R(x)`. -/
lemma envelope_le_pow_mul {n : ℕ} {R c : ℝ} (hR : 0 < R)
    {x u : EuclideanSpace ℝ (Fin n)} (h : R + ‖x‖ ≤ c * (R + ‖u‖)) :
    envelope n R u ≤ c ^ (n + 1) * envelope n R x := by
  rw [envelope_eq_div hR, envelope_eq_div hR, mul_div_assoc', div_le_div_iff₀ (by positivity)
    (by positivity)]
  have : (R + ‖x‖) ^ (n + 1) ≤ c ^ (n + 1) * (R + ‖u‖) ^ (n + 1) := by
    rw [← mul_pow]; exact pow_le_pow_left₀ (by positivity) h _
  nlinarith

/-- For `L ≤ R`, `|x| > 2R` and `|z| ≥ |x|/2`: `B_L(z) ≤ 4^{n+1} B_R(x)`. -/
lemma envelope_le_of_far {n : ℕ} {R L : ℝ} (hL : 0 < L) (hLR : L ≤ R)
    {x z : EuclideanSpace ℝ (Fin n)} (hx : 2 * R < ‖x‖) (hz : ‖x‖ / 2 ≤ ‖z‖) :
    envelope n L z ≤ 4 ^ (n + 1) * envelope n R x := by
  have hR : 0 < R := hL.trans_le hLR
  have hx0 : 0 < ‖x‖ := by linarith
  rw [envelope_eq_div hL, envelope_eq_div hR]
  calc L / (L + ‖z‖) ^ (n + 1) ≤ R / (‖x‖ / 2) ^ (n + 1) :=
        div_le_div₀ hR.le hLR (by positivity) (pow_le_pow_left₀ (by positivity) (by linarith) _)
    _ = 4 ^ (n + 1) * (R / (2 * ‖x‖) ^ (n + 1)) := by
        rw [div_pow, mul_pow]; field_simp; rw [← pow_mul, mul_comm, pow_mul]; norm_num
    _ ≤ 4 ^ (n + 1) * (R / (R + ‖x‖) ^ (n + 1)) := by
        gcongr; linarith

/-- Pointwise bound for `L ≤ R`:
`B_R(x - z) B_L(z) ≤ 4^{n+1} B_R(x) (B_L(z) + B_R(x - z))`. -/
lemma envelope_mul_le_of_le {n : ℕ} {R L : ℝ} (hL : 0 < L) (hLR : L ≤ R)
    (x z : EuclideanSpace ℝ (Fin n)) :
    envelope n R (x - z) * envelope n L z ≤
      4 ^ (n + 1) * envelope n R x * (envelope n L z + envelope n R (x - z)) := by
  have hR : 0 < R := hL.trans_le hLR
  have e1 := envelope_nonneg hR (x - z)
  have e2 := envelope_nonneg hL z
  have e3 := envelope_nonneg hR x
  by_cases hA : ‖x‖ / 2 ≤ ‖x - z‖ ∨ ‖x‖ ≤ 2 * R
  · have hb : envelope n R (x - z) ≤ 4 ^ (n + 1) * envelope n R x := by
      rcases hA with hA | hA
      · refine (envelope_le_pow_mul (c := 2) (x := x) (u := x - z) hR (by linarith)).trans ?_
        gcongr; norm_num
      · refine (envelope_le_pow_mul (c := 3) (x := x) (u := x - z) hR
          (by linarith [norm_nonneg (x - z)])).trans ?_
        gcongr; norm_num
    calc envelope n R (x - z) * envelope n L z ≤ 4 ^ (n + 1) * envelope n R x * envelope n L z :=
          mul_le_mul_of_nonneg_right hb e2
      _ ≤ _ := mul_le_mul_of_nonneg_left (by linarith) (by positivity)
  · simp only [not_or, not_le] at hA
    have hz : ‖x‖ / 2 ≤ ‖z‖ := by
      have := norm_sub_norm_le x z
      linarith
    have hb := envelope_le_of_far hL hLR hA.2 hz
    calc envelope n R (x - z) * envelope n L z ≤
          envelope n R (x - z) * (4 ^ (n + 1) * envelope n R x) :=
          mul_le_mul_of_nonneg_left hb e1
      _ = 4 ^ (n + 1) * envelope n R x * envelope n R (x - z) := by ring
      _ ≤ _ := mul_le_mul_of_nonneg_left (by linarith) (by positivity)

/-- Pointwise bound for all `R, L > 0`:
`B_R(x - z) B_L(z) ≤ 4^{n+1} B_{max(R,L)}(x) (B_L(z) + B_R(x - z))`. -/
lemma envelope_mul_le {n : ℕ} {R L : ℝ} (hR : 0 < R) (hL : 0 < L)
    (x z : EuclideanSpace ℝ (Fin n)) :
    envelope n R (x - z) * envelope n L z ≤
      4 ^ (n + 1) * envelope n (max R L) x * (envelope n L z + envelope n R (x - z)) := by
  rcases le_total L R with h | h
  · rw [max_eq_left h]; exact envelope_mul_le_of_le hL h x z
  · rw [max_eq_right h]
    have := envelope_mul_le_of_le hR h x (x - z)
    rw [sub_sub_cancel] at this
    linarith [mul_comm (envelope n R (x - z)) (envelope n L z)]

/-- The constant `2 · 4^{n+1} C_n` of Blueprint Lemma 2.4 (`lem:maximal`) in
`B_R *_E B_L ≤ C B_{max(R,L)}`. -/
noncomputable def envelopeConvConst (n : ℕ) : ℝ := 2 * 4 ^ (n + 1) * envelopeConst n

/-- Blueprint Lemma 2.4 (`lem:maximal`), equation (2.1) (`eq:envelope`), second inequality:
for `R, L > 0` (in particular `R, L ≥ 1`) and `x ∈ E`, `z ↦ B_R(x - z) B_L(z)` is integrable and
`(B_R *_E B_L)(x) = ∫ B_R(x - z) B_L(z) dz ≤ C B_{max(R,L)}(x)`, `C = envelopeConvConst n`. -/
theorem envelope_conv_le {n : ℕ} {R L : ℝ} (hR : 0 < R) (hL : 0 < L)
    (x : EuclideanSpace ℝ (Fin n)) :
    Integrable (fun z => envelope n R (x - z) * envelope n L z) volume ∧
      ∫ z, envelope n R (x - z) * envelope n L z ≤
        envelopeConvConst n * envelope n (max R L) x := by
  obtain ⟨hiR, hIR⟩ := integrable_envelope_and_integral_le (n := n) hR
  obtain ⟨hiL, hIL⟩ := integrable_envelope_and_integral_le (n := n) hL
  have hiR' : Integrable (fun z => envelope n R (x - z)) volume := hiR.comp_sub_left x
  have hbd : Integrable (fun z => 4 ^ (n + 1) * envelope n (max R L) x *
      (envelope n L z + envelope n R (x - z))) volume := (hiL.add hiR').const_mul _
  have hcont : Continuous fun z => envelope n R (x - z) * envelope n L z :=
    ((continuous_envelope n hR).comp (continuous_const.sub continuous_id)).mul
      (continuous_envelope n hL)
  have hint : Integrable (fun z => envelope n R (x - z) * envelope n L z) volume :=
    hbd.mono' hcont.aestronglyMeasurable (Eventually.of_forall fun z => by
      rw [Real.norm_of_nonneg (mul_nonneg (envelope_nonneg hR _) (envelope_nonneg hL _))]
      exact envelope_mul_le hR hL x z)
  refine ⟨hint, ?_⟩
  have hM := envelope_nonneg (R := max R L) (lt_max_of_lt_left hR) x
  calc ∫ z, envelope n R (x - z) * envelope n L z
      ≤ ∫ z, 4 ^ (n + 1) * envelope n (max R L) x * (envelope n L z + envelope n R (x - z)) :=
        integral_mono hint hbd (envelope_mul_le hR hL x)
    _ = 4 ^ (n + 1) * envelope n (max R L) x *
          ((∫ z, envelope n L z) + ∫ z, envelope n R z) := by
        rw [integral_const_mul, integral_add hiL hiR',
          integral_sub_left_eq_self (fun z => envelope n R z) volume x]
    _ ≤ 4 ^ (n + 1) * envelope n (max R L) x * (envelopeConst n + envelopeConst n) := by
        gcongr
    _ = envelopeConvConst n * envelope n (max R L) x := by
        unfold envelopeConvConst; ring

/-! ## Lemma 2.5 (`lem:ttstar`): Schur, Hilbert–Schmidt, and linearization -/

section Schur

variable {α β : Type*} [MeasurableSpace α] [MeasurableSpace β] {μ : Measure α} {ν : Measure β}

/-- `((a b)^{1/2} c)^2 = a b c^2` in `[0, ∞]`. -/
lemma sqrt_mul_mul_rpow_two (a c : ℝ≥0∞) : (a ^ (1 / 2 : ℝ) * c) ^ (2 : ℝ) = a * c ^ (2 : ℝ) := by
  rw [ENNReal.mul_rpow_of_nonneg _ _ (by norm_num), ← ENNReal.rpow_mul]
  norm_num

/-- Blueprint Lemma 2.5 (`lem:ttstar`), first assertion (Schur test), nonnegative majorant form:
on s-finite measure spaces (e.g. σ-finite ones, or counting measure on `ℤⁿ`), for a kernel `H`
that is a.e. strongly measurable on `X × Y`, with row bound `∫ |H(x,y)| dy ≤ A` (a.e. `x`) and
column bound `∫ |H(x,y)| dx ≤ B` (a.e. `y`), and any a.e. strongly measurable `g`,
`‖x ↦ ∫ |H(x,y)| |g(y)| dy‖₂ ≤ √(AB) ‖g‖₂`. -/
theorem eLpNorm_lintegral_kernel_le_schur [SFinite μ] [SFinite ν] {H : α → β → ℂ}
    (hH : AEStronglyMeasurable (Function.uncurry H) (μ.prod ν)) {A B : ℝ≥0∞}
    (hA : ∀ᵐ x ∂μ, ∫⁻ y, ‖H x y‖ₑ ∂ν ≤ A) (hB : ∀ᵐ y ∂ν, ∫⁻ x, ‖H x y‖ₑ ∂μ ≤ B)
    {g : β → ℂ} (hg : AEStronglyMeasurable g ν) :
    eLpNorm (fun x => ∫⁻ y, ‖H x y‖ₑ * ‖g y‖ₑ ∂ν) 2 μ ≤ (A * B) ^ (1 / 2 : ℝ) * eLpNorm g 2 ν := by
  have hHe : AEMeasurable (fun z : α × β => ‖H z.1 z.2‖ₑ) (μ.prod ν) := hH.enorm
  have hge : AEMeasurable (fun z : α × β => ‖g z.2‖ₑ) (μ.prod ν) :=
    (hg.comp_snd (μ := μ)).enorm
  have hM : AEMeasurable (fun x => ∫⁻ y, ‖H x y‖ₑ * ‖g y‖ₑ ∂ν) μ :=
    (hHe.mul hge).lintegral_prod_right'
  have h2 : AEMeasurable (fun z : α × β => ‖H z.1 z.2‖ₑ * ‖g z.2‖ₑ ^ (2 : ℝ)) (μ.prod ν) :=
    hHe.mul (hge.pow_const _)
  rw [eLpNorm_ennreal_le_iff (by norm_num) (by norm_num) _ hM]
  simp only [ENNReal.toReal_ofNat]
  rw [sqrt_mul_mul_rpow_two, eLpNorm_two_rpow_two hg]
  have hrow : ∀ᵐ x ∂μ, AEStronglyMeasurable (fun y => H x y) ν := hH.prodMk_left
  calc ∫⁻ x, (∫⁻ y, ‖H x y‖ₑ * ‖g y‖ₑ ∂ν) ^ (2 : ℝ) ∂μ
      ≤ ∫⁻ x, A * ∫⁻ y, ‖H x y‖ₑ * ‖g y‖ₑ ^ (2 : ℝ) ∂ν ∂μ := by
        refine lintegral_mono_ae ?_
        filter_upwards [hA, hrow] with x hx hxm
        refine (lintegral_mul_rpow_le_young ν (by norm_num) hxm.enorm hg.enorm).trans ?_
        norm_num only [ENNReal.rpow_one]
        exact mul_le_mul_left hx _
    _ = A * ∫⁻ x, ∫⁻ y, ‖H x y‖ₑ * ‖g y‖ₑ ^ (2 : ℝ) ∂ν ∂μ :=
        lintegral_const_mul'' _ h2.lintegral_prod_right'
    _ = A * ∫⁻ y, ∫⁻ x, ‖H x y‖ₑ * ‖g y‖ₑ ^ (2 : ℝ) ∂μ ∂ν := by
        rw [lintegral_lintegral_swap h2]
    _ ≤ A * ∫⁻ y, B * ‖g y‖ₑ ^ (2 : ℝ) ∂ν := by
        refine mul_le_mul_right (lintegral_mono_ae ?_) _
        filter_upwards [hB] with y hy
        rw [lintegral_mul_const' _ _ (ENNReal.rpow_ne_top_of_nonneg (by norm_num) enorm_ne_top)]
        exact mul_le_mul_left hy _
    _ = A * B * ∫⁻ y, ‖g y‖ₑ ^ (2 : ℝ) ∂ν := by
        rw [lintegral_const_mul'' _ (hg.enorm.pow_const _), mul_assoc]

omit [MeasurableSpace α] in
/-- Pointwise bound `|∫ H(x,y) g(y) dy| ≤ ∫ |H(x,y)| |g(y)| dy`. -/
lemma enorm_integral_kernel_le (H : α → β → ℂ) (g : β → ℂ) (x : α) :
    ‖∫ y, H x y * g y ∂ν‖ₑ ≤ ∫⁻ y, ‖H x y‖ₑ * ‖g y‖ₑ ∂ν :=
  (enorm_integral_le_lintegral_enorm _).trans_eq (by simp [enorm_mul])

/-- The kernel operator `x ↦ ∫ H(x,y) g(y) dy` is a.e. strongly measurable. -/
lemma aestronglyMeasurable_integral_kernel [SFinite ν] {H : α → β → ℂ}
    (hH : AEStronglyMeasurable (Function.uncurry H) (μ.prod ν)) {g : β → ℂ}
    (hg : AEStronglyMeasurable g ν) :
    AEStronglyMeasurable (fun x => ∫ y, H x y * g y ∂ν) μ :=
  (hH.mul (hg.comp_snd (μ := μ))).integral_prod_right'

/-- Blueprint Lemma 2.5 (`lem:ttstar`), first assertion (Schur test): on s-finite measure spaces
(e.g. σ-finite ones, or counting measure on `ℤⁿ`), for an a.e. strongly measurable kernel `H`
with row bound `∫ |H(x,y)| dy ≤ A` (a.e. `x`) and column bound `∫ |H(x,y)| dx ≤ B` (a.e. `y`),
the operator `Hg(x) = ∫ H(x,y) g(y) dy` satisfies `‖Hg‖₂ ≤ √(AB) ‖g‖₂` for every a.e. strongly
measurable `g` (so `‖H‖_{2→2} ≤ √(AB)`). -/
theorem eLpNorm_integral_kernel_le_schur [SFinite μ] [SFinite ν] {H : α → β → ℂ}
    (hH : AEStronglyMeasurable (Function.uncurry H) (μ.prod ν)) {A B : ℝ≥0∞}
    (hA : ∀ᵐ x ∂μ, ∫⁻ y, ‖H x y‖ₑ ∂ν ≤ A) (hB : ∀ᵐ y ∂ν, ∫⁻ x, ‖H x y‖ₑ ∂μ ≤ B)
    {g : β → ℂ} (hg : AEStronglyMeasurable g ν) :
    eLpNorm (fun x => ∫ y, H x y * g y ∂ν) 2 μ ≤ (A * B) ^ (1 / 2 : ℝ) * eLpNorm g 2 ν :=
  (eLpNorm_mono_enorm (aestronglyMeasurable_integral_kernel hH hg) fun x => by
    rw [enorm_eq_self]; exact enorm_integral_kernel_le H g x).trans
    (eLpNorm_lintegral_kernel_le_schur hH hA hB hg)

/-- Blueprint Lemma 2.5 (`lem:ttstar`), second assertion (Hilbert–Schmidt), nonnegative majorant
form: on s-finite measure spaces, for an a.e. strongly measurable kernel `H` and a.e. strongly
measurable `g`, `‖x ↦ ∫ |H(x,y)| |g(y)| dy‖₂ ≤ ‖H‖_{L²(X × Y)} ‖g‖₂`. -/
theorem eLpNorm_lintegral_kernel_le_hilbertSchmidt [SFinite μ] [SFinite ν] {H : α → β → ℂ}
    (hH : AEStronglyMeasurable (Function.uncurry H) (μ.prod ν)) {g : β → ℂ}
    (hg : AEStronglyMeasurable g ν) :
    eLpNorm (fun x => ∫⁻ y, ‖H x y‖ₑ * ‖g y‖ₑ ∂ν) 2 μ ≤
      eLpNorm (Function.uncurry H) 2 (μ.prod ν) * eLpNorm g 2 ν := by
  have hHe : AEMeasurable (fun z : α × β => ‖H z.1 z.2‖ₑ) (μ.prod ν) := hH.enorm
  have hge : AEMeasurable (fun z : α × β => ‖g z.2‖ₑ) (μ.prod ν) :=
    (hg.comp_snd (μ := μ)).enorm
  have hM : AEMeasurable (fun x => ∫⁻ y, ‖H x y‖ₑ * ‖g y‖ₑ ∂ν) μ :=
    (hHe.mul hge).lintegral_prod_right'
  have h2 : AEMeasurable (fun z : α × β => ‖H z.1 z.2‖ₑ ^ (2 : ℝ)) (μ.prod ν) :=
    hHe.pow_const _
  rw [eLpNorm_ennreal_le_iff (by norm_num) (by norm_num) _ hM]
  simp only [ENNReal.toReal_ofNat]
  rw [ENNReal.mul_rpow_of_nonneg _ _ (by norm_num), eLpNorm_two_rpow_two hg,
    eLpNorm_two_rpow_two hH]
  have hrow : ∀ᵐ x ∂μ, AEStronglyMeasurable (fun y => H x y) ν := hH.prodMk_left
  calc ∫⁻ x, (∫⁻ y, ‖H x y‖ₑ * ‖g y‖ₑ ∂ν) ^ (2 : ℝ) ∂μ
      ≤ ∫⁻ x, (∫⁻ y, ‖H x y‖ₑ ^ (2 : ℝ) ∂ν) * ∫⁻ y, ‖g y‖ₑ ^ (2 : ℝ) ∂ν ∂μ := by
        refine lintegral_mono_ae ?_
        filter_upwards [hrow] with x hxm
        have hh := ENNReal.lintegral_mul_le_Lp_mul_Lq ν Real.HolderConjugate.two_two
          hxm.enorm hg.enorm
        refine (ENNReal.rpow_le_rpow hh (by norm_num : (0 : ℝ) ≤ 2)).trans_eq ?_
        rw [ENNReal.mul_rpow_of_nonneg _ _ (by norm_num), ← ENNReal.rpow_mul,
          ← ENNReal.rpow_mul]
        norm_num
    _ = (∫⁻ x, ∫⁻ y, ‖H x y‖ₑ ^ (2 : ℝ) ∂ν ∂μ) * ∫⁻ y, ‖g y‖ₑ ^ (2 : ℝ) ∂ν :=
        lintegral_mul_const'' _ h2.lintegral_prod_right'
    _ = (∫⁻ z, ‖Function.uncurry H z‖ₑ ^ (2 : ℝ) ∂μ.prod ν) * ∫⁻ y, ‖g y‖ₑ ^ (2 : ℝ) ∂ν := by
        congr 1; exact (lintegral_prod _ h2).symm

/-- Blueprint Lemma 2.5 (`lem:ttstar`), second assertion (Hilbert–Schmidt): on s-finite measure
spaces, for an a.e. strongly measurable kernel `H` and a.e. strongly measurable `g`,
`‖x ↦ ∫ H(x,y) g(y) dy‖₂ ≤ ‖H‖_{L²(X × Y)} ‖g‖₂` (so `‖H‖_{2→2} ≤ ‖H‖_{L²(X × Y)}`). -/
theorem eLpNorm_integral_kernel_le_hilbertSchmidt [SFinite μ] [SFinite ν] {H : α → β → ℂ}
    (hH : AEStronglyMeasurable (Function.uncurry H) (μ.prod ν)) {g : β → ℂ}
    (hg : AEStronglyMeasurable g ν) :
    eLpNorm (fun x => ∫ y, H x y * g y ∂ν) 2 μ ≤
      eLpNorm (Function.uncurry H) 2 (μ.prod ν) * eLpNorm g 2 ν :=
  (eLpNorm_mono_enorm (aestronglyMeasurable_integral_kernel hH hg) fun x => by
    rw [enorm_eq_self]; exact enorm_integral_kernel_le H g x).trans
    (eLpNorm_lintegral_kernel_le_hilbertSchmidt hH hg)

end Schur

/-! ### Lemma 2.5, third assertion (`‖T‖² = ‖TT*‖`) -/

section TTstar

variable {𝕜 E F : Type*} [RCLike 𝕜] [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
  [CompleteSpace E] [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]

open ContinuousLinearMap in
/-- Blueprint Lemma 2.5 (`lem:ttstar`), third assertion: for a bounded operator `T : E → F`
between Hilbert spaces, `‖T‖² = ‖T T*‖`, and also `‖T*‖ = ‖T‖` and `‖T‖² = ‖T* T‖`. -/
theorem norm_sq_eq_norm_comp_adjoint (T : E →L[𝕜] F) :
    ‖T‖ ^ 2 = ‖T ∘L adjoint T‖ ∧ ‖adjoint T‖ = ‖T‖ ∧ ‖T‖ ^ 2 = ‖adjoint T ∘L T‖ := by
  have hadj : ‖adjoint T‖ = ‖T‖ := LinearIsometryEquiv.norm_map _ _
  refine ⟨?_, hadj, ?_⟩
  · have h := norm_adjoint_comp_self (adjoint T)
    rw [adjoint_adjoint, hadj] at h
    rw [h, sq]
  · rw [norm_adjoint_comp_self, sq]

end TTstar

/-! ### Lemma 2.5, fourth assertion (linearization) -/

section Linearization

variable {α ι : Type*} [MeasurableSpace α]

/-- Measurable selection of a maximizing index: for a nonempty finite set `F` of indices and
measurable `g a : α → [0, ∞]` (`a ∈ F`), there is `σ : α → F` with measurable level sets such that
`g (σ x) x` is the maximum of `g a x` over `a ∈ F` (ties resolved by the order of insertion). -/
lemma exists_measurable_argmax (g : ι → α → ℝ≥0∞) {F : Finset ι} (hF : F.Nonempty)
    (hg : ∀ a ∈ F, Measurable (g a)) :
    ∃ σ : α → ι, (∀ x, σ x ∈ F) ∧ (∀ a, MeasurableSet (σ ⁻¹' {a})) ∧
      ∀ x, ∀ b ∈ F, g b x ≤ g (σ x) x := by
  classical
  revert hg
  induction hF using Finset.Nonempty.cons_induction with
  | singleton a =>
    intro _
    refine ⟨fun _ => a, fun x => Finset.mem_singleton_self a, fun b => ?_, fun x b hb => ?_⟩
    · rw [Set.preimage_const]; split_ifs <;> simp
    · rw [Finset.mem_singleton.1 hb]
  | cons a s ha hs ih =>
    intro hg
    obtain ⟨σ', hσ'F, hσ'm, hσ'⟩ := ih fun b hb => hg b (Finset.mem_cons_of_mem hb)
    set S : Set α := {x | g (σ' x) x ≤ g a x} with hS_def
    have hga : Measurable (g a) := hg a (Finset.mem_cons_self a s)
    have hS : MeasurableSet S := by
      have : S = ⋃ b ∈ s, (σ' ⁻¹' {b} ∩ {x | g b x ≤ g a x}) := by
        ext x
        simp only [hS_def, Set.mem_ofPred_eq, Set.mem_iUnion, Set.mem_inter_iff,
          Set.mem_preimage, Set.mem_singleton_iff, exists_prop]
        exact ⟨fun h => ⟨σ' x, hσ'F x, rfl, h⟩, fun ⟨b, _, hb, h⟩ => hb ▸ h⟩
      rw [this]
      exact Finset.measurableSet_biUnion _ fun b hb =>
        (hσ'm b).inter (measurableSet_le (hg b (Finset.mem_cons_of_mem hb)) hga)
    refine ⟨fun x => if x ∈ S then a else σ' x, fun x => ?_, fun b => ?_, fun x b hb => ?_⟩
    · dsimp only
      split_ifs
      · exact Finset.mem_cons_self a s
      · exact Finset.mem_cons_of_mem (hσ'F x)
    · have : (fun x => if x ∈ S then a else σ' x) ⁻¹' {b} =
          (S ∩ {_x | a = b}) ∪ (Sᶜ ∩ σ' ⁻¹' {b}) := by
        ext x
        by_cases hx : x ∈ S <;> simp [hx]
      rw [this]
      exact (hS.inter (MeasurableSet.const _)).union (hS.compl.inter (hσ'm b))
    · dsimp only
      rcases Finset.mem_cons.1 hb with rfl | hb
      · split_ifs with hx
        · exact le_rfl
        · exact (not_le.1 hx).le
      · split_ifs with hx
        · exact (hσ' x b hb).trans hx
        · exact hσ' x b hb

/-- Blueprint Lemma 2.5 (`lem:ttstar`), fourth assertion, selection: for a nonempty finite family
of a.e. strongly measurable functions `u a` (think `u a = T_a f`), there is a selection
`σ : α → F` with measurable level sets such that `|u (σ x) x| = max_{a ∈ F} |u a x|` for almost
every `x` (for every `x` if the `u a` are strongly measurable). -/
theorem exists_linearization {E : Type*} [NormedAddCommGroup E] {μ : Measure α}
    (u : ι → α → E) {F : Finset ι} (hF : F.Nonempty)
    (hu : ∀ a ∈ F, AEStronglyMeasurable (u a) μ) :
    ∃ σ : α → ι, (∀ x, σ x ∈ F) ∧ (∀ a, MeasurableSet (σ ⁻¹' {a})) ∧
      ∀ᵐ x ∂μ, ‖u (σ x) x‖ₑ = F.sup fun a => ‖u a x‖ₑ := by
  classical
  set v : ι → α → E := fun a => if h : a ∈ F then (hu a h).mk (u a) else u a
  have hv : ∀ a ∈ F, Measurable fun x => ‖v a x‖ₑ := fun a ha => by
    simp only [v, ha, ↓reduceDIte]
    exact (hu a ha).stronglyMeasurable_mk.enorm
  obtain ⟨σ, hσF, hσm, hσ⟩ := exists_measurable_argmax (fun a x => ‖v a x‖ₑ) hF hv
  refine ⟨σ, hσF, hσm, ?_⟩
  have hae : ∀ᵐ x ∂μ, ∀ a ∈ F, u a x = v a x := by
    rw [Finset.eventually_all]
    intro a ha
    simp only [v, ha, ↓reduceDIte]
    exact (hu a ha).ae_eq_mk
  filter_upwards [hae] with x hx
  rw [hx _ (hσF x)]
  refine le_antisymm ?_ (Finset.sup_le fun b hb => ?_)
  · rw [← hx _ (hσF x)]
    exact Finset.le_sup (f := fun a => ‖u a x‖ₑ) (hσF x)
  · rw [hx b hb]; exact hσ x b hb

/-- The linearized function `x ↦ u (σ x) x` of a selection with measurable level sets is a.e.
strongly measurable. -/
lemma aestronglyMeasurable_linearization {E : Type*} [NormedAddCommGroup E] {μ : Measure α}
    (u : ι → α → E) {F : Finset ι} (hu : ∀ a ∈ F, AEStronglyMeasurable (u a) μ) (σ : α → ι)
    (hσF : ∀ x, σ x ∈ F) (hσm : ∀ a, MeasurableSet (σ ⁻¹' {a})) :
    AEStronglyMeasurable (fun x => u (σ x) x) μ := by
  classical
  have : (fun x => u (σ x) x) = ∑ a ∈ F, (σ ⁻¹' {a}).indicator (u a) := by
    funext x
    rw [Finset.sum_apply, Finset.sum_eq_single (σ x)]
    · rw [Set.indicator_of_mem (by simp)]
    · intro b _ hb
      exact Set.indicator_of_notMem (by simpa [eq_comm] using hb) _
    · intro h; exact absurd (hσF x) h
  rw [this]
  exact Finset.aestronglyMeasurable_sum _ fun a ha => (hu a ha).indicator (hσm a)

/-- Blueprint Lemma 2.5 (`lem:ttstar`), fourth assertion (linearization), general form: for a
finite family of a.e. strongly measurable functions `u a` (`a ∈ F`), any `0 < p ≤ ∞` (indeed any
`p`), if `‖x ↦ u (σ x) x‖_p ≤ C` for every selection `σ : α → F` with measurable level sets, then
`‖max_{a ∈ F} |u a|‖_p ≤ C`. -/
theorem eLpNorm_finset_sup_le_of_linearization {E : Type*} [NormedAddCommGroup E]
    {μ : Measure α} {p : ℝ≥0∞} (u : ι → α → E) (F : Finset ι)
    (hu : ∀ a ∈ F, AEStronglyMeasurable (u a) μ) (C : ℝ≥0∞)
    (hC : ∀ σ : α → ι, (∀ x, σ x ∈ F) → (∀ a, MeasurableSet (σ ⁻¹' {a})) →
      eLpNorm (fun x => u (σ x) x) p μ ≤ C) :
    eLpNorm (fun x => F.sup fun a => ‖u a x‖ₑ) p μ ≤ C := by
  rcases F.eq_empty_or_nonempty with rfl | hF
  · simp
  obtain ⟨σ, hσF, hσm, hσ⟩ := exists_linearization u hF hu
  have hmeas := aestronglyMeasurable_linearization u hu σ hσF hσm
  calc eLpNorm (fun x => F.sup fun a => ‖u a x‖ₑ) p μ
      = eLpNorm (fun x => ‖u (σ x) x‖ₑ) p μ := eLpNorm_congr_ae (hσ.mono fun x hx => hx.symm)
    _ = eLpNorm (fun x => u (σ x) x) p μ := eLpNorm_enorm _ hmeas
    _ ≤ C := hC σ hσF hσm

/-- Blueprint Lemma 2.5 (`lem:ttstar`), fourth assertion (linearization), operator form: for a
finite family `T a` (`a ∈ F`) of operators (e.g. convolution operators) and a fixed `f` with each
`T a f` a.e. strongly measurable (automatic on `ℤⁿ`), a uniform bound `‖T_{σ(·)} f‖_p ≤ C` for all
pointwise selections `σ : α → F` with measurable level sets bounds the maximal function:
`‖max_{a ∈ F} |T a f|‖_p ≤ C`. Combine with `eLpNorm_iSup_le_of_finset_count` or
`eLpNorm_iSup_le_of_finset_countable` (Lemma 2.1) to pass to infinite families. -/
theorem eLpNorm_finset_sup_le_of_linearization_op {β : Type*} {μ : Measure α} {p : ℝ≥0∞}
    (T : ι → (β → ℂ) → α → ℂ) (f : β → ℂ) (F : Finset ι)
    (hT : ∀ a ∈ F, AEStronglyMeasurable (T a f) μ) (C : ℝ≥0∞)
    (hC : ∀ σ : α → ι, (∀ x, σ x ∈ F) → (∀ a, MeasurableSet (σ ⁻¹' {a})) →
      eLpNorm (fun x => T (σ x) f x) p μ ≤ C) :
    eLpNorm (fun x => F.sup fun a => ‖T a f x‖ₑ) p μ ≤ C :=
  eLpNorm_finset_sup_le_of_linearization (fun a => T a f) F hT C hC

end Linearization

end Tools

end Auto
